### ISSUE TITLE
Security issue with linked module

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1000]
When platform is running and has a linked module added, the module is not initialized if security settings prevent IIS from reading the module folder.

Version info: 
- Browser version: 
- Platform version:
- Module version: 

### Expected behavior
Should immediately display security exception when admin is refreshed.

### Actual behavior
Nothing happens, no errors until IIS is restarted.

### Steps to reproduce
1. Create new module under user documentation folder and compile it.
2. Open platform admin.
3. Add link to new module.
4. Check if module appears under modules blade (it won't).
5. Restart IIS and refresh admin.
6. You will see security exception.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-90
