### ISSUE TITLE
Settings manager should search settings in web.config first

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#1002]
Settings in web.config have higher priority than settings in the database.
Settings manager should check if a setting is present in the web.config in the appSettings or connectionStrings section first and if so it should take the value from web.config and mark it as read-only.

UI should display read-only settings differently and not allow to edit them.

**Comment by OlegoO** [comment]
Implemented

**Comment by artem-dudarev** [comment]
It's not implemented yet.

**Comment by asvishnyakov** [comment]
@OlegoO part about disabling in UI still not exist

**Comment by artem-dudarev** [comment]
Not only UI part. Actually nothing is done.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-103
