### ISSUE TITLE
 AngularJS Token Authentication using ASP.NET Web API 2, Owin, and Identity

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1007]
Use  token authentifcation for cross-domain requests between storefront and platform manager.
Main workflow:
1. Sign in in storefront by standart way
2. After succesfull login in to storefront client script autamaticaly send POST  /admin/token request with credentials in request body to platform API 
3. Server respond with authorization token
4. Client preserve it in local storage and use it for all crossdomain requests to platform api
Exceptions:
It is necessary to handle situations when the token and session are out of sync
It is necessary to take care of refreshing the token

http://bitoftech.net/2014/06/09/angularjs-token-authentication-using-asp-net-web-api-2-owin-asp-net-identity/
http://bitoftech.net/2014/06/01/token-based-authentication-asp-net-web-api-2-owin-asp-net-identity/

**Comment by asvishnyakov** [comment]
1. As I can see, there is no angular events (or something like that) which we can use to understand that user login/logout. All work are made on server side in C#.
2, 3. We may use satellizer. Request with login/password is not cross-domain, but just token-based OAuth authentication, as I understand. It's mean that we, possible, already have fully configured platform and don't need to do something else.
4.1. Look at 1. If we resolve this issue, then we just can use isAuthorized() method from satellizer to understand that user in unauthorized and we need to log out him/her.
4.2. http://bitoftech.net/2014/07/16/enable-oauth-refresh-tokens-angularjs-app-using-asp-net-web-api-2-owin/
