### ISSUE TITLE
Add validation rules for catalog property in manager UI

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1009]
Make changes in current property detail blade according  to wireframe
![image](https://user-images.githubusercontent.com/7566324/27852125-2a2eff36-615e-11e7-9056-e89455d3cae2.png)

**Comment by Woland2k** [comment]
We should move required checkbox to validation rules as well.

**Comment by tatarincev** [comment]
- Try to reposition the check-boxes in one line
- Bad formatted the description below the `custom pattern` in validation rules
![image](https://user-images.githubusercontent.com/7566324/28258279-ad25a78e-6ad0-11e7-82f1-931aa901913e.png)
- For multi-value property, validation errors are not displayed

**Comment by Woland2k** [comment]
it shouldn't say same description at the bottom either "You won't be able to publish and entry ..."

**Comment by Woland2k** [comment]
As I mentioned in the comment yesterday, the description of validation rule is incorrect, it shouldn't say "You won`t be able to publish an entry if there is an existing entry with identical content"

**Comment by ksavosteev** [comment]
Changed to "You won`t be able to publish an entry if it is not within character limit".
