### ISSUE TITLE
1.2 version of vs project template doesn't compile right away

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1020]
When creating a new project with the latest template, an error is generated:
VirtoCommerce.Contentful.csproj(154,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\VirtoCommerce.Module.0.12.0\build\VirtoCommerce.Module.targets.

### Expected behavior
Should compile right out of the box without any issues.

### Actual behavior
Compile error is generated

### Steps to reproduce
1. Download latest template.
2. Create new project.
3. Click compile.

**Comment by artem-dudarev** [comment]
Cannot reproduce.
I don't know where I can click 'Compile', but when I click 'Build Project' or 'Build Solution' all NuGet packages are automatically restored and build succeeds.
![image](https://user-images.githubusercontent.com/8775253/27983378-0c2612f4-63bb-11e7-9889-af54b726e817.png)

**Comment by Woland2k** [comment]
@artem-dudarev didn't work on my machine, maybe someone else can try?

**Comment by OlegoO** [comment]
Cannot reproduce. I've tested and all is ok with VS2017 template
