### ISSUE TITLE
Deploy.cmd generate TransformXml error

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1024]
Version info: 
Windows 10 
Visual Studio 2017

`error MSB4036:
 The "TransformXml" task was not found. Check the following: 1.) The name of the task in the project file is the same a
s the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interfa
ce. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:
\Program Files (x86)\MSBuild\14.0\bin" directory.
`

Similar error throw on `compress-module` command
`C:\Projects\VirtoCommerce\Modules\vc-module-b2b-extensions\VirtoCommerce.B2BExtensionsModule.Web\VirtoCommerce.B2BExtensionsModule.Web.csproj(207,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

**Comment by artem-dudarev** [comment]
Fixed in 70702a228e13235fe10dfe2ad73198218c4ad261
