### ISSUE TITLE
Platform - bug with displaying modules icons 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1025]
http://localhost/platform#/workspace/modules
Icons are blinking and hiding randomly

**Comment by asvishnyakov** [comment]
Can't reproduce issue. Icons are loading async, but after a half of second they appear and not blinking/hiding.

**Comment by tatarincev** [comment]
![image](https://user-images.githubusercontent.com/7566324/28257565-315535ce-6acc-11e7-9316-0b2eed6cc7f8.png)

**Comment by OlegoO** [comment]
To fix the problem we should replace 
<div class="image" style="background-image: url('Modules/$(VirtoCommerce.ImageTools)/Content/logo.png')" ng-if="grid.getCellValue(row, col)"></div>
with
<div class="image" ng-if="grid.getCellValue(row, col)">
<img src="Modules/$(VirtoCommerce.ImageTools)/Content/logo.png" />
</div>

+ img style 
    width: 40px;
    height: 40px;

**Comment by OlegoO** [comment]
Also we need add icon if we have a new version

![image](https://user-images.githubusercontent.com/7639413/28894536-66f20e76-77d5-11e7-9e92-042140456212.png)

**Comment by asvishnyakov** [comment]
![image](https://user-images.githubusercontent.com/6369252/28957481-7c5accc6-790b-11e7-8867-f2deec219ea7.png)

**Comment by artem-dudarev** [comment]
What this icon means? I believe it should be just a straight arrow up.
