### ISSUE TITLE
B2B store account management - record E2E tests

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1029]
- [ ] Organization owner registration
- [ ] Change profile (address, personal information)
- [ ]  Create organization members
- [ ] Invite organization members

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-b2b-extensions #1](https://github.com/VirtoCommerce/vc-module-b2b-extensions/issues/1) via [**ZenHub**](https://www.zenhub.com/)
