### ISSUE TITLE
Cache module: Force storefront cache invalidation when any theme changes 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1035]
Problem: 
When content configured to work with local disk storage, all theme changes immediately reflected in the storefront, thanks for FilesystemWatcher, but for azure blob storage it it does not work.

Solution:
Need to define decorator for IContentBlobStorageProvider (defined in ContentModule) and change special timestamp (ChangesTrackingService) for each blob changing operations. This decorator must be constructed only when azure blob content provider is configured.

The update  `changes timestamp`  may be reached by dummy cache region invalidation inside decorator.

**Comment by Woland2k** [comment]
blob storage supports notification mechanism: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob

**Comment by OlegoO** [comment]
Given Virtocommerce Admin is installed on separate instance from storefront
And a manager edits content (theme, page and etc)
When a manager saves modified content
Then module should call WebHooks to inform storefront 
And  a manager should see updated content on storefront 

**WebHooks** are a form of user-defined custom HTTP callbacks. With the WebHook model, a client provides the event producer with an endpoint to which the event producer can post the events. When an event is posted to the endpoint, the client application that is interested in such events can take appropriate actions.

**Comment by asvishnyakov** [comment]
@OlegoO #565

**Comment by Woland2k** [comment]
@OlegoO There are couple solutions here:

1. When using blob storage in azure, it has notification mechanism to inform about the changes, which should notify storefront.
2. There is a shared drive in azure which allows sharing same blob storage as a physical drive between admin and storefront.

I would focus on second approach for now as it is just a matter of configuration instead of any development.

**Comment by OlegoO** [comment]
Added workaround into AzureBlobContentProvider which implements AzureFilesystemWatcher and reset cache if file has been changed in Azure Storage
https://github.com/VirtoCommerce/vc-storefront/commit/023cd3fade20738b79ed71bf9209c5d9f5f5d08e

@tatarincev then we should reorganize how to work AzureBlobContentProvider on storefront

**Comment by tatarincev** [comment]
I think we made more "elegant" way to do invalidation without azure blob brootforcing.  
https ://github.com/VirtoCommerce/vc-module-cache/pull/2

**Comment by tatarincev** [comment]
Oh

**Comment by OlegoO** [comment]
@tatarincev  
https ://github.com/VirtoCommerce/vc-module-cache/pull/2
It doesn't work if we update file in Azure storage directly.

**Comment by tatarincev** [comment]
Yes, it is. What about this technology  https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob?  We can use it for cache invalidation?

**Comment by Woland2k** [comment]
I think actually better solution would be to use queue triggers instead as blob triggers have a lot of limitations. So in our case, when we updating blob storage, we simply add new record to the queue saying that blob has been updated and trigger is called. Read me here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue

**Comment by tatarincev** [comment]
My opinion is we  need to looking on the asynchronous event bus https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-async-messaging or https://www.rabbitmq.com 
This we also w
Can use in the platform for microservices communication and data consistency.
