### ISSUE TITLE
Sitemap module: Do not include in resulting sitemap excess resources

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1038]
Currently images and other files are including in the resulting sitemap with 'static content' type.
If content folder and concrete page included in the same sitemap, whole sitemap was stopping generate

**Comment by Andrew-Orlov** [comment]
I discovered that method `GetBlobInfo` of `AzureBlobProvider` doesn't populate the property `RelativeUrl`. This property is used by SitemapModule for sitemap records generation. `LocalStorageBlobProvider` fills up this property. The question is: what method should be modified - of SitemapsModule or AzureBlobProvider?
