### ISSUE TITLE
Platform: Change to Azure Gallery process

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1040]
Details in email `Change to Azure Gallery submission process`

**Comment by artem-dudarev** [comment]
Waiting for approval.

**Comment by OlegoO** [comment]
@artem-dudarev Do you get any feedback?

**Comment by artem-dudarev** [comment]
Microsoft has published "some" package which doesn't look like the one we have submitted to the gallery.
After testing the deployment there were some issues and I've submitted the correct package again.
Current status is 'Validating'.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
