### ISSUE TITLE
Wrong localization for indexing blade

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1043]
![image](https://user-images.githubusercontent.com/1566470/28222479-8784bb1a-687c-11e7-8b1e-8f78628ecc1b.png)

"Indexed 4 hours ago" should be in English

**Comment by asvishnyakov** [comment]
No. You chooses Russian as regional setting, so it will be displayed in Russian. Try to choose Russian regional settings in English windows, you get the same result.

**Comment by Woland2k** [comment]
I actually get "TypeError: Cannot read property 'name' of undefined" when trying to open account profile page in admin now. I'm logged in as ApiDocs
