### ISSUE TITLE
Discounts on demo clothing store are displayed with liquid error: Object of type 'System.Decimal' cannot be converted to type 'System.String'.%

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#1044]
Discounts on demo clothing store are displayed with liquid error: Object of type 'System.Decimal' cannot be converted to type 'System.String'.%

Version info: 
- Browser version: any 
- Platform version: 2.13.9
- Module version: 

### Expected behavior
there shouldn't be errors 

### Actual behavior
![image](https://user-images.githubusercontent.com/5917756/28260311-1c560b3c-6ae3-11e7-806c-a11e0166f370.png)

### Steps to reproduce
1. Create any promotion for clothing store with percentage discount
2. Open home or product page. It display new and old prices correctly, but with liquid error

**Comment by Andrew-Orlov** [comment]
![image](https://user-images.githubusercontent.com/10347112/28625702-508b34a4-721d-11e7-8f02-c2c11da19194.png)
![image](https://user-images.githubusercontent.com/10347112/28625733-65a7e404-721d-11e7-99a2-c03c56cc7e9d.png)
