### ISSUE TITLE
Developer pain: an easy way to switch between release & debug version of modules

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1048]
As a developer, I want to have an easy way to switch between release version of module automatically installed by admin site and debug version of module manually installed by developer. Also, I want to automatically fetch & pull repositories where me is not active developer.

Currenty, to develop & debug module, we must:
1. Remove current module folder from Modules folder in platform
2. Create symbolic link to folder with module source code
3. Watch to repository updates and fetch & pull changes to stay on latest version of repository

If we want to debug latest stable version, we must checkout master branch.
If we want to use release version of module, we must manually download, unzip release version and replace symbolic link with it.

All of these steps can be automated and even be available from admin UI.

**Comment by tatarincev** [comment]
I think this is requirements addressed most to environments and CD processes than to the platform itself. 
We have this task in internal roadmap https://virtocommerce.atlassian.net/browse/PRD-89 i think it will cover your requirements when it will be done.
