### ISSUE TITLE
Marketing Module: Exception when adding a content item to an existing publishing element

### ISSUE THREAD

**Issue by BuzzKeith** [VirtoCommerce/vc-platform#1054]
Unable to add a content item to an existing publishing item as the api call when saving throws and exception. This can be reproduced on demo site with step below.

### Actual behavior
Save fails when adding items to a publishing item

Exception:
Multiplicity constraint violated. The role 'PublishingGroupContentItemEntity_PublishingGroup_Target' of the relationship 'VirtoCommerce.MarketingModule.Data.Repositories.PublishingGroupContentItemEntity_PublishingGroup' has multiplicity 1 or 0..1.

Stack trace:
 at System.Data.Entity.Core.Objects.DataClasses.EntityReference`1.VerifyNavigationPropertyForAdd(IEntityWrapper wrapper)
↵   at System.Data.Entity.Core.Objects.EntityEntry.AddRelationshipDetectedByGraph(Dictionary`2 relationships, Object relatedObject, RelatedEnd relatedEndFrom, Boolean verifyForAdd)
↵   at System.Data.Entity.Core.Objects.EntityEntry.DetectChangesInRelationshipsOfSingleEntity()
↵   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChangesInNavigationProperties(IList`1 entries)
↵   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()
↵   at System.Data.Entity.Core.Objects.ObjectContext.DetectChanges()
↵   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
↵   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
↵   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
↵   at System.Data.Entity.DbSet.Add(Object entity)
↵   at VirtoCommerce.Platform.Data.Infrastructure.EFRepositoryBase.Add[T](T item)
↵   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.<>c__DisplayClass1_0.<GetChangeTracker>b__1(Object x)
↵   at VirtoCommerce.Platform.Core.Common.ObservableChangeTracker.<Attach>b__8_0(Object sender, NotifyCollectionChangedEventArgs args)
↵   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
↵   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
↵   at System.Collections.ObjectModel.Collection`1.Add(T item)
↵   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.<>c__DisplayClass7_0`1.<Patch>b__0(EntryState state, T x, T y)
↵   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.CompareTo[T](ICollection`1 source, ICollection`1 target, IEqualityComparer`1 comparer, Action`3 action)
↵   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.Patch[T](ICollection`1 source, ICollection`1 target, IEqualityComparer`1 comparer, Action`2 patch)
↵   at VirtoCommerce.MarketingModule.Data.Model.DynamicContentPublishingGroupEntity.Patch(DynamicContentPublishingGroupEntity target)
↵   at VirtoCommerce.MarketingModule.Data.Services.DynamicContentServiceImpl.SavePublications(DynamicContentPublication[] publications)
↵   at VirtoCommerce.CacheModule.Data.Decorators.MarketingServicesDecorator.SavePublications(DynamicContentPublication[] publications)
↵   at VirtoCommerce.MarketingModule.Web.Controllers.Api.MarketingModuleDynamicContentController.UpdateDynamicContentPublication(DynamicContentPublication publication)
↵   at lambda_method(Closure , Object , Object[] )
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Cors.CorsMessageHandler.<HandleCorsRequestAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()

### Steps to reproduce
1. On demo site go to Marketing > Content Publishing
2. Add content item to any of the exsisting publishing items
3. Hit save.  The api call returns a 500 error

**Comment by megafreeman** [comment]
@tatarincev this issue is the same as #1082
