### ISSUE TITLE
Catalog Module Clone Functionality for Properties

### ISSUE THREAD

**Issue by retschgi** [VirtoCommerce/vc-platform#1055]
Please provide detailed information about your issue, thank you!

Version info: 
- Platform version: 2.13.10
- Module version: Catalog Module 2.18.1

### Expected behavior
We often need to capture a long list of properties with different Names, but identical Dictionary-Values. It would be nice to have a "Clone"-Button. Same functional behavior as you clone a Product.

### Actual behavior

![screenshot](https://user-images.githubusercontent.com/610493/28369454-ed5533ba-6c97-11e7-8fa1-482221925a47.JPG)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #23](https://github.com/VirtoCommerce/vc-module-catalog/issues/23) via [**ZenHub**](https://www.zenhub.com/)
