### ISSUE TITLE
Write unit tests for catalog module 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1056]
Here is main topics which should be covered by Unit and E2E tests

**CRUD**
Catalog, categories, product, variations

**Properties**
Definition levels (Catalog, Category)
Applies to (Catalog, category, product, variation)
Types (Dictionary, Multilingual, Multi-value)
Value types 
Validation rules
Display names for multi-languages

**Inheritance**
Property inheritance Catalog -> Category -> Product 
Inheritance by variation from main product (Images, Descriptions, Prices, Dimensions)

**Associations**
Manage product associations

**Virtual catalog**
Virtual catalog
Categories in virtual catalog
Linking categories or products to the virtual catalog or categories

**Multilingual**
Descriptions, property values,  SEO slugs,  property display names and values for different languages

**Export/Import**
 CSV import/export
Platform Export/Import

**Partial update**
Products, Categories

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #27](https://github.com/VirtoCommerce/vc-module-catalog/issues/27) via [**ZenHub**](https://www.zenhub.com/)
