### ISSUE TITLE
Lucene search provider: does not correct handle multiple values filter

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1057]
`property: value1,value2` does not work properly on Lucene  search provider

**Comment by artem-dudarev** [comment]
Cannot reproduce. I get correct results for `brand:Sony,Asus`:
![image](https://user-images.githubusercontent.com/8775253/28567578-074e690e-7133-11e7-9903-a5031c68dabd.png)
![image](https://user-images.githubusercontent.com/8775253/28567557-f0c52e66-7132-11e7-944e-33c9a3271250.png)
