### ISSUE TITLE
Create unique validator field

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1061]
In order to allow unique field type of validation, create a new fields in PropertyValue named "ShortTextUniqueValue" and "IntegerUniqueValue" (unique will only be available for short and integer value fields).

Then create the following type of constraints:

CREATE UNIQUE NONCLUSTERED INDEX idx_shorttextuniquevalue_notnull
ON PropertyValue(ShortTextUniqueValue)
WHERE ShortTextUniqueValue IS NOT NULL;

**Comment by OlegoO** [comment]
1. Display [Is Unique] checkbox [UI]
2. Add new column ShortTextUniqueValue, IntegerUniqueValue into persistent model
3. Add Database constrain into repository 
4. Update model mapping  (Domain to Persistent, Persistent to Domain)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #28](https://github.com/VirtoCommerce/vc-module-catalog/issues/28) via [**ZenHub**](https://www.zenhub.com/)
