### ISSUE TITLE
Provide ability to load products by SKU[]

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1063]
Provide ability to load products by SKU

### Expected behavior
load products by SKU

### Actual behavior
now we have API method to get products by ID only

**Comment by tatarincev** [comment]
You might use ICatalogSearchService for this task
```
ICatalogSearchService.Search(new SearchCriteria { Code = "product sku", ResponseGroup = SearchResponseGroup.WithProducts }).Products.FirstOrDefault();
```
