### ISSUE TITLE
Catalog module: Make product assets management similar as images

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1064]
Toolbar with next commands (Add, Link, Remove)
Grid with  next columns (mimetype, size, name)
Grid row actions (Download, copy link, delete)

**Comment by tatarincev** [comment]
file size does not displayed for newly uploaded asset.
Steps to reproduce:
1. Open assets blade
2. Click Add command on toolbar
3. Upload new file
4. Assets will displayed in assets list but column with size will be empty
5, Click save product
6. Open assets list again and  columns size will contains value

**Comment by ksavosteev** [comment]
fixed bug, need to update platform (dev branch)
