### ISSUE TITLE
Add 3th party image editor for new images 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1066]
The editor should be able to сcrop, rotate and change size for new image

**Comment by ksavosteev** [comment]
Image editor;
https://github.com/partnermarketing/pm-image-editor

**Comment by ksavosteev** [comment]
moved to On Hold because Image Editor directive doesn't provide an ability to save edited files

**Comment by OlegoO** [comment]
Look on
http://mattketmo.github.io/darkroomjs/

**Comment by Woland2k** [comment]
Look at this (maintained version of ngImgCrop): https://github.com/CrackerakiUA/ui-cropper

**Comment by OlegoO** [comment]
We should create a new module based on aviary
https://www.aviary.com/
https://creativesdk.adobe.com/docs/web/#/articles/gettingstarted/index.html
https://creativesdk.adobe.com/docs/web/#/articles/imageeditorui/index.html
