### ISSUE TITLE
Plug 3th party chats on fs-demo

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1068]

**Comment by megafreeman** [comment]
Zendesk chat was plugged as 3rd party chat on b2b theme.
https://www.zopim.com/zendesk
![image](https://user-images.githubusercontent.com/7536694/28519107-a09605fa-706a-11e7-93cb-2bb0008ddccf.png)
![image](https://user-images.githubusercontent.com/7536694/28519130-b845e418-706a-11e7-8af0-5e2fff67e791.png)

**Comment by megafreeman** [comment]
Commit link: https://github.com/VirtoCommerce/vc-b2b-theme/commit/a0a6b74a20bb0e22fe4aa8c37582e1a8d4fc674c
