### ISSUE TITLE
Hide prices and buy buttons on fs-demo for anonymous users

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1069]

**Comment by IgorisB** [comment]
For B2B store only

**Comment by megafreeman** [comment]
For b2b theme sign in button with corresponding text is displayed instead product price.
![image](https://user-images.githubusercontent.com/7536694/28519336-741331b4-706b-11e7-8e4a-d6664906479b.png)
![image](https://user-images.githubusercontent.com/7536694/28519364-8f9c1432-706b-11e7-82b9-d87b270ad9ca.png)
![image](https://user-images.githubusercontent.com/7536694/28519380-a3c4acd0-706b-11e7-86ff-7dda7954a005.png)

**Comment by megafreeman** [comment]
Commit link: https://github.com/VirtoCommerce/vc-b2b-theme/commit/dd5cfa1aa17e040d2c081260ab244d783eddc27e
