### ISSUE TITLE
Write instructions describing the search phrase syntax 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1073]
Better do inline help  in manager near search boxes.

**Comment by artem-dudarev** [comment]
We already have this documentation:
https://github.com/VirtoCommerce/vc-module-search#search-phrase-syntax

Just need to copy it to vc-module-core or create an article on vc.com

**Comment by tatarincev** [comment]
Repeat: Better do inline help in manager near search boxes.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. https://virtocommerce.atlassian.net/browse/PRD-47
