### ISSUE TITLE
Catalog CSV import enhancement

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1074]
**Functional requirements:**
- [x] Allow to select  encoding for csv file
- [ ]  Work with mapping  configuration presets (define, store, choose)
- [ ] Preview changes before import (new metadata, list of  changes  for each object type)
- [x] More verbose error informing with showing concrete line in csv file where error occur
- [ ] Data validation and display all validation errors before import process
- [x]  Allow to partial update product even simple properties not only nested collections (update exist object should not be destructive, any deletion not permitted) 
- [x]  Allow to forbid the property metadata changes (new dict values creation)
- [x]  Unobtrusive importing data cleanup (trim spaces)
- [ ]  Support the import of product associations
- [ ]  Support the import of multilingual values (descriptions, seo etc)
- [x]  Support for import property  multi-values

**Comment by Woland2k** [comment]
Need support for saving mappings so future imports can be done faster.

**Comment by OlegoO** [comment]
We should test all VC properties types.
Support import prices.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-8
