### ISSUE TITLE
Searching Assets with Azure Search

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1076]
If we configure Azure Storage for Assets, we should index Documents in Azure Blob Storage with Azure Search.

https://docs.microsoft.com/en-us/azure/search/search-blob-storage-integration 
https://docs.microsoft.com/en-us/azure/search/search-howto-indexing-azure-blob-storage

### Expected behavior
Activate Azure Search for Assets and use  Azure Search in VC Admin to search by keyword

**Comment by tatarincev** [comment]
Can I close this issue, because it duplicated it?
https://github.com/VirtoCommerce/vc-platform/issues/1039
