### ISSUE TITLE
Size displayed as NaN Bytes in themes list

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1078]
![image](https://user-images.githubusercontent.com/1566470/28559639-34dccefe-70cc-11e7-9954-06c3ffbb3893.png)

**Comment by ksavosteev** [comment]
https://github.com/VirtoCommerce/vc-module-content/commit/183dc226ddb86ca138d6c9ea6d7b3ca15593434f

![image](https://user-images.githubusercontent.com/20122385/28616959-e317a9e8-71fe-11e7-9851-5977e9f996ec.png)
