### ISSUE TITLE
B2B module : Importing demo sample data failed

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1079]
Steps to reproduce:
1. download sample data from this url
http://virtocommerce.blob.core.windows.net/sample-data/clothing-and-electronics_2_13_10_demo.zip
2. Open Export&Import  in main menu
3. Upload zip with previously downloaded data
4. Choose only `VirtoCommerce.Customer` module
5. Click start import
6. Receive the error `VirtoCommerce.Customer: Validation failed: -- You must specify an unique email and the ony one. You must specify an existing company and the ony one.`

**Comment by asvishnyakov** [comment]
Yep, it's fails and it's right behavior. Look at your exported data: there is no organizations & emails for Bob Marley:
![untitled1](https://user-images.githubusercontent.com/6369252/28589121-316fe876-7196-11e7-90fa-bfa4e8bb2876.png)

**Comment by asvishnyakov** [comment]
Not actual after latest changes related to B2B functionality
