### ISSUE TITLE
Customers want 10% on all Products in stock

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1080]
Customers want 10% on all Products in stock

### Expected behavior
Create a new promotion based on inventory 10% on all Products in stock (Inventory.Quantity > 0)

**Comment by OlegoO** [comment]
[Marketing Module]
* Add new attributes into Promotion Context (InStockQuantity)
* Extend UI
![image](https://user-images.githubusercontent.com/7639413/28620516-8a6e7d76-720d-11e7-942a-fe9e7c4f8b54.png)
* Update evaluator

[Storefront]
* Set PromotionContext.InStockQuantity on storefront to check

* Acceptance Criteria:
Create a new promotion based on inventory 10% on all Products in stock (Inventory.Quantity > 0)
Promotions should be applied only on product with Inventory.Quantity > 0 only

**Comment by megafreeman** [comment]
Added new condition for promotions based on inventory count for all product
![image](https://user-images.githubusercontent.com/7536694/28717364-c3a137b0-73a1-11e7-95ff-e2213d959383.png)
![image](https://user-images.githubusercontent.com/7536694/28717412-f616ebea-73a1-11e7-8cba-7effa57cb5f6.png)
![image](https://user-images.githubusercontent.com/7536694/28717467-30820c9c-73a2-11e7-8efe-8b195d0cba2d.png)
https://github.com/VirtoCommerce/vc-module-dynamic-expressions/commit/300bdbe0bcbc7f83cf43052913b30873f0929d85

**Comment by megafreeman** [comment]
Promotion condition with InStockQuantity parameter was improved. Now we can create promotion with different discounts depend on quantity of inventory in stock.
Here we created 3 promotions with different percent of discount. Discount depends on quantity of products in stock.
![image](https://user-images.githubusercontent.com/7536694/28964459-1ad83fb8-790d-11e7-919b-7eef6d84dbb0.png)

In catalog we set different in stock count of inventory in some products
![image](https://user-images.githubusercontent.com/7536694/28964560-92290ee4-790d-11e7-8710-3fdf27fab163.png)
![image](https://user-images.githubusercontent.com/7536694/28964565-9719709c-790d-11e7-94c1-ac6de2223dac.png)
![image](https://user-images.githubusercontent.com/7536694/28964570-9c07df6c-790d-11e7-9774-5a373de7a44c.png)

As the result we can see different discounts for products
![image](https://user-images.githubusercontent.com/7536694/28964668-09d0ddfa-790e-11e7-88f1-eb8be0181ce5.png)

For correct work of promotion with InStockQuantity condition don't forget to set Fulfullment center for store
![image](https://user-images.githubusercontent.com/7536694/28964765-762145e4-790e-11e7-9c2d-85e03208c246.png)

This functionality uses modules with versions:
* Core module ver. 2.24.5 or above
* Marketing module ver. 2.16.5 or above
* Dynamic expressions module ver. 2.12.3 or above

Commit link: https://github.com/VirtoCommerce/vc-storefront/commit/cac565aa90697b1405e1f859cc387760919f608a

@artem-dudarev @OlegoO @asvishnyakov could you make code review for this commit please.

**Comment by megafreeman** [comment]
In last commits the process of receiving inventory for cart items was refactored to get data from the one method with cache. The obtained data are used in at least two cases:
1. To validate cart items with specified rules.
2. To fill the context to resolve promotion rewards.

https://github.com/VirtoCommerce/vc-storefront/commit/d22ecb536119e3c279bc9b795b67687d357ce127
https://github.com/VirtoCommerce/vc-storefront/commit/7d731581bba063448a2a49ee938187f926ef71a0

**Comment by megafreeman** [comment]
@alex765022 was assigned for code review

**Comment by alex765022** [comment]
Reviewed.
