### ISSUE TITLE
Modifying existing content publishing entry generates error

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1082]
{"message":"An error has occurred.","exceptionMessage":"Multiplicity constraint violated. The role 'PublishingGroupContentItemEntity_PublishingGroup_Target' of the relationship 'VirtoCommerce.MarketingModule.Data.Repositories.PublishingGroupContentItemEntity_PublishingGroup' has multiplicity 1 or 0..1.","exceptionType":"System.InvalidOperationException","stackTrace":"   at System.Data.Entity.Core.Objects.DataClasses.EntityReference`1.VerifyNavigationPropertyForAdd(IEntityWrapper wrapper)\r\n   at System.Data.Entity.Core.Objects.EntityEntry.AddRelationshipDetectedByGraph(Dictionary`2 relationships, Object relatedObject, RelatedEnd relatedEndFrom, Boolean verifyForAdd)\r\n   at System.Data.Entity.Core.Objects.EntityEntry.DetectChangesInRelationshipsOfSingleEntity()\r\n   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChangesInNavigationProperties(IList`1 entries)\r\n   at System.Data.Entity.Core.Objects.ObjectStateManager.DetectChanges()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.DetectChanges()\r\n   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)\r\n   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)\r\n   at System.Data.Entity.DbSet.Add(Object entity)\r\n   at VirtoCommerce.Platform.Data.Infrastructure.EFRepositoryBase.Add[T](T item) in D:\\Work\\Code\\Git\\vc\\vc-platform\\VirtoCommerce.Platform.Data\\Infrastructure\\EFRepositoryBase.cs:line 211\r\n   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.<>c__DisplayClass1_0.<GetChangeTracker>b__1(Object x) in D:\\Work\\Code\\Git\\vc\\vc-platform\\VirtoCommerce.Platform.Data\\Infrastructure\\ServiceBase.cs:line 30\r\n   at VirtoCommerce.Platform.Core.Common.ObservableChangeTracker.<Attach>b__8_0(Object sender, NotifyCollectionChangedEventArgs args) in D:\\Work\\Code\\Git\\vc\\vc-platform\\VirtoCommerce.Platform.Core\\Common\\ObservableChangeTracker.cs:line 32\r\n   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)\r\n   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)\r\n   at System.Collections.ObjectModel.Collection`1.Add(T item)\r\n   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.<>c__DisplayClass7_0`1.<Patch>b__0(EntryState state, T x, T y) in D:\\Work\\Code\\Git\\vc\\vc-platform\\VirtoCommerce.Platform.Core\\Common\\CollectionExtensions.cs:line 110\r\n   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.CompareTo[T](ICollection`1 source, ICollection`1 target, IEqualityComparer`1 comparer, Action`3 action) in D:\\Work\\Code\\Git\\vc\\vc-platform\\VirtoCommerce.Platform.Core\\Common\\CollectionExtensions.cs:line 135\r\n   at VirtoCommerce.Platform.Core.Common.CollectionExtensions.Patch[T](ICollection`1 source, ICollection`1 target, IEqualityComparer`1 comparer, Action`2 patch) in D:\\Work\\Code\\Git\\vc\\vc-platform\\VirtoCommerce.Platform.Core\\Common\\CollectionExtensions.cs:line 118\r\n   at VirtoCommerce.MarketingModule.Data.Model.DynamicContentPublishingGroupEntity.Patch(DynamicContentPublishingGroupEntity target)\r\n   at VirtoCommerce.MarketingModule.Data.Services.DynamicContentServiceImpl.SavePublications(DynamicContentPublication[] publications)\r\n   at VirtoCommerce.CacheModule.Data.Decorators.MarketingServicesDecorator.SavePublications(DynamicContentPublication[] publications)\r\n   at VirtoCommerce.MarketingModule.Web.Controllers.Api.MarketingModuleDynamicContentController.UpdateDynamicContentPublication(DynamicContentPublication publication)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Cors.CorsMessageHandler.<HandleCorsRequestAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()"}

### Expected behavior
Should save the new modified entry

### Actual behavior
Generates javascript exception

### Steps to reproduce
1. Go to Marketing->Content Publishing and create new entry.
2. After saving new entry, open it again in edit mode.
3. Modify something and save.

**Comment by megafreeman** [comment]
@tatarincev could you check this bug please

**Comment by OlegoO** [comment]
Moved to https://github.com/VirtoCommerce/vc-module-marketing/issues/10
