### ISSUE TITLE
Can't pick organization for an existing user

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1084]
### Expected behavior
Should display a list of organizations

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/28596602-4cc2d554-714e-11e7-8a62-5e89c469193f.png)

Organization is not available.

**Comment by eMazeika** [comment]
@Woland2k @OlegoO I can't reproduce this issue with the latest code. It might be fixed already as there were significant code changes since then.
Closing the issue; feel free to reopen with more details.
