### ISSUE TITLE
When searching for something on storefront, phrase is not remembered in textbox

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1085]
### Expected behavior
Searching for "phone" and clicking enter, should refresh the page keeping "phones" entered in searchbox

### Actual behavior

searchbox is empty

**Comment by Andrew-Orlov** [comment]
![image](https://user-images.githubusercontent.com/10347112/28625584-013f55f6-721d-11e7-80cf-eb1050a0749a.png)

http://demovc-public-qa.azurewebsites.net/Electronics/en-US/search?type=product&q=sony
