### ISSUE TITLE
Can see products from other catalog by short seo-link 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1086]
I can see see products from other store/catalog by short seo-link 

Version info: 
- Browser version: Any
- Platform version: 2.13.11

### Expected behavior
Get 404 error if try to open product by seo link from other catalog

### Actual behavior
http://demo.virtocommerce.com/Electronics/en-US/burgundy-baroque-lace-waist-dress

![image](https://user-images.githubusercontent.com/7639413/28607751-8e8ad146-71dd-11e7-9a36-a7ab4ee078b0.png)

### Steps to reproduce
1. Go to http://demo.virtocommerce.com/admin
2. Go to Store > Electronics > Set Seo Url to short
3. Open http://demo.virtocommerce.com/Electronics/en-US/burgundy-baroque-lace-waist-dress

**Comment by artem-dudarev** [comment]
Fixed: https://github.com/VirtoCommerce/vc-storefront/commit/09630d88756f6fe73abce7ce2d6f1cc28f0c5404
