### ISSUE TITLE
add store availability in storefront

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1093]
Customer should be able to pick which store to pick up item from. Use geo location to determine nearest store (in our case store is a fulfillment center) that has item available in stock.

![image](https://user-images.githubusercontent.com/1566470/28694455-793c8454-72de-11e7-975c-b36ae61e140b.png)

![image](https://user-images.githubusercontent.com/1566470/28694459-8087eafa-72de-11e7-82a1-e01984fb82b6.png)

**Comment by tatarincev** [comment]
There is already some implementation of this on the B2B theme
![image](https://user-images.githubusercontent.com/7566324/71475023-11560480-27e7-11ea-9166-f40b665f05f8.png)
