### ISSUE TITLE
Wrong totals 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1096]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Firefox
- Platform version: 2.13.11

### Expected behavior
See correct total

### Actual behavior
Product 
![image](https://user-images.githubusercontent.com/7639413/28718480-8a6dd660-73a6-11e7-80d8-e1ef4345bc9b.png)

Cart 
![image](https://user-images.githubusercontent.com/7639413/28718487-95c5af06-73a6-11e7-9c94-a51a99ace174.png)

Checkout
![image](https://user-images.githubusercontent.com/7639413/28718531-cea6ce72-73a6-11e7-9437-1699514d5f31.png)

Thank you page
![image](https://user-images.githubusercontent.com/7639413/28719334-daa5f61e-73a9-11e7-9d82-7eb25937131f.png)

Order 
![image](https://user-images.githubusercontent.com/7639413/28718640-1f77c7b6-73a7-11e7-9e14-a628343a222e.png)

Order in admin
![image](https://user-images.githubusercontent.com/7639413/28718998-9c5e8732-73a8-11e7-8a9e-d398f931d880.png)

![image](https://user-images.githubusercontent.com/7639413/28719067-e27cae92-73a8-11e7-93de-a2462bb9ad50.png)

### Steps to reproduce
Create an order

**Comment by asvishnyakov** [comment]
I think this may be because of Stripe checkout (see 3rd screenshot)

**Comment by Andrew-Orlov** [comment]
Seems that there is a disambiguation within a `price` and a `price with taxes` terms.

**Comment by Andrew-Orlov** [comment]
Added totals details for a customer order on thank-you page (similar to checkout totals). Changed label for line item totals and a value of line item totals on widget for a customer order.
![image](https://user-images.githubusercontent.com/10347112/28783981-59e27c12-7612-11e7-9c9b-7b5ca661cec4.png)
![image](https://user-images.githubusercontent.com/10347112/28783966-4af8efd8-7612-11e7-9499-edce31f2b2ce.png)
