### ISSUE TITLE
Why does it take so long to see the error message If connection string is broken.

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1101]
Why does it take so long to see the error message If connection string is broken.

Version info: 
- Platform version: 2.13.12

### Expected behavior
Get user friendly error message asap if sql connection is invalid.
Maybe we should have multi step health check before start.

### Actual behavior
We should wait for a long time  If connection string is broken.

### Steps to reproduce
1. Download platform
2. Setup wrong SQL Connection 
3. Start and wait, .....

**Comment by OlegoO** [comment]
#1098

**Comment by asvishnyakov** [comment]
Research:
The difference between platform startup with already created db and newly created db is about ~30 sec (for me):
![screenshot 332](https://user-images.githubusercontent.com/6369252/29048961-d995a7f6-7bec-11e7-9d52-b027c55e9cf6.png)
Most part of this time is taken by db creation and first db initialization (migrations apply):
![screenshot 333](https://user-images.githubusercontent.com/6369252/29049000-0fea976c-7bed-11e7-9f09-4366f663ac1a.png)
![screenshot 334](https://user-images.githubusercontent.com/6369252/29049003-12d7cd82-7bed-11e7-8a99-4f5c92966014.png)
We need to do that asynchronously from UI. Starting research about possible UI progress about platform initialization.

**Comment by Woland2k** [comment]
The main use case that didn't work, is when connectionstring is incorrect, it takes 10 min to get an error.

**Comment by asvishnyakov** [comment]
@Woland2k  In this case, for me, platform is freeze for at least 30 min. But it doesn't matter, because it caused by the same code.

**Comment by asvishnyakov** [comment]
#1110

**Comment by asvishnyakov** [comment]
#1117
