### ISSUE TITLE
Provide ability to get  either debug version or map file for modules scripts

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1102]
To simplify development process with runtime version of platform.
We should have ability to get  either debug version or map file for modules scripts.

Version info: 
- Platform version: 2.13.12

### Expected behavior
get  either debug version or map file for script.
/admin/scripts/angular
/admin/scripts/modules

### Actual behavior
We have one minimized bundle

**Comment by asvishnyakov** [comment]
I can't reproduct issue (if I set debug attribute to true for platform compiled in release mode, bundles does not minify and combine files). But debug attribute affect not only bundles, so we may not revert commit to have separate option to disable/enable bundle optimizations.

**Comment by asvishnyakov** [comment]
Already in release
