### ISSUE TITLE
Switch to environmental variables for connection strings

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1105]
### Expected behavior
When environmental variable is specified, use that instead of always getting from settings.
So it repositories and others should utilize https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Data/Common/ConnectionStringHelper.cs class. 

### Actual behavior
Some settings (during initialization) are taken from environmental variables and some are not.

### Steps to reproduce
1.

**Comment by artem-dudarev** [comment]
* Use environment variables with `VIRTO_CONN_STR_` prefix
* Use ConnectionStringHelper to get the connection string value:
``` C#
using VirtoCommerce.Platform.Core.Common;
var connectionStringValue = ConnectionStringHelper.GetConnectionString(nameOrConnectionString);
```
