### ISSUE TITLE
Can't install modules when the platform version is not the latest version

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1108]
Version info: 
- Browser version: 
- Platform version: 2.13.12
- Module version: 

### Expected behavior
It should download latest versions available for my platform release. This basically will prevent all our installations completing in azure environments at the moment.

### Actual behavior
Displays error and stops installation.

![image](https://user-images.githubusercontent.com/1566470/28983274-e1179dcc-790d-11e7-9355-ed2097245e98.png)

### Steps to reproduce
1.

**Comment by tatarincev** [comment]
Need to update platform to  `2.13.14` or higher to solve this dependency check issue.

**Comment by asvishnyakov** [comment]
@tatarincev He mean that we should install latest compatible with platform version of module
