### ISSUE TITLE
Missing resized images after data import

### ISSUE THREAD

**Issue by dimitri-ak** [VirtoCommerce/vc-platform#1112]
Version info: 
- Browser version: Chrome Version 60.0.3112.90
- Platform version: 2.13.14
- Module version: latest commerce group

### Expected behavior
After data import should have images with all necessary sizes - *_64x64.jpg, _168x168.jpg, *_348x348.jpg
### Actual behavior
Getting errors that images are missing

**Comment by tatarincev** [comment]
This is required of enabling this setting
![image](https://user-images.githubusercontent.com/7566324/71475339-6cd4c200-27e8-11ea-985b-8bd4449c5b71.png)
