### ISSUE TITLE
Pricing module - display product price lists depending on the navigation catalog

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1115]
### Expected behavior
System should display only price lists with have assignments to this (active) virtual catalog

### Actual behavior
System display price lists only with have assignments to physical catalog of product

### Steps to reproduce
Open virtual catalog -> open any of linked product -> click to prices widget

**Comment by IgorisB** [comment]
I propose to show all pricelists for the product without looking into assignments. Basically product blade is the same for all catalogs and can be opened without any catalog context, right? How you recognise active catalog?

**Comment by asvishnyakov** [comment]
@IgorisB It's not accurate, but it's possible now. In gitter, client asks to blade navigation routing. If we implement this feature, it will be easy to get current routing path and make custom logic based on it. @tatarincev So I think we don't need to resolve this issue right now.

**Comment by megafreeman** [comment]
To resolve this issue the following tasks were implemented:
1. Price widget in product detail blade now shows the price for the current catalog, ex. virtual catalog.
2. Pricelist list was reconfigured to display assigned catalog(s).

![image](https://user-images.githubusercontent.com/7536694/29514372-9b0a5f5a-8668-11e7-8cba-1c4a423152b5.png)

If there is no assigned price list for the catalog, then the price for the goods will not be displayed in price widget.
![image](https://user-images.githubusercontent.com/7536694/29514512-26b9784c-8669-11e7-8ee5-c65605c21773.png)

https://github.com/VirtoCommerce/vc-module-pricing/commit/6fef138d5dbd7de7da1041a3d134450a773fa2af
https://github.com/VirtoCommerce/vc-module-pricing/commit/ebb1204bce0d5dd45591382fb3c7eec6af4b823f

**Comment by tatarincev** [comment]
Product prices blade should display the list of avail prices instead of the price lists. This is a key difference from how it is done now.

**Comment by megafreeman** [comment]
As an option, the future product prices list can be as follows:

List Price | Currency | Price List | Catalog
------------- | ------------- | ------------- | -------------
1256 | USD | ElectronicsUSD | Electronics
1300 | USD | ElectronicsVirtualUSD | Electronics virtual
1012 | EUR | ElectronicsEUR | Electronics
1022 | EUR | ElectronicsVirtualEUR | Electronics virtual
1212 | USD | ElectronicsSpecialUSD | Electronics, Electronics virtual

**Comment by tatarincev** [comment]
It covers only prices display, also we need functionality to adding new prices to the product in the specified price list.

**Comment by tatarincev** [comment]
Here is desired product prices management view
![image](https://user-images.githubusercontent.com/7566324/29558609-eb720992-872c-11e7-8828-09729defa0aa.png)

**Comment by asvishnyakov** [comment]
@tatarincev Nowhere in platform we have similar UI. Usually we add "Add" button on toolbar and open new blade with OK/Cancel buttons where user can fill all needed fields lke Sale/List. I don't mean we should doing it in the way I described, but I think we need another UI.

**Comment by tatarincev** [comment]
Here is one example similar UI
![image](https://user-images.githubusercontent.com/7566324/29559923-bd2c7334-8730-11e7-8ed7-0de647cf85f1.png)

**Comment by asvishnyakov** [comment]
@tatarincev Ok, just in your sketch it looks like combobox and button is placed in balde-static area, where search appear

**Comment by Woland2k** [comment]
My view:
Add price should be on top (in toolbar).
Now when I click "Add" button, this happens:

Case 1 "No price lists".
No price list is defined, show message with a link that opens new blade to create new price list and automatically assign it to the catalog, then proceed to a case 2.

Case 2 "One price list". 
In case when there is only 1 price list defined, it should just pick that price list and add a new row with default price.

Case 3 "Multiple price lists".
In this case, open blade on the right that allows to select price list, once it is selected, add new row in the grid with a select price and proceed further.
