### ISSUE TITLE
Catalog personalization: Domain model implementation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1119]
### Functional requirements
- [ ] Extend product and categories indexation process to store with these object associated with them tags in 'UserGroups' field. (see  example how to extend product index https://github.com/VirtoCommerce/vc-module-pricing/tree/master/VirtoCommerce.PricingModule.Data/Search)
- [ ] Provide tagged values inheritance down of the object hierarchy in the search index
- [ ] Provide full module state export/import within common platform export/import process.

![personalization module - domain model](https://user-images.githubusercontent.com/7566324/29622885-e5882856-8824-11e7-805b-a85f8660cbd7.jpg)

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog-personalization #2](https://github.com/VirtoCommerce/vc-module-catalog-personalization/issues/2) via [**ZenHub**](https://www.zenhub.com/)
