### ISSUE TITLE
Catalog personalization: Create new vc-catalog-personalization module

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1120]
Use [VisualStudio template](https://github.com/VirtoCommerce/vc-visualstudio-templates) for module creation

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog-personalization #3](https://github.com/VirtoCommerce/vc-module-catalog-personalization/issues/3) via [**ZenHub**](https://www.zenhub.com/)
