### ISSUE TITLE
Catalog personalization: Applying personalization on the storefront

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1121]
- [ ] Read `UserGroups` from logged in customer  and pass it in the products and categories search request
- [ ] Use `UserGroups`  from logged in customer for filtration content menu link items

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog-personalization #4](https://github.com/VirtoCommerce/vc-module-catalog-personalization/issues/4) via [**ZenHub**](https://www.zenhub.com/)
