### ISSUE TITLE
Subscription module: Layout bug in UI tree 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1122]
1.![image](https://user-images.githubusercontent.com/7566324/29213366-3b3c2d78-7ea3-11e7-8dd5-78480a41abd6.png)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-subscription #2](https://github.com/VirtoCommerce/vc-module-subscription/issues/2) via [**ZenHub**](https://www.zenhub.com/)
