### ISSUE TITLE
Order module - Tons of JS errors in order list and in store filtering properties widget

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1134]
### Steps to reproduce:
Open orders lists -> Add Status column in the grid
Get tons of errors 
`Cannot read property toLowerCase' of undefined`

**Comment by asvishnyakov** [comment]
![screenshot 339](https://user-images.githubusercontent.com/6369252/29560004-2329e112-874a-11e7-95e2-fa34ed325351.png)
Some of Store widgets is not working because of the same error.

**Comment by eMazeika** [comment]
Some orders in sample data has undefined status. @tatarincev, review this code fix and decide if need to fix sample data.

**Comment by tatarincev** [comment]
No,  fix for sample data, not needed
