### ISSUE TITLE
Catalog module: Switch product and category details to  use meta-form

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1139]
Need to replace [item-detail.tpl.html](https://github.com/VirtoCommerce/vc-module-catalog/blob/master/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html)  and [category-detail.tpl.html](https://github.com/VirtoCommerce/vc-module-catalog/blob/master/VirtoCommerce.CatalogModule.Web/Scripts/blades/category-detail.tpl.html) views to use meta-form instead 'hard coded' fields list. (see meta-form usages examples [using in template]( https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Web/Scripts/blades/customerOrder-detail.tpl.html#L10) and [form initialization](https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Web/Scripts/order.js#L82))

### How to article:
https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/basic-functions/metaform

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #41](https://github.com/VirtoCommerce/vc-module-catalog/issues/41) via [**ZenHub**](https://www.zenhub.com/)
