### ISSUE TITLE
Export catalog category prices

### ISSUE THREAD

**Issue by slang123** [VirtoCommerce/vc-platform#1140]
Version info: 
- Browser version: Chrome, Version 60.0.3112.101 (Official Build) (64-bit)
- Platform version: 2.13.14
- Module version: VirtoCommerce.Catalog 2.18.16

# Export catalog category prices.

### Expected behavior
I should be able to select a pricelist when exporting a catalog.
### Actual behavior
select list is empty
### Steps to reproduce
1. Select Catalog
2. Select Category
3. Export
![export-prices](https://user-images.githubusercontent.com/7000708/29615978-bbbb5da8-8807-11e7-9c2a-08326904e1ff.PNG)

**Comment by tatarincev** [comment]
This feature has already implemented in the following modules:
https://github.com/VirtoCommerce/vc-module-export
https://github.com/VirtoCommerce/vc-module-pricing/releases/tag/v2.18.8
