### ISSUE TITLE
Klarna payment modules Euro/US : Update VC nuget dependencies to latest versions

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1141]
- [ ] Update all VirtoCommerce NuGet packages  to the latest version for all projects
- [ ] Switch all projects to .NET 4.6.1
- [ ] Ensure that all unit tests pass
- [ ] Conduct a code review for compliance with current requirements

**Comment by HtrBr** [comment]
Did You made any progress?

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-KlarnaCheckout-Euro #2](https://github.com/VirtoCommerce/vc-module-KlarnaCheckout-Euro/issues/2) via [**ZenHub**](https://www.zenhub.com/)
