### ISSUE TITLE
Catalog personalization: Integration to the catalog management UI 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1142]
- [ ] Extend `Product` and `Category` details meta-forms with new listbox field `User groups` which support multi selection and gets available data from  `UserGroups` setting defined in customer module. Actual selected data for host objects should be taken from personalization module API. `api/personalization/taggeditems/{id}/{type}` 
- [ ] All of this 'User groups' field changes does not a part of the host product changes transaction and all of these changes must be immediately send to the API.

**Comment by megafreeman** [comment]
@tatarincev @IgorisB @Woland2k 
As an alternative implementation of UI, I propose to consider the option using widget and two new blades to assign and manage tags.
![new wireframe 1](https://user-images.githubusercontent.com/7536694/30423518-5ea1b098-9943-11e7-9b0b-5e5832ab9f9a.png)

This blades can be used to manage tags for both users, and for product, categories, etc.

**Comment by OlegoO** [comment]
![image](https://user-images.githubusercontent.com/7639413/30424004-e1aedc80-9944-11e7-9b1d-6764c2023be0.png)

**Comment by megafreeman** [comment]
@IgorisB @Woland2k 
Do we need to support a large number of tags? It depends on whether we need searching, sorting and pagination in blades.

**Comment by Woland2k** [comment]
1. Ticket should be moved under personalization module
2. UI proposed by @OlegoO is good with grid list (that way we can support unlimited number of tags).
3. Create UI for adding/removing tags from list of available tags.

**Comment by megafreeman** [comment]
After discussion with @tatarincev we came to the conclusion that in this case, we need to create just one blade to assign and remove tags. For managing all tags we will use the standard settings dictionary editor blade.
![new wireframe 1 copy](https://user-images.githubusercontent.com/7536694/30488120-bf056522-9a35-11e7-9b4a-cdc5a75e95f7.png)

**Comment by megafreeman** [comment]
@Woland2k 
About the first item of your message, this ticket is a part of Epic and Sprint. So, if I will move this ticket under personalization module, then I should move other tickets from this Sprint too. Maybe we should finish this Sprint in current repository, and new tickets will create under personalization module?

**Comment by Woland2k** [comment]
@megafreeman tickets should be created in the module they are related to, so yes, move them, right now they are in platform which they don't have any connection to

UI doesn't look very user friendly, as it is not clear when you need to click save and when you need to click delete and to what those action correspond

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog-personalization #1](https://github.com/VirtoCommerce/vc-module-catalog-personalization/issues/1) via [**ZenHub**](https://www.zenhub.com/)
