### ISSUE TITLE
Not work order products by created date

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#1146]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: All
- Platform version: 2.13.15

### Expected behavior
Products sorted by created date
### Actual behavior
Products not sorted by crearted date
### Steps to reproduce
1. Open category with products
![image](https://user-images.githubusercontent.com/14821555/29660831-95d9c9ba-88c2-11e7-8743-1160f9c13a18.png)

2. Select sort filter "Date, new to old", products sorted
![image](https://user-images.githubusercontent.com/14821555/29660888-c2438f4a-88c2-11e7-812c-bc90efac23cc.png)
3. Select sort filter "Date, old to new", page reloaded, but list of product not changed
![image](https://user-images.githubusercontent.com/14821555/29660947-ee19161c-88c2-11e7-86eb-fc7c632454b8.png)

**Comment by Andrew-Orlov** [comment]
Seems that storefront pass the `created` query string parameter but search index contains the property `createddate`.

**Comment by Andrew-Orlov** [comment]
Fixed in the default storefront theme.
![scr-capture](https://user-images.githubusercontent.com/10347112/29665264-9945e578-88d3-11e7-85b2-b8748dbbe31d.gif)

**Comment by alex765022** [comment]
Reviewed.
