### ISSUE TITLE
When autoinstall is called through API, "system" user is hard coded preventing getting notifications

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1147]
### Expected behavior
"/api/platform/modules/autoinstall" should either require authentication, or allow passing the userid which then can be used to get pushnotification and status of module installs.

### Actual behavior
Notification is created like this:
var notification = new webModel.ModuleAutoInstallPushNotification("System")

with hard coded system user.

**Comment by tatarincev** [comment]
@Woland2k  please review my commit

**Comment by Woland2k** [comment]
@tatarincev you fixed sample data, that import actually worked just fine as it had special method called state ... autoinstall for modules is the one that doesn't work
