### ISSUE TITLE
Make username editable

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#1148]
From admin UI we should be able to edit usernames.

**Comment by tatarincev** [comment]
Visual bug with username edit.
How to reproduce:
Edit username for an account
Click save
User detail blade will lose context and become without data (all input fields are empty)

**Comment by ksavosteev** [comment]
Can't reproduce the bug, maybe js file was cached?

**Comment by tatarincev** [comment]
Try to set sorting by username in the grid
