### ISSUE TITLE
Create anonymous statistics gathering platform feature

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1150]
This feature should be similar to how jenkins gathers plugin and installs statistics and should be anonymous (no personal identifying info included).

Some reference is available here: https://wiki.jenkins.io/display/JENKINS/Plugin+Installation+Statistics

It should be possible to turn it on/off using platform settings screen.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
