### ISSUE TITLE
Make Account assignable to Contacts/Employees

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#1151]
Riight now when we open up a contact details blade we can go to the Account blade to create an account associated to this contact. Though we can't assign an account that is already created.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-customer #4](https://github.com/VirtoCommerce/vc-module-customer/issues/4) via [**ZenHub**](https://www.zenhub.com/)
