### ISSUE TITLE
Create command line step-by-step installation scripts for development environment

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1153]
Now it's very hard to install and configure VirtoCommerce Platform, Storefront, modules & themes from source source. We need to command line step-by-step installation scripts which will create basic development environment on developer machine.

**Comment by OlegoO** [comment]
#492

**Comment by tatarincev** [comment]
Please look at this repository https://github.com/VirtoCommerce/vc-module-training-docker it should simplify the platform dev env setup.
