### ISSUE TITLE
Selecting "empty" as sample data causes UI to display no browse links

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1155]
### Expected behavior
Should display all modules.

Refreshing the browser fixed the issue:
![image](https://user-images.githubusercontent.com/1566470/30302042-4d9a18f8-9713-11e7-9818-aa2049b2e2dd.png)

### Actual behavior
Only "Assets" is displayed under browse, although all modules has been installed.

![image](https://user-images.githubusercontent.com/1566470/30302004-114fed5a-9713-11e7-9d5c-04c3f07488f9.png)

### Steps to reproduce
1. Setup a new environment (preferably using docker up -d) and navigate to admin.
2. Login and wait until all modules are setup and click restart.
3. On restart select "empty".

**Comment by eMazeika** [comment]
First task for trainee: verify if this is still actual.

**Comment by adminoren** [comment]
Installed platform 2.13.40 manually from release, after modules intallation checked "empty" instead of demo data. All menu items in "browse" are shown correctly. Checked in chrome and mozilla.
I also checked deployment via docker, after modules installation there were all items in browse menu.

**Comment by eMazeika** [comment]
@adminoren , in such cases move the pipeline to the next status then ("Review/DEV")
