### ISSUE TITLE
Update styleguide and blade constructor

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1160]
Both should have the latest code and controls used by platform:

https://virtocommerce.com/styleguide/index.html
https://virtocommerce.com/styleguide/blade-constructor.html

**Comment by Andrew-Orlov** [comment]
Where can I find sources for Blade Constructor?

**Comment by Woland2k** [comment]
@Andrew-Orlov  https://github.com/VirtoCommerce/vc-platform/tree/master/Design/documentation

Next time, please check with @tatarincev on where to find files.

**Comment by Andrew-Orlov** [comment]
HTML files was updated on production.

**Comment by Woland2k** [comment]
Blade constructor is still buggy:
![image](https://user-images.githubusercontent.com/1566470/30617494-2652adda-9d4b-11e7-99a4-494df23992fe.png)

**Comment by Andrew-Orlov** [comment]
@Woland2k Repository [https://github.com/VirtoCommerce/vc-platform/tree/master/Design/documentation](https://github.com/VirtoCommerce/vc-platform/tree/master/Design/documentation) doesn't contain actual file versions. At least production content doesn't equal to these files. I had to take actual HTML files from production, change and upload them once again.
