### ISSUE TITLE
Change markdown dialog to split mode when maximized

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1165]
Currently when maximized, markdown view is displayed with tabs (markdown and preview) which need to be switched manually to see how content looks like:
![image](https://user-images.githubusercontent.com/1566470/30629932-2ec45818-9d93-11e7-8510-eb16dc58ab2c.png)

Change this to split view instead when certain width is reached so there is no need to manually switched to preview mode when editing content (it is a setting of the control).

![image](https://user-images.githubusercontent.com/1566470/30630121-0653c8ae-9d94-11e7-8977-d74619006f70.png)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-core #11](https://github.com/VirtoCommerce/vc-module-core/issues/11) via [**ZenHub**](https://www.zenhub.com/)
