### ISSUE TITLE
When product updated property value ids always changed

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-platform#1166]
Please provide updating property values instead re-creating.

Version info: 
- Browser version: Any
- Platform version: 2.13.15
- Module version: Catalog module v2.19.2

### Expected behavior
When product updated existing property values must be updated

### Actual behavior
When product updated existing property values are re-created

### Steps to reproduce
1. Before product update
![image](https://user-images.githubusercontent.com/7644848/30702402-1d4cb016-9eed-11e7-8d96-6d550e1f61ab.png)

2. After product update
![image](https://user-images.githubusercontent.com/7644848/30702442-3d03609e-9eed-11e7-940e-897b5ebb07a5.png)

**Comment by tatarincev** [comment]
I guess you do not include property values identifiers in your update request.
Without specifying property value identifier there is no way to construct equality hash code to find exist value record for update.

See the example of the right request:
Post http://localhost/admin/api/catalog/categories
```
.....
"properties":[
      {     
         "name":"boolProperty",       
         "type":"Category",
         "values":[
            {
               "propertyName":"boolProperty",             
               "valueType":"Boolean",
               "value":false,          
               "id":"a735b117e3fe4f87af3645eb57ea0cda" <-- Need secify the exist property value Id to prevent generation new records
            }
         ],
```

**Comment by OlegoO** [comment]
@alex765022 please review it
