### ISSUE TITLE
Display as much breadcrums as possible

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1170]
Based on discussion in #687
Instead of `[Root] [...] [N-1] [N]` I propose to display as much breadcrumbs as possible, i.e. display `[Root] [...] [N-3] [N-2] [N-1] [N]` if they have less width than blade.
Why:
![image](https://user-images.githubusercontent.com/6369252/30968157-cfebc934-a477-11e7-94c7-99295608a2ad.png)
Breadcrumbs is not useful for navigation in `[Root] [...] [N-1] [N]` case, because you already may easily navigate to this items via other navigation elements. The most important part of breadcrumbs, in my opinion, is an availability to navigation to one of previous parents in one click.

**Comment by eMazeika** [comment]
@asvishnyakov what problem are you referencing? Is it a general Platform issue or.... is it a suggestion for only 1 particular scenario in Catalog module (not even a part of Platform)?
If that's the first case, then DO reference Platform UI like Assets or Settings blades:
![image](https://user-images.githubusercontent.com/5801549/31003794-36aaf546-a4fa-11e7-9f4d-1b3c59821723.png)

If that's the second case, then... that's an interesting improvement for Catalogs (but NOT Platform).

**Comment by asvishnyakov** [comment]
@eMazeika Breadcrumbs must be declared in platform and be the same for all modules. Not only Platform and Catalog use breadcrumbs - Marketing, for example, too. I just want to do the same thing as you say: if blade let us to display more info in breadcrumbs - we must display more info. Just I think we may not only increase width of breadcrumbs, but display more breadcrumb items too. And it's not problem: I just describe current situation, say that I would prefer other solution and provide my version for discuss.

**Comment by asvishnyakov** [comment]
Not so bad: 
![image](https://user-images.githubusercontent.com/6369252/31007705-d6485d3a-a51a-11e7-9a68-3ab2ffc2bc2f.png)

**Comment by eMazeika** [comment]
That is exactly the problem: we don't know how much space we have and how many breadcrumb items can fit there.
As you can see, not all blades are the same. And there can't be a single "golden rule for everything".

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #310](https://github.com/VirtoCommerce/vc-module-catalog/issues/310) via [**ZenHub**](https://www.zenhub.com/)
