### ISSUE TITLE
Dynamic properties assigned to contact are not deleted after contact deletion

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1171]
Version info: 
- Browser version: Firefox 56
- Platform version: 2.13.15
- Module version: Customer module 2.14.5

### Expected behavior
After deleting user I expect all dynamic properties assigned to this user to be deleted

### Actual behavior
Dynamic properties are not deleted

### Steps to reproduce
1. Define dynamic property for Contact.
2. Create a new Contact and fill its dynamic property
3. Delete Contact.
4. In DB you will notice there are still dynamic properties that were assigned to deleted user

**Comment by tatarincev** [comment]
Need to manually delete the dynamic properties during the delete operation of the member
see example: https://github.com/VirtoCommerce/vc-module-order/blob/master/VirtoCommerce.OrderModule.Data/Services/CustomerOrderServiceImpl.cs#L164

**Comment by danielstarzewski** [comment]
I can't do it from UI? Please correct me if I am wrong but I would expect deleting Contact will delete all data associated with this Contact. Is it possible to see somewhere in UI that I have dynamic property data associated with non existing Contact?

**Comment by danielstarzewski** [comment]
Ok, so you think this is correct behavior?

**Comment by tatarincev** [comment]
I think what happened misunderstandings. :)  My comment is targeted at a developer who will fix this issue :)
Excuse me.

**Comment by danielstarzewski** [comment]
Ok ok :)

**Comment by OlegoO** [comment]
We will create a new issue in out road map
