### ISSUE TITLE
Add official and community badges to modules

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1172]
Currently all modules look the same under "modules" in virto commerce. We need to separate them and mark modules who's owner is "VirtoCommerce" as official.

Also add "Developed by Virto Commerce"", where name is taken from Owners. This should be displayed in both list and details screen.

**Comment by OlegoO** [comment]
We should display information in:
- list
- details
- add corner badge image

**Comment by OlegoO** [comment]
![image](https://user-images.githubusercontent.com/7639413/31379863-de9e97e0-adaf-11e7-8714-0fea78ea22ca.png)
![image](https://user-images.githubusercontent.com/7639413/31379990-469167ec-adb0-11e7-9dd5-afd726baf336.png)
![image](https://user-images.githubusercontent.com/7639413/31380297-416455da-adb1-11e7-993e-378b3713db44.png)

**Comment by eMazeika** [comment]
Not so informative list as too much info is displayed. Suggestion: include "Developed by.." only for NON-virto modules:
![image](https://user-images.githubusercontent.com/5801549/31386240-c81a53a0-adce-11e7-9f0a-8ca1dad3f80b.png)

**Comment by eMazeika** [comment]
Proposed UI: medal in the list and details
![image](https://user-images.githubusercontent.com/5801549/31432003-08c51db8-ae7e-11e7-8c72-044429213d92.png)

**Comment by Woland2k** [comment]
@eMazeika  Lets have this icon: http://www.iconsdb.com/guacamole-green-icons/approval-icon.html, more specifically http://www.iconsdb.com/icons/download/guacamole-green/approval-16.png

**Comment by eMazeika** [comment]
latest UI:
![image](https://user-images.githubusercontent.com/5801549/31435631-ebda754e-ae88-11e7-9e1a-8a06c3f3793f.png)
![image](https://user-images.githubusercontent.com/5801549/31435681-1ff14542-ae89-11e7-82e6-aa6b25001370.png)

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.17
