### ISSUE TITLE
Add accept terms and conditions when license is specified for a module

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1173]
Should be near install button in modules in admin. Use screenshot below as an example:

![image](https://user-images.githubusercontent.com/1566470/31329039-04b14a14-ac8d-11e7-9013-6e371ff1ea32.png)

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-7
