### ISSUE TITLE
Catalog sorting with search phrase

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-platform#1176]
Sorting does not work when search phrase specified

Version info: 
- Browser version: Any
- Platform version: 2.13.16
- Module version: Catalog module 2.20.1

### Steps to reproduce
1. Specify search phrase, ex. 'a'
2. Change sorting by any column, ex. CreatedDate

![](http://g.recordit.co/RAKQnd0CNU.gif)

**Comment by eMazeika** [comment]
That's "by design". @tatarincev should this be changed in some way to fulfill client's expectations?

**Comment by asvishnyakov** [comment]
@alex765022 @eMazeika This is just not implemented: https://github.com/VirtoCommerce/vc-module-catalog/blob/20756a22fbb7a866879812a5133553d5113f4f68/VirtoCommerce.CatalogModule.Data/Services/CatalogSearchServiceDecorator.cs#L48
And I think @alex765022 you should move issue to catalog module

**Comment by eMazeika** [comment]
@asvishnyakov you're just partially correct. If a search keyword is specified, then a client-side data grouping (and sorting) is taking place (as displayed above).

**Comment by tatarincev** [comment]
I got an error after this changes
![image](https://user-images.githubusercontent.com/7566324/31765824-fe1568d4-b4c5-11e7-8be1-d6d05b82cfde.png)

**Comment by eMazeika** [comment]
Clear browser cache as this template was removed.

**Comment by eMazeika** [comment]
How about this switch:
![image](https://user-images.githubusercontent.com/5801549/31773423-630e2080-b4eb-11e7-8e6e-551ac4508391.png)
And we could also add a "Path" column to indicate where a particular item belongs.

**Comment by eMazeika** [comment]
Latest UI (with optional grouping):
![image](https://user-images.githubusercontent.com/5801549/31822356-2eb0fe36-b5b1-11e7-9a96-ecbc062229df.png)

**Comment by tatarincev** [comment]
We decided to remove any grouping from catalog search because this operation must be made only at data source level.

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.2
