### ISSUE TITLE
Twitching icons

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-platform#1177]
Please provide stable displaying icons on search result list.

Version info: 
- Browser version: Chrome
- Platform version: 2.13.16
- Module version: Catalog module 2.20.1

### Steps to reproduce
1. Move your mouse over the icons
![](http://g.recordit.co/1NkFW1tN4L.gif)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.20.2
