### ISSUE TITLE
DateTime is not supported in module settings

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#1178]
Version info:  All platform

### Expected behavior
Set module setting type as DateTime
### Actual behavior
Get module setting type as ShortText

**Comment by asvishnyakov** [comment]
Techincally: DateTime is missed here: https://github.com/VirtoCommerce/vc-platform/blob/174b175e3d86119c3e4ced83d1b1b01e706a637e/VirtoCommerce.Platform.Data/Settings/SettingExtensions.cs#L59

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.17
