### ISSUE TITLE
Can't drag widgets to second column under category details

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1182]
### Expected behavior

Should be able to drag SEO widget next to properties (how it is displayed by default).

![image](https://user-images.githubusercontent.com/1566470/31739453-c6f5059e-b402-11e7-8e3d-dbf2abc9674f.png)

### Actual behavior
Once you start dragging, widget goes under the properties widget.

### Steps to reproduce
1. Open category details and start dragging widgets.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.18
