### ISSUE TITLE
Move product in catalog failed

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#1189]
Please provide detailed information about your issue, thank you!

### Expected behavior
Cut product in category and paste other category
### Actual behavior
Paste action returns 500 error

![image](https://user-images.githubusercontent.com/14821555/31992705-4658f3cc-b97b-11e7-8279-1219eafb4d0a.png)

Exception text:
[NullReferenceException: Object reference not set to an instance of an object.]
   VirtoCommerce.CatalogModule.Web.Model.ListEntry..ctor(String typeName, AuditableEntity auditableEntity) +38
   Void .ctor(System.String, VirtoCommerce.Platform.Core.Common.AuditableEntity)(Object[] ) +141
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) +1720
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) +727
   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id) +541

### Steps to reproduce
1. Cut product in category
2. Navigate to other category (new category)
3. Paste product

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #60](https://github.com/VirtoCommerce/vc-module-catalog/issues/60) via [**ZenHub**](https://www.zenhub.com/)
