### ISSUE TITLE
ui-grid should be more resistant to templates errors

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1190]
ui-grid should be able to detect column template loading errors (404s) and reset saved state to initial.

Version info: 
- Platform version: 2.13.16

### Expected behavior
ui-grid should display data even if a saved state contains (already removed) non-existing column template.

### Actual behavior
In some rare cases, after changing ui-grid column definition, the data is not displayed and script error raised:
Couldn't fetch/use colDef.cellTemplate

### Steps to reproduce
missing/unknown

**Comment by asvishnyakov** [comment]
Related to VirtoCommerce/vc-platform#936

**Comment by asvishnyakov** [comment]
I think, we can save only width, sort and visible properties (which user can customize) + column name. We're control saving process (we get serialized object and save it to local storage), so we can control which properties to save.
@eMazeika @tatarincev @Woland2k What's your opinion?

**Comment by eMazeika** [comment]
We shouldn't touch serialized data. But we can load only needed properties from deserialized ui-grid state. Submitted solution: omit the cellTemplate from saved state.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.18
