### ISSUE TITLE
Demo contains multiple roles with the same name

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1191]
Version info: 
- Browser version: 
- Platform version:
- Module version: 

### Expected behavior
Should only have one "Corporate Manager" etc.
### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/32020590-8b6bbd8c-b985-11e7-8197-1148ad41bee8.png)

**Comment by tatarincev** [comment]
This is due to the fact that on the demo site was installed not actual B2B module extension, which was contained some bugs. 
Issue moved to https://github.com/VirtoCommerce/vc-module-b2b-extensions/issues/4
