### ISSUE TITLE
Add check for missing owners tag in module.manifest

### ISSUE THREAD

**Issue by ksavosteev** [VirtoCommerce/vc-platform#1192]
modules-main.js, line 23, x.owners is undefined for modules with no <owners> in module.manifest
If there is such custom module installed to platform Modules blade won't open.

**Comment by asvishnyakov** [comment]
![image](https://user-images.githubusercontent.com/6369252/32042965-d2266402-ba52-11e7-88e7-663370e60898.png)
???

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.18
