### ISSUE TITLE
Notifications are not being sorted correctly

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1198]
Hello, 
Please see my issue below.

Version info: 
- Platform version: 2.13.15

### Steps to reproduce
1. Create more than 20 notifications (or as many as needed to display them on more than 1 page).
2. Navigate to Emails journal.
3. Add sent date as a visible column in the grid.
4. Sort notifications by Sent date

### Expected behavior
All notifications will be sorted - not only those displayed at the first page.

### Actual behavior
Only notifications displayed in the first page are being sorted.

Please see my exaple below:
![image](https://user-images.githubusercontent.com/30530759/32166217-6e5ff710-bd65-11e7-8567-4ac2463acd65.png)
![image](https://user-images.githubusercontent.com/30530759/32166234-7708a2ae-bd65-11e7-96ca-fd74eebe6afc.png)

In my case I would expect those two notifications from the second page to be displayed in the first page. Please look into it. 
Thank you.
Daniel

**Comment by tatarincev** [comment]
Here was skipped sorting on the data search.

**Comment by Skrypt** [comment]
I'd really love eventually seeing a search box and/or some filters on those notifications.

**Comment by tatarincev** [comment]
@Skrypt  I've added you requirement in this Epic https://github.com/VirtoCommerce/vc-platform/issues/467

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.18
