### ISSUE TITLE
Allow user to choose time in date time picker control

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1204]
Currently, the date-picker control allows you to select a single date and does not allow you to set the time for the selected date.
![image](https://user-images.githubusercontent.com/7566324/32330227-29d4f67e-bfe8-11e7-8560-7e194be0bc55.png)
As one probably solution it, need to add a special flag to the date-picker popup which will allow entering time for the selected date after activation.

**Comment by asvishnyakov** [comment]
And remember about time zones, please.

**Comment by n2pro** [comment]
Use [ this ]( https://github.com/Gillardo/bootstrap-ui-datetime-picker) help solve your problem

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.20
