### ISSUE TITLE
Setup guide confusing instructions

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1206]
Current instructions (https://virtocommerce.com/docs/vc2devguide/deployment/storefront-deployment/deploy-from-source-code) say to point Default Website to the root of storefront folder. 

> Open IIS Manager and change physical path of Default Web Site to C:\vc-storefront\VirtoCommerce.Storefront. Select application pool which uses .NET CLR Version 4.0 and Integrated pipeline mode.

However if admin site is setup in /admin folder, storefront won't work due to web.config. We need to provide more clear guidance here.

**Comment by asvishnyakov** [comment]
What exactly happen? The only thing I know is a problem with cache.

**Comment by Woland2k** [comment]
When admin is configured under nested storefront the configs will be inherited.

**Comment by tatarincev** [comment]
Removed  confused paragraph from docs
https://github.com/VirtoCommerce/vc-content/commit/81761618ea78eee71fb133cbda3191032f5acca6
