### ISSUE TITLE
HandleStaticFiles Throws an exception trying to load auth.js

### ISSUE THREAD

**Issue by newtro** [VirtoCommerce/vc-platform#1207]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Latest Chrome
- Platform version: .Net 4.6
- Module version: 

### Expected behavior
Should load the storefront

### Actual behavior
Throws an exception trying to load D:\projects\virto\vc-storefront\VirtoCommerce.Storefront\auth.js
![2017-11-02 14_58_16-image png 866x385](https://user-images.githubusercontent.com/24457520/32344759-57dc5436-bfde-11e7-9d12-7b2ea2146657.png)
### Steps to reproduce
1. Debug storefront in Visual Studio.

**Comment by Woland2k** [comment]
Might be because of b2b theme.

**Comment by OlegoO** [comment]
You should copy auth.js file from root into App_Data\Themes\default\assets folder.

**Comment by Woland2k** [comment]
it is our default theme i believe ... so something misconfigured

**Comment by asvishnyakov** [comment]
auth.js exist only on platform and b2b theme. so yes, it's misconfiguration

**Comment by tatarincev** [comment]
Was misconfiguration on the client side

**Comment by newtro** [comment]
What was the misconfiguration?

**Comment by tatarincev** [comment]
Missed defined themes for default store or storefront installed with the platform in the same IIS application.

**Comment by newtro** [comment]
ok. Thank you. You guys may want to update your documentation as I followed it precisely 3 times. Your documentation states to create the platform under the storefront site in IIS.

**Comment by tatarincev** [comment]
I recently removed this paragraph :)

**Comment by newtro** [comment]
Great. Thank you
