### ISSUE TITLE
Can't find product just created

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1208]
Product doesn't show up when "is:priced" filter is used (product was re-indexed). Also going physically to the dbo.Item database table and changing StartDate field (-1 month) and re-indexing makes the product appear.

My timezone is PST(-8)

Version info: 
latest versions

### Expected behavior
Once product is created and re-indexed I expect it to show in admin when searching.

### Actual behavior
No product is shown.

![image](https://user-images.githubusercontent.com/1566470/32354314-707e7dcc-bfe6-11e7-8b12-3db7e5551544.png)

### Steps to reproduce
1. Setup a new instance of platform with default images and no sample data.
2. Create new catalog and add a product and pricing info.
3. Re-index.
4. Select filter "is:priced".
5. No results displayed.
6. Open dbo.Item and change StartDate.
7. Reindex.
8. Product is now displayed using filter "is:priced".

**Comment by IgorisB** [comment]
do we have a fix for that? @artem-dudarev I thought it is fixed in other projects... I confirm that just created product doesn't show in search with timezone<0

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #314](https://github.com/VirtoCommerce/vc-module-catalog/issues/314) via [**ZenHub**](https://www.zenhub.com/)
