### ISSUE TITLE
Use custom domain (CDN) for Azure Content

### ISSUE THREAD

**Issue by megafreeman** [VirtoCommerce/vc-platform#1214]
As an IT Manager, I want to set custom domain (CDN) for Azure Content.
Given Storefront App Service,
When I go to Azure App Service's settings,
Then I can set custom domain (CDN) for Azure Content.

As an Customer, I want to load VC content from CDN.
Given Storefront App Service with configured custom domain (CDN).
When I open home any page,
Then All VC content images should be downloaded from custom domain (CDN).

1. Add cdnUrl as connection string parameter.
2. Build absolute URL using provided CDN in next function: https://github.com/VirtoCommerce/vc-platform/blob/39e4f018fc6dddd89fd8acc5d6cf932f5aeb7ec4/VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs#L227

**Comment by asvishnyakov** [comment]
@tatarincev @megafreeman This PR probably cause 500 error in Content module with the following exception:
`... "Method not found: 'Void VirtoCommerce.Platform.Data.Azure.AzureBlobProvider..ctor(System.String)'.","exceptionType":"System.MissingMethodException" ...`

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.18
