### ISSUE TITLE
How to format NotificationParameter of type DateTime?

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1216]
Hi,

I created custom email notification and I would like to use NotificationParameter of type DateTime. Everything works fine without date formatting. Is it possible to provide a format let say "dd-MM-yyyy" for DateTime property? Right now it always display dd-MM-yyyy ss:mm:hh or similar to that.

Version info: 
- Platform version: 2.13.15

**Comment by tatarincev** [comment]
You can use the "Date" liquid filter to format the date in the notification templates 
Please read more about syntax here:
https://help.shopify.com/themes/liquid/filters/additional-filters#date

**Comment by danielstarzewski** [comment]
Thank you for answer. In my case it seems that some of the formats are working are some are not e.g.:
1. {{datePropertyName | date: "%e %B %Y" }} outputs "e B Y"
2. {{datePropertyName | date: "%d-%m-%y" || outputs "30-0-17"
3. {{datePropertyName | date: "%d-%m-%Y" }} outputs "30-0-Y"
All tests were made for 30th November 2017. Do you know what might be the issue in this case?

**Comment by asvishnyakov** [comment]
@danielstarzewski This is because platform doesn't configure liquid with `UseRubyDateFormat = true`, so .NET date format used.
@tatarincev Is it bug?

**Comment by tatarincev** [comment]
You can look at 'Date' liquid filter implementations for better understand how it works. https://github.com/VirtoCommerce/dotliquid/blob/master/src/DotLiquid/StandardFilters.cs#L520

If look more closely you can find that this implementation uses default .NET DateTime.ToString(format) method for date formating. 
https://msdn.microsoft.com/en-us/library/zdtaw1bw(v=vs.110).aspx

**Comment by tatarincev** [comment]
@asvishnyakov  Yes, seems platform doesn't set `UseRubyDateFormat = true` setting and DotLiquid used default .NET `DateTime.ToString()` method

**Comment by tatarincev** [comment]
@danielstarzewski  May I close this issue?

**Comment by danielstarzewski** [comment]
@tatarincev yes, thank you for your help
