### ISSUE TITLE
Available tags in notification's body 

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1217]
Hi, 
Could you please provide me with a link to some kind of documentation or just explain in a few words what kind of tags can be used in notification's body textarea? Are there any custom tags, only html4 tags etc?

Thank you,
Daniel

**Comment by asvishnyakov** [comment]
Hi! Please, look at https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/basic-functions/working-with-notifications

We use [liquid](https://shopify.github.io/liquid/) to render notification parameters.

We have no explicit limits about content of notification template, but HTML usage is depend on target device type. If you send email notification, you can use HTML (and even inline css), but be careful: not all email clients support not all HTML tags & CSS possibilities. If you send SMS notification, I think, you can't use HTML.

**Comment by danielstarzewski** [comment]
Thanks!
