### ISSUE TITLE
Incorrect product properties for variation product

### ISSUE THREAD

**Issue by krzysztofwalachmw** [VirtoCommerce/vc-platform#1218]
After adding product property (on catalog, for all products) and setting different values for product+it's variation, when fetching CatalogProduct via API, I keep receiving incorrect values. BackOffice UI presents proper values.

Used service:
`VirtoCommerce.Domain.Catalog.Services.GetByIds(ids, ItemResponseGroup.ItemLarge)`
reading variation `CatalogProducts` from
`CatalogProduct.Variations`
from which I am reading property values from:
`CatalogProduct.PropertyValues.Value`.

Excpected value is property assigned to "child" variation
Actual value is value from "parent" product

VC version from side menu: 2.13.15

**Comment by asvishnyakov** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #74](https://github.com/VirtoCommerce/vc-module-catalog/issues/74) via [**ZenHub**](https://www.zenhub.com/)

**Comment by asvishnyakov** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #73](https://github.com/VirtoCommerce/vc-module-catalog/issues/73) via [**ZenHub**](https://www.zenhub.com/)
