### ISSUE TITLE
VirtoCommerce MultiTenant

### ISSUE THREAD

**Issue by brunobertechini** [VirtoCommerce/vc-platform#1219]
Hello there, I would like to know if vc-platform supports multitenant and how it is implemented.

When I say multitenant I mean one customer with multiple stores. And another customer with other stores.

Are these saved in the same database?

Are these controller only using permissions ?

Any documentation about this specific topic ?

Bruno

**Comment by brunobertechini** [comment]
Thanks @asvishnyakov 

Let me try to explain:

Im looking for a solution in terms of SaaS / MultiTenant for ecommerce.

I am evaluating several ecommerce platforms and virtocommer is the one that best fit so far.

My company will be a solution provider where we will use one platform like VirtoCommerce as base and start from there.

We have couple requirements for architecture:

1) One deploy of our "ready solution" for multiple customers. When I say Customer I mean "my customer", i.e.: A given tenant (with a monthly subscription) that may have several stores.

Basically in virtocommerce terms, each tenant from this point of view must have its own Azure deployment in order to achieve this goal.

We are indeed using microservices (Soa Done Right Services) for our solution.

So (just for clarification in this scenario):

Provider = My company providing a "Erp+ECommerce" solution for OUR customers.
Customer = Some company that has purchased our product subscription and may have one or more stores.

In our solution (one single deploy of VirtoCommerce) I do not see how to handle multiple tenants (each tenant will be a given customer with monthly subscription). 

I can see how we can split up stores and admins but this, in my scenario, should be separated by tenant.

Are there any plans in future for microservices/dotnetcore in a roadmap ?

Regards

**Comment by Woland2k** [comment]
There are several ways how your scenario can be achieved with VC but for most of them you should  try to keep customer data separated from each other. The reason is your want to be and to restore/backup data per customer. 

As for the actual deployment, one of the  best and most efficient way would be to use docker images. We have Linux one available for storefront and windows for backend.

**Comment by brunobertechini** [comment]
THanks @Woland2k My goal is to have one database per tenant.

But only one deploy of VirtoCommerce

**Comment by Woland2k** [comment]
It should be quite easy to change connectionstring based on customer logging in.

**Comment by brunobertechini** [comment]
Yes but still We would have a full installation not only a tenant.

Indeed for multitenant, you also have one database for all tenants. Its a common scenario. Althoght its not supported by VC.

But still Im moving forward and try to integrate one service bus with VC in order to publish events to my enterprise core ERP

Thanks again

**Comment by brunobertechini** [comment]
Closing. Reason: No answer.
