### ISSUE TITLE
'Select all' functionality

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1223]
Hi Team,

On the 'Contacts' blade as well as other blades in the whole VC you see checkbox to select many items at once. 
Let's suppose I would like to select all Contacts and click Delete next. Correct me if I am wrong but currently only currently visible rows (20 rows by default) are selected. I am not able to delete all Contacts at once. Is there a place in VC or functionality that would enable such feature to select all rows matching given criteria and run actions on that set?
![image](https://user-images.githubusercontent.com/30530759/33064956-bd42e43e-cea7-11e7-9e3b-a2e4514d4e78.png)

Version info: 
- Platform version: 2.13.15

**Comment by danielstarzewski** [comment]
Did you have a chance to look at my question? 
Thank you.

**Comment by asvishnyakov** [comment]
As a manager I think no, it's not possible. As a developer, you can pass `take: Number.MAX_SAFE_INTEGER` in search criteria and get all available contacts.

**Comment by asvishnyakov** [comment]
@tatarincev @n2pro Possible related to infinity scroll and discussed deletion behavior

**Comment by danielstarzewski** [comment]
@asvishnyakov do I understand correctly you are working on infinity scroll right now or you plan to work on it?

**Comment by tatarincev** [comment]
Remove all functionality, can be achieved by adding a new API method or adding a parameter  `bool deleteAll` to the existing API DELETE method without any additional changes in the user interface.
@danielstarzewski  please track the status of this feature in this issue, we will implement it soon.

**Comment by danielstarzewski** [comment]
Ok, thank you.

**Comment by tatarincev** [comment]
@kostyrin all changes should be made in the https://github.com/VirtoCommerce/vc-module-catalog  repository

**Comment by kostyrin** [comment]
There is functional in project https://github.com/VirtoCommerce/vc-module-customer. I have made changes in the project.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-customer/releases/tag/v2.14.10
