### ISSUE TITLE
Datetime placeholder issue

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1226]
Hello,

When i use a placeholder of type DateTime in notifications I am also able to provide custom formatting for that date. In my case the placeholder is used as follows:
**{{Deadline | date: "d MMMM yyyy"}}**

MMMM displays full month name. When I save notification for en-US the date is correctly formatted (e.g. 17 November 2017) but if I save another translation e.g. for de-DE I would expect the date to be displayed with German month name translation instead of English.

Version info: 
- Platform version: 2.13.5

**Comment by asvishnyakov** [comment]
@danielstarzewski  @tatarincev Possible we need to pass `CultureInfo` created from `Notification.Language` to template `Render` method: https://github.com/VirtoCommerce/vc-platform/blob/e15be3ae7854f82272c86e3c02ae004b42cb1d13/VirtoCommerce.Platform.Data.Notifications/LiquidNotificationTemplateResolver.cs#L70

**Comment by asvishnyakov** [comment]
@danielstarzewski Also, to prevent confuse: in English and German November has the same name. You may use October (Oktober in German) or other culture (Russian, for example).

**Comment by danielstarzewski** [comment]
@asvishnyakov yes, that was bad example but you got my point ;)
