### ISSUE TITLE
VC platform GDPR compliance

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#1227]
### Purpose
Make sure VirtoCommerce platform provides all necessary tools to support GDPR compliance

### References
- MS GDPR compliance manager: [https://aka.ms/ComplianceManager](https://aka.ms/ComplianceManager)
- Info protection scanner: [https://docs.microsoft.com/en-us/information-protection/deploy-use/deploy-aip-scanner
](https://docs.microsoft.com/en-us/information-protection/deploy-use/deploy-aip-scanner
)
### Requirements
- [ ] ?

### Related issues
- [ ] ?

### User stories
- [ ] ?

### Acceptance criteria
- [ ] ?

### Definition of Done
- [ ] ?

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
