### ISSUE TITLE
The user under security can't be deleted

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-platform#1233]
Please provide detailed information about your issue, thank you!

Version info:
- Browser version: Google Chrome 62.0.3202.94
- Platform version: 2.13.17

### Steps to reproduce
1.Delete selected users
2.Failure(Failed to load resource: the server responded with a status of 405 (Method Not Allowed) /api/platform/security/users?name=Demo)
3.
![image](https://user-images.githubusercontent.com/31033741/33750328-35819d0a-dc0e-11e7-83b5-42d8cf4930b1.png)

**Comment by asvishnyakov** [comment]
Please, look at 2.13.18 release notes: https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.18

The deleted DELETE api/users API method has been restored [#1203](https://github.com/VirtoCommerce/vc-platform/issues/1203)

**Comment by ruyi-kooboo** [comment]
@asvishnyakov Thank you
