### ISSUE TITLE
404 thrown on Contact blade

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1235]
Hello,
Version info: 
- Platform version: 2.13.19

### Steps to reproduce
1. Go to demo site http://admin-demo.virtocommerce.com/
2. Rebuild index to make sure it is up to date.
3. Go to Orders blade.
4. Open order details.
5. Click on customer link

404 error is thrown and displayed in UI. 
Please fix.

Thank you.

**Comment by n2pro** [comment]
Corrected [this comment](https://github.com/VirtoCommerce/vc-module-core/commit/a58f837f20dd3d464c9e914f3049b51408244804)

**Comment by n2pro** [comment]
Bug fixed  [this](https://github.com/VirtoCommerce/vc-module-customer/commit/b928b45e8c23679accb488658028d20e6f0eca38) commet
