### ISSUE TITLE
Dates are not formatted correctly in orders grid

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1236]
Hello,
Version info: 
- Browser version: IE11.0.9600.18838
- Platform version: 2.13.19

Dates are not displayed correctly in orders grid. Please visit demo site.
![image](https://user-images.githubusercontent.com/30530759/33891664-efd2e98e-df56-11e7-970c-51f69da1d976.png)

**Comment by asvishnyakov** [comment]
They are correctly displayed in one of regional Chinese formats. In our public demo all users use the same credentials, so user settings shared between all logged in users. Just someone chose regional format different than English. It's not a bug.
