### ISSUE TITLE
Add Geo-point datatype for Dynamic Properties

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1238]
After comlpetion of VirtoCommerce/vc-module-catalog#84, make the same changes for Dynamic Properties, so then we can use it (for example) for fulfillment center search and complete VirtoCommerce/vc-theme-b2b#71

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
