### ISSUE TITLE
Add alias to the email account that sends out email notifications

### ISSUE THREAD

**Issue by stravero** [VirtoCommerce/vc-platform#1239]
So when an email notification goes to our customers, there isn't an alias used on our sender email address.  So when the user receives it, it shows as noreply@domain.com in their inbox instead of a clean name "Joe Smith <noreply@domain.com>".  When user's see the noreply they will automatically delete or dump into their junk mail.

We need the ability to apply an alias to our sender account within the Notification settings where we set our email connections.  We are going live in mid-January.  Would really appreciate this update ASAP.  Sort of surprised that it isn't a part of the system or been brought up by other customers.

**Comment by tatarincev** [comment]
We have moved this issue to special milestone and will work on it  which other notification improvements
