### ISSUE TITLE
"Select" list is closing randomly in Firefox

### ISSUE THREAD

**Issue by krzysztofwalachmw** [VirtoCommerce/vc-platform#1241]
I have problem with "select" element in my custom blade, closing randomly. After clicking the select element, the list appears correctly, but, when I try to select an option and move mouse down the list, the select closes before clicking. I need to do 1-3 tries in average, to select desired option.

It happens in FF 57.0.2, whilst working correctly in Chrome.

The code is as follows (removed other inputs for clarity, kept whole div structure)

```html
<div class="blade-content">
    <div class="blade-inner">
        <div class="inner-block">
            <form class="form" name="formScope">
                <div ng-init="setForm(formScope)">                    
                    <div class="form-input" ng-if="blade.currentEntity.modelProperty=='value'">
                        <select name="selectName" id="selectName"
                                ng-options="option for option in myOptions track by option"
                                ng-model="blade.currentEntity.valueProperty">
                         </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
```

**Comment by n2pro** [comment]
@krzysztofwalachmw  try to use [ui-select directives  ](https://angular-ui.github.io/ui-select/) as we do. For example you can see [here.](https://github.com/VirtoCommerce/vc-module-catalog/blob/7074309f88aec9faea22790984dab32bcfba7ef8/VirtoCommerce.CatalogModule.Web/Scripts/blades/item-detail.tpl.html#L190)

**Comment by krzysztofwalachmw** [comment]
@n2pro thank you, luckily UI result was acceptable in my case.
