### ISSUE TITLE
Issue with column sorting

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1242]
Hello,

Sorting by column with name containing space characters does not work. See example in demo environment:
![image](https://user-images.githubusercontent.com/30530759/34513002-2d936832-f066-11e7-93bb-f2b39bbccb6b.png)

Nothing happens when clicking column name. Results stay in the same sequence.
The issue is that for sorting, search phrase contains 'isVirtual' key whilst it is indexed by 'Is Virtual'.
The same issue appears on 'Contacts' blade. Please note I would like to be able to use exact column names in search query input so that I don't have to quess what is the key.

Version info: 
- Platform version: 2.13.19

**Comment by danielstarzewski** [comment]
Did you have a chance to look at this issue? It is quite important if someone is extending the platform with own indexed objects.

**Comment by tatarincev** [comment]
@danielstarzewski  The main reason for this problem not in how the column displayed in grid(it is just localized label),  but that api/catalog/catalogs doesn't  support sorting and pagination at all.  

@andshk  Need to extend API GET api/catalog/catalogs method  in the [CatalogModuleCatalogsController.cs](https://github.com/VirtoCommerce/vc-module-catalog/blob/master/VirtoCommerce.CatalogModule.Web/Controllers/Api/CatalogModuleCatalogsController.cs) with new formal parameter of type `SearchCriteria` to allow use pagination and sorting in the catalogs search.

**Comment by danielstarzewski** [comment]
@tatarincev ok this was a bad example. Let's look at the Contacts blade. List is sorted correctly if you click on 'Created Date' column but suppose admin wants to filter out contacts based on created date. How would he know he has to use 'createdDate' key instead of 'Created Date' in search phrase?
e.g. createdDate:["2016-01-01T00:00:00.000Z" TO "2017-12-31T23:59:59.999Z"]
and "Created Date":["2016-01-01T00:00:00.000Z" TO "2017-12-31T23:59:59.999Z"]

**Comment by tatarincev** [comment]
I understand your confusion, the fact is that ui-grid itself implicitly  converts bonded data properties to display label by splitting CamelCase names into spaced parts if  it does not find explicitly defined display names for these fields in definition

` columnDefs: [
{ name: 'memberType', displayName: 'Customer type' },
{ name: 'name', displayName: 'Customer name', sort: { direction: uiGridConstants.ASC } }`

so by this declaration, these properties will be displayed as:
'myProperty' -> 'My Property" - implicitly conversion
 'memberType' -> 'Customer type' - explicitly conversion
 'name' -> 'Customer name' - explicitly conversion

And now about sorting expression, this code [uiGridUtils.js#L187](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Scripts/common/uiGridUtils.js#L187) is used to get the actual sort expression from the ui-grid instance, and as you can see, only real property names are used to create the sort expression, aren't any localized values used.

**Comment by danielstarzewski** [comment]
@tatarincev what solution do you propose then?

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/edit/v2.21.1
