### ISSUE TITLE
404s are logged as an error

### ISSUE THREAD

**Issue by krzysztofwalachmw** [VirtoCommerce/vc-platform#1244]
Virto Commerce 2.13

In VC platform, Global.asax, all unhandled errors are logged within Application_Error.
This is desirable, besides requests ending up with 404, 400, 403, 401, ... - those results are not an application error, just normal responses to user doing illegal action. As a result, e.g. any 404 lands in error logs and generates false positive monitoring alerts.

Desired behavior: log only actual errors, or at least provide a web.config variable/method available from VC module, to control whats/at what level is logged.

**Comment by tatarincev** [comment]
Yes, I agree,  it is strange behavior why ASP.NET generates errors  ( Server.GetLastError(); return not null) for 404, 400, and 403 status codes.

**Comment by tatarincev** [comment]
it seems this issue is no longer relevant for platform 3.0 version
