### ISSUE TITLE
New confirmation dialog

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1246]
Request to build in a simplified confirmation dialog into the platform. I would be similar to browser confirmation dialog:
![image](https://user-images.githubusercontent.com/30530759/34862452-c6cfb54a-f76a-11e7-9c9e-2e1a233c670d.png)

In most cases Yes/Cancel are sufficient.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
