### ISSUE TITLE
Prepare module solution for Notifications functionality

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1248]
Solution at least  should contains three projects 
VirtoCommerce.NotificationsModule.Core - for notifications abstractions
VirtoCommerce.NotificationsModule.Data - for data access layer and business logic implementation
VirtoCommerce.NotificationsModule.Web - for API and UI
See the exists Module/Module1 as example

**Comment by kostyrin** [comment]
look at https://github.com/VirtoCommerce/vc-platform-core/tree/feature/notifications
