### ISSUE TITLE
Grid's cells misaligned when scrolled to the bottom

### ISSUE THREAD

**Issue by krzysztofwalachmw** [VirtoCommerce/vc-platform#1259]
VC 2.13.15

When having full page of list/grid, when i scroll to the very bottom, having cursor placed over first or second column (selection + 3-dot menu for actions), those 2 first columns are scrolled a little less than the rest of the grid. Please check on screenshot below.

![image](https://user-images.githubusercontent.com/33751761/35156546-706be396-fd31-11e7-8327-8892b5b239da.png)

The behavior is reproducible at your demo commerce app.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
