### ISSUE TITLE
Change from one index search engine to another without big downtime

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-platform#1260]
We want to move our product/member index from azure elasticsearch to cloud elasticsearch. 
But we have some limitations:
- we can't change connection string and start REBUILD because at that time catalog on storefront will unavailable
- we can't create new web app with another instance of VC admin with cloud elasticsearch connectionstring

What you can advice to us? Is it any plans for handle that kind of situation?

**Comment by tatarincev** [comment]
Merged with this issue https://github.com/VirtoCommerce/vc-module-core/issues/37
