### ISSUE TITLE
New installation - Catalog module - dependency injection failure

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1269]
I have a new installation, latest bits cloned from GitHub and added the Catalog module.
I get the following error when trying to do anything Catalog related:

An error occurred when trying to create a controller of type 'CatalogModuleCatalogsController'. Make sure that the controller has a parameterless public constructor.

Apparently DI doesn't work as expected?

**Comment by asvishnyakov** [comment]
@brgrz Please, provide the following information:
- Which version or cloned branch name of your Platform?
- List of modules and their versions or cloned branches names you have installed?
If you install your modules manually, it's possible what you miss some dependency. Please, try to install modules via standard installation wizard and then replace needed to source code from GitHub.

**Comment by brgrz** [comment]
Version number is 2.13.21.

I just cloned my cloned repo (as is), then prepped everything per instructions, ran it and the only thing I did I went into modules installer and chose Catalog module and Csv Catalog import module. Everything installed fine and the installer brought in two other (Core) modules.

**Comment by brgrz** [comment]
I just removed the Csv import module so now I only have the three modules developed by Virto Commerce team and the exception remains the same.

![image](https://user-images.githubusercontent.com/193816/35797362-caa79126-0a5f-11e8-8e9c-37fb02b04aa9.png)

Request to http://localhost/virto/api/catalog/catalogs?count=20&sort=name:asc&start=0 failed

Stack trace: 


"message": "An error has occurred.",
"exceptionMessage": "An error occurred when trying to create a controller of type 'CatalogModuleCatalogsController'. Make sure that the controller has a parameterless public constructor.",
"exceptionType": "System.InvalidOperationException",
"stackTrace": "   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)\r\n   at System.Web.Http.Controllers.HttpControllerDescriptor.CreateController(HttpRequestMessage request)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Cors.CorsMessageHandler.<SendAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()",
"innerException": {
"message": "An error has occurred.",
"exceptionMessage": "Resolution of the dependency failed, type = \"VirtoCommerce.CatalogModule.Web.Controllers.Api.CatalogModuleCatalogsController\", name = \"(none)\".\r\nException occurred while: while resolving.\r\nException is: InvalidOperationException - The current type, VirtoCommerce.Domain.Store.Services.IStoreService, is an interface and cannot be constructed. Are you missing a type mapping?\r\n-----------------------------------------------\r\nAt the time of the exception, the container was:\r\n\r\n  Resolving VirtoCommerce.CatalogModule.Web.Controllers.Api.CatalogModuleCatalogsController,(none)\r\n  Resolving parameter \"itemSearchService\" of constructor VirtoCommerce.CatalogModule.Web.Controllers.Api.CatalogModuleCatalogsController(VirtoCommerce.Domain.Catalog.Services.ICatalogService catalogService, VirtoCommerce.Domain.Catalog.Services.ICatalogSearchService itemSearchService, VirtoCommerce.Platform.Core.Security.ISecurityService securityService, VirtoCommerce.Platform.Core.Security.IPermissionScopeService permissionScopeService)\r\n    Resolving VirtoCommerce.CatalogModule.Data.Services.CatalogSearchServiceDecorator,(none) (mapped from VirtoCommerce.Domain.Catalog.Services.ICatalogSearchService, (none))\r\n    Resolving parameter \"productSearchService\" of constructor VirtoCommerce.CatalogModule.Data.Services.CatalogSearchServiceDecorator(VirtoCommerce.CatalogModule.Data.Services.CatalogSearchServiceImpl catalogSearchService, VirtoCommerce.Domain.Catalog.Services.IItemService itemService, VirtoCommerce.CatalogModule.Data.Search.IProductSearchService productSearchService, VirtoCommerce.Platform.Core.Settings.ISettingsManager settingsManager)\r\n      Resolving VirtoCommerce.CatalogModule.Data.Search.ProductSearchService,(none) (mapped from VirtoCommerce.CatalogModule.Data.Search.IProductSearchService, (none))\r\n      Resolving parameter \"searchRequestBuilders\" of constructor VirtoCommerce.CatalogModule.Data.Search.ProductSearchService(VirtoCommerce.Domain.Search.ISearchRequestBuilder[] searchRequestBuilders, VirtoCommerce.Domain.Search.ISearchProvider searchProvider, VirtoCommerce.Platform.Core.Settings.ISettingsManager settingsManager, VirtoCommerce.Domain.Catalog.Services.IItemService itemService, VirtoCommerce.Platform.Core.Assets.IBlobUrlResolver blobUrlResolver, VirtoCommerce.CatalogModule.Data.Search.IAggregationConverter aggregationConverter)\r\n        Resolving VirtoCommerce.Domain.Search.ISearchRequestBuilder[],(none)\r\n          Resolving VirtoCommerce.CatalogModule.Data.Search.ProductSearchRequestBuilder,ProductSearchRequestBuilder (mapped from VirtoCommerce.Domain.Search.ISearchRequestBuilder, ProductSearchRequestBuilder)\r\n          Resolving parameter \"termFilterBuilder\" of constructor VirtoCommerce.CatalogModule.Data.Search.ProductSearchRequestBuilder(VirtoCommerce.Domain.Search.ISearchPhraseParser searchPhraseParser, VirtoCommerce.CatalogModule.Data.Search.ITermFilterBuilder termFilterBuilder, VirtoCommerce.CatalogModule.Data.Search.IAggregationConverter aggregationConverter)\r\n            Resolving VirtoCommerce.CatalogModule.Data.Search.TermFilterBuilder,(none) (mapped from VirtoCommerce.CatalogModule.Data.Search.ITermFilterBuilder, (none))\r\n            Resolving parameter \"browseFilterService\" of constructor VirtoCommerce.CatalogModule.Data.Search.TermFilterBuilder(VirtoCommerce.CatalogModule.Data.Search.BrowseFilters.IBrowseFilterService browseFilterService)\r\n              Resolving VirtoCommerce.CatalogModule.Data.Search.BrowseFilters.BrowseFilterService,(none) (mapped from VirtoCommerce.CatalogModule.Data.Search.BrowseFilters.IBrowseFilterService, (none))\r\n              Resolving parameter \"storeService\" of constructor VirtoCommerce.CatalogModule.Data.Search.BrowseFilters.BrowseFilterService(VirtoCommerce.Domain.Store.Services.IStoreService storeService)\r\n                Resolving VirtoCommerce.Domain.Store.Services.IStoreService,(none)\r\n",
"exceptionType": "Microsoft.Practices.Unity.ResolutionFailedException",
"stackTrace": "   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)\r\n   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)\r\n   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)",
"innerException": {
"message": "An error has occurred.",
"exceptionMessage": "The current type, VirtoCommerce.Domain.Store.Services.IStoreService, is an interface and cannot be constructed. Are you missing a type mapping?",
"exceptionType": "System.InvalidOperationException",

**Comment by tatarincev** [comment]
The platform should automatically installed the default set of modules, so did you? 
![image](https://user-images.githubusercontent.com/7566324/35798140-9585d178-0a6a-11e8-88d6-8d98c2cecbac.png)

**Comment by brgrz** [comment]
I only have 3 modules installed: Catalog, Commerce core and Image tools modules. Nothing got installed automatically.

?

**Comment by tatarincev** [comment]
Try to delete your DB `virtocommerce2` , reset IIS  and open platform in browser again

**Comment by brgrz** [comment]
Ha! I did as you said and the modules were installed. Don't know why it didn't happen in the first place.
