### ISSUE TITLE
The user should not have access to unrelated stores

### ISSUE THREAD

**Issue by vkrashenko** [VirtoCommerce/vc-platform#1270]
### Steps to reproduce

1. Register in some store. For example in Electronics
2. Go to the platform and check that stores are NOT binded
3. Next go to the other store and try to login with your account from step 1.

finally you will see next
![storeIssue.png](https://images.zenhubusercontent.com/595cebc061b4ca3b0a7348ac/43c0ed66-790e-460e-a859-3a896e7eaaa2)

**Comment by asvishnyakov** [comment]
Issue moved to [VirtoCommerce/vc-storefront-core #67](https://github.com/VirtoCommerce/vc-storefront-core/issues/67) via [**ZenHub**](https://www.zenhub.com/)
