### ISSUE TITLE
User shouldn`t have possibility to set negative numbers or letter in input

### ISSUE THREAD

**Issue by vkrashenko** [VirtoCommerce/vc-platform#1271]
Fix the smart-float directive, which validates fields with numbers

<details><summary>Images</summary>

![catalogBug.png](https://images.zenhubusercontent.com/595cebc061b4ca3b0a7348ac/30ce1ef3-3010-4cf9-9515-29f2c15a519b)
![couponIssue.png](https://images.zenhubusercontent.com/595cebc061b4ca3b0a7348ac/af3d6206-71d6-4239-b0b0-acac9f1f6f42)

</details>

**Comment by tatarincev** [comment]
Divided and moved
https://github.com/VirtoCommerce/vc-module-marketing/issues/17
https://github.com/VirtoCommerce/vc-module-catalog/issues/119
