### ISSUE TITLE
How can I set the reset password token deadline?

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-platform#1279]
Version info: 
- Browser version: Chrome
- Platform version: 2.13.19
**Hi,Such as the title,I want to set the reset password token active time(such as 1h),What should I do?**
Thanks

**Comment by tatarincev** [comment]
Hi, how to change `reset password token` expiration time, described on this  article
https://docs.microsoft.com/en-us/aspnet/identity/overview/features-api/account-confirmation-and-password-recovery-with-aspnet-identity
all that you need is to add these  lines to the `ApplicationUserManager` implementation
```
if (dataProtectionProvider != null)
 {
    manager.UserTokenProvider =
       new DataProtectorTokenProvider<ApplicationUser>
          (dataProtectionProvider.Create("ASP.NET Identity"))
          {                    
             TokenLifespan = TimeSpan.FromHours(3)
          };
 }
```
but unfortenately you can't do it without `[ApplicationUserManager`](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Data.Security/Identity/ApplicationUserManager.cs) source code modification. 
But there is another way to do it, you can define your own  `CustomApplicationUserManager : ApplicationUserManager`  derivative type and register it in DI container by this line `container.RegisterType<ApplicationUserManager, CustomApplicationUserManager>(); ` within your module, I think it should help.

**Comment by ruyi-kooboo** [comment]
@tatarincev  @asvishnyakov Thank you for your answers, because there are some special cases on my side, so my intention is that I'm not going to change your code,maybe other way such as  configuring and setting the expiration time, which doesn't seem to be possible at the moment, but I think you another  suggest is good,I will try it,Thank you!

**Comment by ruyi-kooboo** [comment]
You suggest(create an module and register it) is work,Thanks
