### ISSUE TITLE
Import shows empty screen in demo environment

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1282]
### Expected behavior

should show standard import functionality and have import installed

### Actual behavior
<img width="1289" alt="screen shot 2018-02-13 at 3 20 51 pm" src="https://user-images.githubusercontent.com/1566470/36179539-7f930346-10d1-11e8-8137-9fedb9e0ad03.png">

**Comment by Woland2k** [comment]
@tatarincev @dimitri-ak can we fix this in demo?

**Comment by tatarincev** [comment]
Sure, We will fix it today

**Comment by tatarincev** [comment]
Done. Included the `vc-module-catalog-csv-import`  module to the default modules group `commerce`
