### ISSUE TITLE
Add ability to cancel export/import

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1284]

**Comment by tatarincev** [comment]
Alexandr no luck, only in the next platform version, sorry :)

**Comment by asvishnyakov** [comment]
@tatarincev Moved to backlog, but still high priority

**Comment by tatarincev** [comment]
This is one of main requirements for new generic export and import functionality. I think this issue can be closed.
You may reopen this issue if it has been closed in error.
