### ISSUE TITLE
Grid menu is cropped when opened near the bottom edge of the blade

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#1286]
When the grid is located near the bottom edge of the page, its menu is cropped, and you can't see all menu items. You cannot scroll down because you are already at the very bottom of the blade.

![image](https://user-images.githubusercontent.com/8775253/36481928-1bb107c0-171a-11e8-83c2-3b9254c61e70.png)

Version info: 
- Platform version: 2.13.21

### Expected behavior
The entire menu should be visible.

### Actual behavior
The menu is opened right under the menu button and is cropped.

**Comment by n2pro** [comment]
it is necessary to correctly calculate the height of the grid, then a scroll appears
```
.grid {
  height: 200px;
}
```

![image](https://user-images.githubusercontent.com/13115017/36545858-8fd492d8-17f2-11e8-98ae-5fd9614cec08.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
