### ISSUE TITLE
Add character counters for SEO

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-platform#1288]
Is it possible to add character counter for SEO blade and if content of field more than limit (for example SEO page title limit = 68 and SEO page description limit = 160) change color of the counter to RED.

![image](https://user-images.githubusercontent.com/1429226/36672741-177ecb9a-1b09-11e8-9473-3c674f557b09.png)

**Comment by tatarincev** [comment]
I think we can write for this task special  AngularJS directive looks like `va-chars-left max-length=255` to be able to re-use in other places. And then use it on Core module in SEO blade

**Comment by n2pro** [comment]
For an implementation example, see [Here](http://textangular.com/).
![capture333](https://user-images.githubusercontent.com/13115017/38236319-185dd506-3724-11e8-8f60-7d767af8fbee.JPG)

**Comment by Tilesto** [comment]
Fixed. Preview video - http://recordit.co/M1MJstwsa0 and screen:

![screenshot_3](https://user-images.githubusercontent.com/28765507/42362856-7ca82e2e-80f5-11e8-9086-c1bc36a820fb.png)

**Comment by Tilesto** [comment]
![capture](https://user-images.githubusercontent.com/28765507/42446017-2b47c954-8375-11e8-8992-ae9569e1ef24.PNG)
Changed color from Red(error) to Yellow(warning), cause this text plays only an informational role

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
