### ISSUE TITLE
Routing issue in angular

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1292]
HI,

Version info: 
- Platform version: 2.13.21

### Expected behavior
Navigation to given blade is working e.g. 
https://admin-demo.virtocommerce.com/#/workspace/orders is taking user directly to Orders blade.

### Actual behavior
User is redirected to home screen.

### Steps to reproduce
1. Please visit demo site
2. Go to e.g. Orders (or any other blade). Notice url is https://admin-demo.virtocommerce.com/#/workspace/orders
3. Hit F5
4. user is redirected to home screen

I am pretty sure it worked well for version 2.13.15

**Comment by n2pro** [comment]
This is bug related with the [commitom](https://github.com/VirtoCommerce/vc-platform/commit/1b74d2e833c4070d81a9c4ece70a7478b5589bc0).

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.24
