### ISSUE TITLE
Update Hangfire.SqlServer to v1.6.17

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#1293]
This is required to make VirtoCommerce.CoreModule.Web.BackgroundJobs.IndexingJobs.RunIndexJobAsync() `async`
https://github.com/VirtoCommerce/vc-module-core/issues/30

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.24
