### ISSUE TITLE
A customer should be able to shop at all our sites without making it obvious that we are the same Company

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1298]
### Expected behavior
It is important that a customer can shop on Store 1, Store 2,... (without making it obvious that we are the same Company).

We need to make sure the sites are set up, so that a user can use the same email address for purchasing at both sites. 

Meaning it should create a different account per site, even for the same customer.
This means that example demo-user@test.com can exist in multiple accounts for all of our sites.

### Actual behavior
Name demo-user@test.com is already taken, error

### Steps to reproduce
1. Create a multiple stores for example: Store 1  and Store 2
2. Create a new customer demo-user@test.com on Store 1
3. Try create a new customer demo-user@test.comStore 2 on Store 2 and get Name demo-user@test.com is already taken.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-91
