### ISSUE TITLE
Allow for dimension properties to be stored and presented at the variant level

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-platform#1304]
**Issue**:
Our client stores dimensions at the variant level, not product level.
There is no dimensions widget at the variant level in order to present Height, Width, Length and Weight.

**Request**:
Under the variant Item details panel, Please allow for dimension properties to be stored and presented at the variant level.

![dimensions](https://user-images.githubusercontent.com/37384557/37431060-86fde336-27aa-11e8-86be-205a3aff4de7.PNG)

**Comment by tatarincev** [comment]
Moved to https://github.com/VirtoCommerce/vc-platform/issues/1304
