### ISSUE TITLE
The RedisSessionStateProvider has a dependency on StackExchange.Redis.StrongName

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1305]
On new Azure Environment we get error: Could not load file or assembly 'StackExchange.Redis.StrongName
because now the RedisSessionStateProvider has a dependency on StackExchange.Redis.StrongName.

Workaround: We downloaded and copied StackExchange.Redis.StrongName in to platform/bin folder manually

Please update dependency to StackExchange.Redis.StrongName.

From https://stackoverflow.com/questions/28584950/what-is-the-difference-between-stackexchange-redis-and-stackexchange-redis-stron
So if you want to use RedisSessionStateProvider, choose the StrongName version unless you want to have two dependencies.
Update: As @Matei_Radu has pointed out, Microsoft.AspNet.SignalR.Redis also has a dependency on StackExchange.Redis.StrongName

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.28
