### ISSUE TITLE
Request - Replace notification template editor to rich text editor

### ISSUE THREAD

**Issue by yongbin-kooboo** [VirtoCommerce/vc-platform#1306]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version:  any
- Platform version:  2.13.19

### Expected behavior
When we edit notification template, we want to have a rich text editor
### Actual behavior
there have only a simple text editor, we can't simply change any notification templates.

@tatarincev

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
