### ISSUE TITLE
Add support of asset entries

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1308]
Extend domain models, db tables, services & controllers with support of asset entries

![c1de939155500983eda8660c6f26509beac39d2cd58b47e07f pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/6369252/37586421-1db111d2-2b7e-11e8-82fe-458791b72c0c.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.24
