### ISSUE TITLE
How to handle changes in extended repositories?

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1314]
Please look into the case below and advice what is your recommendation.
I have extended an existing repository (I will use OrderRepositoryImpl as an example). I made the extension using guide from here https://virtocommerce.com/docs/vc2devguide/extending-commerce/extending-members-domain-types 

I created my new repository:
```
public class ExtendedOrderRepository : OrderRepositoryImpl
{
...
}
```
I initialized repository in Module.cs:
```
using (var context = new ExtendedOrderRepository(ConnectionStringName, _container.Resolve<AuditableInterceptor>()))
{
   var initializer = new ExtendedOrderDbInitializer();
   initializer.InitializeDatabase(context);
}
```
Then I added several migrations - everything worked fine. Please note I store migrations in my solution using my default ContextKey.
Next, I upgraded Orders module. It happened that orders module had a new migration added (real case for ver 2.17.7). The new migration was run during startup and saved to _migrationHistory table in DB. 
Now, when I run my solution I get an errror:
The model backing the 'ExtendedOrderRepository' context has changed since the database was created
The error ocured because regardless of the migration being executed, EF compares state of the model with the state from the most recent migration entry in DB for ContextKey matching my extended repository. 
To fix this issue I have to add a new migration and clear its contents. It's easy and it works but I am not sure if that should be the way to handle those cases. 

Do you have any recommendations on how to approach this issue? It would be ideal for me to not to care about any migrations you add to your code. Have your ever had this issue before?

**Comment by tatarincev** [comment]
Yes, it is the known issue, to solve it you have to update your module dependency with the new Nuget package  `VirtoCommerce.OrderModule.Data` which contains new migration and generate new migration for your extended ExtendedOrderRepository. Then clean the resulting migration .cs file, leave only empty methods  `Up` and `Down`.

**Comment by tatarincev** [comment]
Unfortunately, this is a side effect of DbContext extension and it cannot be bypassed in another way.

**Comment by danielstarzewski** [comment]
Ok, thank you for your reply. This is exactly how i fixed it for now. I have some ideas for solving this but not without breaking changes :)

**Comment by danielstarzewski** [comment]
So, do I understand correctly you are not currently planning any changes regarding this area?

**Comment by tatarincev** [comment]
I'd love to have some plans, but we do not know how!

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-45
