### ISSUE TITLE
Can't pass model returned by GET /ap/assets to AssetEntry

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1320]
Currently GET /api/assets return `AssetListItem`. So, if I use AutoRest client, I need to convert model returned from GET /api/assets to pass it to `AssetEntry`. Also, `AssetEntry.BlobInfo` accepts only `fileName`, not `name`, but still require `Name` field

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
