### ISSUE TITLE
Make errors logs more easily readable

### ISSUE THREAD

**Issue by vanzegbroecke** [VirtoCommerce/vc-platform#1321]
Right now, it's very difficult to read the errors in the logs.

![image](https://user-images.githubusercontent.com/21342840/38358840-b2b8eb38-38c6-11e8-94dc-58edef4a170e.png)

This would be fixed by: in _project-modules.sass for .log: 
- replacing 'overflow: auto' by 'overflow-x: hidden'
- removing 'wrap: nowrap'

and in _cosmetic.sass for .error
adding 
- overflow-wrap: break-word;

I haven't created a PR because I have issues generating the CSS. I get an error in _forms:
Invalid CSS after "-": expected 1 selector or at-rule, was "-moz-ui-invalid:not"
        on line 1 of Content/themes/main/sass/modules/_forms.sass
        from line 477 of Content/themes/main/sass/modules/_base-modules.sass
        from line 8 of Content/themes/main/sass/main.sass

Perhaps I have the wrong version of something, I don't know. But I think you could fix it by changing that. 

I don't know if this has any negative effects for other views, if so, then maybe adding a new class would be helpful.

The same logs then look like:
![image](https://user-images.githubusercontent.com/21342840/38359029-5b9823f4-38c7-11e8-9dfb-ed11b9e86542.png)

Which is much easier to read. :)

**Comment by tatarincev** [comment]
@vanzegbroecke  Thanks for the well-detailed issue, very valuable!

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
