### ISSUE TITLE
Import export never show error details

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1330]
Version info: 
- Browser version: Chrome 65
- Platform version: 2.13.26

### Expected behavior
If error occurs on import/export, error details should appear in dialog from blade header

### Actual behavior
![image](https://user-images.githubusercontent.com/6369252/39632621-0a446a7a-4fcf-11e8-99ed-0a3a9f214790.png)

### Steps to reproduce
1. Throw error on import/export
2. Profit

**Comment by avas** [comment]
I accidentally managed to reproduce similar error on different blade. The symptoms are the same, so it *might* be related to this issue.

Platform: 2.13.36
Browser: Firefox 64.0a1, Chrome 69

Steps to reproduce:
1. Create a new user account, set `Is administrator` flag for it.
2. Log in with that account.
3. Try to delete this account while being logged in with it.

Result: server responds with error 401 and describes the reason in the `message` property, but that message is not displayed in the error dialog:
![image](https://user-images.githubusercontent.com/1835759/46009911-27a87880-c0eb-11e8-8aec-e5c9c867aa6b.png)

Possible reason: the frontend [registers](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Scripts/app/app.js#L152) `platformWebApp.httpErrorInterceptor` that displays detailed errors on blades, but for some reason it sometimes does not intercept errors (as in this case). So the blade itself [displays an error](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Scripts/app/security/blades/account-list.js#L21) with message like `Error xxx` and no error details.

**Comment by dvs39** [comment]
Cant reproduce for both cases
Chrome: 70.0.3538.110
Platform: 2.13.38

**Comment by yecli** [comment]
Handled both cases.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.39
