### ISSUE TITLE
Add Russian localization to the platform and commerce modules

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1336]
Need to copy the appropriate resources to the following modules:
- [x] Platform
- [ ] VirtoCommerce.AviaryImageEditorModule
- [x] VirtoCommerce.Cache
- [ ] VirtoCommerce.Cart
- [ ] VirtoCommerce.Catalog
- [ ] VirtoCommerce.CatalogCsvImportModule
- [ ] VirtoCommerce.CatalogPersonalization
- [ ] VirtoCommerce.Content
- [ ] VirtoCommerce.Core
- [ ] VirtoCommerce.Customer
- [ ] VirtoCommerce.GoogleEcommerceAnalytics
- [ ] VirtoCommerce.ImageTools
- [ ] VirtoCommerce.Inventory
- [ ] VirtoCommerce.Marketing
- [ ] VirtoCommerce.Orders
- [ ] VirtoCommerce.Pricing
- [ ] VirtoCommerce.Quote
- [ ] VirtoCommerce.Sitemaps
- [ ] VirtoCommerce.Store
- [ ] VirtoCommerce.Subscription

[RU-ru-localization-pack.ZIP](https://github.com/VirtoCommerce/vc-platform/files/1994524/RU-ru-localization-pack.ZIP)

**Comment by asvishnyakov** [comment]
@tatarincev Is https://github.com/VirtoCommerce/vc-localization deprecated?

**Comment by MalikJuly** [comment]
All ru.*.json files added to the appropriate modules.
