### ISSUE TITLE
Allow to change application authentication options in Web.config

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1339]
Load this CookieAuthenticationOptions properties:

1. AuthenticationMode
2. AuthenticationType (use DefaultAuthenticationTypes.ApplicationCookie as default value)
3. CookieDomain 
4. CookieHttpOnly
5. CookieName
6. CookiePath
7. CookieSecure
8. <s>Description</s>
9. ExpireTimeSpan
10. LoginPath
11. LogoutPath
12. ReturnUrlParameter
13. SlidingExpiration

in the same way as they loaded for [ApplicationUserManager](https://github.com/VirtoCommerce/vc-platform/blob/527b2019ddbc69ab20520f63ee9bfe9b2d572e16/VirtoCommerce.Platform.Data.Security/Identity/ApplicationUserManager.cs).

Use `VirtoCommerce:Authentication:Cookie` prefix, omit Cookie prefix in property name if exist (i.e. `VirtoCommerce:Authentication:Cookie:AuthenticationMode`, but `VirtoCommerce:Authentication:Cookie:HttpOnly`)

Get default values from [here](https://github.com/aspnet/AspNetKatana/blob/dev/src/Microsoft.Owin.Security.Cookies/CookieAuthenticationOptions.cs) and [here](https://github.com/aspnet/AspNetKatana/blob/9f6e09af6bf203744feb5347121fe25f6eec06d8/src/Microsoft.Owin.Security/AuthenticationOptions.cs), except `AuthenticationType`

**Comment by aartiomov** [comment]
@asvishnyakov it's for admin, right?

**Comment by asvishnyakov** [comment]
@aartiomov Yep

**Comment by asvishnyakov** [comment]
@eMazeika Update: Description not needed

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
