### ISSUE TITLE
Fix read-only fields support in Metaform

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1340]
### Expected behavior
meta form should support read-only fields as described in the [docs](https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/basic-functions/metaform)

### Actual behavior
Declaring meta-field with isReadonly=true produces editable input.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
