### ISSUE TITLE
Marketing Module - Add ability to configure BOGO (Buy one get one) or "Stacking promotions"

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-platform#1344]
Marketing module - Add ability to configure BOGO (Buy one get one) or "Stacking promotions"

Business use case:
Buy any 2 reeds from a virtual catalog, get 50% off both (Buy One, Get One) or 50% off one (Buy One, Get 50% off).
Client would also like to have rewards like 100% off one, $5 off one, etc. for every exactly [count] of products.

It seems like we could potentially accomplish this by having some sort of toggle that would allow stacking.
For instance, given a promotion was configured like this with an "Allow Stacking" toggle switched on, the reward would apply for every time the conditions are met:

Business use case:  Buy Two, Get One 50% Off
Configuration:
Allow Stacking?  True
Visitor:  Consumer
If any of these catalog conditions are true:
Category is Reeds
If any of these cart conditions are true:
Exactly 3 of item in category Reeds
They get
50% off 1 of select entry
Expected result:  For every 3 items that meet the above conditions, give 50% off the lowest priced item that meets the requirements.
Given 3 reeds for $5.99 each, reduce one by 50%
Given 2 reeds for $9.99 each and 1 for $6.99, reduce $6.99 by 50%
Given a total of 9 reeds with the below pricing, reduce as indicated
4 for $14.99
3 for $12.99 (reduce 1 by 50%)
2 for $9.99 (reduce 2 by 50%)
Given a total of 5 reeds with the below pricing, reduce as indicated
2 for $14.99
1 for $10.99
2 for $9.99 (reduce 1 by 50%)

Its a common promotion concept

**Comment by tatarincev** [comment]
@emathavan  Thanks for the detailed feature request, very appreciated!
I've moved this issue into https://github.com/VirtoCommerce/vc-module-marketing repository
https://github.com/VirtoCommerce/vc-module-marketing/issues/31
