### ISSUE TITLE
Can't change DynamicProperty name in Organization

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#1345]
Version info: 
- Browser version: all
- Platform version: 2.13.27

### Expected behavior
DynamicProperty name changed after save
### Actual behavior
Saving dynamicproperty returned error.

![image](https://user-images.githubusercontent.com/14821555/41149939-1cf4209e-6b0d-11e8-8283-4728ccea7e98.png)

### Steps to reproduce
1. Creating dynamic property in organisation
2. Close blade and reopen the property
3. Change field "Property name" and click save

**Comment by asvishnyakov** [comment]
Related to #1393, #1291

**Comment by tatarincev** [comment]
Fixed https://github.com/VirtoCommerce/vc-platform/releases
