### ISSUE TITLE
When my user is about to be deleted, I want to be notified that I am about to delete the user I am sign in with

### ISSUE THREAD

**Issue by spnikitin** [VirtoCommerce/vc-platform#1346]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: any
- Platform version: 2.13.27

### Expected behavior

GIVEN I am signed in to the backend admin 
AND the security module is open 
AND the user I am signed in with is checked 

WHEN I click delete 

THEN I want to be notified that I am about to delete a user I am signed in with (modal window with option to choose)
AND that I will be signed out if I do so 
AND I want to be signed out when I delete the user I am signed in with
AND redirected to the sign in page

### Actual behavior

It just deletes my user and nothing happens

**Comment by tatarincev** [comment]
Very unusual scenario, any deletion is not a trivial operation. Need to use lock user instead of or revoke access.
