### ISSUE TITLE
Expire date works different between pricelists and marketing

### ISSUE THREAD

**Issue by acandersson** [VirtoCommerce/vc-platform#1352]
Hi.
I just noticed that the function "expire date" works different between marketing/content publishing and prices. This might be something for you to keep in mind for next release. 
From a user perspective its much better if the functions are the same, and if not please add explanation text.

Version info: 
- Browser version: 
- Platform version:

### Expected behavior
The expire date functionality should act the same for both price lists and marketing

### Actual behavior
Today the expire date within marketing means the very FIRST minute of the expire date. Whereas the price list expire date expires the very LAST minute of the set date.

### Steps to reproduce
1. Set a price list to expire date 26 of June
2. Set a marketing activity ( content publishing) to expire date 26 of June.
3. At the 26 of June mid-day... the price list have expired but marketing still active.

**Comment by andrey-ciclicci** [comment]
Couldn't reproduce the unexpected behavior, it appears to be already fixed.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
