### ISSUE TITLE
In admin, Forgot password form always use default template for reset password notification

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1354]
This is because we use "en-us" culture by default and create template for it, while platform [always use "en"](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Controllers/Api/SecurityController.cs#L443). I believe we should use "en-us" or current user language if we can get it.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
