### ISSUE TITLE
Error when downloading sample data and unable to run store front completely

### ISSUE THREAD

**Issue by ahmedshaabansoliman** [VirtoCommerce/vc-platform#1374]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Chrome 67.0.3396.99 
- Platform version:Win10
- VS 2017 community

### Expected behavior
Things work smoothly
### Actual behavior
When I choose the electronics and clothing sample data instead of empty it finishes and then displays 3 object not set to an instance of object , for the customers and other two modules
### Steps to reproduce
1.go open the documentation
2.follow the install from source code steps precisely for the platform
3.when you are done choose to download the sample data instead of empty
4.sample data gets downloaded but you will get 3 object null reference errors . click close , the platform UI will still run smoothly
5.open the documentation to get the front store running
6.follow the install from source code steps for the store front
7.I get this error when I  try to run store front "Looks like you missed theme :(

We looked for 'index' view in the following locations

Electronics\vc-theme-default-1.3.2
But it simple to fix: follow our instructions to download and correctly configure theme for your storefront."
8.I always get this error , and even tried to remove themes and download them again , still not working

**Comment by tatarincev** [comment]
@ahmedshaabansoliman  Could you check into your storefront appsettings.json file this connection string `ContentConnectionString` value, it should points to `/App_Data/cms-content`   in the platform installation directory
For example:
if platform installed by this path `c:\vc-platform` 
Consequently  the `ContentConnectionString` should  has follow value
appsettings.json 
```
...
   "ContentConnectionString": "provider=LocalStorage;rootPath=c:\vc-platform\App_Data\cms-content"
...
```

**Comment by ahmedshaabansoliman** [comment]
Thank you for your fast response , I will confirm this and tell you
