### ISSUE TITLE
Doesn't work details-blade after filtering

### ISSUE THREAD

**Issue by Tilesto** [VirtoCommerce/vc-platform#1376]
Blade doesn't show up (but he tries) after search/filter conditions.
Preview: http://recordit.co/4GVljYfxpr

Steps:
Open Demo -> Catalog -> enter in "Search keyword.."-input some word (for example: r) -> on second blade select some row (folder)

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #312](https://github.com/VirtoCommerce/vc-module-catalog/issues/312) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #311](https://github.com/VirtoCommerce/vc-module-catalog/issues/311) via [**ZenHub**](https://www.zenhub.com/)
