### ISSUE TITLE
Doesn't work required-attribute for generic datetime input

### ISSUE THREAD

**Issue by Tilesto** [VirtoCommerce/vc-platform#1378]
GenericInput template for dateTime type doesn't have ng-required attribute.
![image](https://user-images.githubusercontent.com/28765507/42633155-d7dd6b94-85df-11e8-9234-9b9c9ca8f999.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
