### ISSUE TITLE
Option to specify CC/BCC for EmailNotifcation per notification type

### ISSUE THREAD

**Issue by benb1n** [VirtoCommerce/vc-platform#1380]
Version info: 
- Platform version:

Our client would like the ability to specific a BCC email address for order email notifications to go to (and potentially other types of notifications).  Currently, the EmailNotification type only supports a recipient and sender.

@IgorisB

**Comment by n2pro** [comment]
All is well.
![screenshot_11](https://user-images.githubusercontent.com/13115017/42690719-bb81f930-86a5-11e8-90f1-dee14426c594.png)

**Comment by benb1n** [comment]
Thanks @tatarincev and @n2pro - We'll pull this into our next release and let you know if we run into anything.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.33
