### ISSUE TITLE
Platform crashes after installing ImageEditing module

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1384]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: chrome
- Platform version: latest

### Expected behavior
Work as normal

### Actual behavior
Grey screen
![image](https://user-images.githubusercontent.com/1566470/43176363-296574a6-8f78-11e8-87ec-84c74545bd41.png)

### Steps to reproduce
1. Install ImageEditing module
2. Click restart

**Comment by tatarincev** [comment]
Moved to https://github.com/VirtoCommerce/vc-module-aviary-image-editor/issues/7
