### ISSUE TITLE
When update order with responseGroup:Default, the OrderModule is getting NullReferenceException

### ISSUE THREAD

**Issue by kostyrin** [VirtoCommerce/vc-platform#1386]
**Describe the bug**
If we make a request like api/order/customerOrders/search with body {sort: "createdDate:desc", skip: 0, take: 20, responseGroup:"Default"} then we get the response with array of Orders without nested collections(Shipments and InPayments). Then if we want to update some property in some order like Status, in the result we get NullReferenceException. Because there are not nested collections in graph of the order.

**Steps to reproduce**
1.  api/order/customerOrders/search with body {sort: "createdDate:desc", skip: 0, take: 20, responseGroup:"Default"}
2. then make PUT api/order/customerOrders {id:"some", status:"Submitted", ...}
3. See error NullReferenceException

**Expected behavior**
have a PUT request without errors

**Version info (please complete the following information):**
 - Browser version:
 - Platform version: 2.13.32

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.16
