### ISSUE TITLE
VirtoCommerce should provide ability to use Azure Active Directory as an authentication provider

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1388]
**Problem:**
We use the corporative Azure Active Directory as a corporative standard. We want to use Azure Active Directory as an authentication provider for single sign in.

**User stories:**

As a manager, I want to sign in to Virto Commerce portal with Azure Active Directory account.
GIVEN An user has Azure Active Directory account
WHEN The user opens Virto Commerce portal
AND The user is not authenticated 
THEN The user should be redirected to Azure Active Directory

GIVEN The user has Azure Active Directory account
AND The user was redirected from  Virto Commerce portal
WHEN The user passes the sign in Azure Active Directory
THEN The user should be redirected to Virto Commerce portal 
AND I see Virto Commerce portal based on user role.

As an administrator, I want to manage roles and permissions in Virto Commerce portal.

As an administrator, I want to manage account in Azure Active Directory .

**Solution:**
https://docs.microsoft.com/en-us/azure/app-service/app-service-authentication-overview
https://docs.microsoft.com/en-us/azure/app-service/app-service-mobile-how-to-configure-active-directory-authentication

**Comment by avas** [comment]
Steps to test this feature:
1. Register platform application in Azure Active Directory:
    1. Go to the [Azure portal](https://portal.azure.com/).
    2. Register an application: **Azure Active Directory > App registrations > New application registration**.
    3. Enter app registration details: ![image.png](https://images.zenhubusercontent.com/5b7037d390d0044746ba55b5/9fab1f3f-bf50-47b8-8167-42382430d2cb)
        * Name - just any human-readable name;
        * Type - `Web app / API`;
        * Sign-on URL - the URL of the application. It should not necessarily be URL of an Azure web site - in my case it just points to a platform on my local IIS.
    4. After creation of an application, note the `Application ID` - you'll need it on the next step.
2. Change Azure AD authentication options in `Web.config`:
    * Change `VirtoCommerce:Authentication:AzureAD.Enabled` to `true`;
    * Paste your Azure AD application ID to the value of `VirtoCommerce:Authentication:AzureAD.ApplicationId`;
    * Insert your Azure AD domain ID to `VirtoCommerce:Authentication:AzureAD.TenantId`. It can be found on the Azure portal: **Azure Active Directory > (your domain) > Properties > Directory ID**.
3. Try the feature:
    * Launch the VirtoCommerce platform and navigate to the login page.
    * Click the `Sign in with Azure Active Directory` link. You will be redirected to the Azure AD login page.
![image.png](https://images.zenhubusercontent.com/5b7037d390d0044746ba55b5/d31b581c-aa84-4976-a94c-76cc9c8c07a2)
    * Choose your account, enter the password (if needed) and grant the VirtoCommerce platform permission to read your account data.
    * After that, you'll be redirected back to VirtoCommerce platform:
        * If there already was a VC platform account with your domain login, it will be updated with an external login info.
        * Otherwise, the platform will create a new account and link it with your Azure AD account. New account will have the `Manager` type and no roles assigned.
![image.png](https://images.zenhubusercontent.com/5b7037d390d0044746ba55b5/2392011b-7f0a-4de0-b877-9ca59e9068b2)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/v2.13.37
