### ISSUE TITLE
When you update dynamic property name 500 error occurs

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-platform#1393]
500 error is displayed when you update existing dynamic property

### Version info:
- Platform version: 2.13.33

### Actual behavior
![aGtDxtAJoD[1].gif](https://images.zenhubusercontent.com/578fb5bee40e5714b16c4fac/e33e18be-40c9-4588-b1f8-13a5cab3ef78)

**Comment by asvishnyakov** [comment]
Related to #1345, #1291

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.39
