### ISSUE TITLE
Make Role & RoleManagementService extandable

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1395]
**Problem:**
In my client project I can't extend Role or RoleService

**Solution:**
Make them extendable in usual way: use virtual methods, AbstractTypeFactory, etc.

**Proposal of changes:**
1. Make methods of RoleManagementService virtual
2. Create Role entity using AbstractTypeFactory
3. Add json converter for RoleSearchRequest

**Comment by asvishnyakov** [comment]
@tatarincev Any plans?

**Comment by tatarincev** [comment]
Already implemented in 3.0 platform version
