### ISSUE TITLE
Add polymorphism support to generated OpenAPI json and UI

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1397]
@asvishnyakov commented on [Tue Mar 20 2018](https://github.com/VirtoCommerce/vc-storefront-core/issues/87)

Research point: https://github.com/Azure/autorest/blob/master/docs/developer/guide/defining-clients-swagger.md#polymorphism

---

@asvishnyakov commented on [Thu Aug 02 2018](https://github.com/VirtoCommerce/vc-storefront-core/issues/87#issuecomment-409709709)

_Updated 27 Mar 2019_

Status:
* OpenAPI generation:
  * Swashbuckle is actually [died](https://github.com/domaindrivendev/Swashbuckle) and [not support](https://github.com/domaindrivendev/Swashbuckle#transitioning-to-swashbuckle-50) polymorphism, [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) (actually it's .NET Standard library, so it can be used in current platform) actively maintained and now support <sup>[[1]](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#compatibility)[[2]](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2#issuecomment-472388765)</sup> polymorphism in preview _(status at 27 Mar 2019)_. 
    * [Third-party nuget](https://www.nuget.org/packages/Swashbuckle.AspNetCore.Polymorphism/0.2.1) available for ASP.NET Core version
  * [NSwag](https://github.com/RSuter/NSwag) support [polymorphism](https://github.com/RSuter/NJsonSchema/wiki/Inheritance)
* UI:
  * [swagger-ui:](https://github.com/swagger-api/swagger-ui/issues/2438) [has no support](https://github.com/swagger-api/swagger-ui/issues/2438) and _has no plans to implement_ in near future
  * [ReDoc](https://github.com/Rebilly/ReDoc): [support](https://github.com/Rebilly/ReDoc#features) polymorphism, but have no built-in console
* Code generation:
  * AutoRest: [support](https://github.com/Azure/autorest/blob/366c80f48e4529b06921b27297ea0b318395d102/docs/how-autorest-generates-code-from-swagger.md#polymorphism) polymorphism
  * [NSwag](https://github.com/RSuter/NSwag) [can also be used](https://github.com/RSuter/NSwag/wiki/SwaggerToCSharpClientGenerator) for generation

Resolution: the blocking issue is UI support: swagger ui has no support of polymorphism, while ReDoc has no built-in console. For OpenAPI generation we may have a few solutions, code generation already ready for polymorphism and not require any additional actions.

**Comment by Woland2k** [comment]
don't swagger UI is that critical, unless it crashes

**Comment by yecli** [comment]
It is working. Storefront is receiving derived objects together with base ones in array using autorest client.
Sample prototype extending Platform API implemented in this [commit](https://github.com/VirtoCommerce/vc-platform/commit/2009458bcade2b43606ede6a1a402224f242db55).

**Comment by yecli** [comment]
Usage example:
Add info about base polymorphic types to your module manifest (assembly qualified name), so not info on derived types needed:
```
    <openAPIPolymorphicTypes>
        <assemblyQualifiedTypeName>VirtoCommerce.Domain.Cart.Model.LineItem, VirtoCommerce.Domain</assemblyQualifiedTypeName>
    </openAPIPolymorphicTypes>
```
Your base and derived types should have property `public string Type` containing value `Type.Name` (or `Type.FullName` in case `UseFullTypeNameInSwagger = true` for the module).

**Comment by asvishnyakov** [comment]
@yecli Can we do that in code? I don't think it's good idea to put .NET-specific information into manifest. Also, in code we can use nameof() operator and use Assembly class, while here we can make mistake in type & assembla names

**Comment by yecli** [comment]
First it was implemented in code using custom attribute for polymorphic base type. But there were some problems when we want to make type from dependent assembly as polymorphic base for specific module (e.g. LineItem from Domain for Cart module) - in such cases we would need to load dependent assemblies to search polymorphic types. Moved polymorphic types declaration to module manifests for explicit and clear declaration. Also we already use assembly qualified type names in manifest - for [defining module type](https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web/module.manifest#L25).

Agree with you, better to do this in the code. @tatarincev said the same and advised to use AbstractTypeFactory for registering polymorphic types. Going to try this solution.

**Comment by yecli** [comment]
Added special interface to register type to be polymorphic for the module:
```
    public interface IPolymorphismRegistrar
    {
        IPolymorphicBaseTypeInfo[] GetPolymorphicBaseTypes(string moduleName);
        void RegisterPolymorphicBaseType(string moduleName, IPolymorphicBaseTypeInfo polymorphismBaseTypeInfo);
    }
```

Example of usage for Customer module polymorphism (`Member` class and its descendants):

```
            // Register Member descendants in AbstractTypeFactory
            AbstractTypeFactory<Member>.RegisterType<Organization>().MapToType<OrganizationDataEntity>();
            AbstractTypeFactory<Member>.RegisterType<Contact>().MapToType<ContactDataEntity>();
            AbstractTypeFactory<Member>.RegisterType<Vendor>().MapToType<VendorDataEntity>();
            AbstractTypeFactory<Member>.RegisterType<Employee>().MapToType<EmployeeDataEntity>();

…
            // Use IPolymorphismRegistrar to tell OpenAPI doc generator to use polymorphism for Member and its descendants
            var polymorphismRegistrar = _container.Resolve<IPolymorphismRegistrar>();
            polymorphismRegistrar.RegisterPolymorphicBaseType(ModuleInfo.Id, new PolymorphicBaseTypeInfo<Member>(nameof(Member.MemberType)));
```

**Comment by yecli** [comment]
Next mechanism rework: left only `AbstractTypeFactory` as a source for OpenAPI polymorphism registration.

Usage - when registering type in `AbstractTypeFactory`, need to fill `TypeInfo.Discriminator` property with the name of base class discriminator property.
Example for `Member` type in vc-module-customer:
```
            // Register Member descendants in AbstractTypeFactory
            AbstractTypeFactory<Member>.RegisterType<Organization>().MapToType<OrganizationDataEntity>().Discriminator = nameof(Member.MemberType);
            AbstractTypeFactory<Member>.RegisterType<Contact>().MapToType<ContactDataEntity>().Discriminator = nameof(Member.MemberType);
            AbstractTypeFactory<Member>.RegisterType<Vendor>().MapToType<VendorDataEntity>().Discriminator = nameof(Member.MemberType);
            AbstractTypeFactory<Member>.RegisterType<Employee>().MapToType<EmployeeDataEntity>().Discriminator = nameof(Member.MemberType); 
```
Generated OpenAPI doc: 
[PolymorphicOpenAPI_VirtoCommerce.Customer.zip](https://github.com/VirtoCommerce/vc-platform/files/3159366/PolymorphicOpenAPI_VirtoCommerce.Customer.zip)

**Comment by yecli** [comment]
Closing as not applicable.
