### ISSUE TITLE
Allow to disable individual notifications

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1398]
**Problem:**
Our client have frustration because of disabled "Set active" button (which actually mean "set this template as default". They want to disable notifications individually.

**Solution:**
Add "Enable/Disable" button for notification (not template), rename "Set active" to "Set default" and add backend support of individual notification disabling.

**Proposal of changes:**
Just make notifications extendable to allow us implement this future by our hands or implement it itself.
Possible require backport of all changes related to notifications which was made for vc-platform-core: #1399

**Comment by tatarincev** [comment]
Seems duplicated https://github.com/VirtoCommerce/vc-platform/issues/1329
