### ISSUE TITLE
Migrate notifications  module from vc-platform-core to 2.x platform version

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1399]

**Comment by tatarincev** [comment]
The migration process can be divided into three phases
1. Move the notification module from 3.x -> 2.x
2. The data for old notifications migration and old logic replacement
3.  Testing

Technical details:
The epic issue allows getting more insight into how the notifications module work
https://github.com/VirtoCommerce/vc-platform/issues/467

**Comment by tatarincev** [comment]
Done https://github.com/VirtoCommerce/vc-module-notification/releases/tag/3.0.0-rc.2
