### ISSUE TITLE
Allow to make Dynamic Properties readonly

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1400]
**Problem:**
Some Dynamic properties are coming from client system on our client project. Client wants to disallow change this properties by their managers. Properties still should be available to view.

**Solution:**
Allow to mark some dynamic properties as readonly in backend. Do not allow to change this value in UI.

**Comment by Woland2k** [comment]
Also need ability to specify field as hidden, which will make dynamic property not appear in the UI

**Comment by tatarincev** [comment]
This issue has been closed because it has no longer relevant to the current operation nature of issues.
You may reopen this issue if it has been closed in error.
