### ISSUE TITLE
Add validation for dynamic properties

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1401]
**Problem:**
Dynamic properties now missing ability to add validations similar to product properties.

![image](https://user-images.githubusercontent.com/1566470/43664528-0c8920ce-9722-11e8-9cb8-2dbe33c27570.png)

**Solution:**
Add validation blade for dynamic properties.
![image](https://user-images.githubusercontent.com/1566470/43664515-052709c2-9722-11e8-9bbe-98ed07e59ae8.png)

**Proposal of changes:**
Make UI similar to product properties and add validation blade.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. https://virtocommerce.atlassian.net/browse/PRD-92
