### ISSUE TITLE
Design refactoring: blade menu background

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1413]
Make it possible to set blade menu and blade top backgrounds to be different. I'd like to have blade menu to have a white background instead of solid color with buttons being in dark outlines.

**Comment by asvishnyakov** [comment]
@Woland2k It's not too simple to make this changes because menu is part of blade header. And I believe we need to discuss about platform design & design extensibility first with people who already have experience with platform UI.

**Comment by Woland2k** [comment]
@asvishnyakov pretty sure you can target styles to sub elements of the blade without changing html, so shouldn't be that hard to accomplish

**Comment by tatarincev** [comment]
There will be complete UI redesign for 3.0 version so this issue no longer relevant
