### ISSUE TITLE
Include Microsoft.ApplicationInsights.SnapshotCollector nuget package

### ISSUE THREAD

**Issue by nickoli4** [VirtoCommerce/vc-platform#1415]
**Problem:**
It would be really practical to automatically collect debug snapshots when an exception occurs. Sometimes we're not there to take a memory dump at the right moment, having a snapshot created automatically would be a great help to see the stacktrace and the values of local variables at the time of the exception.

**Solution:**
This can easily be done by including the Microsoft.ApplicationInsights.SnapshotCollector nuget package ([https://docs.microsoft.com/en-us/azure/application-insights/app-insights-snapshot-debugger](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-snapshot-debugger)). Seeing as application insights support is already incorporated in Virto, this seems like a nice addition.

**Comment by tatarincev** [comment]
@nickoli4  Thanks for the issue
We already enable this feature in the storefront https://github.com/VirtoCommerce/vc-storefront-core/issues/140

**Comment by nickoli4** [comment]
Hi,

We are not using the storefront, we call the virto api directly because we integrated it with a clients own website that runs on the Sitecore CMS. Nevertheless it would be really useful to have access to this functionality when not running storefront.

**Comment by tatarincev** [comment]
@nickoli4  Ok, sure we are going to add this feature to the platform

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/v2.13.36
