### ISSUE TITLE
New feature: Allow to use multiple coupons for one shopping cart 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1416]
**Functional requirements:**
As a customer, I want to be able to enter several coupons during checkout and get multiple discounts associated with these coupons.

**Technical details:**
Need to extend storefront  project logic to handle multiple coupons entered by a customer  
Need to extend the default theme to allow enter multiple coupons during the checkout process
Extend Shopping cart domain type and persistent layer to support multiple coupons 

The process diagram of calculating discounts on the entered coupon
![image](https://user-images.githubusercontent.com/7566324/44259950-44f84600-a213-11e8-8352-99bfbdc22d1d.png)

**Comment by Woland2k** [comment]
Make sure there is a setting that allows switching to turn multiple coupons on and off.

**Comment by tatarincev** [comment]
@Woland2k Ok, it will be the only theme setting
