### ISSUE TITLE
Establish the 'Light' CI pipeline 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1423]
![image](https://user-images.githubusercontent.com/7566324/44667447-14868800-aa1b-11e8-9078-fa5c25392b94.png)
We need to prepare Three  'Light' pipelines for each kins of our projects (Modules, Platform, and Storefront) 
The light CI pipeline should consist of the following steps:
 - Download code from the repository 
-  Build process for managed code.
-  Run all unit test which will be discovered in the processed project
-  Perform step for  automatic quality control analyze via integration with SonarQube  (Quality, Security, Test coverage), need have individual settings for each type of project 
- Prepare step for swagger docs validity check for Platform and Modules projects which can expose REST API methods.

Need to establish the new email notification process which will inform about which step hasn't passed and error details in the human-readable form. 

**Already existing pipelines:**
https://github.com/VirtoCommerce/jenkins-pipeline-scripts/tree/master/vars

**Comment by Woland2k** [comment]
@tatarincev what is wrong with current CI build? We need to have docker images build in order to simplify future deployments and allow integrations tests.

**Comment by tatarincev** [comment]
@Woland2k  We are using current CI/CD as a start point. And we have three  primary goals in this project 
1. Get a person who will respond and understand for all our CI/CD processes.
2. Improve our current DevOps process (there are a lot of what we missed and working not as we expected).
3. Get a DevOps process as a product which we can use  in other projects

**Comment by asvishnyakov** [comment]
@Woland2k Simple: it's Phase 1 of new CI/CD which will replace current. They start from zero because it's hard to reconfigure current CI and its scripts <sub>(sad, but true; sorry)</sub>

**Comment by Woland2k** [comment]
@tatarincev @asvishnyakov instead of rewriting existing implementation, consider using approach described here: https://m.habr.com/company/flant/blog/352036/, that would be a more useful way to invest in CI automation

**Comment by asvishnyakov** [comment]
Wow
