### ISSUE TITLE
Research and integration templates for notifications

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1429]
Find already exist notifications templates and engine for further use as primary CI/CD reports.

**Comment by Woland2k** [comment]
This is not a correct approach, we shouldn't use emails for notifications regarding issues during builds. These should be created as "Issues" in the issue tracking app. Jenkins supports Jira out of the box and there might also be support for Github issue, so when certain module breaks, the issue should be created in Github and assigned to a person who cause the break (last person to checkin the change).
