### ISSUE TITLE
Virto Critical Issue: Platform Down in UrlRewriterOwinMiddleware

### ISSUE THREAD

**Issue by vanzegbroecke** [VirtoCommerce/vc-platform#1435]
The whole platform was unusable.

 All I have are the logs: [virto.log.zip](https://github.com/VirtoCommerce/vc-platform/files/2359865/virto.log.zip)

![availability](https://user-images.githubusercontent.com/21342840/45206862-7601ee80-b286-11e8-9425-44a33f80972b.png)

These are the modules and versions we are using: 
 5e5344e297376134a631afbb43247244386af718 Platform (v2.13.27-6-g5e5344e29)
 0c4e34fa8db6a456d237fbed47a772302bf311c1 VirtoModules/vc-module-cart (v2.16.12-7-g0c4e34f)
 4df844a32bd4eaa88e4977e7060d0c830760034a VirtoModules/vc-module-catalog (v2.21.9-2-g4df844a)
 dc667eb733d732ed00f0df170817a92dd5ff0ebe VirtoModules/vc-module-catalog-csv-import (v1.0.10)
 8576d526bc1140baf3d8108733701f56ebe5f1bf VirtoModules/vc-module-core (v2.25.9-1-g8576d526)
 59cb2bd9211fe34df66a01e3c7e984a50567680c VirtoModules/vc-module-customer (v2.14.18)
 403c50c38418aea8e4179ec81002643603fe1e30 VirtoModules/vc-module-dynamic-expressions (v2.12.6-1-g403c50c)
 b3eabfe781f8d902dfaad040aeb39157663c4644 VirtoModules/vc-module-elastic-search (v1.1.1-1-gb3eabfe)
 6b53075991eb021d68bb051a6a2b2c82e0b44d2c VirtoModules/vc-module-image-tools (v1.2.0-5-g6b53075)
 60c281163cf870c10e1222a41ac14f70f8da30fd VirtoModules/vc-module-inventory (v2.13.2)
 707b7654eace4b3cd82a8327221a8cd39ecd80b4 VirtoModules/vc-module-lucene-search (v1.1.0)
 3b81920199acea28aa4d043ff441955cf7cb804d VirtoModules/vc-module-marketing (v2.16.10)
 c66705dd5b8151c1bcdd5c81607d63d55c9b0813 VirtoModules/vc-module-order (v2.17.12-2-gc66705d)
 0baf72a125d7ce2c824a1c129ecc10735790dd04 VirtoModules/vc-module-pricing (v2.17.9)
 eaa501fa8fafedd20d9f27f3d37c2aa4828f7173 VirtoModules/vc-module-store (v2.13.5)

**Comment by tatarincev** [comment]
@vanzegbroecke Could you provide more information, any errors from ApplicationInsight will be helpful!

**Comment by vanzegbroecke** [comment]
@tatarincev That's the first thing I checked, but unfortunately Virto did not log any exceptions during this time, while there was also no sampling.

**Comment by tatarincev** [comment]
@vanzegbroecke  Is it storefront doesn't work or the platform?  It does not run at all?

**Comment by vanzegbroecke** [comment]
@tatarincev We don't use the Virto storefront. The platform didn't work anymore.

**Comment by tatarincev** [comment]
@vanzegbroecke  Why do you decided what this error related to UrlRewriterOwinMiddleware?

**Comment by tatarincev** [comment]
@vanzegbroecke  I'm afraid I can't provide any advice based on this telemetry. Need more information, maybe ve can schedule skype call?

**Comment by vanzegbroecke** [comment]
@tatarincev If that helps, sure :)

**Comment by vanzegbroecke** [comment]
@tatarincev It was on our production environment.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
