### ISSUE TITLE
Duplicated dictionary values

### ISSUE THREAD

**Issue by alex765022** [VirtoCommerce/vc-platform#1436]
We need exclude way to make duplicate values for one property and one locale.

Catalog module: 2.22.2

![vl78rakcvo](https://user-images.githubusercontent.com/7644848/45689367-13490680-bb54-11e8-9efb-3fa6ef30b711.gif)

**Comment by tatarincev** [comment]
The system doesn't allow to save dictionary values with the same alias
Released https://github.com/VirtoCommerce/vc-module-catalog/releases/v2.23.0
