### ISSUE TITLE
Upgrade platform and modules to latest .NET Framework 4.7.2

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1441]
**Problem:**
.NET Framework <= 4.7.1 has bugs that _may_ cause exceptions when you try to use .NET Standard assemblies as a dependency.
https://github.com/dotnet/standard/issues/481
https://github.com/dotnet/standard/issues/567

**Solution:**
Upgrade platform and modules to latest 4.7.2

**Proposal of changes:**
Upgrade platform and modules to latest 4.7.2

**Comment by tatarincev** [comment]
No longer relevant because of the next major version is built on .NET Core 3.1
