### ISSUE TITLE
In-site payment forms should be declared in theme, instead of payment module

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1442]
**Problem:**
Same payment module can be used in different themes with different layout. Currently, form declared & redners in module, theme receive only rendered html. It cause problems, because layout of form may be incompatible with theme layout.

**Solution:**
Allow to declare payment form in theme.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-93
