### ISSUE TITLE
Implement script for VC platform automatic installation on the newly created docker image

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1444]
You might use the already existing script as the base.

Install the platform from the triggered branch or master if CI pipeline triggered  changes made in another project 

Download the code and build of the latest modules versions (from master branch) or from the triggered branch of a concrete module. The test projects must be also copied and be available for discovery.

Import the sample data with errors monitoring, any error on this stage must be interpreted as breaking pipeline issue.

**Comment by Woland2k** [comment]
What is Virtual machine here? We don't use VMs, is that supposed to be docker container?
