### ISSUE TITLE
Implement script of the storefront automatic installation on a newly created docker image

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1446]
Install the storefront from triggered of the current CI pipeline branch with all test projects

Сonfigure the storefront platform endpoint to work with the platform that runs on the same virtual machine connected to the same pipeline

**Comment by Woland2k** [comment]
What is Virtual machine here? We don't use VMs, is that supposed to be docker container? We also should reuse containers for both storefront and platform, they should each run in its own container and preferably each module should run as a service in its own container.
