### ISSUE TITLE
Create a docker image that can be used for development purpose

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1449]
- It should allow easy modifications of theme files, they should be exposed for editing on the host machine
- Should expose modules folder on the host machine, so new modules can be easily added
- Should allow debugging of the image by attaching to a process and walking through the code if needed for both storefront and backend

Additional features to consider:
- pre-installed modules and pre-populated database for even quicker deployment

**Comment by tatarincev** [comment]
Done https://github.com/VirtoCommerce/vc-module-training-docker
