### ISSUE TITLE
Rename docker images

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1450]
Create a more consistent way of naming images before it gets out of hand.

Currently we have the following docker images available publicly:

- virtocommerce/platform:latest
- virtocommerce/platform:dev
- virtocommerce/storefront:latest
- virtocommerce/storefront:dev - point to dev branch
- virtocommerce/storefront-linux:latest
- virtocommerce/storefront-core:latest
- virtocommerce/storefront-core:dev

instead we should have:

RUNTIME/PRODUCTION images
- virtocommerce/platform:latest - points to latest platform image, ready for production deployment (currently asp.net based instance)
- virtocommerce/storefront:latest - points to latest platform image, ready for production deployment (currently .net core based instance, can be both linux or windows depending on the host containers)

DEVELOPMENT images
virtocommerce/platform:sdk - points to the latest platform image that can be used for development
virtocommerce/storefront:sdk - points to the latest platform image that can be used for development

Also on local CI, we can have images for dev branches
virtocommerce/platform:dev-branch
virtocommerce/storefront:dev-branch

**Comment by tatarincev** [comment]
Moved to internal Jira https://virtocommerce.atlassian.net/browse/VP-1194
