### ISSUE TITLE
Link builder in Store allows to link across catalogs but links don't work (404)

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1451]
I am having hard time understanding how the whole linking system works and apparently there are some kind of URL rewrites going on but not for everything and every time.

Is it possible that storefront matches parts of the URL, for instance category names across catalogs? I'm seeing weird issues.

However, what really bugs me is that we are able to create link list within the store's link builder with links that point to another catalog (the store is configured to use virtual catalog but we can create links to categories in the original catalog). Unfortunately (or rightful so) the links then don't work - they get rendered for instance in the main-menu but 404 when you follow them.

Can somebody explain what is going on? Is this documented somewhere?

For some reason, storefront uses physical category code on the storefront homepage for collection links.

For instance, I created physical category T-shirts and imported some products.

Proceeded to create virtual category V-T-shirts (actually named it with V to better understand what is going on) and assigned code v-t-shirts. Within it linked the physical T-shirts category and some related products from other physical categories.

In all of the links rendered on storefront entry page (for collections) I am seeing the /t-shirts links instead of the /v-t-shirts. The links actually work and take me to the V-T-shirts category.

I am thinking that it must be matching within the category slug with "contains" or something. Is that how it works?

Already reset cache both in platform and storefront, restarted IIS Express for storefront, restarted IIS for Platform.. nothing helps.

Actually the /collections page shows two categories and they have the following URLs:
/t-shirts/t-shirts (points to the physical category that is linked to within the v-t-shirts virtual category)
/t-shirts (points to the virtual category V-T-shirts but should be using the code v-t-shirts, so it should be /v-t-shirts)

Also please note:

/collections/all returns 404.

There is really something weird going on here.

**Comment by tatarincev** [comment]
The each VC store has a special setting which controls behavior how the SEO Slug URLs being generated on the storefront  
![image](https://user-images.githubusercontent.com/7566324/46813276-b4ebfe00-cd76-11e8-9eea-a8d0bb15c640.png)
There are four modes:
Let's assume that we have followed virtual catalog structure
**Physical catalog**: physical-parent-category/my-cool-category/my-cool-product 
**Virtual catalog**:  virtual-parent-category <- physical-parent-category (category link from **Physical catalog**)
So the resulting links on the strorefront will be follow depend on active  mode
**Long**: /virtual-parent-category/physical-parent-category/my-cool-category/my-cool-product - which represent full object outline path in hierarhy including virtual categories
**Collapsed**: /virtual-parent-category/my-cool-category/my-cool-product -From URL will be excluded physical category which directly linked to the virtual category (very helpful mode if you want to link all products belongs to one or multiple  physical categories to one virtual  and hide their physical categories from resulting path)
**Short** : /my-cool-product - used only  SEO slug  defined for end object without hierarchy path
**None**: /product/123 - doesn't used slug at all, object type and identifiers used instead

**Comment by brgrz** [comment]
I'm using the default Long scheme and for some reason the top level slug doesn't use the virtual category's code but the physical category's code and then the 2nd level is the actual physical category again but yet somehow links work.

So in my case when using the default Long scheme the links should be
/v-t-shirts/t-shirts

instead they are /t-shirts/t-shirts

**Comment by brgrz** [comment]
Right, just figured out that SEO settings for category override the "code" property setting. In my case, for some reason the SEO settings set the slug for the above mentioned virtual category to "t-shirts", so that explains it.
