### ISSUE TITLE
Physical category code used instead of virtual category code

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1452]
For some reason, storefront uses physical category code on the storefront homepage for collection links.

For instance, I created physical category T-shirts and imported some products.

Proceeded to create virtual category V-T-shirts (actually named it with V to better understand what is going on) and assigned code v-t-shirts. Within it linked the physical T-shirts category and some related products from other physical categories.

In all of the links rendered on storefront entry page (for collections) I am seeing the /t-shirts links instead of the /v-t-shirts. The links actually work and take me to the V-T-shirts category. 

I am thinking that it must be matching within the category slug with "contains" or something. Is that how it works?

Already reset cache both in platform and storefront, restarted IIS Express for storefront, restarted IIS for Platform.. nothing helps.

**Comment by brgrz** [comment]
UPDATE:

Actually the /collections page shows two categories and they have the following URLs:
/t-shirts/t-shirts (points to the physical category that is linked to within the v-t-shirts virtual category)
/t-shirts (points to the virtual category V-T-shirts but should be using the code v-t-shirts, so it should be /v-t-shirts)

Both links work.

**Comment by brgrz** [comment]
Also please note:

/collections/all returns 404.

There is really something weird going on here.

**Comment by tatarincev** [comment]
Merged into https://github.com/VirtoCommerce/vc-platform/issues/1451
