### ISSUE TITLE
Allow to use raw search provider expression for indexed search

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1454]
- Need to extend type [SearchRequest]( https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.Domain/Search/SearchRequest.cs) with **RawQuery** property.  This property should contain the search expression in the native syntax for concrete search provider.
- Handle the new  property  **RawQuery** in the  [vc-module-azure-search](https://github.com/VirtoCommerce/vc-module-azure-search)
- Handle the new  property  **RawQuery** in the  [vc-module-elastic-search](https://github.com/VirtoCommerce/vc-module-elastic-search)

**Comment by Woland2k** [comment]
it should be RawSearchCriteria in the actual server side implementation

**Comment by asvishnyakov** [comment]
If you plan to use this solution instead of implementing our own search syntax, then totally disagree. It will complicate moving to another search provider.

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.8

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-module-azure-search/releases/tag/v1.1.4
