### ISSUE TITLE
SignalR doesn't work via redis

### ISSUE THREAD

**Issue by kostyrin** [VirtoCommerce/vc-platform#1462]
if use RedisConnectionString in web.config

**Comment by kostyrin** [comment]
link https://github.com/VirtoCommerce/vc-platform/issues/878

**Comment by kostyrin** [comment]
https://github.com/VirtoCommerce/vc-platform/pull/1464

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.38
