### ISSUE TITLE
Platform support for GDPR requirements

### ISSUE THREAD

**Issue by danielstarzewski** [VirtoCommerce/vc-platform#1465]
Dear VC Team,

One of the requirements of GDPR says that _In automated systems, it must be possible to carry out a retrospective examination of what personal data was entered at what time and by which person._

Does VC Platform support that requirement? I am referring to editing Contacts information by administrators in the backoffice especially.

Thank you,
Daniel

**Comment by tatarincev** [comment]
So we have some like this for security accounts, is would this be suitable have same auditing log for contacts?
![image](https://user-images.githubusercontent.com/7566324/48186712-834c5f80-e341-11e8-8924-69374c2fba8a.png)

**Comment by piotr-kd** [comment]
Hi,
I'm Daniel's colleague, working on the same project and we agreed that I'll follow up here.
In my opinion the auding mechanism you referred to could do. As long as we can identify based on this:
* who modified personal data (which user)
* when it happened
* what data was modified (from what value to which value)

May I ask:
* does this mechanism exist already? And does it allow to answer the 3 questions above?
* if so, can I just re-use it for Contacts?
* or perhaps you planned to implement it in Contacts and we should wait and then upgrade?

GDPR is quite a big thing in Europe these days. Perhaps you have some other mechanism in Virto that satisfies GDPR requirements or something official that would explain why tracking changes in the back office (Admin) is not required to satisfy GDPR? I assumed it is required but perhaps I'm wrong?

Thanks for looking at this,
PKD

**Comment by tatarincev** [comment]
In addition regarding to GDPR  there are other  requirements that can  also  be provided by system, please let me know which of these requirements will be most critical for you? 

- stop the personal data processing upon the request;
- temporary restrict the data processing (prevent a specific data subject’s personal data from
- undergoing certain processing activities);
- delete the personal data processing upon the request;
- rectify the personal data processing upon the request (inaccurate data, incomplete data);
- save the record saying user gives consent to process his/her personal data (consent can be withdrawn anytime);
- send the notification regarding data breaches within 72 hours (any delay);
- provide data subject with their personal data in a common, structured format (machine-readable format).

**Comment by tatarincev** [comment]
I've created the new work issue https://github.com/VirtoCommerce/vc-module-customer/issues/46 you might track the progress there

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
