### ISSUE TITLE
Allow to  change shortcut icon for platform application

### ISSUE THREAD

**Issue by vturovets** [VirtoCommerce/vc-platform#1467]
**Problem:**
Need to add possibility  to change shortcut icon  for the platform application

**Comment by tatarincev** [comment]
Technical details:
The platform has a special setting that allows to do some UI customization. 
![image](https://user-images.githubusercontent.com/7566324/48331069-9c158780-e657-11e8-9954-a45ecbe55d69.png)
We need to extend this setting with the new parameter with name `favicon` that can contains path to the icon that is used as shortcut icon for application.
Also need to somehow to read `favicon` setting value and use it in the `_Layout.cshtm` or 
 use the default if this  setting not set. https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Views/Shared/_Layout.cshtml#L8

**Comment by tatarincev** [comment]
The default favicon path doesn't work
![image](https://user-images.githubusercontent.com/7566324/49726898-b4d58500-fc77-11e8-8413-d0bf9f08a805.png)

**Comment by yecli** [comment]
Changed default favicon path: "~/favicon.ico" => "favicon.ico".

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.39
