### ISSUE TITLE
Load assemblies with debugging symbols

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1468]
I can't see lineNumber:symbolPlace in logs on production, because debugging symbols is not loading (we create them for releases)

Here:
https://github.com/VirtoCommerce/vc-platform/blob/444df1e1d12cad614fe52451fe560dc918f7caa6/VirtoCommerce.Platform.Web/VirtoCommercePlatformWebBootstrapper.cs#L120
instead of using simple Assembly.Load we should use Assembly.Load(byte[], byte[]) to provide debugging symbols, if exist.

**Comment by tatarincev** [comment]
No longer relevant for 3.0
