### ISSUE TITLE
Search facet terms should be case insensitive

### ISSUE THREAD

**Issue by emathavan** [VirtoCommerce/vc-platform#1471]
**Issue**

System generated facet search terms are treated case sensitive.

**Actual behavior**
A system generated url of https://mac-test-virto.miretail.com/guitars?terms=__featured:TopRated works but this url https://mac-test-virto.miretail.com/guitars?terms=__featured:toprated fails to return search results. 

The understanding is that case sensitve handling is native to how Virto handles this.

**Expected behavior**
We would like facet search terms to be treated in a case insensitive manner.

**Comment by tatarincev** [comment]
Moved to https://github.com/VirtoCommerce/vc-platform/issues/1471

**Comment by tatarincev** [comment]
Moved to https://github.com/VirtoCommerce/vc-platform/issues/1471

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-47
