### ISSUE TITLE
New api account blade console errors

### ISSUE THREAD

**Issue by priboltik** [VirtoCommerce/vc-platform#1472]
**Describe the bug**
When user open the form for adding API account, there are some errors in console.

**Steps to reproduce**
1. Go to Security -> Users
2. Select anybody.
3. Click on "API Accounts" section
4. Click "Add"

**Expected behavior**
Add form will open without any bugs))

**Screenshots (optional)**
![default](https://user-images.githubusercontent.com/1209682/48537319-0be37680-e8d3-11e8-95b3-43afded234e0.png)

**Version info (please complete the following information):**
 - Browser version: Google Chrome 70.0.3538.102
 - Platform version: 2.13.37

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.38
