### ISSUE TITLE
CacheManagerExtension shoud be moved to VirtoCommerce.Platform.Core

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#1473]
**Problem:**
When I want to use CacheManagerExtension methods I have to add a dependency on VirtoCommerce.Platform.Data, which in turn adds many other dependencies.

**Proposal of changes:**
Move CacheManagerExtension to VirtoCommerce.Platform.Core.
For backward compatibility keep this class in VirtoCommerce.Platform.Data and make it call the new class from VirtoCommerce.Platform.Core.

**Comment by tatarincev** [comment]
No longer relevant for 3.0
