### ISSUE TITLE
Locally installed demo doesn't have B2B catalog

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1477]
**Describe the bug**
Installing new demo store locally and selecting our default demo templates creates 3 demo store with B2B not functioning correctly.

**Steps to reproduce**
Setup new demo locally

**Expected behavior**
Should have bolts catalog

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1566470/48809883-500fb600-ecdb-11e8-9371-73af9ca6b960.png)

**Comment by tatarincev** [comment]
I've updated the sample data and  added the B2B catalog.
