### ISSUE TITLE
Application Insights: Make adaptive sampling optional

### ISSUE THREAD

**Issue by nickoli4** [VirtoCommerce/vc-platform#1478]
Hi,

Adaptive sampling of application insights telemetry is enabled by default, however there are times where we'd prefer to have no sampling. We'd like to have the option to turn of adaptive sampling and use Ingestion sampling instead. Can inclusion of the adaptive sampling processor be based on an app setting?

**Comment by tatarincev** [comment]
@nickoli4 I do not think that this should be done on the platform side. The  [AppInsight sampling](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling) is well documented in the official MS documentation, as well as the process of switching between them, so overriding the AppInsight default settings logic using our own logic seems as bad idea for me.
Therefore, I suggest using the default recommended ways for sampling policies switch, as described in this article https://docs.microsoft.com/en-us/azure/application-insights/app-insights-sampling.

For you case, to switch sampling policy to **Ingestion** you just need to comment [AdaptiveSamplingTelemetryProcessor](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/ApplicationInsights.config#L7 )in the`ApplicationInsights.config` of your platform application.
  
```
<!-- Disabled adaptive sampling:
  <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
    <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
  </Add>
-->
```

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
