### ISSUE TITLE
Vertical scrollbar does not show in link list builder

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1481]
Within the link list builder when the number of added links exceeds the height of the browser window vertical scrollbar does not appear but it should.

As such it is impossible to edit anything below the last link shown at the bottom of the page.

![image](https://user-images.githubusercontent.com/193816/49315442-0189c500-f4ee-11e8-8169-2cf621cf15fa.png)

**Comment by yecli** [comment]
Fixed, released in https://github.com/VirtoCommerce/vc-module-content/releases/v2.13.10
