### ISSUE TITLE
Add logging for all entities across platform

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1486]
**Problem:**
Currently when we need to understand who and how changed object, it's not always possible, because information logging only for some objects like Orders.

**Solution:**
Add logging to all entities, but allow to disable it for some entity/module if not needed. Also, need a single entry point for logging to see all logged events.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-29
