### ISSUE TITLE
Swagger UI: add support for OAuth2 authentication

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-platform#1490]
**Problem:**
Currently, Swagger UI relies on cookie-based authentication. But, as of #1476, the VirtoCommerce platform won't be using cookies for authentication anymore - it uses [OAuth2 Password Grant Flow](https://www.oauth.com/oauth2-servers/access-tokens/password-grant/) instead. It is not supported by the `swagger-ui.js` used in the platform, so the authentication fails for methods that require additional authorization, e.g. `GET /api/platform/security/user/{userName}`:
![image](https://user-images.githubusercontent.com/1835759/49589288-9469aa00-f99b-11e8-9c1d-abeba5de2677.png)

**Solution:**
The easiest solution would probably be to update the `swagger-ui`. Current version (3.20.1 at the moment of writing this) has built-in support for OAuth authentication:
![image](https://user-images.githubusercontent.com/1835759/49589767-cb8c8b00-f99c-11e8-8ecb-b5e31d624759.png)
![image](https://user-images.githubusercontent.com/1835759/49589840-01ca0a80-f99d-11e8-9548-7b181eccfd28.png)

**Proposal of changes:**
* Install updated version of `swagger-ui` (from bower or directly from the [swagger-ui repository](https://github.com/swagger-api/swagger-ui/tree/master/dist));
* Update the `SwaggerConfig.cs` to include it's files;
* Apply VirtoCommerce branding to it;
* Apply [tags auto-collapsing](https://github.com/swagger-api/swagger-ui/issues/3088);
* Investigate what else had been changed in `swagger-ui.js` for VC Platform. If there were some valuable changes, they need to be applied too.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.39
