### ISSUE TITLE
Invoice PDF can't be generated (Exception)

### ISSUE THREAD

**Issue by MarkusReuter** [VirtoCommerce/vc-platform#1491]
**Describe the bug**
Using a platform wich is freshly deployed from GitHub to Azure with the commerce-bundle I can't create an an Invoice PDF from any order. This results in an exception.

**Steps to reproduce**

1. Deploy Platform to Azure from GitHub
2. Install Modules and Commerce Bundle
3. Login as Admin/store
Do nothing else and then

4. Go to Orders
5. Click on any order, e.G. CO180503-00004 (Customer woland)
6. Click on "Get Invoice PDF"
7. See Error:

{"message":"An error has occurred.","exceptionMessage":"Cannot save a PDF document with no pages.","exceptionType":"System.InvalidOperationException","stackTrace":"   at PdfSharp.Pdf.PdfDocument.DoSave(PdfWriter writer)\r\n   at PdfSharp.Pdf.PdfDocument.Save(Stream stream, Boolean closeStream)\r\n   at VirtoCommerce.OrderModule.Web.Controllers.Api.OrderModuleController.GetInvoicePdf(String orderNumber)\r\n   at lambda_method(Closure , Object , Object[] )\r\n
...

**Expected behavior**
The invoice PDF is generated like in the demo store (https://admin-demo.virtocommerce.com)

**Version info (please complete the following information):**
 - Browser version:
Chrome Version 70.0.3538.110
 - Platform version:
2.13.38

**Additional context (optional)**
First I've tried to reproduce it in admin-demo.virtocommerce.com, but there it works. Since the Platform-Version is identical, I thought there is a problem with my installation, therefore I deployed a new platform from scratch without any changes by me, but the error keeps the same.

**Comment by tatarincev** [comment]
@yecli Could you take a look at this issue?

**Comment by yecli** [comment]
Sure, will check

**Comment by n2pro** [comment]
@tatarincev and @yecli Maybe this is due to the azure tariff plan. 
We have already encountered a similar problem. This is due to the fact that Free does not support GDI+

https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

**Comment by n2pro** [comment]
@MarkusReuter  Are you probably using free or basic ?

**Comment by MarkusReuter** [comment]
@n2pro You are right. Plans Free and Shared are not working. But Basic does well. Thanx!
