### ISSUE TITLE
Checkout Fees

### ISSUE THREAD

**Issue by gdllp** [VirtoCommerce/vc-platform#1494]
**Problem:**
Looking to add fees to the checkout process and noticed fields in the database to accommodate this but cannot figure out how to implement this.

**Solution:**
Provide some documentation describing the process of managing and implementing fees at the cart/checkout level

**Comment by tatarincev** [comment]
@gdllp Maybe you can provide some concrete your requirements for this feature or your vision how it should be done?

**Comment by gdllp** [comment]
@tatarincev We currently have an api that is provided to us by our ERP provider.  This api will feed us fees based on an item number.   The ability to plug this number provided by the api into the order is really what we are looking for. Maybe one possibility is linking some items of the catalog that are non-inventory with inventoried one and dynamically assigning the fee amount at checkout? In sorts like a kitted item.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-112
