### ISSUE TITLE
Create method that parses Enum flags from string that would skip wrong values and return result

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-platform#1499]
**Problem:**
We need a method that parses Enum flags from string and is able to handle wrong value and return result. Standard .NET Enum.TryParse(String, out TEnum) does not fit as it returns default(TEnum) in case of wrong value in parsed string.

**Solution:**
Implement method that returns enum containing all the values we could parse from the string.

**Proposal of changes:**
Implement methods in VirtoCommerce.Platform.Core.Common.EnumUtility class that parse all valid values from string delimited by separator and return their logical disjunction.
public static T SafeParseFlags(string value, T defaultValue)
public static T SafeParseFlags(string value, T defaultValue, string separator)

**Comment by artem-dudarev** [comment]
Public methods should not have default values for arguments.
So we need two methods:
`public static T SafeParseFlags(string value, T defaultValue)`
`public static T SafeParseFlags(string value, T defaultValue, string separator)`

**Comment by artem-dudarev** [comment]
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1026-default-parameters-should-not-be-used?view=vs-2017

**Comment by yecli** [comment]
Ok, will change

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.39
