### ISSUE TITLE
Image editor - Adobe announces the end of life for photo editor by Aviary

### ISSUE THREAD

**Issue by rayprestige** [VirtoCommerce/vc-platform#1504]
We can no longer get api key for the image editor - Aviary

Adobe has announced the shutting down of Aviary. 
ref: http://blog.aviary.com/archive/eol/

Not sure what an alternative that the team would consider, but a replacement would be extremely helpful. 

Thanks 
Ray

**Comment by yecli** [comment]
Hi Ray,

We do not have plans to replace Aviary in the near future.
In case you have solution with other editor - we are opened to contribution.
