### ISSUE TITLE
Show object ID in UI

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1505]
**Problem:**
For some cases like problems resolving on production site to which we have no access, we need to know ID of object. But we can't see ID of object in UI and because of that need to ask clients get it through API, incl. swagger console 

**Solution:**
Show ID in UI for all objects

**Proposal of changes:**
Review all "details" blades in VirtoCommerce and add text with object ID

**Comment by tatarincev** [comment]
I guess this functionality could be achieved via Angular UI routing by adding the current entity Id to the url path

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-95
