### ISSUE TITLE
Move all notification templates from project resources into embedded resources as solution files

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1506]
Do the same as described in this issue https://github.com/VirtoCommerce/vc-module-order/issues/74

**Comment by yecli** [comment]
Found that html subject templates contain \r\n because of autoformat on save in VS. This leads to errors when sending all these emails with real mail provider - \r\n cannot be the part of Subject.
Need to remove trailing line feeds and to save all templates again outside of VS.

**Comment by yecli** [comment]
Released in [v2.13.42](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.42)
