### ISSUE TITLE
Show CDN URLs for assets instead of Blob storage ones

### ISSUE THREAD

**Issue by mvsmal** [VirtoCommerce/vc-platform#1509]
**Problem:**
In the list of assets when right-clicking on a file and choosing "Copy link", the link appears with the Url of blob storage. If there is a CDN, admin has to manually replace the hostname with the CDN's one.

**Solution:**
We can generate the link with respect of CDN URL, which comes as a configuration.

**Proposal of changes:**
In the [`AzureBloblProvider.Search()`](https://github.com/VirtoCommerce/vc-platform/blob/dev/VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs#L175) and [`AzureBlobProvider.GetBlobInfo()`](https://github.com/VirtoCommerce/vc-platform/blob/dev/VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs#L53) methods, we can use `GetAbsoluteUrl()` method, but we need to pass `Uri.PathAndQuery` as argument, since [`GetAbsoluteUrl()`](https://github.com/VirtoCommerce/vc-platform/blob/dev/VirtoCommerce.Platform.Data.Azure/AzureBlobProvider.cs#L314) doesn't use `_cdnUrl` for absolute URLs.

**Additional context (optional)**
In our project administrators use assets (images) for banners, so they copy-paste the wrong links. We cannot make sure every user manually and properly replaces the hostname in the link.

It is a bit complicated to test the mentioned methods, since they use `CloudBlobClient` and `CloundStorageAccount` classes from [`WindowsAzure.Storage` package](https://www.nuget.org/packages/WindowsAzure.Storage/) directly. We could implement some wrappers with interfaces, which would be mocked for testing.

**Comment by tatarincev** [comment]
@mvsmal Thanks, did you test these changes with/without  CDN?

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.41
