### ISSUE TITLE
Admin bugs & improvement suggestions

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-platform#151]
Catalog:
1. Creating new catalog - need a way to add languages from language edit blade.
2. In environment where admin services and DB are placed in different machines so there is some delay between user action and response. While creating category, after “Create” click there is some delay and no feedback to the user that he clicked the button. User can think he didn’t click it and clicks again. As the result two categories created (or as many as user has clicked “Create” button).
3. Why user sees product level property edit area in catalog/category properties view? If there are many such a properties the UI can be overloaded and confusing.
4. Editing property value. Copy/Paste to the property value (long text property) doesn’t activate “Save” button.
5. If property definition changed (example: from single language to multilanguage) old values of the property in items not available and new can not be saved.
6. Duplicate item functionality would be great.
7. Creating product variation. Accessories are not copied while creating new variation of a product.
8. Product associations. Association properties can’t be changed.
  Example:
    Added product as “Accessories” group, need to change to “Related Items”.
    Now I need to delete old association and after that add new Associated item.
9. Product associations. Need batch association group change.
10. The same item can not be added to the product as association of different group (not sure if it’s a bug of a feature).
11. Product association edit view. Show Associated product details/edit blade if it has been clicked.
12. Export. Product associations not exported.
13. Add Price to Variation from product page. “Save” button not activated.

Dashboard:
14. Shortcuts to mostly used modules. Catalog, Order etc. (module could add shortcut widgets to dashboard)

**Comment by eMazeika** [comment]
1. added
2. fixed
3. non-editable property values hidden
4. fixed
5. fixed
6. need to decide if/when we add this feature
7. need to decide if/when we add this
8. need to decide if/when we add this
9. need to decide if/when we add this
10. 
11. fixed
12. API bug
13. validation fixed
14. need to decide if/what to add
