### ISSUE TITLE
Make Restart button more visible

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1513]
**Problem:**
New users can't spot the activated "Restart" button after installing a module.

**Solution:**
Should make it more noticeable. E.g.: display the button in a new modal dialog.

**Proposal of changes:**
Display the button a modal dialog, like all other confirmations.

**Comment by yecli** [comment]
Released in [v2.13.42](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.42)
