### ISSUE TITLE
Allow to login on behalf without defined url for  stores 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1518]
**Functional requirements:**
The current behavior:
![image](https://user-images.githubusercontent.com/7566324/52254817-4ed44980-2918-11e9-9e75-0f4a65f0ab07.png)

The blade with store selections must yo be removed and replaced to popup with  allows user enter a storefront url on "Login on behalf" action as it done for sitemaps:
![image](https://user-images.githubusercontent.com/7566324/52254865-a07cd400-2918-11e9-929b-4cb6cbd877cc.png)

remark: need to add placeholder for url input

**Use cases:**
**As a user** I press Login on behalf on specific user **so I can** login to store on behalf with selected user account, and if store secure URL is not specified, be able to enter it manually.

**Technical details:**
vc-module-store
1. Extend current ["Login on behalf" blade](https://github.com/VirtoCommerce/vc-module-store/blob/097b12e9f5d5e1fd9036da85283253149c8fa469/VirtoCommerce.StoreModule.Web/Scripts/blades/loginOnBehalf/loginOnBehalf-list.tpl.html) with popup allowing us to enter store URL if it was not presented. Form should contain URL placeholder.

Login on behalf blade when one shop have Secure URL and other does not:
![image](https://user-images.githubusercontent.com/15610352/52398219-2dbb5680-2ada-11e9-93eb-066356cee031.png)

Required popup when we click on the shop without secure URL:
![image](https://user-images.githubusercontent.com/15610352/52399108-02863680-2add-11e9-89c3-01a9878ac341.png)

Similar sitemaps popup:
![image](https://user-images.githubusercontent.com/15610352/52341078-710eba00-2a33-11e9-83da-be0e365c5579.png)

2. Link generator logic should remain [the following](https://github.com/VirtoCommerce/vc-module-store/blob/097b12e9f5d5e1fd9036da85283253149c8fa469/VirtoCommerce.StoreModule.Web/Scripts/blades/loginOnBehalf/loginOnBehalf-list.js#L32).

**Comment by Woland2k** [comment]
I think behavior should be remain as is with one extra case when url is not defined. 

If store has URL defined, it should open the store URL. If URL is not defined then offer enter URL.

**Comment by yecli** [comment]
![loginonbehalf](https://user-images.githubusercontent.com/15610352/52482043-03e55b00-2bd2-11e9-8765-6dacb68b3531.gif)

**Comment by yecli** [comment]
[2.13.8](https://github.com/VirtoCommerce/vc-module-store/releases/tag/v2.13.8)
