### ISSUE TITLE
VC-platform remove button

### ISSUE THREAD

**Issue by novik90** [VirtoCommerce/vc-platform#1530]
**Describe the bug**
when you click the remove button, nothing happens

**Steps to reproduce**
1. Go to vc-platform
2. Click on 'More'
3. add in search field word
4. Click on remove button

**Expected behavior**
Search field is clear

**Screenshots (optional)**
![remove](https://user-images.githubusercontent.com/12540891/53553160-09d5b880-3b4e-11e9-9845-81f003b6f64f.png)

**Version info (please complete the following information):**
 - Browser version: firefox 65.0.1
 - Platform version: v2.13.41

**Comment by eMazeika** [comment]
confirmed. Same bug in settings, users blades. Should review all search inputs

**Comment by blazemachine** [comment]
This problem is meeting in 65 Firefox version. Recommended update your Firefox to more later version for fix it.
