### ISSUE TITLE
Authorization in API browser affect authorization on main site

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1532]
**Describe the bug**
When you log in on API browser page (`/docs/ui/index`) it affect authorization on main site (you will be logged in, but has not same permissions).

**Steps to reproduce**

0. Log out on https://admin-demo.virtocommerce.com and https://admin-demo.virtocommerce.com/docs/ui/index if you was logged in, clear cookies
1. Go to https://admin-demo.virtocommerce.com/docs/ui/index
2. Click on `Authorize`
3. Type default demo credentials (`admin`/`demo`)
4. Click `Authorize` & `Close`
5. Go to https://admin-demo.virtocommerce.com
6. Open any order
7. You will see 401 error in developer console

**Expected behavior**
When you log in on API browser page (`/docs/ui/index`) it shouldn't affect man site or should grant same permissions

**Version info (please complete the following information):**
 - Browser version: Chrome 72
 - Platform version: 2.13.42

**Comment by AliveMen** [comment]
If bearer token authentication is enabled and we use 3rd - party web applications to authorization, LimitedPermissions claims will be granted to the user. 

Even if we login as Admin and don’t have, for example "platform:module:read" claims in LimitedPermissions, access to modules will be denied.

But when we login as Admin as usual on login page LimitedPermissions claims will be empty and Admin will have full access.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
