### ISSUE TITLE
Incorrect fields in "Registration notification" template

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1533]
**Describe the bug**
Parameters in the template are not bound.

**Steps to reproduce**
1. Go to 'Notifications'
2. Click "Registration notification" template

**Expected behavior**
Parameters in "Body" should match the ones provided in the top (check Screenshot)

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/5801549/54425885-20b80580-471f-11e9-9404-68cdc2c19704.png)

**Version info (please complete the following information):**
 - Platform version: 2.13.42

**Additional context (optional)**
As a first template in the list, this one gets tested most frequently.

**Comment by tatarincev** [comment]
No longer relevant for platform 3.0 version
