### ISSUE TITLE
keys instead of labels

### ISSUE THREAD

**Issue by kamilgarey** [VirtoCommerce/vc-platform#1538]
![image](https://user-images.githubusercontent.com/2689494/54693223-4f771700-4b37-11e9-9359-66e93fe1b216.png)

More details:
**Describe the bug**
UI names of fields and buttons are replaced with system names.

**Steps to reproduce**
1. Go to https://admin-demo.virtocommerce.com/#/workspace/catalog
2. Click names of fields, modules etc.
3. I see the following:

![image](https://user-images.githubusercontent.com/30014191/55696671-436ccf80-59e8-11e9-996b-1a61ab423c3f.png)

**Expected behavior**
Expect to see normal names of fields, buttons, and modules

Possible reason: authentication token expiration

**Comment by eMazeika** [comment]
Any status update?
#localization

**Comment by tatarincev** [comment]
@eMazeika  We are going to take this issue into work at this week

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.51.
