### ISSUE TITLE
The field Detail must be a string with a maximum length of 2048 or max

### ISSUE THREAD

**Issue by JeroenVandenabeele** [VirtoCommerce/vc-platform#1539]
**Describe the bug**
The length size from the field "Detail" in the table PlatformOperationLog. The comment on OrderLineItem & can store 2048 charachters. The Detail field contains the old comment and the updated comment.

**Steps to reproduce**

**Expected behavior**
length 2048

**Screenshots (optional)**

**Version info (please complete the following information):**
 - Browser version:
 - Platform version:

**Additional context (optional)**

**Comment by yecli** [comment]
Released in [v2.13.43](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.43).
