### ISSUE TITLE
Updating an objects containing dynamic properties generates a large amount of SQL queries 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1541]
**Problem:**
Update operations for some complex object  e.g `CustomerOrder` may generates a huge amount of SQL queries due that  not optimal logic for saving dynamic properties values for objects. This fact can leads to significant performance  degradation on update operations  for objects that implement `IHasDynamicProperties` interface.

**Solution:**
Change the logic for saving objects dynamic properties from each object to  batch operation.

**Comment by yecli** [comment]
Released in [v2.13.43](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.43).
