### ISSUE TITLE
Clarify the difference between "Is administrator" flag and "Administrator" role in UI

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1542]
**Problem:**
We have both `Is Administrator` flag and `Administrator` role in UI. It may confuse, because they have different scopes, as I know:
- `Administrator` role will allow customer to login into admin UI and call API, if customer has `call API` permission also (accounts with `Customer` role will not be able to call API even if they have the following permission)
- `Is Administrator` flag will grant unrestricted access to admin UI, API call. System will even not check any permissions if account has this flag, just grant access immediately, as I know.

**Proposal:**
Rename `Is Administrator` flag to `Unrestricted access` in UI and specify `Administrator` & `Manager` roles difference of `Customer` role in hint under selection box.

**Comment by Woland2k** [comment]
I think is administrator should be rehabbed to super user to reflect uninjured permissions.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
