### ISSUE TITLE
Blade duplication

### ISSUE THREAD

**Issue by artmakarov** [VirtoCommerce/vc-platform#1543]
Two blades open when you configure permission scopes

![blade_dublicate](https://user-images.githubusercontent.com/37446577/54902705-28c83000-4eeb-11e9-9b37-fec2fc68d4fb.gif)

**Problem:**
Two "click" events are triggered on the "label" tag.

**Solution:**
Use $event.preventDefault();

VirtoCommerce.Platform.Web\Scripts\app\security\blades\permission-scopes.tpl.html
``` javascript
 <label ... ng-click="blade.selectNode(data, !data.$selected, $event)">
```
VirtoCommerce.Platform.Web\Scripts\app\security\blades\permission-scopes.js
``` javascript
blade.selectNode = function (node, selected, event) {
  if (event) {
    event.preventDefault();
  }

  node.$selected = selected;

  if (selected && node.selectFn) {
    node.selectFn(blade, function (assignedScopes) {
      node.assignedScopes = assignedScopes;
      node.assignedScopesLabels = getNodeAssignedScopesLabels(node);
    });
  }

  $scope.selectedNodeId = node.type;
};
```

**Version info:**
Platform version: 2.13.42

**Comment by yecli** [comment]
Released in [v2.13.44](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.44).
