### ISSUE TITLE
The order of Multiple values doesn't work

### ISSUE THREAD

**Issue by yongbin-kooboo** [VirtoCommerce/vc-platform#1544]
**Describe the bug**
I am using the Multivalue of value type for a property, after saving, the order is random when I reload the property.

**Steps to reproduce**
1. Setup the values(a, b, c, d) for multiple value property
2. Save the property
3. Reload the property
4. The values are (a, d, c, b) not I entered values(a, b, c, d)

**Expected behavior**
The values should be (a, b, c, d) not (a, d, c, b)

**Version info (please complete the following information):**
 - Browser version: Chrome 72.0.3626.121
 - Platform version: 2.13.19

**Comment by AliveMen** [comment]
For right sorting order you should use dictionary values with priority.

![AAI_190329_163634](https://user-images.githubusercontent.com/11813599/55237076-593d0080-5242-11e9-865b-a51b19ac3f11.png)


https://github.com/VirtoCommerce/vc-module-core/blob/025ae6e5722f49033899122994c9a65aad22d5fe/VirtoCommerce.Domain/Catalog/Model/PropertyDictionaryItem.cs#L10

**Comment by yecli** [comment]
@yongbin-kooboo This property was introduced in vc-module-catalog [v2.23.13](https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/v2.23.13).
Does it solve the problem?

**Comment by yongbin-kooboo** [comment]
Sorry, reply late.
No, my property is not a dictionary.

![property](https://user-images.githubusercontent.com/4169113/56174581-bb10af00-6025-11e9-8f2c-9aaa6bb0862c.png)

**Comment by yecli** [comment]
For non dictionary values we do not have a possibility to set order. So i think the solution for you could be using dictionary property.
