### ISSUE TITLE
The price of a product display very slow

### ISSUE THREAD

**Issue by yongbin-kooboo** [VirtoCommerce/vc-platform#1545]
**Describe the bug**
We have over 3000 price list, when we open a product in virto, the related price display very slow or timeout.

**Steps to reproduce**
1. Go to 'Catalog'
2. Click a product
3. Scroll down to 'price' block
4. Can't see the price

**Expected behavior**
The price should be displayed quickly. It takes 2 minutes to load the price.

**Version info (please complete the following information):**
 - Browser version: 73.0.3683.86
 - Platform version: 2.13.19

@tatarincev

**Comment by yecli** [comment]
@yongbin-kooboo You could try update to the latest [platform version ATM](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.43) to see if it became faster.
If you have some customizations of our modules, not just pure platform - it could also make some impact on performance.

**Comment by yongbin-kooboo** [comment]
> @yongbin-kooboo You could try to update to [the latest platform version ATM](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.43) to see if it became faster.
> If you have some customizations of our modules, not just pure platform - it could also make some impact on performance.

Thank you!
Do you have another suggestion? upgrade the version is difficult for us, we just want to optimize the price list module so that the prices can load fast.

**Comment by OlegoO** [comment]
Could you send us more information about the environment: 
- Do you use Azure or Dedicated server? 
- Which MS SQL Versions or DTU plan?

Do you use Azure Application Insights? Could you capture performance metrics (API call and dependencies)? 
It helps to identify the bottleneck.

**Comment by yongbin-kooboo** [comment]
@OlegoO , 

We are using Azure, the plan is Standard S2: 50 DTUs

![price](https://user-images.githubusercontent.com/4169113/56174949-99b0c280-6027-11e9-9e56-ad56f22031a2.png)

I can't find the related metrics

**Comment by OlegoO** [comment]
Could you activate Application Insights and enable Profiler? 
https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler-overview

Also, could you look Intelligent Performance section for MS SQL? Do you see any performance issues or missing indexes?  

It helps to understand where is more resource is required.

**Comment by zhangpengchen** [comment]
@OlegoO The root cause is loading all prices without a pagination, 3000 different prices for one product is a lot.

**Comment by OlegoO** [comment]
@zhangpengchen  @yongbin-kooboo 
**Workaround:** 
1. Create a virtual catalog For example: PIM
1. Add root categories as links
1. Use virtual catalog for navigation without timeout and resource utilization 
1. You will see N/A in price widget but  if you click you see price lists

**Comment:**
pricesWidget API uses catalog id to evaluate the price, in your case, you don't have any price assignments with Virtual Catalog and response is empty.

@yecli Could you plan the reorganization of pricesWidget API, because it doesn't make sense for the huge amount of the price lists.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-44
