### ISSUE TITLE
Broken url in assets - catalog - SKU image

### ISSUE THREAD

**Issue by nikerla** [VirtoCommerce/vc-platform#1551]
If login under admin, open more setings - assets - catalog & choose any folder - copy link 
than receive broken url with double //
![image](https://user-images.githubusercontent.com/47101773/55544692-e6150d80-56cb-11e9-8c9e-d718c5812bd9.png)

and in order confirmation email & storefront this [SKU image is missing](https://demo.virtocommerce.com/Electronics/en-US/headphones/beats-by-dre-solo-2-on-ear-headphones-color-black)
![image](https://user-images.githubusercontent.com/47101773/55545154-e5c94200-56cc-11e9-9e42-716e09cba341.png)

**Comment by AliveMen** [comment]
Broken urls are only on azure storage assets. If assets in local folders all urls are right

**Comment by AliveMen** [comment]
about BEATS BY DRE SOLO 2 ON-EAR HEADPHONES. Image just not selected in the admin page 
![AAI_190405_115211](https://user-images.githubusercontent.com/11813599/55616135-d106b000-5799-11e9-997a-6386de1d9afe.png)

**Comment by OlgaShvedai** [comment]
@AliveMen what should be done in order to make images visible in case it's added from assets?

**Comment by yecli** [comment]
There will be a platform release with the fix, so you'd need to update platform after it.

**Comment by EugeneOkhriemnko** [comment]
@yecli When we can expect platform release?

**Comment by yecli** [comment]
Here is the email with broken images:
[Fwd_ Your order BBID_12300958 has been confirmed.zip](https://github.com/VirtoCommerce/vc-platform/files/3078778/Fwd_.Your.order.BBID_12300958.has.been.confirmed.zip)

**Comment by ZolXela** [comment]
Last platform fix did not solve the problem with double "/" un the URL an added new bug which related with correct save images to the BLOB.

![Problem_with_blob](https://user-images.githubusercontent.com/1710177/56123663-906b1b80-5f7d-11e9-9b95-34f5160c7367.png)
![Problem_with_blob_2](https://user-images.githubusercontent.com/1710177/56123812-ea6be100-5f7d-11e9-80bb-54766a3ac50d.png)

**Comment by yecli** [comment]
@EugeneOkhriemnko Platform release could be expected tomorrow, Apr 16.

**Comment by yecli** [comment]
Released in [v2.13.44](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.44).
