### ISSUE TITLE
Inconsistency in packages makes autorest hard to use

### ISSUE THREAD

**Issue by pixellos** [VirtoCommerce/vc-platform#1555]
**Describe the bug**
Autorest have feature of generating common glue code 
https://github.com/Azure/autorest/tree/master/Samples/1d-common-settings

Now we have to generate each endpoint client module separatelly, when we want to use few modules at one application we have to modify generated code by hand (!!!)

**Steps to reproduce**
1. Get most recent version of virto
2.  Configure autorest like https://github.com/Azure/autorest/tree/master/Samples/1d-common-settings and add `OrderModule`, `CartModule` and `Catalog` to input files
4. Launch autorest
5.See error
```

ERROR (Fatal/DuplicateModelCollsion): Duplicated model name with non-identical definitions
    - http://localhost/docs/VirtoCommerce.Orders/v1:2927:4 ($.definitions.PropertyValue)
    - http://localhost/docs/VirtoCommerce.Catalog/v1:2052:4 ($.definitions.PropertyValue)
    - http://localhost/docs/VirtoCommerce.Cart/v1:2400:4 ($.definitions.PropertyValue)
```

**Expected behavior**
Modules should be synchronized with platform version to generate consistent code.

**Version info (please complete the following information):**
 - Platform version: 2.13.43

**Additional context (optional)**
https://github.com/VirtoCommerce/vc-module-order/blob/dev/VirtoCommerce.OrderModule.Web/packages.config

https://github.com/VirtoCommerce/vc-module-cart/blob/dev/VirtoCommerce.CartModule.Web/packages.config

Not matching packages versions

**Comment by yecli** [comment]
We have command for all common platform module controllers generation here: [readme](https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/AutoRestClients/!readme.txt).

Here is the [usage inside one application](https://github.com/VirtoCommerce/vc-storefront-core/blob/9e2b722e1838c63104010265bdcac4754d2f2eff/VirtoCommerce.Storefront/DependencyInjection/ServiceCollectionExtension.cs#L68).

ATM there is an [error with Quotes](https://github.com/VirtoCommerce/vc-module-quote/issues/8), which will be fixed soon.

It does not require manual fixing of packages. Doesn't it feet your needs?

**Comment by pixellos** [comment]
This command for generation platform module api creates duplicated Orders, PriceLists, Products for multiple modules

**Comment by yecli** [comment]
All platform modules inside one module should have the same versions (like https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web/packages.config#L23-L25). But there is no guarantee that different modules use the same platform versions, as well as VirtoCommerce.Domain one. 
For VirtoCommerce.Domain (I guess you want it be the same) - modules use minimal version having required domain classes. There is no sense in forcing all other modules to use the latest VirtoCommerce.Domain if its latest version changes are used only in one module.

So probably feature you want to use is not supported by our modular system concept.
