### ISSUE TITLE
Disable setting if it overridden in Azure

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1557]
**Problem:**
Currently, if you override settings in web.config / Azure / other hosting env., setting in UI (in db) will be just ignored. It may confuse developers and customers.

**Solution:**
Disable this setting and show warning like Microsoft do for their settings, if they set by group policies:

![image](https://user-images.githubusercontent.com/6369252/55782657-36bea900-5ac6-11e9-88df-0c7e43236684.png)

**Comment by artem-dudarev** [comment]
I've already created this issue 2 years ago =)
https://github.com/VirtoCommerce/vc-platform/issues/1002

**Comment by asvishnyakov** [comment]
@artem-dudarev Ooops
Closed as duplicate of #1002
