### ISSUE TITLE
Incorrect upload Images in the assets with "spaces" in the name

### ISSUE THREAD

**Issue by ZolXela** [VirtoCommerce/vc-platform#1565]
**Describe the bug**
Incorrect upload Images in the assets with "spaces" in the name

**Steps to reproduce**
1. Go to assets section in the admin side
2. Click on upload image with space in the file name "test name.jpg"
3. click on the uploaded image and try to delete for example
4. See no reaction
5. Try to check image by the URL you can see 

![Problem_with_blob_3](https://user-images.githubusercontent.com/1710177/56130901-ca90e900-5f8e-11e9-8356-ccd404812d12.png)

**Comment by yecli** [comment]
Released in [v2.13.44](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.44).
