### ISSUE TITLE
Old module version exist after update

### ISSUE THREAD

**Issue by kamilgarey** [VirtoCommerce/vc-platform#1567]
Actually it's a minor issue - may be it's even not be fixed.
Reason: Modules are installed manually from the source code. And they have different folder names then installed from UI for example **vc-module-customer** vs **VirtoCommerce.Customer**

**Comment by yecli** [comment]
Do not clearly understand the issue. Could you describe it in details - some screenshots and so on.

**Comment by kamilgarey** [comment]
![image](https://user-images.githubusercontent.com/2689494/56192026-25c9e680-6036-11e9-9ece-37360388c81a.png)

1) Install old version of module manually from github 
for example from https://github.com/VirtoCommerce/vc-module-pricing.
Set an old version of module.
2) Run Platform and Update the module.
  After reset you got exception that modules installed twice.

**Comment by yecli** [comment]
Proper way of manual installation is creating link named "VirtoCommerce.Catalog" to "vc-module-catalog
\VirtoCommerce.Catalog.Web" project (cloned git repository), that is located **outside** of Modules folder.
In general there should not be such cases with one module having two different folders. Installing one means deletion of previous.
So i think it is about proper manual installation (it is described in [our docs](https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/creating-new-module) and training videos).
