### ISSUE TITLE
Error: This operation is not available unless admin mode is enabled: FLUSHDB

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#1570]
After importing any data with platform's Export & Import function we get the following error:
`This operation is not available unless admin mode is enabled: FLUSHDB`

This happens when platform tries to clear the cache:
https://github.com/VirtoCommerce/vc-platform/blob/02b5099c467fa2e6a1dd438c4070ef711f81506f/VirtoCommerce.Platform.Data/ExportImport/PlatformExportImportManager.cs#L163

Also, you can get this error when clearing the cache through API:
GET /api/cache/reset

I think this happens because we are using Redis cache in Azure.

Platform version: 2.13.44

**Comment by AliveMen** [comment]
You should add "allowAdmin=True" to RedisConnectionString

**Comment by yecli** [comment]
@artem-dudarev Are you satisfied with the proposed solution?
