### ISSUE TITLE
Adjust available quantity when product placed in shopping cart

### ISSUE THREAD

**Issue by kamilgarey** [VirtoCommerce/vc-platform#1571]
Available quantity should be equal to InStockQuantity - ReservedQuantity(Sum of all quantities that placed to shopping cards).

**Comment by kamilgarey** [comment]
I'll make PR for this.

**Comment by asvishnyakov** [comment]
Issue moved to [VirtoCommerce/vc-module-inventory #24](https://github.com/VirtoCommerce/vc-module-inventory/issues/24) via [**ZenHub**](https://www.zenhub.com/)
