### ISSUE TITLE
As a content manager, I want to upload a theme for the selected shop

### ISSUE THREAD

**Issue by vturovets** [VirtoCommerce/vc-platform#1577]
**Describe the bug**
When a content manager is trying to upload the selected zip-file with theme folders and files for the store in Commerce Manager (admin), the Commerce Manager returns status 401 (see the screenshot below).

**Steps to reproduce**
Prerequisites.
1) A content manager logged in into Commerce Manager (https://vcdemo-admin.azurewebsites.net ) with Administrator role granted (e.g. apiDocs)
2) A new shop has been successfully created (e.g. AOSmith).

**Expected behavior**
- [ ] GIVEN I am in Content section WHEN I click on Themes widget for AOSmith store AND I click on Upload button on Theme list blade THEN I select zip-archive with the theme AND I do uploading AND I see the message that the theme has been uploaded.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/20731316/57369074-66c89d00-7195-11e9-98eb-8e8d42de1772.png)

**Version info (please complete the following information):**
 - Browser version: FireFox Quantum 66.0.4 (64-bit), Google Chrome 74.0.3729.131 (Official Build) (64-bit)
 - Platform version: Community license 2.13.44

Additional information.
The example is available at https://vcdemo-admin.azurewebsites.net and https://vcdemo-public.azurewebsites.net

**Comment by tatarincev** [comment]
Released 
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.48
