### ISSUE TITLE
Cannot log in website. UserName cannot be null

### ISSUE THREAD

**Issue by dku4cdm** [VirtoCommerce/vc-platform#1578]
**Description**
When I try to log in or create a new user, I receive an error. userName parameter cannot be null, but I entered it before. Please, help to find the solution.
![username](https://user-images.githubusercontent.com/30338225/57376998-03953580-71aa-11e9-9860-d5ae02b8cd04.png)

**Steps to reproduce**
1. Go to 'login page': http://localhost:XXXX/account/login
2. Enter username and password
3. Click to login

**Screenshots**
![error](https://user-images.githubusercontent.com/30338225/57376585-0ba0a580-71a9-11e9-880d-86feb188c30a.PNG)

**Version info:**
 - Browser version: Chrome latest
 - Platform version: vc-storefront and vc-platform repos

**Comment by dku4cdm** [comment]
At demo.virtocommerce.com all works perfectly.
Use the latest version from github v.2.22.0

[login.zip](https://github.com/VirtoCommerce/vc-platform/files/3157805/login.zip)

**Comment by tatarincev** [comment]
@dku4cdm Seems you are using deprecated storefront version (no longer supported). Please use  storefront from this repository  https://github.com/VirtoCommerce/vc-storefront-core

**Comment by tatarincev** [comment]
@dku4cdm Seems you are using deprecated storefront version (no longer supported). Please use  storefront from this repository  https://github.com/VirtoCommerce/vc-storefront-core. The latest version at this moment is https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.2.9

**Comment by dku4cdm** [comment]
Can I use vc-platform with vc-storefront-core or I need to move on cs-platform-core too?

**Comment by tatarincev** [comment]
@dku4cdm platform-core still under development and have not released yet. The new storefront 3.0 works with 2.x platform version by design

**Comment by yecli** [comment]
You could try to check new user creation or login on [our demo site](https://demo.virtocommerce.com).
If it works (seems it is - just checked Create account) - probably there is something with you setup. 

Probably debug could help.

**Comment by tatarincev** [comment]
Please provide the storefront version that you use and source code for liquid template of new user form registration
