### ISSUE TITLE
Memory leak introduced with vc-platform v2.13.43

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1579]
Probably vc-platform v2.13.43 version contains memory leak issue.

It seems it has been introduced by updating the Application Insights modules.

Suspicion is that the leakage is to be found within the System.Threading.ExecutionContext, having an immutable dictionary holding the values of all AsyncLocal instances. This AsyncLocal is used by System.Diagnostics.Activity which in turn is used by the AI DependencyCollector. Having a lot of hangfire related SQL calls, tracked by the collector, makes the Activity instance steadily grow.

Temporarily disabling the **DependencyCollector** in the **ApplicationInsights.config** file helps to eliminate this issue.

Need to perform more diagnostic tests by Visual Studio diagnostic tools to see whole picture and find system solution to fix this issue.

![2019-05-02_15-47-56](https://user-images.githubusercontent.com/7566324/57615108-301aca00-757b-11e9-9816-8bca7320e7e5.jpg)
![2019-05-09_9-23-48](https://user-images.githubusercontent.com/7566324/57615109-301aca00-757b-11e9-98c4-814d48024d04.jpg)

**Comment by trueboroda** [comment]
Possible memory leackage related to bug that existe in current used version of AI. That version have critical bug https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/1090. It was fixed only in 2.9-beta1. I suggest update AI packages to latest stable version.

**Comment by yecli** [comment]
Released in [v2.13.45](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.45).
