### ISSUE TITLE
Incorrect data in StoreFront if create an account with a login equal to the deleted account.

### ISSUE THREAD

**Issue by dvvkgd** [VirtoCommerce/vc-platform#1580]
1. In backend create account "Test1" under distributor "Dustributor1".
2. Delete account.
3. In backend create account "Test1" under distributor "Dustributor2" (instead of accont from step 1).
4. Indexed and reset cache.
5. Go to StoreFront inder user "Test1".

Expected: account "Test1" under "Dustributor2".
Actueal: account "Test1" under "Dustributor1".

![Screenshot_2](https://user-images.githubusercontent.com/50042902/57701069-79dae180-765b-11e9-9285-6cc48847992b.png)

**Version info (please complete the following information):**
 - Browser version: 74.0.3729.131 (64 bit)
 - Platform version: 2.13.44

**Comment by tatarincev** [comment]
@dvvkgd please don't post issues from internal products in public github repositories.
