### ISSUE TITLE
API Account strange behaviour

### ISSUE THREAD

**Issue by krankenbro** [VirtoCommerce/vc-platform#1589]
Strange behaviour

**Steps to reproduce**
1. Add an Api Account (Simple)
![image](https://user-images.githubusercontent.com/42555001/58890045-2ef83b00-86ea-11e9-80f3-560c4743fdb7.png)
2. Remove "readonly" attribute from App ID input tag
![image](https://user-images.githubusercontent.com/42555001/58890143-5d761600-86ea-11e9-903f-c491b5ca3d91.png)
3. Now we can change generated App ID (i changed the last digit) and save
![image](https://user-images.githubusercontent.com/42555001/58890256-94e4c280-86ea-11e9-95c0-137450ca6494.png)
4. Now we can reopen/refresh the page
5. Open api account, remove the readonly attr, change value again. And save: 
![image](https://user-images.githubusercontent.com/42555001/58890667-5996c380-86eb-11e9-9caf-697cb5a63c8b.png)
Api account is gone!
![image](https://user-images.githubusercontent.com/42555001/58890698-6d422a00-86eb-11e9-98a7-3e117d1c4b5c.png)

**Version info (please complete the following information):**
 - Browser version: Chrome Версия 74.0.3729.169 (Официальная сборка), (64 бит)
 - Platform version: 2.13.45

**Comment by tatarincev** [comment]
Please don't remove `readonly` attribute from the resulting HTML. And all will be fine!
