### ISSUE TITLE
Demo site doesn't have any pages or blog defined

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1591]
**Describe the bug**
demo.virtocommerce.com doesn't have working about-us page or blog

**Steps to reproduce**
1. Go to demo.virtocommerce.com
2. Click on blog in the top menu

**Expected behavior**
Should display the blog

**Comment by yecli** [comment]
Need to check after demo env revamp. Blogs exist in sample data file, and were restored correctly locally. Maybe someone delete them in demo admin tool.

**Comment by yecli** [comment]
Problem is still here after reset. Will need to investigate further.

**Comment by yecli** [comment]
Problem is in sample data for demo site, VirtoCommerce.Content.json doesn't contain required data. 
Need to replace it in demo sample data package with the proper one - e.g. with the one from default clothing-and-electronics_2_13_35.zip v2 sample data.

**Comment by Woland2k** [comment]
any update on this? our demo is quite poor without this functionality

**Comment by tatarincev** [comment]
Fixed by adding static pages to sample data for demo site
