### ISSUE TITLE
Can't add email to copy or blind copy when use emailnotifications

### ISSUE THREAD

**Issue by AkulovOleg** [VirtoCommerce/vc-platform#1592]
**Describe the bug**
When i add emails to bcc or cc properties of EmailNotification object and call ScheduleSendNotification method i don't receive email to that addresses. 

BCC and CC don't save to database, so when job take notifications from database, BCC and CC properties are empty.
https://github.com/VirtoCommerce/vc-platform/blob/853d66a976c47bf8d7b2c5222c6acf2bfc720915/VirtoCommerce.Platform.Data/Notifications/NotificationConverter.cs#L10

 - Platform version: 2.13.47

**Comment by tatarincev** [comment]
Released
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.48
