### ISSUE TITLE
Check platform export / import for extensibility

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1593]
As described in VirtoCommerce/vc-module-inventory#27 and VirtoCommerce/vc-module-pricing#50, if you will use domain type directly in Deserialize method, it will fail with "unable cast to" exception. Instead of that, you should use workaround like this: https://github.com/VirtoCommerce/vc-module-catalog/blob/dev/VirtoCommerce.CatalogModule.Web/ExportImport/CatalogExportImport.cs#L172-L173

But this is bad approach, because you instantiate orphan object for every deserialization call (i.e. if you have N entires in json, you will have 2*N objects in memoty, where N is used for import and N is orpans)

Instead of that, we should create new method in AbstractTypeFactory, which will return required type, instead of creating new object instance. Also, we need to check all modules where export/import available for that bug.

**Comment by tatarincev** [comment]
We took into account all your valuable notes in the general export module.
