### ISSUE TITLE
Outbound Network Connection Limit

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1594]
**Describe the bug**
Few days back I ran into a problem where our production azure web apps were throwing below error:

**OriginalException:**

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.0.1.4:9200

We reviewed and found App Service Plan (running on Standard S2 1 Instances) are hitting the outbound connection limit. 

![image](https://user-images.githubusercontent.com/7639413/59773773-82ec4d80-92ae-11e9-8cd3-55dad08f57c5.png)

The reason of it is maxconnection="96" in
https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Web.config#L119

We changed it to 8000 to prevent see the error. Please this value to 8000 to prevent see the same error for other solution.

Azure has own limits:

App Service Plan | Connection Limit
-- | --
Free F1 | 250
Shared D1 | 250
Basic B1 1 Instance | 1920
Basic B2 1 Instance | 3968
Basic B3 1 Instance | 8064
Standard S1 1 Instance | 1920
Standard S1 2 Instances | 1920 per instance
Standard S2 1 Instance | 3968
Standard S3 1 Instance | 8064
Premium P1 1 Instance (Preview) | 1920

**Comment by tatarincev** [comment]
Released 
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.48
