### ISSUE TITLE
After the removal of goods, they remain in search count

### ISSUE THREAD

**Issue by n2pro** [VirtoCommerce/vc-platform#1595]
After the removal of goods, they remain in search count 
![Screenshot_1](https://user-images.githubusercontent.com/13115017/59917400-18f4b500-9422-11e9-927b-1e824aa1c438.png)

**Comment by yecli** [comment]
It is because we are using indexed search for products. Deleted products (as like as newly created ones) are not indexed automatically (probably due to performance reasons).
Building Product index after such manipulations should help.
