### ISSUE TITLE
After updating prices the old price remains active on products

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1596]
**Describe the bug**
After importing/overwriting articles with new prices the old prices remain on the product (a sort of price history behavior if you will). The issue is new price got imported correctly but it was imported with minimum quantity = 0 while the old one has minimum quantity = 1.

When product is displayed on the storefront corrent prices are shown.

When you add products to cart the cart will take the new price, discount it and show the old price as the actual price. I believe this is happening because the minimum quantity of 1 has been hit.

The VS catalog does not allow two prices with minimum quantity = 1 set (does not allow saving the product).

inverting the minimum quantity results in incorrect (old) price being shown.

The only solution is to delete the old price to have the correct pricing behaviour. 

**Steps to reproduce**
Import new prices (higher) for existing products into the catalog and you should see those imported with minimum quantity equals 0 as such they are not used when at least one piece of item is in cart.

**Expected behavior**
Deleting (or deactivating somehow) the old price should be done automatically when new prices are imported.

**Version info (please complete the following information):**
 - Browser version: Chrome latest
 - Platform version: 2.13.36

**Comment by priboltik** [comment]
Additional scenario:
1. We have 2 pricelists for one catalog: the first is default pricelist and the second - special pricelist for some usergroup.
2. Special pricelist has higher priority than default pricelist.

**Expected behavior**
We see prices from special pricelist for products.

**Current behaviour**
We see prices from pricelist with minimum quantity = 0. And system ignore priorities in this way.

**Comment by brgrz** [comment]
@yecli @priboltik So I see two more issues were referenced however there is still no fix for the platform or storefront to prevent it to take the wrong price. Is there a fix we could do ourselves?

**Comment by yecli** [comment]
@brgrz This issue were included into upcoming sprint for one of our teams. So I think we will have it done in 2-3 weeks.

**Comment by brgrz** [comment]
@yecli Has this been resolved with a commit I missed?

**Comment by yecli** [comment]
Yes, it was resolved in https://github.com/VirtoCommerce/vc-module-catalog-csv-import/pull/32.
I think we'll prepare release soon.

**Comment by yecli** [comment]
@brgrz Yes, this was fixed in https://github.com/VirtoCommerce/vc-module-catalog-csv-import/pull/32. We will release it soon.

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-catalog-csv-import/releases/tag/v1.1.4
