### ISSUE TITLE
Remove obsolete GitHub repositories

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1597]
Here is the list of obsolete repositories that aren't longer used by various reasons, which we decided to remove from our GitHub organization.

vc-module-wishlist
vc-localization
vc-module-search-api
vc-module-b2b-customer
vc-module-b2b-extensions
vc-module-find-purchased
vc-module-search
vc-mobile
vc-module-find-store
vc-theme-demo
vc-azure-api-app
Autorest 
blog-redirect
swigger-codegen
vc-marketplace
Swashbuckle

**Comment by Woland2k** [comment]
they need to be moved to https://github.com/orgs/VirtoCommerce-archieve instead of being removed

**Comment by dimitri-ak** [comment]
@tatarincev do you have access to the repo that Sasha mentioned?

**Comment by artem-dudarev** [comment]
There is a typo. It should be `archive`, not 'archieve`.

**Comment by tatarincev** [comment]
@dimitri-ak  Any progress with this task?

**Comment by eMazeika** [comment]
would the old links work? e.g., "Search phrase syntax" is available only in vc-module-search and is the only place to reference it.

**Comment by asvishnyakov** [comment]
@Woland2k @dimitri-ak @tatarincev @artem-dudarev @eMazeika We don't need to remove or move anything from organization. GitHub support archiving of repositories, you should see corresponded button in settings.

**Comment by asvishnyakov** [comment]
@eMazeika Create a bug in Core module about that fact

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-114
