### ISSUE TITLE
Notifications are not sent from background tasks.

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-platform#1598]
After proper configuration of SmtpClient we could send Registration notification via Platform interface:
![image](https://user-images.githubusercontent.com/15610352/60500859-7e735c00-9cd4-11e9-8820-8215d4822437.png)
![image](https://user-images.githubusercontent.com/15610352/60501039-c85c4200-9cd4-11e9-99b8-90008efe5b09.png)

At the same time, when we Set this Registration notification template active and register user using storefront (means call sending notification through API), it is not sent properly.
Error message:
Сбой при отправке сообщения электронной почты.System.IO.IOException: Не удается прочитать данные из транспортного соединения: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подключение
 в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
 --- Конец трассировки внутреннего стека исключений ---
 в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
 в System.Net.DelegatedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
 в System.Net.BufferedReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
 в System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine)
 в System.Net.Mail.SmtpReplyReaderFactory.ReadLine(SmtpReplyReader caller)
 в System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
 в System.Net.Mail.SmtpClient.GetConnection()
 в System.Net.Mail.SmtpClient.Send(MailMessage message)
![image](https://user-images.githubusercontent.com/15610352/60501366-57695a00-9cd5-11e9-8cba-d0b8ac56ec94.png)

Seems the only difference is that when sending through API it is sent as Hangfire background job.

Need to find the problem.
Maybe this could be related to the problem: https://stackoverflow.com/questions/45382254/update-net-web-service-to-use-tls-1-2

**Comment by kostyrin** [comment]
before
![image](https://user-images.githubusercontent.com/8361000/60895202-8139f800-a264-11e9-8de3-12e745e411c0.png)
after
![image](https://user-images.githubusercontent.com/8361000/60895240-9151d780-a264-11e9-8d11-bea474e29860.png)
these emails were sending in background and also it is working via api
can't reproduce.

**Comment by yecli** [comment]
Could you please check if Registration notifications are sent when new user is registered in Storefront (means we have active Registration notification template)?

**Comment by yecli** [comment]
Seems there is no need in this PR for proper notification sending, as it is just a refactoring.
Need to recheck if it is reproducible.

**Comment by tatarincev** [comment]
Relerased 
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.48
