### ISSUE TITLE
Library loading exception when AzureAd enabled

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-platform#1600]
Enabling Authentication:AzureAD seems to break the platform, (the app fails to start):

Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by tatarincev** [comment]
Released 
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.48
