### ISSUE TITLE
Register user request fails when username contains special symbols

### ISSUE THREAD

**Issue by adminoren** [VirtoCommerce/vc-platform#1605]
When we try to register a new user and username contains one of these symbols: 
#$~!`%\^&*_+=|[\]\\:"<>?/{};, the request fails
![MagicSymbolsInUserName](https://user-images.githubusercontent.com/38526853/61029181-e52efe80-a3d3-11e9-8aaf-1bac15988c10.gif)

![image](https://user-images.githubusercontent.com/38526853/61027265-296bd000-a3cf-11e9-8b4b-685533bfe49f.png)
Create user in storefront first calls platform API method api/platform/security/users/{userName} to search for an existing user with the same name. This call uses get method and passes username in query parameter. Default IIS URL filter setting blocks this request. If we change the setting in IIS, this platform api call will be completed successfully. The bug is reproducing in local IIS hosting and Azure hosting for the platform. I've made the gif on demo site.
![image](https://user-images.githubusercontent.com/38526853/61029398-5c649280-a3d4-11e9-9563-5565a926ec3f.png)

To solve the problem we can add a post method to find a user by username.

**Comment by tatarincev** [comment]
So temporary solution is restrict to use `+`  char in user names. You might do this by adding follow setting in appsettings.json of your storefront
```Json
 "IdentityOptions": {
    "Password": {
      "RequiredLength": 8,
      "RequireDigit": false,
      "RequireNonAlphanumeric": false
    },
    "User": {
      "AllowedUserNameCharacters": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@"
    },
    "Lockout": {
      "DefaultLockoutTimeSpan": "0:15:0"
    }
  },
```

**Comment by adminoren** [comment]
Thanks, we have already restricted the input field in the frontend, and it'll be useful to set allowed characters in identity options. I just wanted to report the problem.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
