### ISSUE TITLE
Fix API Account creating UI

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1607]
**Describe the bug**
Can't add new API Account to user from UI.

**Steps to reproduce**
1. Go to 'Security'
2. Click on 'Users'
3. Click on a User, currently having no API Accounts
4. Click on 'API Accounts' widget
5. Proceed to create new API Account
6. The Ok button does noting

**Expected behavior**
The Ok button should close the blade and add new API Account to the list.

**Screenshots (optional)**
Console error:
![image](https://user-images.githubusercontent.com/5801549/61284389-85679780-a7c7-11e9-9c89-4901681eed2f.png)

**Version info (please complete the following information):**
 - Platform version: 2.13.48

**Comment by eMazeika** [comment]
2 more issues, could be related:
1. Non-administrator can't login Platform Manager: Exception is thrown
2. Administrator user without any API Account can't see orders: Exception is thrown

**Comment by yecli** [comment]
We found the reason (#1590), checking the best way to fix.

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.49
