### ISSUE TITLE
Restore "password is incorrect" message in login dialog

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1608]
**Describe the bug**
incorrect error message is displayed in login dialog

**Steps to reproduce**
1. Go to Platform login and submit invalid credentials
2. "Authentication error (code: 400)." gets displayed

**Expected behavior**
"The login or password is incorrect." message displayed.

**Version info (please complete the following information):**
 - Platform version: 2.13.48

**Comment by akak1977** [comment]
Released: https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.54
