### ISSUE TITLE
Platform fails to start if unknown SMS gateway is selected

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-platform#1610]
**Describe the bug**
If `VirtoCommerce:Notifications:SmsGateway` application setting has some value unknown by the platform (i.e. not `Default`, `Twilio` or `ASPSMS`), the platform does not register any SMS gateway implementations. If SMS gateway was not registered by any other modules, the platform will fail to start.

**Steps to reproduce**
1. Open `web.config` and go to `appSettings`.
2. Set `VirtoCommerce:Notifications:SmsGateway` to some value other than `Default`, `Twilio` and `ASPSMS` - e.g. to `UnknownSmsGateway`.
3. Restart the platform.
4. Try to open VC Platform Manager and see the error: `The current type, VirtoCommerce.Platform.Core.Notifications.ISmsNotificationSendingGateway, is an interface and cannot be constructed. Are you missing a type mapping?`

**Expected behavior**
IMO, the platform should successfully start and use default SMS provider instead.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1835759/61509708-06b66880-aa1a-11e9-868f-0708bb22c5f3.png)

**Version info (please complete the following information):**
 - Browser version: Chrome 75.0.3770.142
 - Platform version: 2.13.47

**Additional context (optional)**
In HOT, we attempt to implement some custom SMS gateways. But we don't want to register these SMS gateways if their configuration is incorrect (e.g. when user name or password are not filled). So, the idea was to use our SMS providers if their configuration is correct, or leave default SMS provider if it isn't. The code looks like this:
```csharp
var smsGatewayName = ConfigurationHelper.GetAppSettingsValue("VirtoCommerce:Notifications:SmsGateway");

ISmsNotificationSendingGateway newSmsGateway = null;

if (smsGatewayName == AfricasTalkingSmsNotificationSendingGateway.Name)
{
    newSmsGateway = BuildAfricasTalkingSmsGateway(); // can return null if configuration is incorrect
}
else if (smsGatewayName == Vas2NetSmsNotificationSendingGateway.Name)
{
    newSmsGateway = BuildVas2NetSmsSendingGateway(); // can return null if configuration is incorrect
}

if (newSmsGateway != null)
{
    _container.RegisterInstance(newSmsGateway);
}
```
However, when SMS gateway is set to something other than `Default`, platform [does not register the default SMS gateway](https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Startup.cs#L754). So, no SMS gateways are registered, and this causes platform to crash when attempting to register SMS notifications.

My proposal is to register default SMS gateway for all `VirtoCommerce:Notifications:SmsGateway` values that are not known by the platform (i.e. for all values other than `Twilio` or `ASPSMS`). This way, if SMS gateway is known by some other module, that module will replace default SMS gateway with some custom provider; otherwise, default SMS provider will still be registered.

**Comment by artem-dudarev** [comment]
I agree that the platform should not fail to start when unknown SMS provider is configured, but if the provider name is correct, it should be registered anyway, even if user name or password is missing.

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.50
