### ISSUE TITLE
As a Content Manager, I want to find certain pages by keywords, so that I can see them in search result list

### ISSUE THREAD

**Issue by vturovets** [VirtoCommerce/vc-platform#1612]
The current implementation of Commerce Manager requires exact match of search criterion and the file name. 

**Steps to reproduce**
1. Go to http://vc-admin-test.azurewebsites.net/#/workspace/content 
2. Click on Pages widget.
3. Specify the search string as 'digitalTransformation.page' (see Pic.1) on the blade.
![image](https://user-images.githubusercontent.com/20731316/61949407-7a74ea00-afb3-11e9-95b3-d5e5d1955c58.png)
Pic. 1.
4. See the result
![image](https://user-images.githubusercontent.com/20731316/61949457-a1cbb700-afb3-11e9-979c-ea4766eff7f4.png)
Pic. 2.

**Expected behavior**
4. The expected search result for 'digital' is shown on Pic. 3.
![image](https://user-images.githubusercontent.com/20731316/61949977-32ef5d80-afb5-11e9-8c07-a5946948c059.png)
Pic. 3.

**Version info (please complete the following information):**
 - Browser version: Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)
 - Platform version: Community license 2.13.42

**Additional context (optional)**
The search should work throughout the whole Pages section including all folders and subfolders.

**Comment by tatarincev** [comment]
@vturovets  The search work with serious  limitations when the azure blob storage is used as asset  provider. I think that this task is not achievable in near prospective.

**Comment by vturovets** [comment]
@tatarincev thanks for the comment. Well, then I am closing this issue.
