### ISSUE TITLE
As a Content Manager, I want to copy/move a certain file (.page file) to the selected folder, so that I can group files by some criteria

### ISSUE THREAD

**Issue by vturovets** [VirtoCommerce/vc-platform#1613]
**Problem:**
There is no capability to move/copy a certain file into specific folder (see Pic. 1).
![image](https://user-images.githubusercontent.com/20731316/61955374-8d8fb600-afc3-11e9-8525-67cde64169e9.png)
Pic. 1.
The workaround with renaming where the full name includes also the folder names (full path) has limited application since once the file is in the sub folder, there is no way up. 

**Solution:**
One would expect to have something like this (see Pic. 2).
![image](https://user-images.githubusercontent.com/20731316/61955533-e8291200-afc3-11e9-8beb-34460d8315a3.png)
Pic. 2.
And then the selected file is pasted/copied to the specified folder.

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-module-content #25](https://github.com/VirtoCommerce/vc-module-content/issues/25) via [**ZenHub**](https://www.zenhub.com/)
