### ISSUE TITLE
As a Content Manager, I want to find a certain page by permalink string, so that I can proceed with editing the selected page

### ISSUE THREAD

**Issue by vturovets** [VirtoCommerce/vc-platform#1614]
**Problem:**
This is pretty much the same as #1612  with the only difference that the search string contains  so called a permalink which could be specified with the slash symbol at the beginning (Pic. 1). 
![image](https://user-images.githubusercontent.com/20731316/61956338-93869680-afc5-11e9-9cf3-6bb06801731f.png)
Pic. 1.

**Comment by tatarincev** [comment]
Issue moved to [VirtoCommerce/vc-content #237](https://github.com/VirtoCommerce/vc-content/issues/237) via [**ZenHub**](https://www.zenhub.com/)
