### ISSUE TITLE
Cannot view uploaded content (images)

### ISSUE THREAD

**Issue by dku4cdm** [VirtoCommerce/vc-platform#1615]
**Question**

Hello, sorry for disturb, but I don't know how to do this.
After deploying to IIS, how to change base URL from localhost to website domain?

![localhost](https://user-images.githubusercontent.com/30338225/62124935-3dbb3280-b2d4-11e9-88fb-102ef27245ed.PNG)

**Comment by yecli** [comment]
You could use AssetsConnectionString publicUrl property from Web.Config:
![image](https://user-images.githubusercontent.com/15610352/62127813-6b13da80-b2ec-11e9-88f6-63fed9b4dc7a.png)

**Comment by dku4cdm** [comment]
Thanks!!!
