### ISSUE TITLE
If add any roles for user with set  IsAdministrator leads to hide orders prices.

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#1616]
**How to reproduce:**
Create a new user, set flag IsAdministrator and assign it to  any of existing role.
Login as a newly created user
Navigate to Orders

**Actual result:**
All orders will return with no prices.

**Expected result:**
All orders will return with prices

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-order/releases/tag/v2.17.27
