### ISSUE TITLE
Compress-Module doesn't work properly in Visual Studio 2019

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#1618]
Compress-Module cannot find MSBuild.exe that is installed with VS 2019 and falls back to MSBuild.exe in the Windows folder, which cannot compile C# 7 code.

https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Module/tools/VirtoCommerce.Module.psm1#L23

Need to update VirtoCommerce.Module.psm1 to support new path for MSBuild.exe in VS 2019, which is 'MSBuild\\**Current**\Bin\MSBuild.exe'.

**Comment by tatarincev** [comment]
Released
