### ISSUE TITLE
An issue after VC platform installation (2.13.49)

### ISSUE THREAD

**Issue by t13ka** [VirtoCommerce/vc-platform#1632]
After making a clean new installation, I've got a problem that I couldn't change the status of any order. I've seen a broken blade panel.
The source that I used for installation https://github.com/VirtoCommerce/vc-platform/releases/download/v2.13.49/VirtoCommerce.Platform.2.13.49.zip

1. Authorize, In the main menu go to 'Orders'
2. Click on some Order
3. Open in your browser the developer tools or just press F12(Chrome)
4. See error:
![issue_2](https://user-images.githubusercontent.com/12604378/64418048-78c73780-d0c4-11e9-90a4-ddb4f9037c43.jpg)

 - Browser version: 76.0.3809.132 (Official Build) (64-bit)
 - Platform version: 2.13.49

 - OS version: Microsoft Windows 10 x64 Build 17763
 - Installed Kaspersky Internet Security version: 19.0.0.1088 (g)

**Comment by blazemachine** [comment]
This problem has been solved after Kaspersky Internet Security version 20 installation.
