### ISSUE TITLE
Localization of custom modules is not working

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-platform#1634]
**Describe the bug**
If you add a resource (resx) file in your custom developed module, always the default language (fallback) is used and not the specified one or the language wich fits to the current ui thread or current thread locale.

**Steps to reproduce**
1. Create a custom module
2. Add a resx file with additional translations (Translations.resx and Translations.de-DE.resx)
3. Use the translations in the module
4. Install the module
5. Use the module and if you use a different language, always the default/fallback language is selected

**Expected behavior**
If a module uses localized resource files, the resource files should be copied in the installation/inizialization process also to the App_Data directory to support the localized resource files for modules

**Screenshots (optional)**

**Version info (please complete the following information):**
 - Browser version: doesn't matter
 - Platform version: v2.13.49

**Additional context (optional)**
If i copy the localized folders (en, de-De, ...) to the App_Data/Modules folder manually, it worked fine

**Comment by corneliusmunz** [comment]
After copying the translation folders and compield translated files in the App_Data folder it works:
![Manual_added_localized_files_in_AppData_folder](https://user-images.githubusercontent.com/8521596/64529809-0183e480-d30c-11e9-9adb-cc0ee2fc1ff4.png)

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.56
