### ISSUE TITLE
Replace the Flags as label for culture name label to the culture names

### ISSUE THREAD

**Issue by blazemachine** [VirtoCommerce/vc-platform#1635]

**Comment by blazemachine** [comment]
This issue is related to https://github.com/VirtoCommerce/vc-module-catalog/issues/250

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.51.

**Comment by yecli** [comment]
@blazemachine There are other places where the same changes required:
![image](https://user-images.githubusercontent.com/15610352/66934337-c041cb80-f053-11e9-8426-bf59f3d61a88.png)

**Comment by yecli** [comment]
These inconsistencies lead to the following:
![image](https://user-images.githubusercontent.com/15610352/66987711-b44d1c80-f0da-11e9-9f25-9647e6e94992.png)
Need to check all the places where this code could be used, and check the result.

**Comment by yecli** [comment]
https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.52
