### ISSUE TITLE
Platform doesn't recognize logins/emails with "+" sign

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#1637]
**Describe the bug**
If you will try to use email with `+` (plus) sign, platform will not find this user.

**Steps to reproduce**
1. Go to User
2. Create new user with email which include `+`
3. PROFIT

**Expected behavior**
We should follow [RFC specification](https://tools.ietf.org/html/rfc2822#section-3.2.4) and support all valid symbols in email.

> addr-spec       =       local-part "@" domain
local-part      =       dot-atom / quoted-string / obs-local-part
dot-atom        =       [CFWS] dot-atom-text [CFWS]
dot-atom-text   =       1*atext *("." 1*atext)
atext           =       ALPHA / DIGIT / ; Any character except controls,
                        "!" / "#" /     ;  SP, and specials.
                        "$" / "%" /     ;  Used for atoms
                        "&" / "'" /
                        "*" / "+" /
                        "-" / "/" /
                        "=" / "?" /
                        "^" / "_" /
                        "`" / "{" /
                        "|" / "}" /
                        "~"

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/6369252/65273735-48a77c00-db3b-11e9-8228-b380e5bd869f.png)

**Version info (please complete the following information):**
 - Platform version: 2.13.49

**Comment by ilyawzrd** [comment]
This bug happens because of the logins. Emails are working fine. Because of our API.
GET request won't accept nothing without security risk. That is, we are thereby obliged to edit the API, and declare this method obsolete.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for a long time
You may reopen this issue if it has been closed in error.
