### ISSUE TITLE
Link to Online Demo in readme.md does no longer work

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-platform#1639]
**Describe the bug**
The link provided in the readme.md in the section "Online-Demo" does no longer work
http://virtocommerce.com/try-now/online-demo 

**Steps to reproduce**
1. go to https://github.com/VirtoCommerce/vc-platform
2. Browse to Online Demo section
3. Try to open the link 

**Expected behavior**
Direct Link to online demo should be available because it is very helpful to have a free access to an up and running demo shop without installing it on my local machine

**Screenshots (optional)**
not applicable

**Version info (please complete the following information):**
 - Browser version:
 - Platform version:

**Additional context (optional)**

**Comment by tatarincev** [comment]
Fixed
