### ISSUE TITLE
Add headers and footers for email notifications

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#1641]
**Problem:**
Even the smallest change requires to update each existing notification template. So inconvenient. 
E.g., updating company logo, contact information, color.

**Solution:**
Add capability to prepare and manage headers and footers separately. Then just assign existing content to use in a notification template.

**Alternative (optional):**
Custom layouts could be supported as well.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-100
