### ISSUE TITLE
Platform 3.0 RC1. Failed to load installed modules in Linux Ubuntu 18.04.3 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by mvktsk** [VirtoCommerce/vc-platform#1656]
**Describe the bug**
When I try to start Platform web app in browser I get error 
> HTTP ERROR 500

In dotnet console got error 

> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
>       An exception was thrown attempting to execute the error handler.
> System.ArgumentException: The directory name /home/mvktsk/vc-platform-core/Modules\ does not exist.
> 

**Steps to reproduce**
1. Deploy Platform in Ubuntu Linux
2. Login to Platform with admin credentials 
3. Install Platform modules
4. Restart Platform

**Expected behavior**
Platform manager started.

**Version info (please complete the following information):**
 - Browser version: any
 - Platform version: 3.0 RC1
- Operating system: Linux Ubuntu 18.04.3 LTS (Bionic Beaver)

**Comment by Woland2k** [comment]
This is fixed in RC4 and was due to incorrect paths in file storage provider.
