### ISSUE TITLE
External Login doesn't work in 3.0 version

### ISSUE THREAD

**Issue by maooson** [VirtoCommerce/vc-platform#1661]
The external login doesn't works when I connect Virtocommerce.Platform release/3.0.0.
It looks like the api `api/platform/security/users/login/external` is missing in the 3.0 version.

**Comment by tatarincev** [comment]
@maooson  Seems it is due to breaking changes with security API introduced in 3.0. We will fix this soon.

**Comment by OlegoO** [comment]
https://admin-demo.virtocommerce.com/docs/index.html
/api/platform/security/users/login/external/{loginProvider}/{providerKey}
