### ISSUE TITLE
How to disable registration mailing when a new customer registers

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-platform#1663]
Dear team:
I saw the welcome email handler about new customer registration there[RegistrationEmailMemberChangedEventHandler.cs](https://github.com/VirtoCommerce/vc-module-core/blob/dev/VirtoCommerce.CoreModule.Data/Handlers/RegistrationEmailMemberChangedEventHandler.cs), now I don't need to send, so I try to overwrite the handle method then register,  but it doesn't work,beacause it only support add new events and I can't remove the existing events, So I need your help, could you give me some advice then I can do it, thanks.

ENV: platform 2.13.44 & core-module: 2.25.2

BR,
Ruyi

**Comment by yecli** [comment]
Looking at this code  https://github.com/VirtoCommerce/vc-module-core/blob/39d693215412422e6710a5ae4cde042e95626600/VirtoCommerce.CoreModule.Web/Module.cs#L92, I think you could try to register your own empty implementation of RegistrationEmailMemberChangedEventHandler in your custom module.

**Comment by ruyi-kooboo** [comment]
Hi @yecli,
Thanks for your answer, yes and I can register my own empty implementation (or use settings),
But this will only add new event subscription, 'RegistrationEmailMemberChangedEventHandle' events will take effect at the same time, because if I inherit and override and then register, both events will exist and work.

BR,
Ruyi

**Comment by yecli** [comment]
I am talking about overriding the class on unity container, not about registering one more handler. That way _container.Resolve should return your impregnation of handler, not the existing one

**Comment by ruyi-kooboo** [comment]
Hi @yecli,
Thanks a million, it works.  Since it depends on Store Module and I didn't care it before, I don't add the dependency to the 'module.manifest' file, your answer let me double check it and after adding the dependency, it works.

BR,
Ruyi
