### ISSUE TITLE
script_dependencies.js is missing in downloaded Clothing and B2B themes.

### ISSUE THREAD

**Issue by yecli** [VirtoCommerce/vc-platform#1701]
**Problem:**
after playing with working electronics store:

simply changed appsettings.json to:

"VirtoCommerce": {
"DefaultStore": "Clothing",
"StoreUrls": {
//Define mapping of concrete stores with public urls in this section
//"

{store id}
":"

{store public url}
"
},

recycled app pool for website.

Went to store url and received http 500 exception

**Resolution:** 
When the platform creates "cms-content" folder with predefined themes, "clothing" and "b2b" theme does not contain "script_dependencies.js" bundle (e.g. for clothing - in assets\___static\bundle). Need to add it to all themes.

**Comment by akak1977** [comment]
Released: https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.54
