### ISSUE TITLE
How can I log in or request reset password only via email

### ISSUE THREAD

**Issue by ruyi-kooboo** [VirtoCommerce/vc-platform#1720]
Dear team:

Now I have an issue that is we want to let user when they want to log in or want to reset their password by self only can via their email, how could I do? I see we implement it at the platform security controller, and we can't simply change them. And I try to add a new API to replace the existing API, I find that this is going to be a lot of work, are there any other simpler ways to do it? I need your suggestions, thanks a billion!
Platform: version-2.13.44

BR,
Ruyi

**Comment by yecli** [comment]
According to this code, Email and Sms confirmations could be configured to be used in forgot password routine: [option ResetPasswordNotificationGateway](https://github.com/VirtoCommerce/vc-storefront-core/blob/3289e31c63c1f023cfee5a6cc7e0e77ac676bcc4/VirtoCommerce.Storefront/Controllers/AccountController.cs#L563).

[Our support channel](http://help.virtocommerce.com/support/home) or [community](https://community.virtocommerce.com/) could be useful to find info or get consultancy.
