### ISSUE TITLE
Some modules have ancient dependencies

### ISSUE THREAD

**Issue by krankenbro** [VirtoCommerce/vc-platform#1726]
vc-module-image-tools
vc-module-quote
vc-module-lucene-search
These modules can't be built without .Net Framework 3.5 development tools installed. Perhaps because of the old version of VirtoCommerce.Module
![image](https://user-images.githubusercontent.com/42555001/69244786-451d8900-0bae-11ea-8b6a-d6681bff927b.png)

**Comment by yecli** [comment]
Done.
