### ISSUE TITLE
New Storefront - Shipment total amount and delivery address is missing

### ISSUE THREAD

**Issue by anwaramoon** [VirtoCommerce/vc-platform#173]
Total amount is missing in shippment document. Delivery address is also missing. As per #168 delivery address was fixed but I am still facing the same issue. However, #168 fix has fixed the customer name for me. I have tried latest from storefront branch. Thanks

Steps:-
1. Add items to cart
2. Go to checkout
3. Login using existing account
4. Select fix rate shipping method
5. Select manual test payment method
6. Complete order

![shipment_total_amount_missing](https://cloud.githubusercontent.com/assets/1743538/11792915/9ba69148-a2a0-11e5-960e-12eddff73358.jpg)

**Comment by Andrew-Orlov** [comment]
Does your order has both of shipping and billing addresses?

**Comment by anwaramoon** [comment]
Total is correct on order display. After assigning fullfilment centre total is still missing for shippment. However, after selecting shipment or payment document you cannot select customerOrder document again. Is it expected behaviour or a bug?

I have both shipping and billing address in my account. Please see below screenshot.

![account_address_details](https://cloud.githubusercontent.com/assets/1743538/11820635/62dd8dae-a35d-11e5-8327-c7e2a37e4de5.jpg)

**Comment by eMazeika** [comment]
Is this still relevant? Re-check, if can be closed

**Comment by yecli** [comment]
It is fixed now.
