### ISSUE TITLE
Incorrect display of dependency versions

### ISSUE THREAD

**Issue by ilyawzrd** [VirtoCommerce/vc-platform#1745]
Dependency versions in module-detail blade are not displayed correctly.

**Steps to reproduce**
1. Go to 'More'
2. Click on 'Modules'
3. Click on 'Installed'
3. Click on any module
4. See that dependency versions display is incorrect

**Expected behavior**
Versions should look exactly like in v2 of platform

**Screenshot**
![dependencies_version_bug](https://user-images.githubusercontent.com/22875828/70735945-e912d400-1d17-11ea-9677-8a579e5d71a6.png)

**Version info:**
 - Platform version: 3.0.0-rc2.1

**Comment by yecli** [comment]
Was merged into https://github.com/VirtoCommerce/vc-platform/tree/release/3.0.0
