### ISSUE TITLE
Changing user details results an error

### ISSUE THREAD

**Issue by ilyawzrd** [VirtoCommerce/vc-platform#1749]
The error appears only when we create new user with a role (1 or more)
**Steps to reproduce**
1. Create new user with 1 or more roles
2. Try to edit and save user details
3. See error

**Expected behavior**
All changes will be saved successfully

**Screenshot**
![error](https://user-images.githubusercontent.com/22875828/70930049-01972d00-203d-11ea-804e-ecc402726571.png)

**Version info:**
3.0.0

**Comment by yecli** [comment]
Was merged into https://github.com/VirtoCommerce/vc-platform/tree/release/3.0.0.
