### ISSUE TITLE
Quotes - get more customer details for anonymous quote request

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#176]
While requesting for Quote from front end site its taking without requiring login. and in backend quote is created without anything specified like emailid etc. so, while doing submit proposal i don't know where it is submitting.

missed without in this.

Basically when i trying to submit Quote then its submitting with login. So, there is no connect details exists for me.
and when accessing from back-end that quote all the contact details were missing.
Then after submitting the proposal , unable to figure out where its getting submitted.
expected behavior should be : it should work like alibaba.com quote system.ie. it should go back to Require quote submitter for further negotiation or bargain.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-quote #1](https://github.com/VirtoCommerce/vc-module-quote/issues/1) via [**ZenHub**](https://www.zenhub.com/)
