### ISSUE TITLE
An error of the opening the content editing blade 

### ISSUE THREAD

**Issue by t13ka** [VirtoCommerce/vc-platform#1760]
**Describe the bug**
A blade for editing selected content should be opened

**Steps to reproduce**
In the admin menu
1. Go to 'Content'
2. Click on 'Themes' (Clothing section)
3. Click 'default'
3. Click 'config', then some any file.
4. See that is nothing happened

**Expected behavior**
A blade for editing selected content should be opened

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/12604378/71467506-9cd69200-27f5-11ea-883c-b2ea6b82c6b0.png)
![image](https://user-images.githubusercontent.com/12604378/71468353-3d2db600-27f8-11ea-8ddd-a737ca8aaf60.png)

**Version info (please complete the following information):**
 - Browser version: chrome  79.0.3945.88 (Official Build) (64-bit)
 - Platform version: 2.13.54

**Additional context (optional)**
Ask @t13ka for needed credentials

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.56
