### ISSUE TITLE
Date picker saves wrong date for dates after 29.03.2020

### ISSUE THREAD

**Issue by mvsmal** [VirtoCommerce/vc-platform#1767]
**Describe the bug**
The date picker in marketing promotions saves the wrong date (the previous day) for dates after 29.03.2020. ~Looks like it is related to the 2020 being a leap year, so the date is 29.02.2019 + 1 month. If you type the date manually, it is saved correctly.~
As @avas noticed, the change actually happens by 1 hour. From 12 AM to 11 PM. Apparently it is related to the daylight saving.

**Steps to reproduce**
1. Go to marketing promotions
2. Open arbitrary promotion
3. Choose end date with the date picker > 29.03.2020. e.g. 30.03.2020
4. Save the promotion.
5. See 29.03.2020 end date instead of 30.03.2020

**Expected behavior**
See 30.03.2020 end date

**Screenshots (optional)**
![leap year](https://user-images.githubusercontent.com/3872761/72438637-880e6e00-37a5-11ea-91fa-66eeebe428a1.gif)

**Version info (please complete the following information):**
 - Browser version: Google Chrome 79.0.3945.117
 - Platform version: 2.13.50 (admin-demo.virtocommerce.com)

**Additional context (optional)**
Probably the date picker library should be updated or replaced.

**Comment by avas** [comment]
Note that the time changes from 12AM to 11PM of previous day for dates after March 29. This might be related to daylight saving time in your timezone (in Russia, transition happens on last Sunday of March between 2AM and 3AM).

**Comment by mvsmal** [comment]
Thanks @avas. I have updated the initial description. Would it actually be possible to fix somehow?
As far as I know, Russia doesn't actually change time to summer/winter ones, but Europe still does and will keep switching for a couple of years, I believe.

**Comment by yecli** [comment]
I think we should not handle that situation specifically. 
During that hour back switch (12AM -> 11 PM) we have 2 moments in a day when the time is 11:30 PM. And we do not know what time to use here - first 11:30 PM or the second - probably both variants could be valid in different cases.

So I think we need to keep in mind that we should not set time in that switching hour to avoid confusion (and help the user).
