### ISSUE TITLE
Extend Application Insights Telemetry with User Identity context information and X-Response-Time

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#1786]
**Problem:**
To simplify Maintenance Tasks in Application Insights, we should extend Telemetry with User Identity context information and X-Response-Time.

![image](https://user-images.githubusercontent.com/7639413/74410806-9acaa000-4e42-11ea-84af-a761fe7d51f4.png)

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.59
