### ISSUE TITLE
Search input missing in catalog module

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1790]
**Describe the bug**
There used to be a quick search input box within the Catalog browsing module and it is now gone after updating to the latest modules.

**Steps to reproduce**
Go to Modules and update to the latest versions

**Expected behavior**
I expect search textbox to be present in the Catalog module

**Version info (please complete the following information):**
 - Browser version: Chrome latest
 - Platform version: 2.13.50

**Comment by yecli** [comment]
Maybe you have cached scripts, which could cause script errors. Please try to open DevTools, disable cache on Network tab and press Ctrl+F5 (for Chrome).

Our demo environment has the latest modules installed - https://admin-demo.virtocommerce.com/.
And the catalog search box is here:
![image](https://user-images.githubusercontent.com/15610352/75768889-07acc800-5d67-11ea-9176-182e34ac1470.png)

Could you try to update the platform to the latest version - [2.13.59](https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.59) ATM?

**Comment by brgrz** [comment]
You're right, that was it.
