### ISSUE TITLE
Duplicate category with same code allowed

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1791]
**Describe the bug**
Today I ran into an issue where two categories with the same name, different casing, were present in the Catalog. Normally I thought this happened during import where category names weren't normalized and I thought the two categories will have different code.

To my astonishment both categories had the same code e.g. slug.

How is this possible? Was this already fixed in new Platform versions? Because this data might be from an old import.

**Steps to reproduce**
Same name, different casing, for two categories was used at import and both categories got created with the same code/slug

**Expected behavior**
There should be an error or at least the two categories should have different code stored

**Version info (please complete the following information):**
 - Browser version: chrome
 - Platform version: 2.13.50

**Comment by yecli** [comment]
Was not able to reproduce it on the latest versions.
Tried to import 2 product with the same SKU and SEO, but with different Ids. Only one was imported.
You can try to reproduce the issue on our public demo, it contains the latest versions:
https://admin-demo.virtocommerce.com/

Personally I think we should not invest in the development of current csv-import module. I hope we will replace it with the combination of generic export/import modules.
