### ISSUE TITLE
Platform picks up old prices

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-platform#1795]
Last year I reported an issue with price import which was supposedly resolved in summer 2019:
https://github.com/VirtoCommerce/vc-platform/issues/1596

Currently it seems that bug was indeed solved and I succesfully imported new prices with correct min quantities set (to 1) but the system is still picking up old prices.

Refreshed and reindexed but still old prices come to storefront.

Any ideas what is going on?

**Comment by yecli** [comment]
You need to check what prices are in the index.
1. If the prices in the index are not correct - you need to revise your pricelists/assignments etc. to get correct prices in the index.
2. When/if prices are correct in the index, and are not refreshed on the storefront - it could be storefront caching problem. Try "/common/resetcache" storefront api to reset the cache and check the result (could be run under admin account). If this was the problem, you could revise cache settings in the storefront: https://github.com/VirtoCommerce/vc-storefront-core/blob/master/VirtoCommerce.Storefront/appsettings.json#L13-L17

**Comment by brgrz** [comment]
@yecli I see tier prices in some xhr responses and also old prices together with new prices (the new prices are there but it is picking up the old ones). No cache reset or site restart helps.

Also, I see some weird values for taxPercentRate in those response, for example 0.2197 or 0.2202 for a fixed tax rate of 22% (0.22). The prices seem to be computed ok but I don't know what these weird values mean.

**Comment by yecli** [comment]
Is the problem solved?

If you have a specific example resulting in wrong behavior with the prices that is reproducible on our demo sites (https://admin-demo.virtocommerce.com/ and https://demo.virtocommerce.com/) - could you please provide the steps to reproduce it?
