### ISSUE TITLE
Implement color swatches in the default theme instead of default selectors

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#180]
Should display color choices with ability to pick to use color images or named colors to display the choices. Similar to https://docs.shopify.com/manual/configuration/store-customization/showcasing-products/add-color-swatches-to-your-products#Demo

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
