### ISSUE TITLE
API widget not found in user blade

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1806]
**Describe the bug**

**Steps to reproduce**
1. Open user
2. See error

**Expected behavior**
Should not have issue.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1566470/77106829-f86f8080-69dc-11ea-922d-243b3bb29bdc.png)

**Version info (please complete the following information):**
 - Browser version:
 - Platform version: v3 rc4

**Additional context (optional)**

**Comment by akak1977** [comment]
Looks strange as if obsolete scripts in brows cache.
There is no more API widget in "User" blade.
This function was moved to OAuth applications "Security" section (look at the image).
Could you try to clear scripts cache (Ctrl+F5)?
![image](https://user-images.githubusercontent.com/9972421/77162881-c3dbf180-6ace-11ea-998f-1cf33dc5e31e.png)
