### ISSUE TITLE
Platform can't run in non https mode and thus can't be deployed to local docker instance

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1818]
Platform currently requires https to be enabled, otherwise the following exception is generated:

`The current request was rejected because the OpenID Connect server middleware has been configured to reject HTTP requests. To permanently disable the transport security requirement, set 'OpenIdConnectServerOptions.AllowInsecureHttp' to 'true'.`

It works fine in local environment, as local certificate can be installed and used, however when more complex docker (compose) is needed, with storefront container connecting to platform container the above (localhost) certificate will no longer work. We have to reference other container by name, for instance "vc-platform-web" and call it from a different container.

To resolve this, we need to make sure platform works without https requirement, as in some cases platform can be located behind firewalls and with no public URL all together in which case certificate is not needed.

I would introduce the same setting called "AllowInsecureHttp" for the platform and make sure to set OpenIdConnectServerOptions.AllowInsecureHttp to that value.

**Comment by tatarincev** [comment]
@Woland2k  Thanks for the detailed requirement description. We will look at this.

**Comment by tatarincev** [comment]
The solution turned out to be very simple, in order to disable HTTPS strict policy you just enough to run the platform and specify the only HTTP schema  
```
dotnet VirtoCommerce.Platform.Web.dll --urls=http://localhost:5000
```

**Comment by Woland2k** [comment]
Login will still give exception due to OpenId, need an environmental variable to disable https of OpenId

**Comment by Woland2k** [comment]
fixed here: https://github.com/VirtoCommerce/vc-platform/commit/39afc510eb6d666db6323ca8ca3501eb8e57dd23

**Comment by tatarincev** [comment]
I did it in a more elegant way. You no longer need any extra setting for this.  https://github.com/VirtoCommerce/vc-platform/commit/8b18b0b17b9b34bddd4677a992858861071382d7

**Comment by Woland2k** [comment]
@tatarincev I see sometimes a need to connect to platform using both https and http (internally for instance)

**Comment by tatarincev** [comment]
I think your requirements are completely satisfied with this commit
https://github.com/VirtoCommerce/vc-platform/commit/6d47cae87a0f95630ea90f8108e6f2dfccaebea4
