### ISSUE TITLE
Error when opening v3 from VS.NET for the first time

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1819]
**Describe the bug**

**Steps to reproduce**
1. Create new folder and checkout v3 repo from github
2. Launch solution using F5
3. Home page opens without showing login

**Expected behavior**
Should open standard login scren.

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/1566470/78397024-4cfe2880-75a5-11ea-9ef6-e56660d83a0b.png)

**Version info (please complete the following information):**
 - Browser version:
 - Platform version: v3 rc4

**Comment by Woland2k** [comment]
Running 

` VC-build webpackbuild`

does resolve the issue, but we need to make it more seamless for the developer or describe this in our instructions.

**Comment by OlegoO** [comment]
@Woland2k I think build and webpackbuild should be part of a single operation.

**Comment by Woland2k** [comment]
It is actually worse when module doesn't have webpack build, as there is no visible error and module simply doesn't show up in the menu.

**Comment by yecli** [comment]
I think it should be fixed in VS 16.6.1 - webpackbuild should be done wit the first build.
