### ISSUE TITLE
Disable MARS in connection string

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1828]
**Describe the bug**
The SQL server feature called MARS or MultipleActiveResultSets should be disabled in platform as it will most likely negatively affect performance, crash system (linux) or promote bad development practices (keeping connections/readers open for a long time etc).

Lets include MultipleActiveResultSets=False in our default platform connection string for v3.

**Comment by lnetrebskii** [comment]
https://github.com/VirtoCommerce/vc-platform/releases/tag/3.2.0
