### ISSUE TITLE
Sample data for electronics missing blogs and pages

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1839]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1566470/79600802-99189500-809c-11ea-89dc-e21ebcfc3afa.png)

![image](https://user-images.githubusercontent.com/1566470/79600813-9ddd4900-809c-11ea-9bfc-294c7a8747bc.png)

Translations are missing in electronics theme as well.

**Comment by yecli** [comment]
Sample data were updated
