### ISSUE TITLE
Use lowercase names for all folders

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1858]
**Problem:**
Since different cases are used for folders, it makes it easy to make configuration errors, especially on case sensitive OS'es (ex. linux). One example is Modules folder, if configuration done in linux and "modules" folder is used.

**Solution:**
Make all folder names lowercase by default.

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2262 has been created

**Comment by eMazeika** [comment]
renamed, ready for release
