### ISSUE TITLE
Latest demo sample data file for v3 is broken

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1860]
**Describe the bug**
clothing-and-electronics_3_0_0.zip has multiple directories inside when it shouldn't and thus doesn't import on platform

**Steps to reproduce**
Perform new install

**Expected behavior**
Should import he file without any error.

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2263 has been created

**Comment by lnetrebskii** [comment]
Fixed and uploaded. The fix is here https://github.com/VirtoCommerce/vc-sample-data/pull/2
