### ISSUE TITLE
Can't see ShipmentMethodOption in Admin

### ISSUE THREAD

**Issue by tuviks** [VirtoCommerce/vc-platform#1861]
I can't find ShipmentMethodOption (Ground or Air) in the shimpment object of an order.

**Steps to reproduce**
1. Go to product
2. Click "Add to cart"
3. Go to cart
4. Submit order with Ground or Air shipping method
5. Go to Admin panel -> Orders
6. Select current order
7. Go to shipment
8. Try to find shipment option: Ground or Air

Manager can view sipping methond and shipping option which was chosen by customer

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/17646910/81508380-76c90e80-930c-11ea-9a88-fdf231324996.png)

I can find this only in database:
![image](https://user-images.githubusercontent.com/17646910/81508535-564d8400-930d-11ea-95d5-c69a4623d11b.png)

**Version info (please complete the following information):**
 - Browser version: Google Chrome  81.0.4044.138
 - Platform version: v2.13.62

**Additional context (optional)**

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2264 has been created
