### ISSUE TITLE
module selection by group is broken

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1867]
**Describe the bug**
When clicking group checkbox, it becomes selected, however sub checks are not

![image](https://user-images.githubusercontent.com/1566470/82004901-d2e7a780-9618-11ea-961f-7062ecc2538b.png)

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-platform/releases/tag/3.54.0
