### ISSUE TITLE
Email instead of username

### ISSUE THREAD

**Issue by tuviks** [VirtoCommerce/vc-platform#1869]
**Problem:**
I need only one field with email for notifications and login. It improves experience for customers and easier to register on the site.

**Solution:**
Add setting "Use email as username". If it is true hide field UserName from registration form, set Email is required and use Email instead of UserName.

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2341 has been created

**Comment by eMazeika** [comment]
@tuviks, 
- platform version not specified: v2 or v3? 
- theme(s) not specified: is it https://github.com/VirtoCommerce/vc-theme-default ?
- alternatively, it could be implemented in a theme-only (switcher in theme settings). Could it be acceptable? Or you could change it in your custom theme as needed.

**Comment by tuviks** [comment]
@eMazeika,

- v2 platform version, but now I'm working with v3 and maybe this issue is not actual
- I got default theme as base
- yes, it will be very good if we will have switcher in default theme. But in this case we should prevent changing email of user (we could hide control at UI but how we prevent directly request to api?). And we should set email as required.

P.S.: thank you for your work!

**Comment by eMazeika** [comment]
I see it only as a UX change, but not api. 
@lnetrebskii , can you update the task in jira accordingly?
