### ISSUE TITLE
RequireConfirmedEmail on registration

### ISSUE THREAD

**Issue by tuviks** [VirtoCommerce/vc-platform#1870]
**Describe the bug**
Setting RequireConfirmedEmail = true is not working on registration. I became logged in. But after logout I can't login again - it's OK.

**Steps to reproduce**
1. Storefront\appsettings.json
2. Add setting "IdentityOptions" -> "SignIn" -> "RequireConfirmedEmail"
3. Set "RequireConfirmedEmail" to true
4. Register new account
5. See user logged in

**Expected behavior**
User can't login before email address was confirmed

**Version info (please complete the following information):**
 - Browser version: Google Chrome 81.0.4044.138
 - Platform version: v2.13.62

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2342 has been created

**Comment by yecli** [comment]
Issue moved to [VirtoCommerce/vc-storefront #557](https://github.com/VirtoCommerce/vc-storefront/issues/557) via [**ZenHub**](https://www.zenhub.com/)
