### ISSUE TITLE
Prevent database creation on first run

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1871]
**Describe the bug**
Currently when there is no database, platform will try creating one automatically. This behavior should be configurable as in many cases i would rather see an error than trying to create a database.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7444 has been created

**Comment by OlegoO** [comment]
You need to create a custom user with limited permission and run Virto Commerce with non-administrator user. So, you will see the error when there is no database. 

https://docs.microsoft.com/en-us/azure/azure-sql/database/logins-create-manage#create-accounts-for-non-administrator-users
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-login-transact-sql?view=azuresqldb-current&preserve-view=true#examples-1
