### ISSUE TITLE
Theme import doesn't work correctly on linux

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#1875]
**Describe the bug**
When importing exported file containing theme files in linux, import completes, however theme is not displayed under content link.

**Steps to reproduce**
1. Go to import/export and export content theme including binary.
2. Go to linux platform installation and import the data file.
3. Check content and see if there is a theme defined.

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2403 has been created

**Comment by eMazeika** [comment]
Could not reproduce on latest docker (linux) containers

**Comment by Aleksandra-Mitricheva** [comment]
Hi @Woland2k ,

we can't reproduce this issue. 
Could you check again if this is still reproducible for you?

**Comment by Woland2k** [comment]
Works now.
