### ISSUE TITLE
Install Virto Commerce 3.x Module Templates to Visual Studio Enterprise 2017

### ISSUE THREAD

**Issue by tuviks** [VirtoCommerce/vc-platform#1895]
**Describe the bug**
I can't install Virto Commerce 3.x Module Templates to Visual Studio Enterprise 2017

**Steps to reproduce**
1. Download template - https://marketplace.visualstudio.com/items?itemName=Virto-Commerce.VirtoCommerce3ModuleTemplates
2. Try to install to Visual Studio Enterprise 2017
4. See logged error "VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products."

**Version info (please complete the following information):**
 - Visual Studio version: 15.9.12

**Additional context (optional)**
[VSIXInstaller_3bfae194-2ce2-424b-b3bb-a547c7c18410.log](https://github.com/VirtoCommerce/vc-platform/files/4707508/VSIXInstaller_3bfae194-2ce2-424b-b3bb-a547c7c18410.log)

**Comment by lnetrebskii** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-2678 has been created

**Comment by eMazeika** [comment]
Both VC Platform 3 and its module projects are targeting .NET Core 3.1. This framework is only supported in Visual Studio 2019: https://dotnet.microsoft.com/download/dotnet-core/3.1. Therefore, the template extension can be installed to VS2019+, but not VS2017.
You should consider upgrading to VS2019; all editions are supported.
