### ISSUE TITLE
Documentation links for v2 to v3 Update are not working

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-platform#1938]
**Describe the bug**
The links in the main Readme.md file where the documentation of the upgrade from v2 to v3 is described does not work: 
https://github.com/VirtoCommerce/vc-platform/blob/master/docs/update-to-version-3/update-module-from-platform-2.0-to-version-3.md

**Steps to reproduce**

1. Open https://github.com/VirtoCommerce/vc-platform
2. Scroll down to section https://github.com/VirtoCommerce/vc-platform#introduction-to-virto-commerce
3. Try to open last link in this section
4. 404 

**Expected behavior**
Documentation how to upgrade opens if i press the link

**Screenshots (optional)**
not needed

**Version info (please complete the following information):**
 - Browser version: all
 - Platform version: newest github version

**Additional context (optional)**

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3661 has been created

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-platform/commit/a914c581af225d2e1a1381aa8834bb6ad3271b55

Correct link is https://github.com/VirtoCommerce/vc-platform/blob/master/docs/release-information/update-to-version-3/update-module-from-platform-2.0-to-version-3.md
