### ISSUE TITLE
OpenIddict 3.0 migration

### ISSUE THREAD

**Issue by kevinchalet** [VirtoCommerce/vc-platform#2010]
Hey folks,

For over a year now, I've been working on OpenIddict 3.0 and beta versions are already available on NuGet.org (3.0 beta4 should ship later this month, once https://github.com/openiddict/openiddict-core/issues/1053 is fixed).

3.0 represents a major overhaul and significant changes have been made:
  - ASOS and the aspnet-contrib validation/introspection middleware have all been merged into OpenIddict.
  - OpenIddict 3.0 now offers [a degraded/ASOS-like mode](https://kevinchalet.com/2020/02/18/creating-an-openid-connect-server-proxy-with-openiddict-3-0-s-degraded-mode/) for the users who don't want to use the OpenIddict stores/managers.
  - It is fully compatible with ASP.NET Core 2.1 (on .NET Framework and .NET Core), 3.1 and 5.0.
  - It now natively supports OWIN/Katana (and thus can be used on >= ASP.NET 4.6.1).
  - JSON.NET has been replaced by `System.Text.Json` across the entire OpenIddict codebase.
  - It natively supports the device code flow.
  - All the error messages are now localized for a better user experience.

For more information, you can read the following blog posts:
  - [Introducing OpenIddict 3.0 beta1](https://kevinchalet.com/2020/06/11/introducing-openiddict-3-0-beta1/)
  - [OpenIddict 3.0 beta2 is out](https://kevinchalet.com/2020/07/08/openiddict-3-0-beta2-is-out/)
  - [Introducing localization support in OpenIddict 3.0 beta3](https://kevinchalet.com/2020/08/03/introducing-localization-support-in-openiddict-3-0-beta3/)

All the samples have been updated to target the latest OpenIddict 3.0 beta version: https://github.com/openiddict/openiddict-samples

It's important to note that **I'll stop supporting OpenIddict 2.x once 3.x ships**, as a considerable effort has been dedicated to making sure that all users of ASOS, the aspnet-contrib extensions or OpenIddict have a migration path to 3.0.
With that in mind, I encourage all teams to start testing the latest OpenIddict 3.0 beta packages in a separate branch/non-production environment, so that they can report possible bugs and easily make the switch when RTM ships.

Please let me know if you have any question.

Cheers!

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-4597 has been created

**Comment by kevinchalet** [comment]
Looks like you're now tracking that internally. Closing.

**Comment by tatarincev** [comment]
@kevinchalet  Thanks for a good job! We'll play around a bit with the beta and keep you informed on issues.

**Comment by kevinchalet** [comment]
FYI OpenIddict 3.0 rc1 was released yesterday: https://kevinchalet.com/2020/11/17/introducing-openiddict-3-0-s-first-release-candidate-version/

3.0 RTM will ship next month (and as mentioned in my first post, 2.0 will no longer be supported once 3.0 officially ships).

**Comment by tatarincev** [comment]
@kevinchalet  We did it! The https://github.com/VirtoCommerce/vc-platform/releases/tag/3.67.0 has been released and now works with OpenIddict 3.0, but since we had to some dirty hack with legacy dependencies because of our modularity nature, in order to provide seamless migration for modules that are referenced to the old version. 
Thank you a lot for your great job, keep it up! 🥇

**Comment by kevinchalet** [comment]
Yeah, I saw that: very nice! 😄 

> Thank you a lot for your great job, keep it up! 🥇

Thanks! Don't hesitate to encourage your company to sponsor the project and help secure your supply chain! ❤️
