### ISSUE TITLE
Setting modules ulr to empty makes platform unusable

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#2054]
Setting ExternalModules:ModulesManifestUrl setting to "" causes long delays when opening any settings dialog.

Need a way to specify that there is no need to load any of the modules.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-5340 has been created

**Comment by Vectorfield4** [comment]
I don't see any performance problems with these settings. No delay. No initialization problems. Any additional info?
