### ISSUE TITLE
Unable to rebuild indices with ElasticSearch

### ISSUE THREAD

**Issue by bulldoguc** [VirtoCommerce/vc-platform#2097]
Running v3.13.0 with ElasticSearch enabled in AppSettings.JSON

If I enable Lucene as my default search engine, then everything works as expected, however when I switch to ElasticSearch, I get the following error when trying to rebuild indices (whether I use "build" or "delete and build") and obviously search no longer works.  Any pointers?

System.AggregateException: One or more errors occurred. (Failed to submit mapping. Invalid NEST response built from a unsuccessful (400) low level call on PUT: /default-product/_mapping # Audit trail of this API call: - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0040851 # OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /default-product/_mapping. ServerError: Type: Reason: "ActionRequestValidationException[Validation Failed: 1: mapping type is missing;]" # Request: <Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.> # Response: <Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.> . URL:http://localhost:9200/, Scope: default) ---> VirtoCommerce.SearchModule.Core.Exceptions.SearchException: Failed to submit mapping. Invalid NEST response built from a unsuccessful (400) low level call on PUT: /default-product/_mapping # Audit trail of this API call: - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.0040851 # OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /default-product/_mapping. ServerError: Type: Reason: "ActionRequestValidationException[Validation Failed: 1: mapping type is missing;]" # Request: <Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.> # Response: <Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.> . URL:http://localhost:9200/, Scope: default ---> Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /default-product/_mapping. ServerError: Type: Reason: "ActionRequestValidationException[Validation Failed: 1: mapping type is missing;]" --- End of inner exception stack trace --- at VirtoCommerce.ElasticSearchModule.Data.ElasticSearchProvider.ThrowException(String message, Exception innerException) in /home/runner/work/vc-module-elastic-search/vc-module-elastic-search/src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs:line 374 at VirtoCommerce.ElasticSearchModule.Data.ElasticSearchProvider.UpdateMappingAsync(String indexName, Properties`1 properties) in /home/runner/work/vc-module-elastic-search/vc-module-elastic-search/src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs:line 340 at VirtoCommerce.ElasticSearchModule.Data.ElasticSearchProvider.IndexAsync(String documentType, IList`1 documents) in /home/runner/work/vc-module-elastic-search/vc-module-elastic-search/src/VirtoCommerce.ElasticSearchModule.Data/ElasticSearchProvider.cs:line 107 at VirtoCommerce.SearchModule.Data.Services.IndexingManager.IndexDocumentsAsync(String documentType, IList`1 documentIds, IIndexDocumentBuilder primaryDocumentBuilder, IEnumerable`1 secondaryDocumentBuilders, ICancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs:line 272 at VirtoCommerce.SearchModule.Data.Services.IndexingManager.ProcessDocumentsAsync(IndexDocumentChangeType changeType, IList`1 documentIds, BatchIndexingOptions batchOptions, ICancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs:line 261 at VirtoCommerce.SearchModule.Data.Services.IndexingManager.ProcessChangesAsync(IEnumerable`1 changes, BatchIndexingOptions batchOptions, ICancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs:line 233 at VirtoCommerce.SearchModule.Data.Services.IndexingManager.ProcessConfigurationAsync(IndexDocumentConfiguration configuration, IndexingOptions options, Action`1 progressCallback, ICancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs:line 177 at VirtoCommerce.SearchModule.Data.Services.IndexingManager.IndexAsync(IndexingOptions options, Action`1 progressCallback, ICancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/Services/IndexingManager.cs:line 99 at VirtoCommerce.SearchModule.Data.BackgroundJobs.IndexingJobs.IndexAllDocumentsAsync(IndexingOptions options, ICancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs:line 313 --- End of inner exception stack trace --- at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.WaitAll(Task[] tasks) at VirtoCommerce.SearchModule.Data.BackgroundJobs.IndexingJobs.RunIndexJobAsync(String currentUserName, String notificationId, Boolean suppressInsignificantNotifications, IEnumerable`1 allOptions, Func`3 indexationFunc, IJobCancellationToken cancellationToken) in /home/runner/work/vc-module-search/vc-module-search/src/VirtoCommerce.SearchModule.Data/BackgroundJobs/IndexingJobs.cs:line 284

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6080 has been created

**Comment by yecli** [comment]
You need to configure ElasticSearch as a search engine first. Useful links:
https://github.com/VirtoCommerce/vc-platform/blob/8e5c19da7ea24c6579786d0cbc89ee5a36b1427a/docs/user-guide/configuration-settings.md section Search
https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/appsettings.json#L115-L131

**Comment by bulldoguc** [comment]
Those are exactly the settings that I have, except I changed "Provider" to be "ElasticSearch" - as below.  I'm running on localhost, so no API key has been defined, and I am able to modify indices using curl when I am logged into that server.

`"Search": {
        "Provider": "ElasticSearch",
        "Scope": "default",
        "Lucene": {
            "Path": "app_data/lucene"
        },
        "AzureSearch": {
            "SearchServiceName": "ServiceName",
            "Key": "AccessKey"
        },
        "ElasticSearch": {
            "Server": "localhost:9200",
            "User": "elastic",
            "Key": "",
            "EnableHttpCompression": ""
        }
    },`

**Comment by yecli** [comment]
Just tried with this config on Win 10 env - seems the same as you provided, with ES available at localhost:9200:
```
    "Search": {
        "Provider": "ElasticSearch",
        "Scope": "default",
        "Lucene": {
            "Path": "app_data/lucene"
        },
        "AzureSearch": {
            "SearchServiceName": "ServiceName",
            "Key": "AccessKey"
        },
        "ElasticSearch": {
            "Server": "localhost:9200",
            "User": "elastic",
            "Key": "",
            "EnableHttpCompression": ""
        }
    },
```
It is also working on Azure and on Linux on our demo environments. 
I'm using ES 7.4.2 (VC only supports ES version 7). Please check your ES version.
Also it could be some environment-related problem, the application could not connect to the ES.

**Comment by bulldoguc** [comment]
Thanks for the follow up Andrey - confirmed it was my version of ES.  The latest download on elastic.co is 7.1.0 - installing and running that service took care of my connection issues!
