### ISSUE TITLE
How to debug external modules like catalogcsvimport ?

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2108]
Hello Team, 
I am new to this eCommerce platform.
I have configured the VC Platform Admin in my system.
My question is how can I import and debug the external modules like catalogcsvimport into the VC Platform solution?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6201 has been created

**Comment by yecli** [comment]
Hi, you can find info in our [docs](https://virtocommerce.com/docs/latest/):
Specifically, about module deployment from source code and debugging:
https://virtocommerce.com/docs/latest/developer-guide/deploy-module-from-source-code/

**Comment by akak1977** [comment]
Let's count it resolved.

**Comment by shubhamdhanetia** [comment]
Hello @yecli, I am able to debug a single module by attaching it to the process. But Is there any way we run multiple modules in debug mode to understand the flow better?
