### ISSUE TITLE
Getting module dependency error when installing webhook module

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2109]
I tried installing the webhook module in VC platform admin. I got a dependency error to install VirtoCommerce..Core module.

Then I installed the VirtoCommerce.Core module and restarted the VC Platform and tried again to install the webhook module. 

Still, I am getting the error of dependency for that module. 

Are there any manual changes need to be done ?

**Comment by akak1977** [comment]
Hi!
What are the platform and modules versions you tried to install?

**Comment by shubhamdhanetia** [comment]
Hello !

Platform as per the latest source code. (Should I use the latest release version instead ?)

VirtoCommerce.Core module version installed: v2.25.35

Now I am trying installing the webhook latest release v0.1.6 and getting a Core Module dependency error.

**Comment by akak1977** [comment]
Current platform master/dev branches contain platform v3.x source codes.
v3.x modules only are compatible with platform v.3.x.
Looks as you try to start the module for platform v2.x under platform v.3.x

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6205 has been created

**Comment by shubhamdhanetia** [comment]
Thanks @akak1977 ,

So should I install the v2 platform releases or should I clone the VC Core module repository to get the latest version, creating the zip and uploading that module instead?

**Comment by akak1977** [comment]
If you are a newcomer, I recommend you just to get the latest platform release [there](https://github.com/VirtoCommerce/vc-platform/releases).
Next, follow the [instructions](https://github.com/VirtoCommerce/vc-platform/blob/master/docs/getting-started/deploy-from-precompiled-binaries-windows.md).
After startup, you will have a completely installed platform, default modules set, and a sample dataset.

**Comment by yecli** [comment]
Please also note that there is no webhook module available for the current v3 net core platform version. It is the recommended version to use.
At the moment it is available only for the old v2 version. V2 is not developing actively, no new features - only critical bug fixes.

**Comment by shubhamdhanetia** [comment]
Thanks @akak1977, I will go through it.

@yecli  Oh Okay, so what do you suggest.
As we will be using Version 3, we would also be needing webhook support to send event data to 3rd party Legacy Application.

**Comment by yecli** [comment]
We are working on it, so I think we'll release webhooks for v3 soon.

**Comment by shubhamdhanetia** [comment]
Thanks, @yecli for the update!

**Comment by akak1977** [comment]
Let's count it resolved.
