### ISSUE TITLE
Issue with rendering notifications

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#2113]
![image](https://user-images.githubusercontent.com/1566470/101823499-b4c72480-3adf-11eb-8641-711d499d9d70.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6388 has been created

**Comment by eMazeika** [comment]
The fix:
![image](https://user-images.githubusercontent.com/5801549/104343737-fbf06d00-5504-11eb-81f5-de78dd388ce7.png)

**Comment by OlegoO** [comment]
Fixed in 
vc-platform 3.39
vc-module-export 3.8
