### ISSUE TITLE
Add possibility to ovveride platform handlers such as LogChangesUserChangedEventHandler

### ISSUE THREAD

**Issue by IvanTsel96** [VirtoCommerce/vc-platform#2114]
**Describe the bug**
Can not override platform handler LogChangesUserChanged EventHandler in custom modules.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6392 has been created

**Comment by Vectorfield4** [comment]
Hi, @IvanTsel96! Look at https://github.com/VirtoCommerce/vc-platform/blob/master/docs/fundamentals/extensibility/extending-using-events.md#how-to-override-an-existing-event-handler-with-a-new-derived-type (last paragraph).

You need:
1. Override event handler with your customer handler thru inheritance;
2. Add overriding thru DI by adding transient service.

If you need more info feel free to open this issue.
