### ISSUE TITLE
platform:security:loginOnBehalf permission is missing

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#2118]
**Describe the bug**
The `Login on behalf` button is bound to the `platform:security:loginOnBehalf` permission, but this permission is not present in the permissions list and it cannot be assigned to any role. So the only way to get the `Login on behalf` button is to set the `Is administrator` flag to `true`.

**Expected behavior**
`platform:security:loginOnBehalf` permission should be present in the permissions list.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/8775253/102761717-f24d6c80-437f-11eb-8d87-e71f6a848584.png)

**Version info (please complete the following information):**
 - Platform version: 3.36.0

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6462 has been created

**Comment by yecli** [comment]
This permission was moved to the store module and is called `store:loginOnBehalf` now. It was done to be able to set allowed stores.
![image](https://user-images.githubusercontent.com/15610352/102891842-ba7a1e00-4480-11eb-92b5-69cf07055670.png)

**Comment by artem-dudarev** [comment]
This is not true.
https://github.com/VirtoCommerce/vc-platform/blob/master/src/VirtoCommerce.Platform.Web/wwwroot/js/app/app.js#L462
![image](https://user-images.githubusercontent.com/8775253/102893626-93b0ed00-446a-11eb-8d97-d752030ce6ff.png)

**Comment by yecli** [comment]
Indeed, we will fix this one.

**Comment by yecli** [comment]
@artem-dudarev 
For proper prioritization (as now we cannot determine the severity of this bug for the client project), please ask client project QA team to follow this common workflow:
1.	A bug is identified by Virto team working on a commercial project:
a.	Jira item exists in commercial project
b.	QA or Developer creates a Jira item in [Platform team board](https://virtocommerce.atlassian.net/secure/RapidBoard.jspa?rapidView=90&projectKey=VP) as per [template](https://virto365.sharepoint.com/:w:/r/sites/VirtoCommerce/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B296E7495-60A9-4224-8598-DCD95EA6B57A%7D&cid=b54c7118-5532-400d-87fb-b00e700df356).
c.	Account for Platform item should be “Platform Development and Support”, label Support should be added and status should be changed to Funnel
Note: full instructions can be found in support workflow  document (“Freshdesk” -> “Escalation to QA team and internal processing” section)

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-platform/releases/tag/3.39.0
