### ISSUE TITLE
Getting Angular script injection error when running Platform

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2119]
![image](https://user-images.githubusercontent.com/71070755/103001836-c551b300-4553-11eb-9ece-86dffc52357f.png)

Getting error when running platform. Tried on platform release 3.34 and latest release.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6485 has been created

**Comment by yecli** [comment]
Seems your catalog module is broken or not completely built by web pack. Are you using old latest catalog v3 module version from github, https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.26.0?

**Comment by shubhamdhanetia** [comment]
Hello @yecli , the issue was coming as we were using SQL Server 2014 in our system, and that's why catalog module couldn't installed properly and throwing SQL exception. Now, since we have updated to SQL Server 2019, catalog module is installed properly and we are not getting this error.
