### ISSUE TITLE
How to use dynamic property in code ?

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2153]
I have created one dynamic property from the platform in the Shipment model.
The reason is I want to store additional information from the user through the storefront UI.
Now, how can we use the newly added dynamic property to work as a new input field? 
What are the code changes required for this? 
Can I manage to store additional info without touching the Shipment module or do I need to create a custom Module?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7020 has been created

**Comment by OlegoO** [comment]
You need to use API. Every entry has DynanicProperties collection. 
So, your form can submit the data via API to Storefront backend, then you need to create a custom code to read it from the form and send to API. You can look on the backend SPA as sample how to read, save dynamic properties.

**Comment by shubhamdhanetia** [comment]
Thanks, @OlegoO, 
So what I understand is using Dynamic properties, we don't need to touch the specific module entity class.
And we need to add custom code in the liquid form for the new property and pass that property to the storefront backend API.
And once we get the dynamic property in storefront API, we need to add that in the dynamic property of the model class and pass it to the platform API.
And by backend SPA Sample, which project you are specifying. Is it VC Platform solution? Is it possible for you to share the link?

**Comment by OlegoO** [comment]
@OlegoO  Virto Commerce support 3 types of extensions:
1. Native - when you create a module  and can default domain model, business logic and DB Layer https://virtocommerce.com/docs/latest/fundamentals/extensibility/extending-domain-models/
2. Declarative - Like Dynamic properties https://virtocommerce.com/docs/2.0/user-guide/configuration/managing-dynamic-properties/
3. API - by using WebHook, AzureEvent event grid and 3rd party services, like Azure Functions, Logic App, etc.
