### ISSUE TITLE
Adding Variant Product to Cart for the Digital Product Type Fails

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2156]
There is an issue when we add variance to the product type: Digital Product. 
On adding the variant product, we cannot able to add the variant product to the cart.
The reason I found is the TrackInventory property for the variance product is 1, but for the parent digital product is 0.
As the TrackInventory property for the variant Digital product is 1, on the storefront, it is not allowing to add the product to the cart.

As you can see, in the database, TrackInventory for the product - Medical Insurance Yearly is 1 which is a variant Digital product.

![image](https://user-images.githubusercontent.com/71070755/108094549-f1496a80-70a4-11eb-978a-e0316f60f73e.png)

On the storefront, we are not able to add it to Cart.

![image](https://user-images.githubusercontent.com/71070755/108094681-11792980-70a5-11eb-9628-6aa630ad0e3a.png)

When I changed the TrackInventory property to 0, I was able to add the variant product to cart.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7060 has been created

**Comment by OlegoO** [comment]
@shubhamdhanetia As a workaround, set TrackInventory to 0 in DB.

**Comment by rahul-reveation** [comment]
@OlegoO  Is there any timeline when this will be fixed? It creates store owner dependency on IT person to update the value in DB.

**Comment by OlegoO** [comment]
@rahul-reveation As I see, should be fixing in the comming release this - next week

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.41.0
