### ISSUE TITLE
Getting Resolver errors from swagger docs

### ISSUE THREAD

**Issue by busbina** [VirtoCommerce/vc-platform#2164]
When I browse to http://localhost:5000/docs/index.html and view the endpoint /api/carts/{cartId} the following errors show at the top of the swagger UI.

> Resolver error at paths./api/carts/{cartId}.get.responses.200.content.text/plain.schema.properties.items.items.properties.price.properties.pricelist.properties.prices.items.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.text/plain.schema.properties.shipments.items.properties.items.items.properties.lineItem.properties.price.properties.pricelist.properties.prices.items.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.application/json.schema.properties.items.items.properties.price.properties.pricelist.properties.prices.items.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.application/json.schema.properties.items.items.properties.price.properties.pricelist.properties.assignments.items.properties.pricelist.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.text/plain.schema.properties.items.items.properties.price.properties.pricelist.properties.assignments.items.properties.pricelist.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.application/json.schema.properties.items.items.properties.price.properties.pricelist.properties.assignments.items.properties.dynamicExpression.properties.children.items.properties.availableChildren.items.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.application/json.schema.properties.items.items.properties.price.properties.pricelist.properties.assignments.items.properties.dynamicExpression.properties.children.items.properties.children.items.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.application/json.schema.properties.items.items.properties.price.properties.pricelist.properties.assignments.items.properties.dynamicExpression.properties.availableChildren.items.properties.availableChildren.items.$ref
Could not resolve reference: Not Found
Resolver error at paths./api/carts/{cartId}.get.responses.200.content.application/json.schema.properties.items.items.properties.price.properties.pricelist.properties.assignments.items.properties.dynamicExpression.properties.availableChildren.items.properties.children.items.$ref
Could not resolve reference: Not Found

**Steps to reproduce**
1. Download VirtoCommerce.Platform.3.45.0.zip
2. Edit the appsettings.json to point at a blank database
3. Start the app using ` dotnet VirtoCommerce.Platform.Web.dll --urls=http://localhost:5000`
4. login using the default credentials
5. Select empty store or generate sample data, it doesn't matter
6. Let the store setup
7. Restart once the store is setup
8. Navigate to `http://localhost:5000/docs/index.html`
9. Expand "Shopping cart module"
10. Click on "GET ​/api​/carts​/{cartId}"
11. A large red error block will appear at the top of the UI.

**Expected behavior**
No errors appear

**Screenshots (optional)**
![Screenshot 2021-02-19 130045](https://user-images.githubusercontent.com/8128599/108561105-8a010580-72b2-11eb-8d0c-c76e730aba0d.jpg)

**Version info (please complete the following information):**
 - Browser version: Chrome 88.0.4324.182
    Platform Version
    3.45.0
    License
    Community license
    Installed Modules
    VirtoCommerce.AzureSearch 3.7.0
    VirtoCommerce.BulkActionsModule 3.2.0
    VirtoCommerce.Cart 3.13.0
    VirtoCommerce.Catalog 3.34.0
    VirtoCommerce.CatalogCsvImportModule 3.15.0
    VirtoCommerce.Content 3.11.0
    VirtoCommerce.Core 3.11.0
    VirtoCommerce.Customer 3.24.0
    VirtoCommerce.ElasticSearch 3.5.0
    VirtoCommerce.ExperienceApi 0.23.0
    VirtoCommerce.Export 3.9.0
    VirtoCommerce.ImageTools 3.11.0
    VirtoCommerce.Inventory 3.15.0
    VirtoCommerce.LuceneSearch 3.4.0
    VirtoCommerce.Marketing 3.19.0
    VirtoCommerce.Notifications 3.13.0
    VirtoCommerce.Orders 3.25.0
    VirtoCommerce.Payment 3.7.0
    VirtoCommerce.Pricing 3.17.0
    VirtoCommerce.Search 3.11.0
    VirtoCommerce.Shipping 3.6.0
    VirtoCommerce.Sitemaps 3.7.0
    VirtoCommerce.Store 3.13.0
    VirtoCommerce.Subscription 3.10.0
    VirtoCommerce.Tax 3.6.0
    CLR version
    3.1.12
    64-bit operating system
    true
    64-bit process
    true

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7136 has been created

**Comment by akak1977** [comment]
Yes, we know about this issue. There is no problem with the schema, this is an old bug in swagger UI when the schema contains recursively defined type references. 
Hope they repair it one day.

**Comment by busbina** [comment]
> Yes, we know about this issue. There is no problem with the schema, this is an old bug in swagger UI when the schema contains recursively defined type references.
> Hope they repair it one day.

Awesome, thanks for taking a look. It doesn't seem to be affecting anything.
