### ISSUE TITLE
Unable to get complete order payload in webhook

### ISSUE THREAD

**Issue by shubhamdhanetia** [VirtoCommerce/vc-platform#2183]
I am not able to get complete order payload at the webhook endpoint.

Is there any update which is not allowing to send complete order payload to the webhook endpoint as previously it was working fine ?

**Comment by shubhamdhanetia** [comment]
Got the below payload at the webhook endpoint for the order changed event.

{
  "EventId": "VirtoCommerce.OrdersModule.Core.Events.OrderChangedEvent",
  "Attempt": 1,
  "EventBody": "[{\"objectId\":\"f5bd8383-82ce-4877-98a4-d18950238254\",\"objectType\":\"VirtoCommerce.OrdersModule.Core.Model.CustomerOrder\"}]"
}

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7319 has been created

**Comment by shubhamdhanetia** [comment]
![webhook issue](https://user-images.githubusercontent.com/71070755/111882190-83c57e00-8971-11eb-8256-b13085f5f237.PNG)

**Comment by OlegoO** [comment]
@shubhamdhanetia 
As a workaround, do call to /api/order/customerOrders/{id} method, to get order document.

Could you provide some details about your web hook integration?  
Which services do you use?

**Comment by shubhamdhanetia** [comment]
Hello @OlegoO,

We will be using Azure Logic Apps. When the order will be created in Virto Commerce, the order payload will be sent to the Azure Logic Apps using the webhook endpoint. The logic apps will then transform the order payload to the 3rd party API request payload and post it to another API.

**Comment by OlegoO** [comment]
@shubhamdhanetia Thx for the complete description. The team is checking ...

**Comment by OlegoO** [comment]
@shubhamdhanetia  one of the reason was to improve performance.  

Here the code which defines EventBody format
https://github.com/VirtoCommerce/vc-module-webhooks/blob/master/src/VirtoCommerce.WebHooksModule.Data/Services/WebHookManager.cs#L115-L117

We are discussing how to resolve it, maybe add some settings ...

**Comment by shubhamdhanetia** [comment]
@OlegoO  Thanks for the detailed response. We will be looking forward to the webhook module updates.

**Comment by dvvkgd** [comment]
@shubhamdhanetia We've fixed the issue. Release: https://github.com/VirtoCommerce/vc-module-webhooks/releases/tag/3.5.0
