### ISSUE TITLE
AspNet.Security.OAuth.Validation package is deprecated in Security Controller

### ISSUE THREAD

**Issue by mehdihadeli** [VirtoCommerce/vc-platform#2229]
Hi,
I see my IDE shows that `AspNet.Security.OAuth.Validation` package is deprecated and should be replaced with 
`OpenIddict.AspNetCore` in `SecurityController`.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7366 has been created

**Comment by OlegoO** [comment]
@mehdihadeli we are checking how to update the OpenIddict component

**Comment by mehdihadeli** [comment]
Ok thanks.
