### ISSUE TITLE
Where is front-end part this platform?

### ISSUE THREAD

**Issue by mehdihadeli** [VirtoCommerce/vc-platform#2235]
Hi,
I can't find the front-end part admin part of this platform !! 
Where is it?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7369 has been created

**Comment by OlegoO** [comment]
@mehdihadeli  Front-end part of admin, now, integrated with platform and modules. It's AngularJS SPA.

For example: in Platform here
https://github.com/VirtoCommerce/vc-platform/tree/master/src/VirtoCommerce.Platform.Web/wwwroot

in any module here:
https://github.com/VirtoCommerce/vc-module-catalog/tree/master/src/VirtoCommerce.CatalogModule.Web/Scripts

https://virtocommerce.com/docs/latest/fundamentals/extensibility/blades-and-navigation/#blade-navigation
https://virtocommerce.com/docs/latest/fundamentals/extensibility/style-guide/

**Comment by mehdihadeli** [comment]
@OlegoO Thanks for your guide.
