### ISSUE TITLE
Install Virto Commerce on Windows10 error

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-platform#2328]
**Describe the bug**
I download the latest version of release VirtoCommerce.Platform.3.70.0.zip and unpack it ,then use the following commands to run it on windows 10  ,
```
dotnet dev-certs https --trust
dotnet.exe VirtoCommerce.Platform.Web.dll
````

 open the Chrome with https://localhost:5001, login ,install modules,and then restart,but when reopen the https://localhost:5001 it response `Startup error`

**Expected behavior**
It works correctly.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/5348170/125182535-75151680-e241-11eb-84c8-3a470f0cca09.png)
![image](https://user-images.githubusercontent.com/5348170/125182656-709d2d80-e242-11eb-854d-15a955c7f094.png)

![image](https://user-images.githubusercontent.com/5348170/125182574-bad1df00-e241-11eb-9363-67279b5f43a2.png)

**Version info (please complete the following information):**
 - Browser version :Chrome  91.0.4472.124
 - Platform version:3.70.0

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7541 has been created

**Comment by six006** [comment]
After installed database sqlserver express 2019,I solved this problem.
