### ISSUE TITLE
When you add a category should determine whether the category name already exists!

### ISSUE THREAD

**Issue by qq550723504** [VirtoCommerce/vc-platform#233]
![20160113154500](https://cloud.githubusercontent.com/assets/6007227/12288156/a9e382ec-ba0c-11e5-9b54-42daa8c85175.png)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #32](https://github.com/VirtoCommerce/vc-module-catalog/issues/32) via [**ZenHub**](https://www.zenhub.com/)
