### ISSUE TITLE
Customer org security scope rule

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#236]
I want to make a user able to Manage only users from his organization.
Also the Marketing Section isn´t boundable to specific organizations.
Creating and saving a new Organization Displays the organization as a customer (Image). Even a refresh doesn´t render the organization Image. After closing and re-opening the Module it Displays the correct Image.

**Comment by OlegoO** [comment]
Implemented in 
https://github.com/VirtoCommerce/vc-module-b2b-extensions
