### ISSUE TITLE
Markdown / Markup product descriptions are not escaped in anyway allowing for XSS.

### ISSUE THREAD

**Issue by loktar00** [VirtoCommerce/vc-platform#2388]
## Issue

Descriptions or "reviews" allow code to be executed, there is no filtering of elements such as script tags allowing for malicious code to be injected into the storefront and the platform itself.

## Steps to reproduce the behavior:
1. Go to products -> any item -> descriptions
2. Open any of the descriptions (full review for example)
3. Place a script tag with executable code for example, `alert(document.cookies)`
4. Code will be executed on the platform if you preview markdown.
5. Save product, go to the storefront (even the default storefront shipped with product)
6. See code executed in the browser on the storefront as well.

## Added in platform
![platform](https://user-images.githubusercontent.com/174857/135878213-6902c02b-2ee3-42fa-be0c-ef0725851e25.PNG)

## Executed in storefront
![execute](https://user-images.githubusercontent.com/174857/135877618-34d87e36-a3fe-422d-bce7-e9812cae9fe7.PNG)

## Expected behavior
Markdown should be limited to truly just markdown escaping any markup but at the very least taking XSS into account and stripping out any common patterns.

## Version info (please complete the following information):
 - Browser version: All.
 - Platform version: Latest.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7771 has been created

**Comment by loktar00** [comment]
I agree from the storefront you can control the escaping, however the primary issue on top of just the storefront is the JS is executed in the platform administration interface as well. 

![image](https://user-images.githubusercontent.com/174857/136236292-ed3d206b-64e1-4123-baff-c0426a1e6b3b.png)

**Comment by OlegoO** [comment]
@loktar00  
First, try to update  Core Module
https://github.com/VirtoCommerce/vc-module-core/releases/tag/3.23.0

If it's not helpful, do you have a step to reproduce the problem?

**Comment by loktar00** [comment]
No unfortunately, it's in the platform itself as shown in my screen shot above,

Steps,

1. Go to any product, open any review type/description
2. Add any JS in a `<script>`
3. save, navigate away navigate back to the description, JS executes.

**Comment by loktar00** [comment]
Yoooo..

This is still an issue just sayin.

**Comment by OlegoO** [comment]
@AlexTzykin  Could you recheck and create a bug if required

**Comment by AlexTzykin** [comment]
we added task to next sprint.
@OlegoO FYI

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-core/releases/tag/3.404.0
