### ISSUE TITLE
UX improvements for virtual catalog creation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#240]
filtration, quick actions, prevent closing.
Ability to quick add product link from search drop down matched list or automatically adding found products from filter preset
![image](https://cloud.githubusercontent.com/assets/7566324/12419660/2e5cc5f8-bec0-11e5-995f-2c1453064192.png)
![image](https://cloud.githubusercontent.com/assets/7566324/12419668/39a31ce6-bec0-11e5-9a1c-0da5c1a2e57a.png)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #33](https://github.com/VirtoCommerce/vc-module-catalog/issues/33) via [**ZenHub**](https://www.zenhub.com/)
