### ISSUE TITLE
Latest Docker package is several versions behind source - 3.89.0 vs 3.69.0

### ISSUE THREAD

**Issue by 3000** [VirtoCommerce/vc-platform#2414]
**Problem:**

The latest source code release for VirtoCommerce platform is 3.89.0 released 13 days ago, but the latest docker package published is 3.69.0-alpha in Jun.

This means developers need to build their own docker image to run the latest VirtoCommerce platform.

**Solution:**

Keep the docker package up to date

**Proposal of changes:**

Not really applicable but perhaps ensure that when a release is tagged a docker image is automatically built and pushed.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7824 has been created

**Comment by Vectorfield4** [comment]
Hi, @3000! Look 
![image](https://user-images.githubusercontent.com/47894313/141064043-d99d4216-4a68-4e66-a3dc-cfc05c72992e.png)

You can get the latest docker container tag from this link https://github.com/VirtoCommerce/vc-platform/pkgs/container/platform

Feel free to reopen if you have any problems/questions.
