### ISSUE TITLE
Contact | Security Issue

### ISSUE THREAD

**Issue by wsmi22** [VirtoCommerce/vc-platform#2424]
Dear VirtoCommerce contributors,

I've tried to contact several of you through email, but got no response.
Please get back to me at: vulnerability@whitesourcesoftware.com.
It's about security issues found in your project.

Thanks,
Miriam

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7843 has been created

**Comment by wsmi22** [comment]
Hi @mvktsk  :) 
Thanks for the quick reply! Could you give me permissions to the task?
miriam.iomin@whitesourcesoftware.com
Thanks in advance :)

**Comment by OlegoO** [comment]
@wsmi22  we received your email with attachments and our team reviewed them. I will provide feedback here

**Comment by OlegoO** [comment]
Hi @wsmi22 

Thank you for your research and step by step examples. We will plan to improve some topics in the feature.

Also, let me point that Virto Commerce Platform with Admin UI doesn't have public access and public registration. It's the back office for employees.

Usually, by our security recommendations, it's closed by a firewall and has limited access. Access is granted by the company administrator and he/she is responsible to apply the right security policy to Azure, Virto Commerce, Network, etc. 

By default, Virto Commerce doesn't have any limitations, it helps the platform bring flexibility. 

But IT Administrators should use configurations, roles with permissions to limit access to some features. For example, use the black list of file extensions, disable/force encoding of the HTML content, etc.
