### ISSUE TITLE
Setting with name Catalog.AssociationGroups is not registered

### ISSUE THREAD

**Issue by antonkondratyev** [VirtoCommerce/vc-platform#2438]
**Describe the bug**
Error while importing sample data on the first launch of the platform after building from source code.

**Steps to reproduce**
1. Clone repository and build source (vc-build compile; vc-build compress)
2. Run Platform
3. Choose sample data "Clothing and Electronics"

**Expected behavior**
Platform launch without errors.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/17160216/146349123-a4d629c2-a427-40aa-ac81-4018694a8772.png)
![image](https://user-images.githubusercontent.com/17160216/146349241-98958414-a640-4c87-80c4-ea99be1b429d.png)
![image](https://user-images.githubusercontent.com/17160216/146349357-9ca4a1d0-de3b-46f9-ac5f-5a62686b1612.png)

**Version info (please complete the following information):**
 - Browser version: opera gx 81.0.4196.61
 - Platform version: 3.99.0

**Additional context (optional)**

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7865 has been created

**Comment by DanilBayushev** [comment]
Bug fixed.
Release: https://github.com/VirtoCommerce/vc-platform/releases/tag/3.204.0
