### ISSUE TITLE
Not able to build virtocommerce in Visual Studio 2022

### ISSUE THREAD

**Issue by jaygithub2010** [VirtoCommerce/vc-platform#2444]
While building solution in VS 2022 i was getting error about node.js is not installed so i installed node.js. Now I am getting error with description npm install exited with code 1. I have also attached screenshot for detailed description. Please help me to get rid of build error.

![image](https://user-images.githubusercontent.com/24474691/149362213-1f066f08-e455-4262-acf7-86fe5c2c5e84.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7890 has been created

**Comment by jaygithub2010** [comment]
Please enable access to email jay.rgukt@yahoo.com

**Comment by Vectorfield4** [comment]
Hi, @jaygithub2010. Try to install node v12.

**Comment by jaygithub2010** [comment]
Thank you @Vectorfield4  it worked after replacing latest node.js version by v12
