### ISSUE TITLE
Default user type setting not working with Azure AD

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-platform#2447]
When I enable AzureAD and log in for the first time, the user account that gets created does not have user type set. It seems that the `DefaultUserType` setting is not being used. My AzureAD settings:
```
"AzureAd": {
        "Enabled": true,
        "AuthenticationType": "AzureAD",
        "AuthenticationCaption": "Azure Active Directory",
        "ApplicationId": "***",
        "TenantId": "***",
        "AzureAdInstance": "https://login.microsoftonline.com/",
        "DefaultUserType": "Manager",
        "UsePreferredUsername": false,
		"Priority": 0
    },
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7897 has been created

**Comment by dvvkgd** [comment]
Hi, @j-mok .
Thanks for the feedback. Very helpful remark. I submitted this case to the platform team for research and estimate.
I will inform you about the decision.

**Comment by DanilBayushev** [comment]
Hi, @j-mok .
The platform team resolved this issue.
Release: https://github.com/VirtoCommerce/vc-platform/releases/tag/3.206.0
