### ISSUE TITLE
When password login is disabled, Management UI still shows password-related components

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-platform#2448]
Some password-login-specific elements of the UI are still visible after switching to Azure AD authentication.

**Steps to reproduce**
1. Disable password login in `appsettings.json`:
```
"PasswordLogin": {
        "Enabled": false
    },
```
2. Enable Azure Active Directory:
```
"AzureAd": {
        "Enabled": true,
        ...
    },
```
3. Log into VC Manager with an AD account
4. Click the profile drop-down in the upper right corner to reveal _Change password_ entry is still there
5. Log into VC Manager as an administrator
6. Go to the Security module and select an AD user to reveal that _Change password_ button is still there

**Expected behavior**
All password-related features should be hidden both in own profile and security blade views when password login is disabled. Anything related to user credentials should be handled by Azure Active Directory. Alternatively password-manipulation components should be visible but marked with a warning when password login is disabled.

**Version info:**
 - Platform version: 3.100.0

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7898 has been created

**Comment by dvvkgd** [comment]
Hi, @j-mok .
Thanks for the feedback. Very helpful remark. I submitted this case to the platform team for research and estimate.
I will inform you about the decision.

**Comment by DanilBayushev** [comment]
Hi, @j-mok. 
Bug has been fixed.
Release https://github.com/VirtoCommerce/vc-platform/releases/tag/3.201.0
