### ISSUE TITLE
Error when running virtoCommerce platform (script injection error)

### ISSUE THREAD

**Issue by MShakerBadr** [VirtoCommerce/vc-platform#2457]
I am getting this error when running the platform for the first time 
![image](https://user-images.githubusercontent.com/37817601/151158396-30ede31e-95d4-487b-a16b-78935ea78b9c.png)

platform version : 3.26
browser  version : chrome  97.0.4692.99

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7910 has been created

**Comment by OlegoO** [comment]
@MShakerBadr , Virto Commerce build Admin SPA (based on AngularJS) automatically on startup from multiple script files in the platform and modules. Looks one of the modules doesn't load properly and crash the solution. 

Could you give more information about your solution? 

1. Did you run the runtime version of the platform or run from source code? If you start the platform from the source, you need to compile web resources.
2. Which modules (and versions) did you install? It helps our QA team to repeat the problem. You can try opening swagger UI by {your-domain}**/docs/index.html** and check the health of the platform and modules by API. 
3. Do you have custom modules? 
4. Do you see any errors in browser console? It can provide some insights about the errors.

**Comment by MShakerBadr** [comment]
@OlegoO 
1. The platform running from source code. v 3.0.0
2. 
![image](https://user-images.githubusercontent.com/37817601/151814850-989c4108-91ba-4948-96a3-70dba4bf36cd.png)
![image](https://user-images.githubusercontent.com/37817601/151814945-97584721-3706-42b8-8ada-cc631c262c48.png)
3.No, there is no custom modules.

**Comment by OlegoO** [comment]
@MShakerBadr I see that you installed Angular 1.8.2. I recommend reverting back to original packages and restart. It should resolve the problem. 

Another recommendation, install a binary version of the Virto Commerce Platform from release. Follow these steps https://virtocommerce.com/docs/vc-quickstart/

![image](https://user-images.githubusercontent.com/7639413/151932964-d5777ca0-a8ce-4b56-873b-98003b2b2c09.png)

**Comment by MShakerBadr** [comment]
@OlegoO , It is working now after changing Angular version, 
Thanks for your support.
