### ISSUE TITLE
Can't find product variations just created

### ISSUE THREAD

**Issue by karimul** [VirtoCommerce/vc-platform#2460]
**Describe the bug**
Product variation doesn't show up on search result. Manually rebuild index makes the product variation appear. Trigger by event and by timer are enabled.

**Steps to reproduce**
1. Add new product variation 
![image](https://user-images.githubusercontent.com/5180710/152267508-a38df1a9-8791-4eb6-8e9f-aac0176ee357.png)
2. Search product using graphql experience api 
`{
  products(storeId: "Electronics", productIds:["ad4ae79ffdbc4c97959139a0c387c72e"],currencyCode: "USD") {
    totalCount
    items {
      id
      name
      variations {
        id
        code
        price {
          currency
        }
        name
      }
    }
  }
}`
3. No product variation just created
![image](https://user-images.githubusercontent.com/5180710/152267751-b649a7b1-4866-433c-b69b-244f0388b0f1.png)

**Expected behavior**
product variation appear on search result without manually rebuild index because trigger by event and by timer are already enabled

**Version info (please complete the following information):**
 - Browser version: Google Chrome  97.0.4692.99
 - Platform version: 3.202.0

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7920 has been created

**Comment by DanilBayushev** [comment]
@karimul Could you please attach images of the settings you mentioned above?

**Comment by karimul** [comment]
here is the setting
![image](https://user-images.githubusercontent.com/5180710/152556351-c5d02a6d-cfce-4991-aec2-3b10f3627f31.png)
![image](https://user-images.githubusercontent.com/5180710/152556414-6e2b09a1-b076-403b-8340-253340a301d9.png)
![image](https://user-images.githubusercontent.com/5180710/152556555-3d63d601-7663-4434-aac8-97f1112af368.png)

**Comment by karimul** [comment]
Search provider: Elasticsearch

**Comment by karimul** [comment]
hello @DanilBayushev, can you reproduce the issue?

**Comment by DanilBayushev** [comment]
@karimul 
Yes, thank you for the information provided.
Bug https://virtocommerce.atlassian.net/browse/PT-6646 has been created.

**Comment by karimul** [comment]
@DanilBayushev, please inform me if this bug has been fixed and released

**Comment by DanilBayushev** [comment]
@karimul As soon as the status of the task changes, I will let you know.

**Comment by karimul** [comment]
hello @DanilBayushev, can you give an estimation of when this bug will be fixed and released?

**Comment by DanilBayushev** [comment]
Hello, @karimul. The platform team rated the priority of the bug as high. The task has been queued. I think the fix will be released by the end of March.

**Comment by DanilBayushev** [comment]
Hello, @karimul!
This issue has been resolved by the Platform Team.
Release: https://github.com/VirtoCommerce/vc-module-catalog/releases/tag/3.210.0
