### ISSUE TITLE
node-sass error when  build vc-platform solution

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-platform#2466]
I download the latest version of vc platform version 3.204,when build it ,it return errors.

```
[4/4] Building fresh packages...
[-/3] ⠐ waiting...
[2/3] ⠈ node-sass
error E:\VirtoCommerce\5.Source\vc-platform-3.204.0\src\VirtoCommerce.Platform.Web\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\VirtoCommerce\5.Source\vc-platform-3.204.0\src\VirtoCommerce.Platform.Web\node_modules\node-sass

```

my node version is v16.13.1
![image](https://user-images.githubusercontent.com/5348170/154958073-fe872c4a-ee62-46b1-aea9-e487675d1395.png)

the npm package node-sass version is "^4.14.0",it can't run at the node version v16 ,
you can see the node version support policy
https://github.com/sass/node-sass#node-version-support-policy
![image](https://user-images.githubusercontent.com/5348170/154958358-d5c17421-9c89-49c8-995d-b0237665989a.png)

so I suggest ,can you replace the  package
```
"node-sass": "^4.14.0",
```
with 
```

"sass": "^1.49.0",
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7946 has been created

**Comment by six006** [comment]
I solved the problem. just use nvm .
