### ISSUE TITLE
what doest the meaning of $(Platform)?

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-platform#2468]
I found many angularjs url is use the `$(Platform)` ，can you tell me how does it work?

for example
```
http://localhost:10645/$(Platform)/Scripts/i18n/angular/angular-locale_en.js
```
![image](https://user-images.githubusercontent.com/5348170/155128357-0721a5a2-3b94-49c4-b0db-5ddd32524ca2.png)

but some url is `http://localhost:10645/dist/app.js` 
![image](https://user-images.githubusercontent.com/5348170/155128994-e7f5f45b-d77b-4403-8de3-e6d4be9a880b.png)

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7949 has been created

**Comment by OlegoO** [comment]
Becasuse Virto Commerce Admin Portal SPA built admin UI from modules, SPA uses custom routing to access resources from platform and modules.

$(module.id) - is reserwed keyword which is used to map it to correct module folder on the server side. 

![image](https://user-images.githubusercontent.com/7639413/156133189-e06133c2-1f78-43d7-b749-88430851790d.png)

So, the $(Platform) means routing to resourse from platform\wwwroot\ folder.

The code which are handled all requests like a $(Platform) and Modules/$({ module.ModuleName }) as static files in correspond folder here:
https://github.com/VirtoCommerce/vc-platform/blob/dev/src/VirtoCommerce.Platform.Web/Startup.cs#L478-L493
