### ISSUE TITLE
Pinning blades is not working?

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#253]
Or I don'y know how and when to use it, but I read this [blogpost](http://blog.virtocommerce.com/2015/04/23/virto-commerce-2-1-may-11/) stating that
"AngularJS UI Refactoring – improvements to views and controls, **enabling pinning blades**"

And thought that this little pin has something to do with it:
![image](https://cloud.githubusercontent.com/assets/1164988/12577741/c23eab0e-c41c-11e5-8ec5-ae6b49fb33de.png)

But I can't notice it doing something? What's it used for and when?

**Comment by tatarincev** [comment]
Hi @jvdonk you right that functionality currently not implemented, But it in our plans and we definitely will implemented in next releases.

**Comment by jvdonk** [comment]
Clear, tnx!
