### ISSUE TITLE
Working With Catalog

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-platform#262]
- editing properties - "Save" button not active;
- creating property in product doesn't allow to set display name, dictionary, multilanguage, attributes;
- creating property in product doesn't allow to set target - variation;
- it would be nice to have some kind of attributes dynamic collection (predefined) in order to quicken property setup and reduce typo errors;

**Comment by tatarincev** [comment]
As I right understand you talking about product instance properties (Click Add property on product) direct instance product properties not have meta-information and can be only short text type and cannot have type and so on.

**Comment by eMazeika** [comment]
As I understand, users have no idea about "product instance properties". They just see "Properties". And they see that properties behave in different way in product UI.

**Comment by aartiomov** [comment]
What is the reason to reduce in-product property setup functionality? 
What if I want to show the product's property on storefront and it has to be displayed differently depending on the storefront language (Display Name)? 
What if I want to place the property on storefront depending on attribute? What if the product has individual variation property? Why should user go back to category management (which is not trivial task) and setup property for the whole category products in all that cases?

**Comment by aartiomov** [comment]
Editing properties "Save" button works. Didn't see the validation error on property (high contrast monitor).
