### ISSUE TITLE
Cannot Launch Storefront  Themes/B2B-store/default/snippets/customers/login-form.liquid(41,53) : error : The function customer_register_link was not found

### ISSUE THREAD

**Issue by asmitaupreti** [VirtoCommerce/vc-platform#2620]
**Describe the bug**
I am not able to launch storefront. I get that its a theme error but not matter what I do (based on my capability) I am not bale to solve it.

**Steps to reproduce**
1. Successfully installed vc-platform and is up and running in localhost:10645
2. Installed sample data clothing and electronics
3. In vc-platform frontend it shows B2B store as active default theme and has all default folder data
4. Created new user test as administrator 
5. Cloned vc-storefront changed the default store value to B2B-store changed  login credentials username: test , Password: Store123
6. Created a symlink  for cms-content  from vc-platform/src/VirtoCommerce.Platform.Web/wwwroot/cms-content( Because platform was already up and running with content) to vc-storefront/VirtoCommerce.Storefront/wwwroot/cms-content
7. Ran storefront . It throws ScriptRuntimeException: Themes/B2B-store/default/snippets/customers/login-form.liquid(41,53) : error : The function `customer_register_link` was not found.

**Expected behavior:
Storefront without error  launched

**Screenshots (optional)**

**Version info (please complete the following information):**
 - Browser version: Version 110.0.5481.177 (Official Build) (x86_64) (Google Chrome)
 - Platform version: 3 

**Additional context (optional)**
I am doing all of this is macOS.  The storefront launches in http://localhost:2083/
![Screenshot 2023-02-28 at 19 52 28](https://user-images.githubusercontent.com/19288767/221954285-92a01cd6-6d17-416e-ac45-b5434318ad84.png)

**Comment by OlegoO** [comment]
Please reinstall platform and storefront based on our steps: https://docs.virtocommerce.org/getting-started/connect-storefront-to-platform-v3/
