### ISSUE TITLE
Can't use Scrutor > 3.0.1 in a module

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-platform#2627]
**The problem**
We wanted to use [Scrutor 4.2.1](https://www.nuget.org/packages/Scrutor/4.2.1) in one of our modules but the module does not load because VC platform cannot load `Scrutor:4.0.0.0`:
```
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Scrutor, Version=4.0.0.0, Culture=neutral, PublicKeyToken=167d3117ac9a6821'. The system cannot find the file specified.
```

**Root cause**
`VirtoCommerce.Platform.Web` references Swashbuckle.AspNetCore.Filters 5.1.2 which transitively references Scrutor 3.0.1 (which in turn holds assembly `Scrutor:3.0.0.0`). That old Scrutor assembly ends up among platform's own dependencies in the root directory and prevents the newer Scrutor assembly from the module to be used.

**Expected behavior**
Provide a way to get around this limitation to Scrutor (specifically) or any 3rd party dependency (generally) version range when that dependency is also used by the VC platform itself. Or add an explicit NuGet reference to the latest Scrutor in `VirtoCommerce.Platform.Web`.

**Comment by Dan-BV** [comment]
The latest version of the platform uses Scrutor version 4.2.0
https://github.com/VirtoCommerce/vc-platform/blob/dev/src/VirtoCommerce.Platform.Web/VirtoCommerce.Platform.Web.csproj#L44
