### ISSUE TITLE
Product cloning upates

### ISSUE THREAD

**Issue by alynabriscoe** [VirtoCommerce/vc-platform#2667]
**Problem:**
Right now, it’s actually worse to clone a product in Virto than create a new one from scratch because none of the things you want to be copied actually do but it does put it in all the virtual catalogs the original item was in. This causes an issue because then you have a half-configured product in a customer-facing location.

**Solution:**
Make so a cloned product is not added to any virtual catalogs, but does include the price, rules, variations, etc of the original product.

**Alternative (optional):**
Just stopping it from being added to the virtual catalogs would be a welcome change and would at least give us the starting point of having the name and properties carried over.

**Proposal of changes:**
Cloning a product SHOULD
- Copy the product SKU but add something like -CLONED to the end
- Copy the product name :check_mark:
- Copy properties :check_mark:
- Copy prices
- Copy rules
- Copy variations
-- SKU
-- Name 
-- properties
-- prices
-- rules

Cloning a product SHOULD NOT:
- Add it to the virtual catalogs where the original item is linked (you only want to do this once the product is fully configured)

**Additional context (optional)**

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8425 has been created

**Comment by OlegoO** [comment]
Thank you for reaching out to us with your feature request. We greatly appreciate your engagement and enthusiasm for enhancing the Virto Commerce Platform.

After careful consideration, we regret to inform you that, at this time, we do not have plans to implement the requested feature in the year 2024. However, please be assured that your suggestion has been diligently recorded in our backlog. Feature requests like yours play a crucial role in shaping the evolution of our platform.

While we may not be able to accommodate this specific request immediately, the priority of features can change based on various factors, including the accumulation of similar requests or the introduction of new functionalities. Your valuable input remains on our radar, and we encourage you to continue sharing your thoughts and ideas with us.

We truly appreciate your understanding and your commitment to making Virto Commerce even better. If you have any further questions or if there's anything else we can assist you with, please feel free to let us know.

Virto Commerce is an open-source project, and we welcome contributions from our community members. If you are interested and have the capability to implement this feature, we encourage you to consider contributing to the Virto Commerce GitHub repository.
