### ISSUE TITLE
Write article how to develop new theme

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#269]
How to VirtoCommerce themes works (key principles, liquid, context, templates resolving, default(global) theme)
Theme developing process (IDE, version controls, updates)
Theme developing preventing VirtoCommerce platform  updates confilct
Static content understanding (Pages, Blogs)

https://docs.google.com/document/d/1oK-c-tTo_CgqyU9MPvwo_SbKugF1yxLmTFgcFbWB3Ag/edit#

**Comment by asvishnyakov** [comment]
Partially complete: https://github.com/VirtoCommerce/vc-default-theme/blob/dev/README.md

**Comment by Woland2k** [comment]
@asvishnyakov Great documentation! Maybe we should create article in our documentation section /docs and link it from the github page?

**Comment by asvishnyakov** [comment]
VirtoCommerce/vc-storefront#33
