### ISSUE TITLE
Dictionary items in dynamic property dropdown truncated to 20

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-platform#2702]
**Description**
In the UI, the dropdown list with dynamic property dictionary items is never longer than 20 items.

Current implementation uses the default `SearchCriteriaBase.Take` value:
https://github.com/VirtoCommerce/vc-platform/blob/54742ee0687ca194c6b87205ee3dd4fac0bbb04d/src/VirtoCommerce.Platform.Web/wwwroot/js/app/dynamicProperties/blades/propertyValue-list.js#L147-L149
https://github.com/VirtoCommerce/vc-platform/blob/54742ee0687ca194c6b87205ee3dd4fac0bbb04d/src/VirtoCommerce.Platform.Web/Controllers/Api/DynamicPropertiesController.cs#L237-L245

**Steps to reproduce**
* Create a dynamic property with >20 items
* When editing the property for an object you can see only 20 items in the dropdown list

**Expected behavior**
Any of these:
* All items are displayed
* The limit is raised to significantly higher number (100, 1000?)
* The limit is configurable
* The dropdown is replaced with some sort of advanced selector (possibly with paging) for high item numbers to avoid an unpractically long list drop (still the threshold should be higher than 20)

**Version info:**
 - Browser version: any
 - Platform version: current dev, 3.421

**Additional context (optional)**

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8452 has been created

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-platform/pull/2706

**Comment by Dan-BV** [comment]
Release https://github.com/VirtoCommerce/vc-platform/releases/download/3.424.0/VirtoCommerce.Platform.3.424.0.zip
