### ISSUE TITLE
Built-in health checks should have configurable failure statuses

### ISSUE THREAD

**Issue by j-mok** [VirtoCommerce/vc-platform#2707]
**Problem:**
`ModulesHealthChecker` is hard-coded to report failure as `Degraded` ([here ](https://github.com/VirtoCommerce/vc-platform/blob/16f7c342852edcd2dd3c2f20295b69d3e6ff4a3f/src/VirtoCommerce.Platform.Web/Infrastructure/HealthCheck/ModulesHealthChecker.cs#L34)and [here](https://github.com/VirtoCommerce/vc-platform/blob/16f7c342852edcd2dd3c2f20295b69d3e6ff4a3f/src/VirtoCommerce.Platform.Web/Startup.cs#L484)). While this is ok in some scenarios, it is not in others, including ours. We deploy the platform with a rigid set of module versions and expect all of them to load successfully before we can deem a deployment successful. A failure to load one module warrants deployment abort. In our deployment pipeline we poke the `/health` endpoint to see if it return 200 before swapping with production. But since `ModulesHealthChecker` reports `Degraded` in case of a module load error, the endpoint maps that to 200, not 503, and we're forced to parse the health report to see the status of the modules.

**Solution:**
Make failure statuses independently configurable for built-in health checks (`ModulesHealthChecker` and `CacheHealthChecker`).

**Comment by OlegoO** [comment]
@j-mok  I agree with you, health should return 503 in case of a module load error, We will fix it in coming release.

**Comment by OlegoO** [comment]
@j-mok  please review https://github.com/VirtoCommerce/vc-platform/pull/2717

**Comment by OlegoO** [comment]
Released with https://github.com/VirtoCommerce/vc-platform/releases/tag/3.433.0
