### ISSUE TITLE
GraphQL API - Unexpected response using products query of virtual catalog

### ISSUE THREAD

**Issue by karimul** [VirtoCommerce/vc-platform#2709]
**Describe the bug**
We have updated the platform version to 3.412.0, but we have an issue using GraphQL API products query when the store’s catalog is a virtual catalog (physical catalog is working properly), the response is not showing the actual data of the physical product. We have used this GraphQL query in the older platform version 3.208.0 which works fine.

**Steps to reproduce**
1. Go to 'Catalog' menu
2. Add virtual catalog 'TestVirtualCatalog'
3. Select 'TestVirtualCatalog' and add a link to physical Category or Product.
4. Go to 'Stores' menu
5. Add new store and select catalog 'TestVirtualCatalog'
6. Query products using GraphQL API

**Expected behavior**
The GraphQL API response is showing the actual data of the physical product.

**Screenshots (optional)**
Screenshots of the GraphQL responses using the same product:
Store using physical catalog
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/0b1fc90e-0f07-4cd1-987c-90d0b54f77a3)

Store using virtual catalog (issue)
isBuyable: false (should be true)
availableQuantity: 0 (should be 98)
price.list.amount: 0 (should be 1100)
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/b399102a-1e82-4913-ad0a-f99569e25dd8)

**Version info (please complete the following information):**
 - Browser version: Google Chrome 117.0.5938.150 (Official Build) (64-bit)
 - Platform version: 3.412.0

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8460 has been created

**Comment by AlexTzykin** [comment]
Hi, @karimul! Could you describe the settings in the store where the virtual catalog is used? Which fulfillment centers are selected? Any price list assignments for this store?

**Comment by karimul** [comment]
@AlexTzykin I used the default settings. There is no changes I did.
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/c1dbbbdb-b03c-4047-8793-1f0b3eaec808)
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/77f7afbe-e69e-4264-abbb-4a36bd10e324)

I didn't select any fulfillment center
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/dc7a23b6-1c95-445d-8b55-db49b2aa8b58)

The distinction I've observed between physical and virtual products lies in the pricing information.
the price in physical product is shown
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/47e9537c-f87e-425e-97c8-922f74ee382f)

the price in virtual product is not available.
![image](https://github.com/VirtoCommerce/vc-platform/assets/5180710/dbd5c2ba-59f1-41a7-ad62-3f3ebacabcc8)

**Comment by AlexTzykin** [comment]
@karimul need to select the fulfillment center in the new store (where the virtual catalog is selected)  to see the availability of product.
You also need to create a new pricelist assignment linked to a new store or virtual catalog.

**Comment by karimul** [comment]
@AlexTzykin ok thanks
