### ISSUE TITLE
Menu is still being placed above the top of the screen

### ISSUE THREAD

**Issue by wsimon** [VirtoCommerce/vc-platform#2723]
**Describe the bug**
Originally reported this issue with https://github.com/VirtoCommerce/vc-platform/issues/2704.

We updated to the latest release and though it has improved, we are still seeing the original issue even though the menu has a scrollbar. We click this select attribute link and the menu opens but the top of it is off screen and now it doesn't open next to the link where we click but further up on the screen.

![image](https://github.com/VirtoCommerce/vc-platform/assets/1576951/69745e79-37a4-4a58-8e87-b4d128dc6715)

**Steps to reproduce**
For any place where that left-click-menu is being used, configure the items in it to have a lot and/or shrink your screen/window down.
Click to open the menu
The top of the menu is above the top of the screen/window so that the top menu items are not selectable.

**Expected behavior**
I would expect the top of the menu to be on screen

**Version info (please complete the following information):**
Browser version: latest Chrome on desktop 
Platform version: 3.431.0

**Additional context (optional)**
I wonder if this javascript is going to have to change, because this is where it calculates what to set the top property of the menu. At the very least, it should probably do a Math.max(0, top) but it might need more to take into account that the height of the menu is no longer greater than 70% of the viewport height so that it is properly aligned with the element that opened it:
https://github.com/VirtoCommerce/vc-platform/blob/dev/src/VirtoCommerce.Platform.Web/wwwroot/js/common/directives/left-click-menu.js#L53

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8476 has been created

**Comment by OlegoO** [comment]
@wsimon  please review https://github.com/VirtoCommerce/vc-platform/pull/2728 this PR should fix the problem.
 
![image](https://github.com/VirtoCommerce/vc-platform/assets/7639413/d6eedd0f-6467-4c27-bac4-7a56a46ef0af)

**Comment by wsimon** [comment]
@OlegoO Thanks! I tested out that change and it looks like it fixes the issue. Looks great!
