### ISSUE TITLE
update  to Full stack web UI with Blazor 

### ISSUE THREAD

**Issue by ghd258** [VirtoCommerce/vc-platform#2729]
update  to Full stack web UI with Blazor

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8486 has been created

**Comment by OlegoO** [comment]
Thank you for suggestion. At this moment, we have option to build BackOffice on AngularJS and [VC Shell on Vue](https://docs.virtocommerce.org/new/dev_docs/custom-apps-development/vc-shell/vc-shell-overview/)

**Comment by OlegoO** [comment]
After careful consideration, we regret to inform you that, at this time, we do not have plans to implement the requested feature in the year 2024. However, please be assured that your suggestion has been diligently recorded in our backlog. Feature requests like yours play a crucial role in shaping the evolution of our platform.

While we may not be able to accommodate this specific request immediately, the priority of features can change based on various factors, including the accumulation of similar requests or the introduction of new functionalities. Your valuable input remains on our radar, and we encourage you to continue sharing your thoughts and ideas with us.

We truly appreciate your understanding and your commitment to making Virto Commerce even better. If you have any further questions or if there's anything else we can assist you with, please feel free to let us know.

If you are interested and can implement this feature, we encourage you to consider contributing to the Virto Commerce GitHub repository.
