### ISSUE TITLE
Latest 3.414.19 version of the platform installs additional module after login

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#2744]
**Describe the bug**
When installing platform using vc-build it fails to install VirtoCommerce.SeqLog:3.200.0 module which then gets installed after the login requiring platform to restart. We should include any required modules out of the box.

![image](https://github.com/VirtoCommerce/vc-platform/assets/1566470/f5aa1350-e556-4e44-81e1-26e11c4b77b0)

**Expected behavior**
Should not automatically install any additional modules.

**Version info (please complete the following information):**
 - Platform version: 3.414.19

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8514 has been created

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-platform/pull/2745

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-platform/releases/tag/3.801.0. Delivered into Stable 7 and Stale 8 releases as well.
