### ISSUE TITLE
Manager Drag&Drop (ui-sortable) UI redesign

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#292]
Need to define a special element to serve as a symbol for the Drag and drop area
And refactor everywhere in manager where we use drag&drop functionality
Sample: http://codepen.io/thgreasi/pen/ihAyr

**Comment by asvishnyakov** [comment]
It's funny (and gorgeous) what we already have this functionality, we just need add css styles. Compare:
![screenshot 42](https://cloud.githubusercontent.com/assets/6369252/23582132/78167f90-0145-11e7-95a5-aabf8f54fe8e.png)
![screenshot 41](https://cloud.githubusercontent.com/assets/6369252/23582133/7af99382-0145-11e7-91b1-19f081bf89b1.png)
