### ISSUE TITLE
Redesign left menu for better UX

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#297]
Left menu needs to be smarter with ability to add most commonly used items/modules. For example if I work with a catalog module a lot, I should be able to add the menu choice for catalogs in there so it can be opened in one click instead of 2 (Browse -> Catalogs). 

Here is an example of improved left menu, it needs to be more narrow and include direct access to modules:

<img width="109" alt="screen shot 2016-07-20 at 12 01 28 pm" src="https://cloud.githubusercontent.com/assets/1566470/16999217/bcf2338e-4e71-11e6-957c-2d0fa356356d.png">

**Comment by asvishnyakov** [comment]
Closed with fd0ce1ab0ec5817877c993a51648ddeb65b257e7
