### ISSUE TITLE
Marketing promotions display hard coded stubs for shipment reward

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#298]
![image](https://cloud.githubusercontent.com/assets/7566324/13196088/6079290c-d7cd-11e5-8b3a-e100eda34146.png)

**Comment by eMazeika** [comment]
IShippingMethodsService.GetAllShippingMethods() isn't available in API. Could AllShippingMethods property be added to Promotion class?

**Comment by tatarincev** [comment]
For getting all shipping methods need to use already exist api api/stores/{store}. resulting store contains all available shipping methods.
