### ISSUE TITLE
Min/Max order quantity not enforced

### ISSUE THREAD

**Issue by daveharnett** [VirtoCommerce/vc-platform#299]
While Products have got Min/Max quantity fields on the back end, these limits are not enforced on the front end. There is no indication that a limit has been exceeded except a generic "Ooops! An error is occured!" message at the checkout.
![capture](https://cloud.githubusercontent.com/assets/1800996/13226858/94be2b6c-d98b-11e5-9840-67fb66c5f113.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1800996/13226859/94d42494-d98b-11e5-8505-d8e9fa29ee9a.PNG)

**Comment by Andrew-Orlov** [comment]
Product properties `MinQuantity` and `MaxQuantity` are unused on storefront for now. A more correct way is using `Inventory`.
