### ISSUE TITLE
Different tax type per store/country

### ISSUE THREAD

**Issue by daveharnett** [VirtoCommerce/vc-platform#300]
It should be possible for a product to have a different tax type in different countries.

**Comment by Woland2k** [comment]
Can you provide a use case for why this is needed? Why can't you use the same tax type and simply interpret it different in another store?

As a workaround you can create another property called TaxTypeUS and set to type used for US.

**Comment by daveharnett** [comment]
There are six different rates of sales tax in Ireland, and three in the UK. That means that to describe all possible permutations _just for two countries_ you would need 18 distinct tax types:

0%IE_0%UK
0%IE_5%UK
0%IE_20%UK
4.8%IE_0%UK
4.8%IE_5%UK
etc...

If you were also selling to France (with 5 different rates), you now need 18*5=90 different tax types to cover every possible combination. For a store selling to 50 US states or the whole Eurozone, this would get really crazy.

Your workaround makes sense, until/unless this becomes a priority.

**Comment by Woland2k** [comment]
Tax type for product is more like a tax category, for instance tax category can be "electronics", which then you can define different taxation for depending on the jurisdiction. That is defined inside the tax management as supposed to product. Product still an electronics tax category and won't depend on the jurisdiction it is sold at.

If you taxation becomes complex, I would suggest using 3rd party service like avalara (which we provide integration with).

**Comment by 5309** [comment]
Currently, we highly recommend to use specific external services or develop custom modules for resolving particular specific cases.
