### ISSUE TITLE
Blog/Article Workflow

### ISSUE THREAD

**Issue by gerfen** [VirtoCommerce/vc-platform#310]
We have a need to support a workflow for publishing Blog articles.  We're more than happy to assist with the development of this feature.

Our high-level requirements are as follows:

**Based on assigned roles**
- Contributor
-  Editor

**Articles**
- Have defined workflow state:
  - Draft
  - Pending
  - Published
  - Scheduled
  - Rejected
  -  Archived
- Article metadata
  - Author
  - Published date
  - Excerpt
  - Image
  - Title
- Can have 0 to N tags
- Can have 0 to N categories

**Collections**
- Need to be able to define a collection of articles for efficient display on a page
  - For example "featured" articles on the home page

**Related Articles**
- Need to be able to associate related articles to one another

**Related Products**
- Need to be able to associate related products to an article

**Workflow**
- A contributor creates an article in the "draft" state
  - When they have completed the article, they move it to the "pending" state.
- An editor reviews the article
  - if approved, the article is given a publication date and placed in the "scheduled" state.
  - An article can be published immediately or scheduled for publication at a later date.
  - Articles that are rejected are placed back into the "rejected" state and the contributor is informed.
    - Need a mechanism to indicate what needs to be addressed.
- A job is used to enumerate the "scheduled" articles and based on the publication date moves them to the "published" state so that they can appear on the web site.

**UI Customization**
- Ability to change Blog to another name in the Admin UI, i.e. "Articles"

**Personalization**
- Eventually we will want to be able to display featured articles to a site visitor based on demographic data.

**Comment by tatarincev** [comment]
Hi @gerfen, almost all your requirements for the most part related to the management UI in VC manager (writing article, publishing, approving etc) and can be included to platform within CMS module. We can write more detailed realization specification for your feature and can discuss it but first we should make some CMS module UI redesign, because in current view it not ready for extensions. We have plans to do it in next sprint and we definitely consider your requirements.

**Comment by gerfen** [comment]
@tatarincev - thank you!  Please let me know how my team can be of assistance with the implementation of this feature.

**Comment by gerfen** [comment]
@tatarincev - I updated my original issue comment to include "related articles" and "related products".  I meant to include those and forgot.

**Comment by tatarincev** [comment]
This feature request has been added to the internal product backlog.
