### ISSUE TITLE
Liquid View Engine doesn't display informative error when view is not found

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#328]
Should display error using standard asp.net approach showing which directories engines tried to locate the view. The implementation is quite simple and requires that:

_themeEngine.ResolveTemplatePath(viewName) 

method return string[] array of paths view was looked at if view file can't be located. That collection then needs to be fed into ViewEngineResult.

**Comment by tatarincev** [comment]
Already fixed in the new storefront version.
![image](https://user-images.githubusercontent.com/7566324/71468755-d2688480-27cf-11ea-88cb-c1e15ef68009.png)
