### ISSUE TITLE
fail to paste category to catalog root

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#329]
exceptionMessage: "An error occurred while updating the entries. See the inner exception for details.
↵An error occurred while updating the entries. See the inner exception for details.
↵The UPDATE statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_dbo.Category_dbo.Category_ParentCategoryId". The conflict occurred in database "VirtoCommerce2", table "dbo.Category", column 'Id'.
↵The statement has been terminated."

**Comment by Andrew-Orlov** [comment]
Already fixed.
