### ISSUE TITLE
Add a Web API or controller action to expose liquid templates as partial views.

### ISSUE THREAD

**Issue by gerfen** [VirtoCommerce/vc-platform#333]
This allows for integrating other MVC applications like forums with VirtoCommerce by sharing themed assets like headers, footers, blog articles and pages.  Ideally the action would take 'templateName' and 'themeName' as parameters.  The theme should default to the theme of the default store if the theme name is not supplied.

The integration in the integrating application could occur through AJAX calls or by making web calls from a custom controller in the integrating application.

**Comment by tatarincev** [comment]
This API will be possible to realize only at the storefront  level.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
