### ISSUE TITLE
Link List in main-menu bar only works with single word link titles

### ISSUE THREAD

**Issue by JamesNCLynch** [VirtoCommerce/vc-platform#346]
Create drop-down menus in the main-menu link list under Browse -> Content will not work if the title is more than one word. Here are some examples from the stock Electronics store.

Drop down menu named "Televisions":
![image](https://cloud.githubusercontent.com/assets/17432646/13709120/29468690-e7aa-11e5-9154-3f7617f480d4.png)

Drop down menu named "All Televisions":
![image](https://cloud.githubusercontent.com/assets/17432646/13709099/0f81a6fe-e7aa-11e5-9947-94ae540e2498.png)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.0.2
