### ISSUE TITLE
import catalog with tab seperator dont work

### ISSUE THREAD

**Issue by pierresetteskog** [VirtoCommerce/vc-platform#352]
The model binding dont seems to work
the raw url is like this but delimiter is null in method GetMappingConfiguration
/api/catalog/import/mappingconfiguration?delimiter=%09&fileUrl=tmp%+ss16+import+10feb16_small.csv

![image](https://cloud.githubusercontent.com/assets/4455363/13814093/49db445c-eb85-11e5-83a8-05e32da04405.png)

**Comment by aartiomov** [comment]
Asp.net doesn't pass 'Tab' and 'Space' correctly for some reason. We'll check for a solution and fix it.
Current workaround would be to replace Tab -> ';' in the import file and use 'Semicolon' delimiter during import process.

**Comment by OlegoO** [comment]
CSV Import in Catalog module is obsolete.

Use a new module
https://github.com/VirtoCommerce/vc-module-catalog-csv-import
