### ISSUE TITLE
Wishlist implementation

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#362]
Functional requirements:
* Provide possibility to adding selected product or variation in to wishlist. Only from product detail view and for  logged in user. System must inform to user what product successfully added in to the user wishlist
* User must access to  personal wishlist only from self cabinet. (new tab 'Whishlist')
* Whishlist should represent for user list of products with images and descriptions (without prices and quantities), similar as it done for order items in cabinet.
* User can do quick navigation  to product detail from whishshlist product list
* User can remove selected product from current wishlist

Nonfunctional requirements:
* Whishlist should use platform Cart API for store data (named shopping cart)
* Need to add some new API to storefront for serve wishlist UI  with next methods

`ApiWishlistController.cs`
  - GET: storefrontapi/wishlist
  - POST: storefrontapi/wishlist/items?id=...
  - DELETE: storefrontapi/wishlist/items?id=...
* Use current `CartBuilder`  for all wishlist operations
* Representing a wishlist  in the LIQUID model is not necessary

**Comment by miguelhasse** [comment]
When is this feature expected? Shouldn't a Wishlist be one of multiple kinds of item list associated with a user?

**Comment by Woland2k** [comment]
This is actually possible with existing API, as single user can have multiple shopping carts (named), so for instance you can create a named cart "wishlist". We will be adding that to our sample store.

**Comment by miguelhasse** [comment]
This issue is related to #217 ...the named cart makes all the sense!

**Comment by tatarincev** [comment]
- Add to the star icon a tooltip with next text  `Add to your wishlist`

**Comment by tatarincev** [comment]
New Lists wireframe
![image](https://user-images.githubusercontent.com/7566324/28361239-79a91c16-6c78-11e7-9a58-736caf3f4101.png)

**Comment by Woland2k** [comment]
- need ability to create new lists when one doesn't exist
- in the wishlist entry, add button to add item in the wishlist to shopping cart
extra advanced:
- allow lists to be private or public with ability to send link to a public list to 3rd party

**Comment by tatarincev** [comment]
- Need to fix horizontal separator 
![image](https://user-images.githubusercontent.com/7566324/28490281-8b38126a-6ed6-11e7-90bf-0e5c61609aa2.png)
See a how it looking in add to cart popup

- All text messages must be localized from resources
- Need to find better way to display information what item already exist in list and also need to change style for list selection border
![image](https://user-images.githubusercontent.com/7566324/28490287-bf01c99c-6ed6-11e7-86fa-15bc723220d6.png)
- Make better animation for note 'added  to cart' in list tab
- Display product prices in list 
- Fix layout in small resolutions
![image](https://user-images.githubusercontent.com/7566324/28490316-8a23049c-6ed7-11e7-8473-c5f0ea8798d1.png)

**Comment by tatarincev** [comment]
Why not use code for price from this https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.Storefront/App_Data/Themes/default/assets/js/common-components/lineItems.tpl.liquid#L20
![image](https://user-images.githubusercontent.com/7566324/28533551-cf7d88f6-709d-11e7-8b13-74fdfe4a5904.png)

**Comment by tatarincev** [comment]
Evaluation for disabling  `Add to list` button must  be on client side through ajax call. Because when FPC ( full page cache) this  wont work properly.

**Comment by tatarincev** [comment]
This issue cannot be close until accessibility  for "Add to list" action is done.

**Comment by vkrashenko** [comment]
[disabling Add to list button | commit](https://github.com/VirtoCommerce/vc-storefront/commit/4a0313a75f0332fea99a4a18b826dc249093f355)

**Comment by tatarincev** [comment]
Already in production
