### ISSUE TITLE
Use LibLog instead of Common.Logging

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#382]
Ever considered LibLog in favor of Common.Logging?

I'm looking into the VirtoCommerce Platform capabilities and realized that when VirtoCommerce used LibLog instead of Common.Logging the logging flexibility of the platform would improve. I could more easily use Serilog instead of NLog.(Ever looked into [Serilog](http://serilog.net/)? Great stuff!)

See for example this discussing when HangFire(also used in VirtoCommerce) moved to LibLog:

https://discuss.hangfire.io/t/move-away-from-common-logging-library/378

and the resulting logging configuration for HangFire because of LibLog:

http://docs.hangfire.io/en/latest/configuration/configuring-logging.html

**Comment by tatarincev** [comment]
Thanks @jvdonk, LibLog looks more prospectively that old man Common.Logging. We schedule migration to this abstraction.

**Comment by tatarincev** [comment]
No longer relevant for the new platform 3.0.0 version
