### ISSUE TITLE
CORS support in platform 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#383]
https://msdn.microsoft.com/en-us/library/owin.corsextensions.usecors(v=vs.113).aspx
you just need to reference the Owin CORS module and make it configurable with a domain list from your settings page or web.config

**Comment by attilah** [comment]
As an out of box option providing a host/domain name/ip address list on the settings page dedicated to CORS would be a good start.

For advanced scenarios a Startup Module extension point can be more useful to make the setup of CorsOptions possible from code.

Another option would be for such modules the supporting C# scripts by using Roslyn.
