### ISSUE TITLE
Discount/Promotion improvements

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#387]
Reintroduce priority and exclusivity for promotions so multiple discounts can be applied in correct order. Exclusivity should be used to prevent other promotions to be applied when the exclusive promotion is applied.

**Comment by ArvidBauters** [comment]
From discussion with @WimVergouwe : 
We are currently also looking into the possibility of multiple discounts. On a previous project (not in Virto) we created a structure with promotion folders which have a combination type. This combination type can be any of these 4 options:
- Largest Adjustment : Select the promotion that benefits the customer the most
- Smallest Adjustment : Select the promotion that benefits the customer the least
- First in Sort Order: Select the first promotion which applies.
- Accumulate: Select all promotions in the group which are valid in the current context and apply all rewards.

Is working with groups something you are considering?

**Comment by tatarincev** [comment]
Yes, first three policies are looking good and even may be easily implemented. But the fourth is the most difficult, because with the composition of the rewards can affect the other promotion conditions. If you have some experience with it, please share to us we will appreciate it.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-marketing #7](https://github.com/VirtoCommerce/vc-module-marketing/issues/7) via [**ZenHub**](https://www.zenhub.com/)
