### ISSUE TITLE
MultiValue Dictionary propert export to CSV is broken

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#394]
I have a product which has a multivalue dictionary multilanguage property in a catalog where English is the default language.

In the exported CSV I saw only 1 value in the Features column and that one value was a German value  of the first property value.

It is in the latest dev (2.10)

**Comment by tatarincev** [comment]
CSV catalog export currently not supported exports products with multi-values or multi-language properties because its cause not trivial CSV resulting  columns. In you case exported  only one value with only one last language.  Of course it should be default language value, we definitely fix it.

**Comment by attilah** [comment]
Having the dictionary based multi values in ONE column with comma separated in the default language, I think is fine. Don't forget to quote the individual values, since the value itself can also contain a comma ;-)

On the counterpart the import procedure must do the reverse. Split on comma and match the default store language version of the defined dictionary.

**Comment by tatarincev** [comment]
yes I agree its solve problem with "boxing" multi-value in one column

**Comment by tatarincev** [comment]
but leave problem with languages? Generate column for language suffix?

**Comment by attilah** [comment]
I don't know how the export of multi valued, dictionary properties happen, when you export the full system, not just a product.

I assume that a store has a default language, that is already imported when someone importing products.
I also assume that the multi valued dictionary properties are also imported at that phase.

Since I miss a "handle" or "id" property for each dictionary value (which would be REALLY USEFUL) we must stick to the default language and during import match upon that.

Once we have additional data for EACH dictionary entry available (I really like to add properties to dictionary items) then we can match on that "handle" or "id" column and exporting that is suffice.

**Comment by tatarincev** [comment]
Well, I have realized that it is impossible to deploy these complex structure into a linear CSV and not loose something. And I think that no one needs. For migrate data between two VC instances used platform import/export serialized all modules data to json. For migrate to other system anyway you will use some other special format. CSV will use only for simple trivial cases as shopify catalog export for example or other simple catalog structure.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
