### ISSUE TITLE
Auto re-size for uploaded images

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#408]
Need create service (module) which will be automatically generate multiple images with different resolutions depending of global or individual settings.
Russian specification:
https://docs.google.com/document/d/1maSCXr6NL84ExAEH56BNNnthm8H9MmxkKzf1qe9FRKE/edit

**Comment by framemytv** [comment]
YES!  This would be very helpful.  I wish GitHub had a "Like"  or Vote feature for items in the issues list.
