### ISSUE TITLE
Storefront add support multilingual  multivalue dictionary properties

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#413]
Liquid usage:
product.metaFields.productFeature -> is an array with dict value objects.
for accessors: product.metaFields.productFeature.dictValueCamelCased === product.metaFields.productFeature["dict-value-camel-cased"] === product.metaFields.productFeature[0]
the dict value object can have the identifier, order, value properties

**Comment by miguelhasse** [comment]
Why not consider using database stored localization resources... I have a sample at https://github.com/miguelhasse/FrameworkExtensions/tree/master/samples/Resources/WebTestApp

**Comment by ksavosteev** [comment]
in Liquid: array of localized strings - product.metafields.properties.propertyName

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-storefront #32](https://github.com/VirtoCommerce/vc-storefront/issues/32) via [**ZenHub**](https://www.zenhub.com/)
