### ISSUE TITLE
for the [https://github.com/VirtoCommerce/vc-modules], when i compile and run...1 module is missing...the ShipStation module is not showing up in [settings]. is the module.cs defined correctly???

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-platform#425]
for the [https://github.com/VirtoCommerce/vc-modules], when i compile and run...1 module is missing...the ShipStation module is not showing up in [settings]. is the module.cs defined correctly???

**Comment by OlegoO** [comment]
We have fixed https://github.com/VirtoCommerce/vc-modules/blob/master/modules.json
Update to latest release.
