### ISSUE TITLE
Demo store doesn't have theme initialize for electronics

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#447]
There is not theme specified for electronics store when in demo. It uses default theme which is taken from storefront. However that makes it hard to demo theme functionality like changing styles, presets and so on. Need to figure out an efficient way to enable this.

**Comment by tatarincev** [comment]
I've added some overridden theme templates and settings on our demo. It enough?

**Comment by Woland2k** [comment]
We need more settings on demo config file, otherwise it looks like magic

**Comment by tatarincev** [comment]
Now all themes for each store contain all cms content and  there is no more any magic
