### ISSUE TITLE
sort for the orders screen DOES NOT WORK.

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-platform#449]
![b7_pageandsort](https://cloud.githubusercontent.com/assets/73307/15271253/99d497d6-1a0d-11e6-8508-56ebd287950b.png)

1.) The sort for the orders screen DOES NOT WORK.
2.) can the paging be done on the server (is this a setting) ==> for production system, where you start having 100,000 ordres, this has to be pull and page form server.
3.) Can we have a filter on the screen based on [Status] ==> we do not need to see "COMPLETED" orders, when the merchant has already fulfilled the order.

**Comment by tatarincev** [comment]
1. Server side sorting will be added its just omission.
2. Order paging done in server side why you decide that it is not working?
3. Order advanced filtration similar to as made in catalog will be done little later.

**Comment by alexdoan102** [comment]
#2 works (sorry)
#1 and #3 is needed urgently. ==> customers need to sort and filter on STATUS asap. thx!

**Comment by jvdonk** [comment]
Same problem with Customer grid.

Problem lies in **VirtoCommerce.Platform.Core/Common/IQueryableExtensions.cs** in the **ThenBySortInfos:** method

```
public static IOrderedQueryable<T> ThenBySortInfos<T>(this IOrderedQueryable<T> source, SortInfo[] sortInfos) {
            var retVal = source;
            if (sortInfos.IsNullOrEmpty()) {
                foreach (var sortInfo in sortInfos) {
                    if (sortInfo.SortDirection == SortDirection.Descending) {
                        retVal = retVal.ThenByDescending(sortInfo.SortColumn);
                    } else {
                        retVal = retVal.ThenBy(sortInfo.SortColumn);
                    }
                }
            }
            return retVal;
        }
```

The NullOrEmptyCheck
```
if (sortInfos.IsNullOrEmpty()) {
```

needs to be inverted:
```
if (!sortInfos.IsNullOrEmpty()) {
```

It's ignoring the other sortinfos now :)

**Comment by asvishnyakov** [comment]
#1, #3 - already done. ThenBySortInfos - fixed.
