### ISSUE TITLE
cannot create new user / register new user ==> get weird supplier null error

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-platform#452]
cannot create new user / register new user ==> get weird supplier null error
 ==> this supplier NULL error happens during orderCreate as well.
     ==> something is really wrong here...MAJOR BUG ==> cannot create new user and other parts of the system getting Supplier Null error as well.

![b9_suppliererror](https://cloud.githubusercontent.com/assets/73307/15271518/a6bb9a4e-1a1c-11e6-9934-39a41c038f25.png)

**Comment by tatarincev** [comment]
'Supplier' is type from demo module  [MemberExtensionSampleModule](https://github.com/VirtoCommerce/vc-modules/tree/master/PLATFORM/Modules/Integration/MemberExtensionSampleModule).  Probably you before it installed and not removed correctly.

**Comment by alexdoan102** [comment]
![b11_migrationextendmembers](https://cloud.githubusercontent.com/assets/73307/15292108/78074138-1b4f-11e6-9ba4-145a3f1bedec.png)

I had the module enable, before the database was created. ==> brand new install.
 ==> i tested again with blank database ==> how come these tables are not created?
the DbMigations is NOT WORKING.  the [dbo.Supplier] table is not created and teh [dbo.Contact2] is not created.  ==> I am testing this module, so i can understand how to extend the domain for other stuff.
Please advise, on why this module is not running the dbmigrations.

**Comment by Andrew-Orlov** [comment]
How to reproduce this issue?

**Comment by tatarincev** [comment]
Unable to reproduce on the new platform version
