### ISSUE TITLE
Page count is wrong in Management interface for store

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#465]
As you see on the image the page count is 0, since in the root folder I've no pages, but I've a Home folder which contains 3 pages. So the 0 count is misleading IMHO.

![image](https://cloud.githubusercontent.com/assets/230432/15455979/38505bc4-2063-11e6-8510-94e8de7323ad.png)

**Comment by megafreeman** [comment]
There are Pages folder and Blogs subfolder, so if we will count files in all subfolders, the result value will be mixed with just pages and blogs's pages.

**Comment by eMazeika** [comment]
@OlegoO any idea on how to quickfix this high priority task?

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-module-content/releases/edit/v2.13.8
