### ISSUE TITLE
routing for pages with permalink fails with 404

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#466]
If I'm defining a permalink for a localized page with value of ~/uber-uns in de-DE local for about-us page and updating the link list to point to ~/uber-uns I'm unable to navigate there.

You can repro it on the Electronics demo store.

**Comment by attilah** [comment]
When can I expect a fix for this?
When is 2.11 planned to get released?

**Comment by tatarincev** [comment]
try to this permalink =uber-uns without leading tilda and slash
29 Май 2016 г. 3:14 пользователь "Attila Hajdrik" <notifications@github.com>
написал:

**Comment by attilah** [comment]
that works, but we both know that it is not how it supposed to work ;-) regarding other parts of the system.

**Comment by tatarincev** [comment]
Need to add underlying descriptions to dynamic properties
