### ISSUE TITLE
Deleting assets return 414 when too many elements are selected

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#474]
I receive  "HTTP/1.1 414 Request-URI Too Long" since this operation is putting asset urls into querystring (why?).

**Comment by tatarincev** [comment]
We try to build our REST API regarding on Martin Fowler recommendation http://martinfowler.com/articles/richardsonMaturityModel.html. 
and we  use for delete operation HTTP method  DELETE but its not allows use body in request that why we pass all identifiers in query string

**Comment by attilah** [comment]
Ok, I understand this, then delete the items with multiple calls. 414 is not acceptable. Also I assume, that if I check the "select all" checkbox, it selected ALL items, not just the ones on the current page visible?

**Comment by OlegoO** [comment]
I offer to use custom VERB X-DELETE

**Comment by tatarincev** [comment]
Bulk operations are implemented by another way to passing queries with selection conditions along with the action. 
Here the example https://github.com/VirtoCommerce/vc-module-customer/blob/dev/VirtoCommerce.CustomerModule.Web/Controllers/Api/CustomerModuleController.cs#L191
