### ISSUE TITLE
Common way to handle API errors in manager UI

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#475]
Connecting to #474 I noticed that the error message is overlapping with the blade close icon, and if the error once occurred, after successful delete operations it stays there. It is true for all blades I think.

**Comment by tatarincev** [comment]
Main problem to make common way for http error handling and its displaying  - is to determine the initiating http request blade. If this problem will be solved we can use angular interceptors to build common way for this issue.
Probably solutions:
1. Add to each http request special headers with blade Id.

**Comment by attilah** [comment]
I think we should separate this kind of error handling.

1. Devmode: if the site is in development mode forward every possible detail and show it to the user. Stacktrace, http request, etc.
2. Prod mode: show a user friendly error and some correlation id if the user wants to follow up in the issue with the devs.

In both cases having something detailed logging like what ELMAH did back in the days would be useful.

Just my 2 cents.

**Comment by tatarincev** [comment]
Yes all agree with all, that's mean we should change error display behavior to something other (instead of show error in blade header). If it will be  like special popup or UI element that's will be easy to do it by common way in one place.

**Comment by attilah** [comment]
Also what I did not mention. We've platform admin and storefront. Both needs some kind of this modification.

I think that a similar to persistent notifications what you already have can help finding such erros, but don't build an AppInsight framework into VC ;-)

For the user friendly messages long time shown, dismissable toast can be good from UX perspective.
For the dev friendly a modal will do fine I think.

**Comment by tatarincev** [comment]
Storefront already have built'in script  error display, http://docs.virtocommerce.com/display/vc2devguide/Configuring+error+logging+and+notifications

**Comment by tatarincev** [comment]
If happened module initialization error need to display this error by standard error way.
