### ISSUE TITLE
SEO duplicate validator ignores the language portion of SEO data

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#476]
for hu-HU I've "energy1", when I edit de-DE and try to set "energy1" it gives duplicate error.

![image](https://cloud.githubusercontent.com/assets/230432/15638007/5eb1d794-25e9-11e6-82ae-da92ecff5b81.png)

**Comment by eMazeika** [comment]
I believe there was a reason to exclude language from duplicates detection algorithm. However, "Duplicate URL found" can be considered as a warning and you can still save such values.

@tatarincev , any details on such behaviour?
