### ISSUE TITLE
Create sample storefront template with hierarchical category tree

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#478]
Dhiren-K @Dhiren-K 
we want to give demo so in that categories should be displayed in multi level hierarchical way

**Comment by Dhiren-K** [comment]
ok

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-storefront #38](https://github.com/VirtoCommerce/vc-storefront/issues/38) via [**ZenHub**](https://www.zenhub.com/)
