### ISSUE TITLE
Renaming folder in theme with Azure Blob Storage Provider throws 500

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#480]
If Azure Blog does not support it, a friendly message would be helpful instead of this:

  "message": "An error has occurred.",
  "exceptionMessage": "The method or operation is not implemented.",
  "exceptionType": "System.NotImplementedException",
  "stackTrace": "   at VirtoCommerce.Content.Data.Services.AzureContentBlobStorageProvider.MoveContent(String oldUrl, String newUrl) in C:\Workspaces\Private\vc-community\PLATFORM\Modules\CMS\VirtoCommerce.Content.Data\Services\AzureContentBlobStorageProvider.cs:line 26

I think that if this is a valid scenario that given operations are not possible by different providers, it either should be implemented as a copy plus delete operation OR a more UX friendly solution would be if the providers expose a Capability property which can be streamed down to the admin and it can hide the rename option for the given provider.

**Comment by asvishnyakov** [comment]
+ same error for files too on latest (2.13.17) platform

**Comment by n2pro** [comment]
duplicate [this issue](https://github.com/VirtoCommerce/vc-module-content/issues/2)

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.13.20
