### ISSUE TITLE
avalara tax rate is not updated on checkout step

### ISSUE THREAD

**Issue by alexdoan102** [VirtoCommerce/vc-platform#488]
after avalara gets the rate, the [Tax] amount on the checkout page is not UPDATED (still says "0") .
please see screenshot
![avalaranoupdatecheckout](https://cloud.githubusercontent.com/assets/73307/15724867/12773100-2817-11e6-8054-a38c6a519b6f.png)

**Comment by tatarincev** [comment]
Try to latest storefront version from dev branch
