### ISSUE TITLE
Getting started wizard

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#492]
Need to help customer to get started with virto commerce, good example is attached (displayed everytime you login
<img width="698" alt="screen shot 2016-06-03 at 11 52 18 am" src="https://cloud.githubusercontent.com/assets/1566470/15789572/d8865734-2981-11e6-8389-7762931b89bb.png">
)

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
