### ISSUE TITLE
Support module route specification

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#501]
The idea is to give modules a feature to define their own routes.

Problem: Currently is that Storefront registers the routes for the "well known" but now separated modules. Modules can't register their routes, since Storefront is not extensible.

Solution:
[ ] Extend the module interface with a member which returns an array of data structure which defines the routes.
[ ] Expose an API for the Storefront which can be called during the startup of the Storefront to register those routes.
[ ] Update modules to use this feature.

This can open the evolution of a Storefront API within the platform by being the first API there ;-)

What do you think?

**Comment by tatarincev** [comment]
But for this case our modules will be know about storefront. It may breaks single responsibility principle and mean what all eCommerce modules should know about storefront and for  other API clients applications will not have any sense.
I think more correct to consider our storefront as some absolutely other application nothing know about internal VC platform modules structure.  Just use only API and all.

**Comment by attilah** [comment]
Partly I agree. But the current storefront would be just a "reference implementation" and not part of the product...

The other thing what would be awesome to have support for storefront modules too then.

Or based on the first sentence, just look at it as a reference implementation.
