### ISSUE TITLE
4.5.2(or higher) schedule?

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#502]
As 4.5.1 is no longer supported, when will VC move to 4.5.2 or higher?

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by attilah** [comment]
I think that the whole source should be based on 4.6.1 (which is the latest in Azure currently).

So: +1 for this.

**Comment by tatarincev** [comment]
Don't see any problem to re-target all our code to more fresher .NET versions.

**Comment by artem-dudarev** [comment]
Switched to 4.6.1

**Comment by jvdonk** [comment]
Yes, awesome, great job!

Why not 4.6.2, any incompatible dependent packages?

**Comment by artem-dudarev** [comment]
4.6.1 was the latest version available in Visual Studio 2015.

**Comment by jvdonk** [comment]
[4.6.2 was released in august 2016](https://blogs.msdn.microsoft.com/dotnet/2016/08/02/announcing-net-framework-4-6-2/) 

To target projects in VS2015 to 4.6.2, one must download the .NET 4.6.2 Developer pack: http://microsoft.com/en-us/download/details.aspx?id=53321
