### ISSUE TITLE
Themes do not apply

### ISSUE THREAD

**Issue by farsh42** [VirtoCommerce/vc-platform#503]
I installed a fresh deployment of 2.11 version and was unable to make any themes work on the stores and platform always uses the default theme. the themes also dont work on the online demo clothing store which is configured to use the material theme. ( http://demo.virtocommerce.com/clothing/en-US/)

**Comment by attilah** [comment]
It is working, check out now. One thing is that demo site as I see on the admin has 2.10 and not 2.11. After theme change, caching can hit in so editing a template file in the theme and saving that forces a reload. Now it is using the Material theme.

|'ve 2.11 deployment and my theme works well.

**Comment by farsh42** [comment]
Yes I've checked the online demo and its working fine now,however somehow I still couldn't manage to get themes working on my 2.11 deployment. my cms content connection string is: "provider=LocalStorage;rootPath=~\App_Data\cms-content" in both cms modules settings and web.config file of storefront project. I've tried different theme files,clearing the cache,rebuilding the solutions,doing a fresh deployment from scratch,etc... I can't find out what I'm doing wrong here...

**Comment by attilah** [comment]
Themes are served from the Assets connection string I think.

In 2.11 I needed to add rootPath to that too, but I’m using azure blob storage.

Without this addition to asset connection string themes were working, but theme resources (css, js) was not served for me in 2.11.

**Comment by attilah** [comment]
How did you deployed it? into a /Admin virtual directory or a separate site?

I found a kind of bug there. I'll create a new issue with it.

**Comment by farsh42** [comment]
I've deployed it locally on IIS 10, the platform is on /admin virtual directory,the storefront is located on http://localhost/.
I've seen the feature in the modules settings,as stated in the docs it should have the same value as the content connection string of the web.config file of the storefront.  

[http://docs.virtocommerce.com/display/vc2devguide/Storefront+Source+Code+Getting+Started](url)
> It should have the same provider and point to the same physical location as configured in VirtoCommerce.Content module's VirtoCommerce.Content.CmsContentConnectionString setting

 I've set everything to their default values but still couldn't make themes to work in 2.11 with LocalStorage provider.(they've worked fine in 2.10) 
I'm doing a fresh deployment on another system to see if the problem persists.

**Comment by eMazeika** [comment]
@farsh42 , how was the new deployment? I see you've read the correct docs and you should be able to configure as expected.

**Comment by farsh42** [comment]
I'm working on it,I'll post an update if I found out what was wrong.

**Comment by tatarincev** [comment]
In your storefront web.config should have **ContentConnectionString** pointed to your VC platform App_Data/cms-content folder. "~\App_Data\cms-content" is invalid path value because its pointed to storefront application  physical path. Instead it should have rootPath with some like this value: 
` <add name="ContentConnectionString" connectionString="provider=LocalStorage;rootPath=c:\Projects\VirtoCommerce\vc-community\VirtoCommerce.Platform.Web\App_Data\cms-content" />`

**Comment by arulselvan** [comment]
yep, this worked for me.  It would be great if added in docs, save searching time for many new developers.

Thanks!
