### ISSUE TITLE
Implement new markdown engine library

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#505]
http://xoofx.com/blog/2016/06/13/implementing-a-markdown-processor-for-dotnet/

**Comment by tatarincev** [comment]
@Woland2k  Its for our static content  functionality? To replace DotLiquid library?

**Comment by Woland2k** [comment]
Yes, it is for static content and no, it is not to replace DotLiquid, it is to replace current markdown library.

**Comment by Woland2k** [comment]
Added library to storefront
