### ISSUE TITLE
Add multi-vendors for products  

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#508]
Let say we have a product name "Logitech G700s 910-003584 Rechargeable Gaming Mouse". We have this product in stock but from 4 sellers with 4 different prices. How could we display this to store front? Something similar to Amazon at https://www.amazon.com/gp/offer-listing/B00BCEK2LU/ref=dp_olp_new?ie=UTF8&condition=new.

**Comment by Woland2k** [comment]
This doesn't need to be implemented as existing functionality does support it. You can create a product with all the descriptions and extra fields populated and then create variations which will be your vendor products. Each variation should have a vendor field specified as well as pricing tied to it. You will then display the product on frontend using variations for pricing. That way you have inventory configured correctly as well.
