### ISSUE TITLE
Configurable storage blob provider path for store product images

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#512]
Currently new images uploaded to  storage path with product.code name. need to create some special setting which will be used for generate  storage path.
Some like this: {catalog}_{product.code}

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #30](https://github.com/VirtoCommerce/vc-module-catalog/issues/30) via [**ZenHub**](https://www.zenhub.com/)
