### ISSUE TITLE
Address update bug

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#518]
During the theme building I added 1 address to my customer in the demo store, then I saw 2 addresses.
Deleted the first one, then 1 left.
I edited that 1 address, after Update I had 2 ;-)

I see some bugs here:

- [ ] Id is not passed anywhere during the update form post, hence the new address I think
- [ ] Is Default Address is not present anywhere, just in Liquid files, so it is not handled
- [ ] Embedding as many address edit forms is...how to say, not nice. I'd like to have a proper  RESTish /account/addresses/{id} route defined, just for that form.

**Comment by Woland2k** [comment]
This basic scenarios need to be included in the automated tests.

**Comment by tatarincev** [comment]
Some required form fields such as (Postal code, Address) does not have client or server validation. Throws exception when posted.

**Comment by Skrypt** [comment]
This happens also when we assign an employee or customer to a user account. It does'nt refresh the UI in the admin so that we see that this user account has been associated to that Contact entity.
