### ISSUE TITLE
Unit tests for platform modules functionality

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#522]
https://docs.google.com/document/d/1EEGNA5t4TQ1W3nE6D1_Ly7LmTjSUgnkEq8YHiIwIy9k/edit#heading=h.uiz9rre11iud

**Comment by eMazeika** [comment]
@tatarincev why not "On Deck"?

**Comment by OlegoO** [comment]
Need to clarify how to create mock data
