### ISSUE TITLE
Don't display settings toolbar button when there are not settings available

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#523]
In the modules list all modules now have settings toolbar button, however some modules don't have any settings. Hide settings in those cases.

**Comment by eMazeika** [comment]
problem: it's unknown whether there are any settings until the settings blade is opened.

**Comment by Woland2k** [comment]
why is that, we have module definition which has settings parameters, can't we check that?

**Comment by eMazeika** [comment]
settings array or settings count (flag?) could be added while returning installed modules list from API.
