### ISSUE TITLE
Credit Note Feature

### ISSUE THREAD

**Issue by DaleCam** [VirtoCommerce/vc-platform#527]
**Introduction**
A Credit Note is where an invoice is needing to be reversed. For example, a customer may purchase and pay for a large order. However if the order cannot be fulfilled for any reason, generally the customer is refunded, and a credit note is generated to record that transaction.
A credit note is a replica of the invoice, the only difference is that instead of the title "Invoice", the title would be "Credit Note".

**Implementation notes**
A credit note can only be issued after an invoice is issued.
A credit note contains all the information of the invoice, but the title should be "Credit Note".
The credit note amount would be DEDUCTED from Sales Totals in reporting. (so the invoice amount is offset by the credit note) 
A credit note should be able to INCREASE the inventory of the the products in the order. (to offset the original deduction from the order)

**Comment by Woland2k** [comment]
This functionality should be implemented as a standard return, since invoice is just another order for which specific PDF was generated and sent to a customer. Invoice can be generated by the means of Power BI and the same Credit Note can be generated using Power BI from order return functionality.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
