### ISSUE TITLE
Assets for authenticated/authorized customers only

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#529]
Is there such an option? To protect assets from being accessed/downloaded. Currently all assets are downloadable via http by just knowing the link: /assets/catalog/SKU/ASSET_FILE_NAME

**Comment by tatarincev** [comment]
For IIS hosted assets you can restrict access via IIS security folder setting
http://stackoverflow.com/questions/18236601/iis-setting-authorization-authentication-on-a-folder

For Azure blob assets you can restrict access for blob container as described in this article
https://azure.microsoft.com/en-us/documentation/articles/storage-manage-access-to-resources

Honestly any  of these methods, we have not tried in action :) We would be grateful if you write about the result

**Comment by jvdonk** [comment]
I'll try to restrict access then via a web.config file in the assets folder(or the parent: app_data).
I'll let you know the results.

**Comment by jvdonk** [comment]
With this web.config in the assets folder, anonymous access is restricted. 
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.web>
        <authorization>
            <deny users="?" />
        </authorization>
    </system.web>
</configuration>
```
When I log out of the admin part of VC, the direct url to an asset no longer works but gives me an 401 Unauthorized

```
http://vc-domain/assets/catalog/16993868/file.txt
```

Logging back in to the VC admin, the asset is accessible and is downloaded when the url is hit.

**Comment by tatarincev** [comment]
That's mean all easy!
