### ISSUE TITLE
Error when after platform restart when updating modules

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#531]
![image](https://cloud.githubusercontent.com/assets/1566470/16534569/9485804e-3f95-11e6-82bd-977e177e7d1b.png)

The only solution is to restart IIS website. Might be because frontend is accessing backedn at the same time or during the update?

**Comment by tatarincev** [comment]
Duplicate, original issue https://github.com/VirtoCommerce/vc-platform/issues/555
