### ISSUE TITLE
Storefront doesn't pass page size to the backend

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#534]
When paginate specifies page size the size is not passed to the backend product search service CatalogModuleSearchController.Search(SearchCriteria criteria), criteria.Take is always stays at 20. So if I want to display 50 products on one page I won't be able to do that.

```
var criteria = workContext.CurrentCatalogSearchCriteria.Clone();
criteria.PageNumber = pageNumber;
criteria.PageSize = pageSize;

var result = catalogSearchService.SearchProducts(criteria);
```

Need to also double check if page number is converted to starting index.

Ideally, API should always retrieve 100 records at a time with a maximum page size of being 50. That way we can completely cache results and the first (most often) request will always come from the cache.

**Comment by attilah** [comment]
Nice find :-P

**Comment by tatarincev** [comment]
Unable to reproduce. All work as expected.

**Comment by attilah** [comment]
Specify a page size in the querystring for collection.liquid page, and in the liquid page use a different page size in the paginate tag.

**Comment by tatarincev** [comment]
seems to "count" page size not getting from the query string.

**Comment by attilah** [comment]
I told @Woland2k that this is a bug and he also debugged it with me that night ;-)

**Comment by tatarincev** [comment]
Issue description have pointed to another problem
