### ISSUE TITLE
VirtoCommerce.Domain.Catalog.Model.SearchCriteria add ItemResponseGroup and CategoryResponseGroup

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#537]
For better control  of resulting data content.
Remove SearchResponseGroup next values
  WithProperties = 4,
        WithCatalogs = 8,
        WithVariations = 16,
        WithPriceRanges = 32,
        WithOutlines = 64,

**Comment by eMazeika** [comment]
@tatarincev why not "On Deck"?
