### ISSUE TITLE
Price evaluation is not handling correctly variants

### ISSUE THREAD

**Issue by attilah** [VirtoCommerce/vc-platform#538]
For product search page when I load variants, the pricing module is invoked by the search.

EvaluateProductPrices method have this line:
```
                        var variations = _productService.GetByIds(productIdsWithoutPrice, Domain.Catalog.Model.ItemResponseGroup.ItemInfo).Where(x => x.MainProductId != null).ToList();
```

This call return the products not the "child" products, variants. Maybe this call should be a filter by ParentId of the products for the given list of Ids?

**Comment by tatarincev** [comment]
Problem was in other place. But anyway all works now.
