### ISSUE TITLE
Notification LiquidResolver support complex .NET types in notification templates

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#542]
Make ILIquidizable all .NET types in runtime

**Comment by Skrypt** [comment]
Are you planning to upgrade the current DotLiquid fork repo to use what has been implemented for that in the main Dotliquid repo ?

**Comment by tatarincev** [comment]
Made in this release https://github.com/VirtoCommerce/vc-platform/releases/tag/v2.12.5
