### ISSUE TITLE
members/search LinqKit.AsExpandable preventing the usage of EntityFramework's Include method

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#544]
The members/search api doesn't allow a responseGroup to be specified, indicating what child objects/lists should be included in the response. For example members addresses.

I tried to include this logic in a custom module and came across the following issue:

In the SearchMembers method(used in the members/search api) in the MemberServiceBase unit a query is constructed with the following code:
```
var query = LinqKit.Extensions.AsExpandable(repository.Members);
```

When adding include logic in this method at first it didn't work. I tried upgrading the LinqKit package as there was an issue with includes and expandables(https://github.com/scottksmith95/LINQKit/issues/14) but that didn't help either.

When removing the AsExpandable call it works(without upgrading the LinqKit package?!):
```
var query = repository.Members;
```

And the keyword search (that's where I believe the expandable was used? With the where predicate?) still works.

So am I missing an usecase for the LinqKit.Extensions.AsExpandable call? Or can this be safely be omitted to be able to use includes for including the member addresses for example when searching for members.

**Comment by tatarincev** [comment]
**AsExpandable** was added because without it not worked PredicateBuilder AND and OR clauses.
Problem detailed described in this post:  http://stackoverflow.com/questions/2947820/c-sharp-predicatebuilder-entities-the-parameter-f-was-not-bound-in-the-specif?rq=1.
But if you claim that it worked without `LinqKit.Extensions.AsExpandable(repository.Members);`I need to check it because it did not work before. (But nothing to changed...)
We also have plans to add **ResponseGroup** to **IMemberSearchService** and if you have ready implementation and we would be grateful if you share you code with us:)

And my IMHO using Include in EF queries not best way to get composite entity due to performance issues. Better use separated queries.

**Comment by jvdonk** [comment]
Maybe the error only shows with nested predicates, as the first marked answer on your mentioned SO-question explains?
Anyways, I tested it as follows:

First I removed the AsExpandable call, then I commented out the predicate part:
```
//Get extra predicates (where clause)
var predicate = GetQueryPredicate(criteria);
query = query.Where(LinqKit.Extensions.Expand(predicate));
```

When this part was commented out the result wasn't filtered with the keyword and gave me a list of all entities.
When this part was not commented out, the result would show only the entity where the keyword matched.

That sounds like that the predicate is working right? Because in that is where the keyword is searched for.

About the performance, this is the VC module code for retrieving the order information:
```
public CustomerOrderEntity GetCustomerOrderById(string id, CustomerOrderResponseGroup responseGroup)
        {
            var query = CustomerOrders.Where(x => x.Id == id)
                                      .Include(x => x.Discounts)
                                      .Include(x => x.TaxDetails);

            if ((responseGroup & CustomerOrderResponseGroup.WithAddresses) == CustomerOrderResponseGroup.WithAddresses)
            {
                var addresses = Addresses.Where(x => x.CustomerOrderId == id).ToArray();
            }
            if ((responseGroup & CustomerOrderResponseGroup.WithInPayments) == CustomerOrderResponseGroup.WithInPayments)
            {
                var inPayments = InPayments.Where(x => x.CustomerOrderId == id).ToArray();
                var paymentsIds = inPayments.Select(x => x.Id).ToArray();
                var paymentAddresses = Addresses.Where(x => paymentsIds.Contains(x.PaymentInId)).ToArray();
            }
            if ((responseGroup & CustomerOrderResponseGroup.WithItems) == CustomerOrderResponseGroup.WithItems)
            {
                var lineItems = LineItems.Include(x => x.TaxDetails)
                                         .Include(x => x.Discounts)
                                         .Where(x => x.CustomerOrderId == id).ToArray();
            }
            if ((responseGroup & CustomerOrderResponseGroup.WithShipments) == CustomerOrderResponseGroup.WithShipments)
            {
                var shipments = Shipments.Include(x => x.TaxDetails)
                                         .Include(x => x.Discounts)
                                         .Include(x => x.Items)
                                         .Include(x => x.Packages.Select(y => y.Items))
                                         .Where(x => x.CustomerOrderId == id).ToArray();
                var shipmentIds = shipments.Select(x => x.Id).ToArray();
                var addresses = Addresses.Where(x => shipmentIds.Contains(x.ShipmentId)).ToArray();
            }
            return query.FirstOrDefault();
        }public CustomerOrderEntity GetCustomerOrderById(string id, CustomerOrderResponseGroup responseGroup)
        {
            var query = CustomerOrders.Where(x => x.Id == id)
                                      .Include(x => x.Discounts)
                                      .Include(x => x.TaxDetails);

            if ((responseGroup & CustomerOrderResponseGroup.WithAddresses) == CustomerOrderResponseGroup.WithAddresses)
            {
                var addresses = Addresses.Where(x => x.CustomerOrderId == id).ToArray();
            }
            if ((responseGroup & CustomerOrderResponseGroup.WithInPayments) == CustomerOrderResponseGroup.WithInPayments)
            {
                var inPayments = InPayments.Where(x => x.CustomerOrderId == id).ToArray();
                var paymentsIds = inPayments.Select(x => x.Id).ToArray();
                var paymentAddresses = Addresses.Where(x => paymentsIds.Contains(x.PaymentInId)).ToArray();
            }
            if ((responseGroup & CustomerOrderResponseGroup.WithItems) == CustomerOrderResponseGroup.WithItems)
            {
                var lineItems = LineItems.Include(x => x.TaxDetails)
                                         .Include(x => x.Discounts)
                                         .Where(x => x.CustomerOrderId == id).ToArray();
            }
            if ((responseGroup & CustomerOrderResponseGroup.WithShipments) == CustomerOrderResponseGroup.WithShipments)
            {
                var shipments = Shipments.Include(x => x.TaxDetails)
                                         .Include(x => x.Discounts)
                                         .Include(x => x.Items)
                                         .Include(x => x.Packages.Select(y => y.Items))
                                         .Where(x => x.CustomerOrderId == id).ToArray();
                var shipmentIds = shipments.Select(x => x.Id).ToArray();
                var addresses = Addresses.Where(x => shipmentIds.Contains(x.ShipmentId)).ToArray();
            }
            return query.FirstOrDefault();
        }
```
There are a lot of local variables for retrieving the composited entity details. Is this the way to do that with separated queries? How does that work then, they are only local variables and not used or glued onto the entity retrieved with the query variable? 

As for the code sharing I currently do not have a ready implementation for the customers module. I have a custom module(where like the customers modules a extension capability exists) where I implemented the responseGroup functionality. But I also have a custom customer module and when I update this module to implement the responseGroup functionality I would be happy to make a PR. Which would be my first PR ever :)

I also came along some anomalies in the Customer module when using this module as a base for my own module and will report those anomalies so you can fix them or maybe I throw in a series of PR's ;-)

**Comment by tatarincev** [comment]
Would be very appreciate see your PR!
 About separated EF requests to load complex entities - Here is a good example demonstrated how it works on practice https://github.com/VirtoCommerce/vc-module-store/blob/master/VirtoCommerce.StoreModule.Data/Repositories/StoreRepositoryImpl.cs

```
var retVal = Stores.Where(x => ids.Contains(x.Id))
                               .Include(x => x.Languages)
                               .Include(x => x.Currencies).Include(x => x.TrustedGroups)
                               .ToArray();
            var paymentMethods = StorePaymentMethods.Where(x => ids.Contains(x.StoreId)).ToArray();
            var shipmentMethods = StoreShippingMethods.Where(x => ids.Contains(x.StoreId)).ToArray();
            var taxProviders = StoreTaxProviders.Where(x => ids.Contains(x.StoreId)).ToArray();
```
This approach work because queries  are invoked within on EF context instance and If you do separate queries that use the same context, EF will automatically join related entities in memory.
