### ISSUE TITLE
Entity with complex property types

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#545]
For example: Address with Country. In the customer module the Country details are flattened on the address entity: Country code and Country name.

Is it possible(considering the web-api, patching with ValueInjecter, Angular frontend, etc) to have this kind of structure to normalize the address details:
```
public class Address {

        public int Id { get; set; }

        public int CountryId { get; set; }
        public virtual Country Country { get; set; }
    }

    public class Country {

        public int Id { get; set; }

        public string Iso2Code { get; set; }

        public string Iso3Code { get; set; }

        public string Description { get; set; }

        public int LanguageId { get; set; }
        public virtual Language Language { get; set; }
    }

    public class Language {

        public int Id { get; set; }

        public string Code { get; set; }
        public string Description { get; set; }

    }
```

I don't see this kind of normalization throughout the VC modules. It's only flattened simple property types(string, int, datetime etc) or collections. So this must be on purpose I think? What is preventing the normalization of entities?

**Comment by tatarincev** [comment]
Here is an example https://github.com/VirtoCommerce/vc-module-catalog module.
Product domain model contains lot of complex types. Images, Assets, Reviews etc. 
https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.Domain/Catalog/Model/CatalogProduct.cs
Here is normalized  persistent layer model definition
https://github.com/VirtoCommerce/vc-module-catalog/tree/master/VirtoCommerce.CatalogModule.Data/Model
Here is Domain <-> Persistent layer converters 
https://github.com/VirtoCommerce/vc-module-catalog/tree/master/VirtoCommerce.CatalogModule.Data/Converters

**Comment by jvdonk** [comment]
Those are all collections. Not a single complex property.

1 address has 1 country, not a list of countries(in my example)

But now that I look again at the CatalogProduct maybe the MainProduct is an example of what I mean. Altough it is a self-reference: CatalogProduct.

You understand what I'm after now? :)

**Comment by tatarincev** [comment]
Actually your question is how to create EF One to One tables relations?

**Comment by jvdonk** [comment]
Well, not One to One(or One-to-Zero-or-One) because the Countries and Languages are shared.

Let me show the db schema:

```
CREATE TABLE Address
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    City VARCHAR(XX) NOT NULL,
    CountryId INT FOREIGN KEY REFERENCES Country(Id) // country for this address
)

CREATE TABLE Country
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    ISO2Code VARCHAR(XX) NOT NULL,
    ISO3Code VARCHAR(XX) NOT NULL,
    Description VARCHAR(XX) NOT NULL,
    LanguageId INT FOREIGN KEY REFERENCES Language(Id) // default language of the country
)

CREATE TABLE Language
(
   Id INT IDENTITY PRIMARY KEY NOT NULL,
   Code VARCHAR(XX),
   Description VARCHAR(XX)
)
```

The Country and Language tables are independent tables(e.g. a list of available countries, like your list of countries which now resides in json: https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.CoreModule.Web/Scripts/common/resources/countries.js) .

So that I can also add Language to the Member entity, using the same language table:

```
CREATE TABLE Member
(
   Id INT IDENTITY PRIMARY KEY NOT NULL,
   ....
   LanguageId INT FOREIGN KEY REFERENCES Language(Id) // language of the member
)
```

One to One(One-to-Zero-or-One) would have this schema
```
CREATE TABLE Address
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    City VARCHAR(XX) NOT NULL
)

CREATE TABLE Country
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    ISO2Code VARCHAR(XX) NOT NULL,
    ISO3Code VARCHAR(XX) NOT NULL,
    Description VARCHAR(XX) NOT NULL,
    AddressId INT FOREIGN KEY REFERENCES Address(Id) // default language of the country
)
```

That would leave me without a table with all available countries.

That was my original question. But maybe there is already an example of One-to-Zero-or-One relationships in VC? I would also need that, in another situation.

**Comment by tatarincev** [comment]
One-to-Zero-or-One does not have references in SQL schema, and it looks at not obvious as magic! And we try to avoid this relation in our projects.

**Comment by jvdonk** [comment]
In my Address/Country/Language sample there are regular FK constraints. No magic/not obvious references involved here? I don't understand your remark.

I was refering to One-to-Zero-or-One as being a optional One-to-One relationship.

**Comment by tatarincev** [comment]
In your above described schema all tables  references it is 'One to many':
Country 0..1  - * Address (One to many)
Language 0..1 - * Country (One to many)
MS SQL does not support one-to one relations type
http://stackoverflow.com/questions/10292355/how-do-i-create-a-real-one-to-one-relationship-in-sql-server
But you can define it (virtually) by define special entity mapping in EF. And two tables will be use same id for referenced records.

**Comment by artem-dudarev** [comment]
The relationship between Category and Product is the same as between Country and Address (1 to N).

**Comment by jvdonk** [comment]
@artem-dudarev I think you overlooked how I wanted the db-schema. Your comment is based on the sample of how I **didn't** want the db-schema to be. (But yes, that is 1 to N)

1 Category has many Products => 1 to N
In the DB-schema this means FK from Item.CategoryId to Category.Id

What I want is:

1 Address has zero or one Country => 1 to 1?
In the DB-schema this should mean FK from Address.CountryId to County.Id

This is not the same.

The last piece of sample code in my remark(https://github.com/VirtoCommerce/vc-platform/issues/545#issuecomment-232932141):
```
CREATE TABLE Address
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    City VARCHAR(XX) NOT NULL
)

CREATE TABLE Country
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    ISO2Code VARCHAR(XX) NOT NULL,
    ISO3Code VARCHAR(XX) NOT NULL,
    Description VARCHAR(XX) NOT NULL,
    AddressId INT FOREIGN KEY REFERENCES Address(Id) // default language of the country
)
```
was a sample of how I did **not** want the design.

Should I elaborate more about what I want? To be clear? :)

**Comment by artem-dudarev** [comment]
```
CREATE TABLE Country
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    ISO2Code VARCHAR(XX) NOT NULL,
    ISO3Code VARCHAR(XX) NOT NULL,
    Description VARCHAR(XX) NOT NULL
)

CREATE TABLE Address
(
    Id INT IDENTITY PRIMARY KEY NOT NULL,
    City VARCHAR(XX) NOT NULL,
    CountryId INT NULL FOREIGN KEY REFERENCES Country(Id)
)

```
Address.CountryId can be null - this means zero or one.

Since many addresses can reference the same country it will be a 1 to N relation.
