### ISSUE TITLE
Keep getting locked file exception when updating a module and hitting restart.

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#555]
The process cannot access the file 'E:\Projects\Git\vc-platform\VirtoCommerce.Platform.Web\App_Data\Modules\VirtoCommerce.CustomerModule.Data.dll' because it is being used by another process.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.IOException: The process cannot access the file 'E:\Projects\Git\vc-platform\VirtoCommerce.Platform.Web\App_Data\Modules\VirtoCommerce.CustomerModule.Data.dll' because it is being used by another process.

Source Error: 

Line 130:                var targetDirectoryPath = Path.GetDirectoryName(targetFilePath);
Line 131:                Directory.CreateDirectory(targetDirectoryPath);
Line 132:                File.Copy(sourceFilePath, targetFilePath, true);
Line 133:            }
Line 134:        }

Source File: E:\Projects\Git\vc-platform\VirtoCommerce.Platform.Web\Modularity\ManifestModuleCatalog.cs    Line: 132 

![image](https://cloud.githubusercontent.com/assets/1566470/20233889/767436ac-a829-11e6-8118-f7b9dab27a99.png)

**Comment by Woland2k** [comment]
Can we fix this issue? The files need to be copied during PreApplicationStartMethod, here is one article describing process: http://shazwazza.com/post/Developing-a-plugin-framework-in-ASPNET-with-medium-trust.aspx

**Comment by tatarincev** [comment]
Same issue when manager work on multiple application instances (scale out on azure)
Probably issue solution  in Shadow Copying Assemblies.
https://msdn.microsoft.com/en-us/library/ms404279(v=vs.110).aspx#EnablingAndUsing

**Comment by zhangpeng-kooboo** [comment]
Hi @tatarincev, Is this issue will be picked up in the coming period? It's an intermittent issue, keep happening when the application was restarted.
