### ISSUE TITLE
Color, size and price filters are not working in clothing theme

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#558]
![image](https://cloud.githubusercontent.com/assets/1566470/17069118/baf71236-5009-11e6-9ec9-b068925b2db5.png)

Should be able to click colors, sizes, prices and brands to filter elements in clothing theme.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-theme-material #9](https://github.com/VirtoCommerce/vc-theme-material/issues/9) via [**ZenHub**](https://www.zenhub.com/)
