### ISSUE TITLE
ui-grid  empty data placeholder  does not displayed.

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#560]
product SEO.

![image](https://cloud.githubusercontent.com/assets/7566324/17139981/fa853514-5346-11e6-8eb1-7a711b58f8ca.png)

**Comment by eMazeika** [comment]
https://github.com/VirtoCommerce/vc-module-core/commit/19e70f649c5e358d2b8c83071bbdcbde25e278ba
