### ISSUE TITLE
Add paging when searching for categories in DB

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#596]

**Comment by miguelhasse** [comment]
Also add paging when searching for assets, or resource that may return large sets of data.

**Comment by eMazeika** [comment]
isn't all this implemented yet?

**Comment by tatarincev** [comment]
Here is a special API for search categories, it also support paging
http://demo.virtocommerce.com/admin/docs/ui/index#!/Catalog_module/CatalogModuleSearch_SearchCategories
