### ISSUE TITLE
Customer creation

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#597]
When I try to create a customer from the admin UI it takes a lot of time.

**Comment by eMazeika** [comment]
Can you describe the problem in more detail? Is the UI too complicated or too much information is required? Or the processing after submitting takes too long? 
How could we improve that?

**Comment by Skrypt** [comment]
The processing after submitting the customer form. Here you can see it took 55 seconds just to create a customer.

![image](https://cloud.githubusercontent.com/assets/3228637/18053627/6fd12746-6dce-11e6-9d22-5634f70bc7cc.png)

I noticed also that when we create a customer. In the `Member` Table, the `Name` column value recorded is always "NULL".

![image](https://cloud.githubusercontent.com/assets/3228637/18053977/fe6e6cb0-6dcf-11e6-952b-022895f5cf1b.png)

I don't know yet what is causing the performance issue. I just report it for now.

**Comment by tatarincev** [comment]
Could you provide which version of VC you use? Are you have  custom code changes in VC customer module?

**Comment by Skrypt** [comment]
I'm using VC 2.11 from source code and I made no changes to the code. I'm running VC Platform locally with IIS. I have though a lot of User accounts "around 5000" created from a TSQL script. But that should not slow down the process that much either.

**Comment by tatarincev** [comment]
We successfully tested recently with 2M contact records  without any performance problems. But thanks for you detailed report we will try to check again.

**Comment by OlegoO** [comment]
Fixed in vc-module-customer 2.14.2 release 
https://github.com/VirtoCommerce/vc-module-customer/commit/25d6e25b18dd67759e1b4c355f912c03560577b8
