### ISSUE TITLE
Contact account creation

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#598]
When we create a customer or employee, we need to also create a user account so that "Contact" be assigned to a user account. Though right now we can only create new user accounts and can't just assign a user account from the list of already created ones. That way though we could assign a single user account to multiple customers or employees.

**Comment by tatarincev** [comment]
Thanks for you question, we will include this task in our backlog and implement in future versions of the customer module. https://github.com/VirtoCommerce/vc-module-customer

**Comment by eMazeika** [comment]
duplicates #203
