### ISSUE TITLE
Module versions with development stage (beta, rc, alpha) break during runtime

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#604]
The error is generated "Input string was not in a correct format" when module manifest file defines version as "2.11.2-rc". Because it tries to use System.Version.Parse method. One alternative can be use this implementation: https://gist.githubusercontent.com/yadyn/959467/raw/01c9ddf6388b659df8b3e23b340341628787043c/SemanticVersion.cs

**Comment by OlegoO** [comment]
We don't use "-rc" suffix. 
Commit in DEV branch publish Pre-release.
Commit in Master branch publish Release.
