### ISSUE TITLE
PropertyValue

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#607]
When a property is deleted, PropertyValue is remain

**Comment by tatarincev** [comment]
This made by design. Values does not hard linked with property meta information.

**Comment by FreeKen** [comment]
But PropertyValue can not be removed from UI, it displays if set value is empty, how can I remove PV?

**Comment by tatarincev** [comment]
Ok we will implement behavior when deleted property will be deleted all values
