### ISSUE TITLE
Increase precision for decimals to store more than 2 decimal values

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#608]
I noticed that the decimal values gets rounded in the admin UI when I type a decimal value for a numeric property. Let me know if you guys can reproduce or if it's just me.

**Comment by eMazeika** [comment]
Only 2 decimal digits precision is currently supported. We should change that to allow higher precision for decimals.

**Comment by OlegoO** [comment]
In MS SQL, we have used decimal(18,2). Need to review how we can migrate and store more than 2 decimal values

**Comment by tatarincev** [comment]
Need to increase precision (to 4) for all decimal columns in all platform tables.

See commit for the similar task: 
https://github.com/VirtoCommerce/vc-module-order/commit/1133ed1d3bd107f92d2a91e284b56d5e96385fed

The article describes how to work with migrations in VC.
https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/managing-module-database
