### ISSUE TITLE
Swagger generation fails with error. 

### ISSUE THREAD

**Issue by busbina** [VirtoCommerce/vc-platform#609]
i was following the  swagger generation steps for my module and ran into this issue.
{
	"message": "An error has occurred.",
	"exceptionMessage": "Conflicting schemaIds: Duplicate schemaIds detected for types VirtoCommerce.Domain.Order.Model.LineItem and VirtoCommerce.Domain.Cart.Model.LineItem. See the config setting - \"UseFullTypeNameInSchemaIds\" for a potential workaround",
	"exceptionType": "System.InvalidOperationException",
	"stackTrace": "   at Swashbuckle.Swagger.SchemaRegistry.CreateRefSchema(Type type)\r\n   at Swashbuckle.Swagger.SchemaRegistry.CreateArraySchema(JsonArrayContract arrayContract)\r\n   at Swashbuckle.Swagger.SchemaRegistry.<CreateObjectSchema>b__16(JsonProperty prop)\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at Swashbuckle.Swagger.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract)\r\n   at Swashbuckle.Swagger.SchemaRegistry.CreateDefinitionSchema(Type type)\r\n   at Swashbuckle.Swagger.SchemaRegistry.GetOrRegister(Type type)\r\n   at Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDesc, SchemaRegistry schemaRegistry)\r\n   at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)\r\n   at VirtoCommerce.Platform.Web.Swagger.CachingSwaggerProvider.<>c__DisplayClass4_0.<GetSwagger>b__0() in C:\\vc-platform\\VirtoCommerce.Platform.Web\\Swagger\\CachingSwaggerProvider.cs:line 26\r\n   at VirtoCommerce.Platform.Data.Common.CacheManagerExtension.Get[T](ICacheManager`1 cacheManager, String cacheKey, String region, Func`1 getValueFunction) in C:\\vc-platform\\VirtoCommerce.Platform.Data\\Common\\CacheManagerExtensions.cs:line 28\r\n   at VirtoCommerce.Platform.Web.Swagger.CachingSwaggerProvider.GetSwagger(String rootUrl, String apiVersion) in C:\\vc-platform\\VirtoCommerce.Platform.Web\\Swagger\\CachingSwaggerProvider.cs:line 26\r\n   at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}

Is there a way to specify the virto swagger to use full namespaces?

**Comment by artem-dudarev** [comment]
Yes, you should add `<useFullTypeNameInSwagger>true</useFullTypeNameInSwagger>` to the `<module>` element in the module.manifest:
```
<module>
    ...
    <useFullTypeNameInSwagger>true</useFullTypeNameInSwagger>
    ...
</module
```
But this is a workaround. The correct way is to get rid of duplicate types in the API.

**Comment by busbina** [comment]
Thanks for the work around. I'll have to figure out how to get rid of the items, they are on return types and I'm not using them directly.
