### ISSUE TITLE
Upload assets using VC Platform API(generated c# client)

### ISSUE THREAD

**Issue by jvdonk** [VirtoCommerce/vc-platform#614]
The API method is there: "AssetsUploadAsset" but it seems to me there is no way of providing the actual bytes of the asset. 

Obviously the API works when using postman and attach some files to the body of the API request but having a generated c# client I was hoping to upload it via this client.

Or am I missing something? :)

Edit:
So swagger needs to be instructed to expect file uploads [As it is said here](http://stackoverflow.com/questions/14455408/how-to-post-files-in-swagger/15087260#15087260)
Also discussed [here](https://github.com/swagger-api/swagger-codegen/issues/2175)

I'm finding out how to do that...

**Comment by jvdonk** [comment]
So I added an another OperationFilter(like the TagsFilter) to the VC Swagger configuration:

```
public class AddFileUploadParams : IOperationFilter {

    public void Apply(Operation operation, SchemaRegistry schemaRegistry, ApiDescription apiDescription) {
        if (operation.operationId == "Assets_UploadAsset") {
            operation.consumes.Add("application/form-data");
            operation.parameters.Add(new Parameter
            {
                name = "file",
                @in = "formData",
                required = true,
                type = "file"
            });
        }
    }
}
```

and now in the platform asset documentation there is an file parameter:

![image](https://cloud.githubusercontent.com/assets/1164988/18515695/834584d2-7a96-11e6-884f-4e025433c870.png)

And this works, it upload a single file successfully to the assets folder. I regenerated the VirtoCommerce.Platform.Client and now there is a new file parameter:

```
List<BlobInfo> AssetsUploadAsset(string folderUrl, System.IO.Stream file, string url = null);
```

But when it's used it blows up with an "The request was aborted: The request was canceled" exception:

```
VirtoCommerce.Platform.Client.Client.ApiException

Error calling AssetsUploadAsset: The request was aborted: The request was canceled.

VirtoCommerce.Platform.Client.Client.ApiException: Error calling AssetsUploadAsset: The request was aborted: The request was canceled.
   at VirtoCommerce.Platform.Client.Api.VirtoCommercePlatformApi.AssetsUploadAssetWithHttpInfo(String folderUrl, Stream file, String url) in C:\TeamCity\buildAgent\work\15f3797984e62f54\VirtoCommerce.Platform.Client\Api\VirtoCommercePlatformApi.cs:line 3088
   at VirtoCommerce.Platform.Client.Api.VirtoCommercePlatformApi.AssetsUploadAsset(String folderUrl, Stream file, String url) in C:\TeamCity\buildAgent\work\15f3797984e62f54\VirtoCommerce.Platform.Client\Api\VirtoCommercePlatformApi.cs:line 3024
```

No idea why this is hapening...

**Comment by tatarincev** [comment]
Thanks for you investigation! We are now switched  to https://github.com/Azure/autorest library for generate client code.  It made in storefront dev branch but we already preparing for new release where it will be included.  http://docs.virtocommerce.com/display/vc2devguide/How+to+generate+module+API+C%23+client+using+AutoRest

We definitely try to use your solution and if it will work, we will including it in next release.

**Comment by jvdonk** [comment]
Don't bother, it works! 😄 

I updated the client modules like in the storefront dev branch to the AutoRest package(nightly) and the files are uploaded without errors.

Well, almost. When uploading a filestream with a network UNC path, it uploads the file to [folderUrl]\[full-unc-path-of-the-uploaded-file]. But when using a FileStream with a local file to upload the file on the client side and AutoRest also sends this file with the ContentDisposition Filename as the full path of the local file. The BlobStorageMultipartProvider on the platform side isn't checking for this and when the file is to be saved it blows up with a bad filename e.g. [folderUrl]c:\temp\myuploaded.file

Difference is the ":" in the local file path I believe.

\\COMPUTER\SHARE\my.file
vs
C:\FOLDER\my.file

**Comment by tatarincev** [comment]
Could you prepare PR with swagger converter to platform/dev branch?

**Comment by ghavipanjeh** [comment]
how to use swagger in storfront ??
