### ISSUE TITLE
Initial setup must be simplified

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#615]
Typical user wants to setup virto commerce with a minimum effort and edit the default store design. In the current platform such approach is too complicated. In order to simplify this, we need to remove certain dependencies:
1. Shouldn't require VS.NET.
2. Should be possible to edit sample store theme right from the admin.
3. Simple deployment on azure cloud.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-storefront #29](https://github.com/VirtoCommerce/vc-storefront/issues/29) via [**ZenHub**](https://www.zenhub.com/)
