### ISSUE TITLE
List associations for product

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#618]
If list associations for product is large, it breaks
![image](https://cloud.githubusercontent.com/assets/14821555/18676360/a34c7db2-7f55-11e6-922e-bd2899a4416b.png)

**Comment by eMazeika** [comment]
this issue was fixed in https://github.com/VirtoCommerce/vc-module-catalog/commit/4a169f3b31339c5b7021920c4919fd391b689cd1 and will be included in the upcomming release.
