### ISSUE TITLE
Theme select wizard in content module

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#619]
Need to be able to easily demonstrate ability to change themes using public demo.

**Comment by tatarincev** [comment]
Need to switch demo.virtocommerce.com to file storage for themes and pages. Only in that case could use FileSystemWatcher for observing theme changes and cache invalidation

**Comment by Woland2k** [comment]
Still can't edit theme in our demo store.

**Comment by tatarincev** [comment]
Need to implement  select theme wizard in admin by clicking new theme action in content module.
Theme selector should be a configurable  and contains next data: theme zip url, name, image
Themes zip archives  could be hosted on github.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
