### ISSUE TITLE
Colors are bad for notification background

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#621]
![image](https://cloud.githubusercontent.com/assets/1566470/18733403/93a711d6-801f-11e6-8568-47c37a204e0b.png)

**Comment by eMazeika** [comment]
catalog CSV export/import UI fixed https://github.com/VirtoCommerce/vc-module-catalog/commit/e9525c42e76cfe0a8e98d3ead32c1daf8c5a3ce5
