### ISSUE TITLE
Azure Deploy sample stores not loading after setting url

### ISSUE THREAD

**Issue by CaptainMM** [VirtoCommerce/vc-platform#623]
It appears with the latest build when deployed to azure with all of the default settings then adding the sample data on first launch makes the store non reachable. The admin center works but when attempting to browse the clothing store an error is displayed. The quick start screen differs from the azure setup video currently available in that the modules setup section has been replaced with "Commerce" as the only option other than empty. 

Setting the default store url to (https://myinstance.azurewebsites.net/clothing) results in "Server Error in '/' Application".

**Comment by tatarincev** [comment]
Could you provide your VC admin url?

**Comment by CaptainMM** [comment]
http://vc-platform0d20.azurewebsites.net/clothing

**Comment by tatarincev** [comment]
All seems normal, could you make sure that made all steps for right storefront deployment
http://docs.virtocommerce.com/display/vc2devguide/Storefront+Microsoft+Azure+Getting+Started

**Comment by CaptainMM** [comment]
Does azure need any special setup in order to set the default store or any store url for that matter? I'm not seeing anything different on that getting started than what I followed.

**Comment by tatarincev** [comment]
You just install only platform. Storefront required another deployment from https://github.com/VirtoCommerce/vc-storefront repository. You can read more detailed instructions in above article. Its need because storefront is just one of possible client of our platform and it may be work in other subscription or application.

**Comment by CaptainMM** [comment]
Ok, thank you. I'll give that a shot.

**Comment by CaptainMM** [comment]
The install appears to have worked although my store always says under maintenance. All keys and urls have been set but I receive a "Under Maintenance" page for my store url. I've tried changing the 'state' of the store but no effect.

**Comment by CaptainMM** [comment]
Everything works great. Thank you for your time and a great product!
