### ISSUE TITLE
store import failing when CyberSource payment gateway is imported

### ISSUE THREAD

**Issue by eMazeika** [VirtoCommerce/vc-platform#630]
The whole data import fails if CyberSource payment gateway data is imported. Error:

VirtoCommerce.Store: Error getting value from 'TransactionConfiguration' on 'Cyber.Source.Managers.CyberSourceMethod'.
 Value cannot be null.
 Parameter name: source

Steps to reproduce:
1. install CyberSource payment gateway
2. enable it in selected store
3. export store data using platform data exporter
4. import the exported data back

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-CyberSource #1](https://github.com/VirtoCommerce/vc-module-CyberSource/issues/1) via [**ZenHub**](https://www.zenhub.com/)
