### ISSUE TITLE
Update VC  on Azure marketplace

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#635]

**Comment by artem-dudarev** [comment]
The application status is 'Pending Review' since 14.03.2017

**Comment by IgorisB** [comment]
@artem-dudarev 
https://webgallery.microsoft.com/apps/vccommunity
says: 
Version:2.13
Release Date:3/31/2017

Is it good?

**Comment by artem-dudarev** [comment]
Yes, the status is Published.
