### ISSUE TITLE
Create and submit WordPress plugin for javascript shopping cart

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#637]
Create a new plugin "Virto Commerce shopping cart plugin" for wordpress and submit it here: https://wordpress.org/plugins/add/. Plugin should add a buton on the post screen that allows to add product to any post page.

**Comment by Woland2k** [comment]
This is not done.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-javascript-shoppingcart #4](https://github.com/VirtoCommerce/vc-module-javascript-shoppingcart/issues/4) via [**ZenHub**](https://www.zenhub.com/)
