### ISSUE TITLE
Copy/paste support for catalog categories & products

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#640]
Need to be able to copy and paste products from one category to another. Currently process involves duplicating product and then cut/paste to a category. Also should be able to copy/paste multiple products.

**Comment by Skrypt** [comment]
I tried also cut/pasting category/products from one catalog to an other. It almost works but we lose the dynamic properties.

**Comment by tatarincev** [comment]
@Woland2k  how to reproduce duplication? We don't have Copy/Paste functionality at all, only Cut/Paste!
@Skrypt yes it expected behavior, because other catalog can not contain properties definition. But if it does all should moved fine. Anyway I'll check this case more carefully.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
