### ISSUE TITLE
Search improvements in admin

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#643]
- search within products should find items by all properties, not just name (basically should use indexed search)
- product filter needs to be much more flexible (show products without prices etc, show products that don't have any text in certain property etc, should be based in indexed search)
- need to have global search that finds contacts, orders, products, categories
- order search needs to find using all properties

**Comment by Skrypt** [comment]
I noticed that when we search for a specific Contact "User" ; if they are inside an Organization it won't return any results. Maybe from the first blade search we could get more detailed results. Someone asked me if we could have a dropdown from the search that would also return Users with links to their latest orders.

**Comment by Woland2k** [comment]
Search should be done using indexed search instead of database based search. So our focus will be migrating it to that which will allow searching within all organizations.
