### ISSUE TITLE
Vendors and user account association

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#644]
This is more a question than anything else. I know that Vendors are associated to the Member table in Virto but maybe that would be usefull to be able to associate Vendors with user accounts.

**Comment by Woland2k** [comment]
It looks like vendor doesn't have accounts associated with it, which is odd. You should be able to associate account with a vendor. It might be a matter of quick extension. @tatarincev why is there no accounts for vendor type?

**Comment by Skrypt** [comment]
From what I understand Vendors are "Tenants" but I thought that if they are Contacts too they should maybe be associated with accounts. Though, quick ugly way is to link the Vendor email to a User account with the same.

**Comment by Woland2k** [comment]
Yeah, I believe it was specifically removed as feature for vendor. Probably just a UI element.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-customer #6](https://github.com/VirtoCommerce/vc-module-customer/issues/6) via [**ZenHub**](https://www.zenhub.com/)
