### ISSUE TITLE
Image property value type

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-platform#650]
VirtoCommerce 2.x look awesome, we are upgrading from 1.x to 2.x, but we are missing the image property value type which is multi language.

**Comment by tatarincev** [comment]
Could you provide information what are you plan to use this type of property?

**Comment by zhangpeng-kooboo** [comment]
We are selling eBooks in multi languages, cover of the eBook is different per language (image property value type), and the e-pub file of the eBook is also different per language (file property value type).

**Comment by tatarincev** [comment]
For product images localization  you could use  images categories feature 
![image](https://cloud.githubusercontent.com/assets/7566324/19514241/22dfbfea-95f3-11e6-9b09-06bf05be76b2.png) 
all uploaded images will be stored in specified category path /EN-US/15536361-Ladybird-on-a-white-background--Stock-Photo-spring-ladybird-shine.jpg

And in your storefront you could use this category prefix to choose prefer image.

Or other way use for this purposes short-text multilingual properties and store image urls to there.

**Comment by zhangpeng-kooboo** [comment]
@tatarincev Image categories feature look great, would you mind to add the asset categories also?
