### ISSUE TITLE
Improving AngularJS performance

### ISSUE THREAD

**Issue by vascofernandes** [VirtoCommerce/vc-platform#651]
Hi, 

Just a quick tip. 

One can improve AngularJS performance a bit by using this settings in production:

```
myApp.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
```

I did not find it in the code.

Regards

**Comment by eMazeika** [comment]
Thanks for the tip!

Saving this link for the future reference https://docs.angularjs.org/guide/production

**Comment by Skrypt** [comment]
I can see the difference already. Thanks for this. @vascofernandes

**Comment by vascofernandes** [comment]
No problem.

In the upcoming 1.5.9 release there will be a couple more improvement one can make.


I'll be back...

**Comment by vascofernandes** [comment]
This can also be applied to the vc-storefront.
