### ISSUE TITLE
when virtocommerce support angular2 or asp.net core

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-platform#652]
I like virtocommerce very much , and angular2 is released, the js code became very  easy to write with typescript and angular,I want to know will virtocommerce support this ,or when?

Also asp.net core is supporting cross platform,will you support that ?

thanks a lot

**Comment by tatarincev** [comment]
Thank you for your declaration of love :)
Yes, we have some plans to  start  migration storefront to ASP.NET Core.  But for AngularJS 2.0 it bit more complicated to say concrete estimate because we have a lot of already done JS code which will need to be rewrite.

**Comment by vascofernandes** [comment]
Some time ago I wrote an article on how to refactor Angular 1.x code to make the transition to angular 2 easier. [https://medium.com/@vascofernandes/the-road-to-angular-2-refactoring-angularjs-1-x-applications-for-smoother-upgrade-69c91364bc4c](See here.)

The first step is to migrate to Typescript is the very first step. It will be a massive boost to the code quality of the project.

**Comment by tatarincev** [comment]
But we are not so bad already started use angular components in our storefront for Checkout wizard :)
https://github.com/VirtoCommerce/vc-storefront/tree/master/VirtoCommerce.Storefront/App_Data/Themes/default/assets/js/checkout
