### ISSUE TITLE
How to use overridden types in storefront.

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#654]
Add new chapter to http://docs.virtocommerce.com/display/vc2devguide/Extending+Members+domain+types

All DTO and model types defined as Partial  need to take in account this fact in article

**Comment by tatarincev** [comment]
And also need to fix MemberExtension sample module to prevent  getByIds get two contacts for dame id. (MemberServiceDecorator execute two different services original and new )

**Comment by artem-dudarev** [comment]
https://virtocommerce.com/docs/vc2devguide/extending-commerce/extending-domain-models
