### ISSUE TITLE
Store payment method detail does not support isArray true

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-platform#655]
I am creating a new payment method module, in the module there has a 'Allowed payment methods' setting. But after I installed the module I could not specific the 'Allowed payment methods' in the store payment method. See the below setting xml:

```
<setting>
    <name>Ogone.AllowedPaymentMethods</name>
    <valueType>string</valueType>
    <defaultValue></defaultValue>
    <title>Allowed payment methods</title>
    <description>Allowed payment methods</description>
    <isArray>true</isArray>
    <arrayValues>
        <value>iDEAL</value>
        <value>MasterCard</value>
        <value>Visa</value>
        <value>Paypal</value>
        <value>etc</value>
    </arrayValues>
</setting>
```

When I looked into the source code I saw it is not implemented yet.
https://github.com/VirtoCommerce/vc-module-store/blob/master/VirtoCommerce.StoreModule.Web/Scripts/blades/paymentMethod-detail.tpl.html

**Comment by tatarincev** [comment]
Probably you forgot to pass your module setting in the PaymentMethod ctor in module initialization.
Please check how it done in other payment method. https://github.com/VirtoCommerce/vc-module-DIBS/blob/master/DiBs/Module.cs

**Comment by zhangpeng-kooboo** [comment]
@tatarincev I did the same as DiBs.
It work perfect in the module settings, but not in the store level.

When you compare the below two html you could see the difference.
https://github.com/VirtoCommerce/vc-platform/blob/master/VirtoCommerce.Platform.Web/Scripts/app/settings/blades/settings-detail.tpl.html

```
<label class="form-label">{{data.title}} <a href="" ng-click="editArray(data);" ng-if="data.isArray" class="form-edit"><i class="form-ico fa fa-pencil"></i></a></label>
<va-generic-value-input ng-model="data" ng-if="!data.isArray" get-dictionary-values="getDictionaryValues"></va-generic-value-input>
```

https://github.com/VirtoCommerce/vc-module-store/blob/master/VirtoCommerce.StoreModule.Web/Scripts/blades/paymentMethod-detail.tpl.html

```
<label class="form-label">{{data.title}}</label>
<va-generic-value-input ng-model="data" ng-if="!data.isArray" get-dictionary-values="getDictionaryValues"></va-generic-value-input>
```

**Comment by eMazeika** [comment]
If I understand correctly, you want to have individual dictionaries for each store. Currently setting dictionaries are defined on platform level and are not adjustable for each object (store in this case). 
Why would you need that?

**Comment by zhangpeng-kooboo** [comment]
In a different country we will enable different payment methods from the same payment gateway.
e.g. the payment gateway is Ogone, in the Netherlands (Store NL) we will enable IDEAL, VISA and so on. But in American (Store US) iDEAL should be removed as not one use that in American.

**Comment by tatarincev** [comment]
I think you should implement this logic on storefront, where you know all customer geo information and may easy filter and show prefer method in checkout.

**Comment by eMazeika** [comment]
I believe this can be closed as store level settings have been implemented
