### ISSUE TITLE
migrate to elastic search 5.0.0

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#656]
Migrate core libraries to work with the latest elastic search release

**Comment by twish** [comment]
I cannot find any information on the plan to implement this functionality in the roadmap or any other place. Is this something that will be implemented soon or is it far away?

**Comment by IgorisB** [comment]
@artem-dudarev please run search tests for elastic search 5 and identify compatibility issues, so we can estimate migration efforts

**Comment by artem-dudarev** [comment]
Switched NEST to v5.3.0 and fixed Elasticsearch provider.
There is NEST v5.3.1 already but it uses Newtonsoft.Json v10.0.0 so we should upgrade platform first.
Tests on Jenkins will fail until we install Elasticsearch v5.x there.
