### ISSUE TITLE
Add a new product property, 'ValueType' is 'DateTime' and 'Multi language' has been selected, the date picker does not shown.

### ISSUE THREAD

**Issue by zhangpeng-kooboo** [VirtoCommerce/vc-platform#657]
When I add a new product property, 'ValueType' is 'DateTime' and 'Multi language' has been selected, the date picker does not shown.

**Comment by OlegoO** [comment]
Multi language should not take affect to DateTime

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #61](https://github.com/VirtoCommerce/vc-module-catalog/issues/61) via [**ZenHub**](https://www.zenhub.com/)
