### ISSUE TITLE
Audits still gets recorded even when an action fails

### ISSUE THREAD

**Issue by Skrypt** [VirtoCommerce/vc-platform#658]
Here, I'm developping a custom module that looks a lot like Quotes module. When I'm trying to update my records from the UI I get a 500 error because I did not implement that part yet. Though, I can see that the changes are getting recorded just like if it did not return any error 500. I can see that the data has not been updated in the database either. I'm guessing here without looking that the events are getting triggered but they don't know if there is any error returned from them.

**Comment by tatarincev** [comment]
Could you explain more detail, which kind of problem you facing? Manager error UX or something other?

**Comment by Skrypt** [comment]
Was having a non-nullable database field and was sending a NULL value to the Web API POST method. Was returning me a error 500 because of database validation. It's a hidden field in that form which I did'nt even implemented since it is "old data". Sure, that it should never happen, but it also felt strange that the audit was getting recorded. Somehow the Audit should not get recorded since there is an error and the record never gets updated. I can demo you if you need.

**Comment by tatarincev** [comment]
I got it, That happened because the audit logs recorded before as main object  will saved.  Need this somehow repair later. Thanks.

**Comment by tatarincev** [comment]
Need to define two event types raised Pre and Post event types and write audit information on Pre event.
(Or wait until we do not implement CQRS pattern in Qquote module) 
https://github.com/VirtoCommerce/vc-module-quote/blob/master/VirtoCommerce.QuoteModule.Data/Services/QuoteRequestServiceImpl.cs#L82
