### ISSUE TITLE
Dynamic virtual catalog and categories

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#665]
Possibility to dynamically link products and categories to virtual catalog. Conditions should be based on search queries (similar to Lucene or Elastic syntax)

**Comment by user386** [comment]
This is the idea I've got so far:
1. Select category maximun size
2. Select search criterion (choose one)
   - New Arrivals
   - Best Seller
   - Most Viewed (if possible)
   - Most Commented
   - Popular (most viewed + most commented)
   - Property Value
3. Select time interval (combine with the criterion)
4. DONE (generate the desirable category)

**Comment by miguelhasse** [comment]
The search criterion should include item properties (eg. create category based on Brand or Type).

**Comment by Woland2k** [comment]
This is an important functionality and is related to epic support of external catalogs. It should also allow materializing catalogs (meaning products will be added to catalog as links instead of performing search in runtime).

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-102
