### ISSUE TITLE
Plug-in extension

### ISSUE THREAD

**Issue by papyr** [VirtoCommerce/vc-platform#670]
Hi, this looks very interesting, I have been using Nopcommerce, smartstore and magento for my clients, I have a few questions and want to try it out.

- [x] Does this let us develop plug-ins easily
- [x] Do you have dynamic roles for users
- [x] Is it easy to theme
- [x] What license is the virtuo code/product under, can I use it like Orchard or WordPress commercially or for personal use

thanks

**Comment by tatarincev** [comment]
https://github.com/VirtoCommerce/vc-samples -  sample modules solutions code
https://virtocommerce.com/docs/vc2devguide/development-scenarios/developing-a-custom-solution - complete tutorial how to develop solutions with VC platform
https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/creating-new-module - how to create new module

Yes you can  create custom roles composed with any from available permissions and even bounded with specific scope. (See orders where I responsible and etc) . Read more  about VC security - https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/basic-functions/working-with-platform-security

At the current moment VC themes full compatible with Shopify themes. https://help.shopify.com/themes/development/getting-started we are use Liquid markup syntax and the same Shopify themes objects. 

Here is our license details https://virtocommerce.com/open-source-license
