### ISSUE TITLE
Manually deleting one of the modules prevents admin from running

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#674]
To replicate remove pricing module directory from Modules. The correct scenario should be admin opening with error warnings.

![image](https://cloud.githubusercontent.com/assets/1566470/20817148/ce107b08-b7da-11e6-9c2b-c408e4925cdf.png)

**Comment by asvishnyakov** [comment]
Pricing modules manually deleted:
![screenshot 330](https://user-images.githubusercontent.com/6369252/29027841-cc8ee140-7b9b-11e7-91aa-8ab740097962.png)
Pricing & Marketing modules manually deleted:
![screenshot 331](https://user-images.githubusercontent.com/6369252/29027842-cc94bab6-7b9b-11e7-810f-4e2dd10c8aa0.png)
