### ISSUE TITLE
Auto rest client generator problem

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-platform#675]
When I'm running auto rest client generator I'm getting that error:

`Unhandled Exception: 
System.IO.FileLoadException: Could not load file or assembly 'AutoRest, Version=0.17.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> 
System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---`

**Comment by tatarincev** [comment]
Found solution there
https://github.com/Azure/autorest/blob/master/docs/developer/guide/building-code.md
need to execute next command
`"C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\sn.exe" -Vr * "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\sn.exe" -Vr *`
