### ISSUE TITLE
JS shopping cart module - third party authentification

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#681]
Main goal for js cart authentication looks like this:
We should get user id on js cart client script by reading special known cookie or other header which can be assigned in other applications

Resources:
https://github.com/openiddict/openiddict-core
https://auth0.com/
https://auth0.com/blog/cookies-vs-tokens-definitive-guide/

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-javascript-shoppingcart #3](https://github.com/VirtoCommerce/vc-module-javascript-shoppingcart/issues/3) via [**ZenHub**](https://www.zenhub.com/)
