### ISSUE TITLE
Order module - implement base state machine for order states

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#684]
State machine should be fluent declarable
Order status should evaluated with other order document statues
State machine should be easy  extensible and override-able 

| Order status   | Payment status                                                          | Shipment status                                           |
|----------------|-------------------------------------------------------------------------|-----------------------------------------------------------|
| Unpaid      | Sum of payments with statuses  (Paid and Authorized) < Order.GrandTotal | Any                                                       |
| Pending        | !Unpaid                                                               | All New or Canceled                                       |
| Processing     | !Unpaid                                                               | Any PickPack                                              |
| Ready to send  | !Unpaid                                                               | All ReadyToSend or  ReadyToSend and Cancelled             |
| Sent           | !Unpaid                                                               | All Sent or Sent and Cancelled                            |
| Partially sent | !Unpaid                                                               | Any Sent and least one on with New, PickPack, ReadyToSent |
| Canceled       | -                                                                       | -                                                         |

Some resources:
http://www.hanselman.com/blog/Stateless30AStateMachineLibraryForNETCore.aspx?utm_content=buffer3a14d&utm_medium=social&utm_source=linkedin.com&utm_campaign=buffer

**Comment by eMazeika** [comment]
Does this change disables manual order status changing in UI?
Should currently predefined statuses set {New, Processing, Cancelled, Completed} be updated?

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-52
