### ISSUE TITLE
Need to support long breadcrumbs in catalog items blade.

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#687]
Current trimmed breadcrumbs not worked properly.
![image](https://cloud.githubusercontent.com/assets/7566324/25091479/9d15459a-2389-11e7-9599-61b4f1b67bf3.png)

**Comment by asvishnyakov** [comment]
There is some problems and questions about that.
Currently, breadcrumb item width limited to 110px and we always show first and two last breadcrumb items. Should we leave this? If not, should we limit breadcrumb item size, but display as much breadcrumb item count as possible or we want to limit breadcrumb item count, but display as long text in breadcrumb item as possible, or we want to combine both behaviors?

**Comment by tatarincev** [comment]
Would be nice try the both solutions.

**Comment by asvishnyakov** [comment]
@tatarincev You mean combine both? Or create two separate solution (one for width limit, one for count limit) and then compare it?

**Comment by tatarincev** [comment]
@asvishnyakov I think full breadcrumbs path would be preferred solution.

**Comment by asvishnyakov** [comment]
@tatarincev What we need to do in this situation?
![Broken breadcrumbs](https://user-images.githubusercontent.com/6369252/26978504-2d7692e4-4d45-11e7-937e-3fdf2e049fd0.png)
Possible solutions:
1. Use Windows behavior and display button with dropdown where user can choose any level:
![Windows breadcrumbs behavior](https://user-images.githubusercontent.com/6369252/26978545-5136598a-4d45-11e7-8dd4-6dc51197b196.png)
2. Collapse first breadcrumbs to single `...`:
![Single three dots](https://user-images.githubusercontent.com/6369252/26979382-02245434-4d48-11e7-87e5-8c1088eff61d.png)
and move to this level when user click, i.e.:
2.1. Current path is `root 1 2 3 4 5 6`
2.2. When user go deeper, it changes to `root ... 2 3 4 5 6 7`, then `root ... 3 4 5 6 7 8`, then `root ... 4 5 6 7 8 9`.
2.3. When user click to `...` he/she go to level 3 and breadcrumb changes to `root 1 2`

**Comment by tatarincev** [comment]
I think that  need to display the full path on several lines without any trimming.

**Comment by eMazeika** [comment]
Several lines doesn't look as a good idea as the space (height) is limited to 1 line there (for ui-grid to fit in the blade).
And several lines would look very strange, IMHO.

**Comment by OlegoO** [comment]
We should use:
[Root] 
[Root] * [1] 
...
[Root] * [1] * [2] * [3]
[Root] * ... * [N-1] * [N]

**Comment by asvishnyakov** [comment]
We MUST NOT use inline styles. Because blade width class specified after breadcrumbs, we can't use css selector to generate breadcrumbs width based on blade width. So the only possible solution - relative width in percents or something like this. I think we need @cukep2012 specialist opinion

**Comment by asvishnyakov** [comment]
@OlegoO And it's foolishly to use [Root] * ... * [N-1] * [N]. You can open Root via previus blade, you already in N and you can open N-1 via Back button:
![image](https://user-images.githubusercontent.com/6369252/30968157-cfebc934-a477-11e7-94c7-99295608a2ad.png)

**Comment by asvishnyakov** [comment]
I'll prefer to revert changes and continue discussion and consults with @cukep2012

**Comment by OlegoO** [comment]
@eMazeika, Approved. You can publish release. 
@asvishnyakov suggest you rules and create a new ticket.

**Comment by OlegoO** [comment]
@eMazeika we should fix bread crumbs on platform level, remove inline style from catalog module.

**Comment by OlegoO** [comment]
Removed inline styles from code
https://github.com/VirtoCommerce/vc-module-catalog/commit/0db6627c2365bd304e9e9857cf348e733772b69d

**Comment by asvishnyakov** [comment]
@OlegoO https://github.com/VirtoCommerce/vc-platform/commit/ff5f2e4ac8616da3fe5f4a7ba25d1e3c858cdd04#diff-f2a213784d680cb4c05135adce6b6fce

**Comment by tatarincev** [comment]
Released https://github.com/VirtoCommerce/vc-platform/releases/edit/v2.13.17
