### ISSUE TITLE
Asset management - Can not delete file from folder if use Azure Blob Storage for assets

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#692]
I can not delete file from folder if use Azure Blob Storage for assets.
Select file, click delete button, confirm and see file in folder. 
No errors. No warning.

**Comment by tatarincev** [comment]
Read more about how to assets work in VC might here https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/basic-functions/storage-of-files
