### ISSUE TITLE
Write  sample module with  external pricing data

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#693]
User requirements :
 I have gold product so i want to calculate my price for the product according to current Gold Rate multiplying with the weight of that product and add some making charges for that.

It is not complete tutorial how to do it, but may be it will enough for you
To implement dynamic prices you should implement this service interface in your custom module
https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.Domain/Pricing/Services/IPricingService.cs
you may just derive your pricing service implementation from default pricing service implementation 
 https://github.com/VirtoCommerce/vc-module-pricing/blob/master/VirtoCommerce.PricingModule.Data/Services/PricingServiceImpl.cs  and override only EvaluateProductPrices method which will be request actual prices for given products.
.

**Comment by tatarincev** [comment]
@eMazeika  could you include example of grid extension point to this sample?

**Comment by IgorisB** [comment]
We made the https://github.com/VirtoCommerce/vc-samples/tree/master/External.PriceModule sample module witch demonstrated how to extend current pricing model with new price type. And article https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/extend-ui-grid-editable that describes sample functionality.

**Comment by eMazeika** [comment]
The article somehow doesn't mention for the most interesting part of code:
```
       editableCellTemplate: 'sale-cellTextEditor',
       validators: { saleValidator: true },
       cellTemplate: 'priceCellTitleValidator',
```
