### ISSUE TITLE
Just spinning during the installation

### ISSUE THREAD

**Issue by varghesep** [VirtoCommerce/vc-platform#695]
I'm following the instructions on this [page ](https://virtocommerce.com/docs/vc2devguide/deployment/platform-deployment/source-code-getting-started) to install the platform on my windows 10 laptop. After the installation, I ran the admin page. But the page at the URL http://localhost/admin is just spinning, no database is created and no error messages. 

- The connection is correct because when I used the wrong user name, it gave me a connection error.
- I'm using SQLEXPRESS.
- I dont see IIS_IUSRS in the list of users

![image](https://cloud.githubusercontent.com/assets/12233474/21965943/5c3caf56-db2f-11e6-80dd-debdc7528457.png)

**Comment by eMazeika** [comment]
I believe that you've identified the issue reason correctly: insufficient permission for IIS_IUSRS. What users/roles are available if you click the "Edit" button? IIS_IUSRS should be there too...

**Comment by tatarincev** [comment]
You are used pre-compiled platform version?

**Comment by varghesep** [comment]
I used the GitHub master branch sources directly.

I see the IIS-IUSERS in the users list, but not when I look at the security tab in the windows explorer 👎 

![image](https://cloud.githubusercontent.com/assets/12233474/21984088/d9b77c56-dbb9-11e6-8241-d94ef2cf3d68.png)

**Comment by tatarincev** [comment]
Grant special permissions it is optional step for installation process, you might omit it in your installation. Main problem in  the lack of any errors  on first application access. Could you send screenshot of your IIS application and please ensure what your platform solution was builded successfully.

**Comment by varghesep** [comment]
I added IIS_IUSRS to the folders of vc-platform. Now I get this error now:

![image](https://cloud.githubusercontent.com/assets/12233474/22005524/939f0796-dc29-11e6-96d9-d2fa1f060fc6.png)

The screenshots of the IIS below:

![image](https://cloud.githubusercontent.com/assets/12233474/22005542/c758fede-dc29-11e6-9c2e-5ef79ce3dad5.png)

![image](https://cloud.githubusercontent.com/assets/12233474/22005562/f9ad5ec0-dc29-11e6-94c9-288ff3bffffb.png)

![image](https://cloud.githubusercontent.com/assets/12233474/22005593/380d680e-dc2a-11e6-921c-0f1b5a4b7f0f.png)

**Comment by tatarincev** [comment]
Do  you compile platform solution after start?

**Comment by varghesep** [comment]
@tatarincev Yes

**Comment by varghesep** [comment]
I reverted all the sources back to as the master branch, restored the nuGet packages, following the instructions to set the permission for the IIS_IUSRS.

I still see the page is spinning without giving any errors. No database is created even after 2 minutes 👎 

![image](https://cloud.githubusercontent.com/assets/12233474/22020187/92adf574-dc7c-11e6-8bea-35c124aee11b.png)

**Comment by tatarincev** [comment]
Could you try to install pre-compiled platform version? Just download https://github.com/VirtoCommerce/vc-platform/releases/download/v2.12.7/VirtoCommerce.Platform.2.12.7.zip unpack to folder and reconfigure IIS application to this folder.

**Comment by varghesep** [comment]
I think I have found the issue. I changed the timeout in the web.config from 420 to 15 and not it fails fast. I also found this during the debugging. The error is the failure to connect to the database.

![image](https://cloud.githubusercontent.com/assets/12233474/22022899/77394412-dc89-11e6-8a34-080b0a15226c.png)

I'm using the SQLEXPRESS

![image](https://cloud.githubusercontent.com/assets/12233474/22022940/ae94d46c-dc89-11e6-9e62-af0101af4168.png)

The connection string is:

![image](https://cloud.githubusercontent.com/assets/12233474/22022989/ef470516-dc89-11e6-8ca2-13d61241e224.png)

**Comment by tatarincev** [comment]
You have wrong connection string. try to replace ./SQLEXPRESS to (local) DataSource=(local).

**Comment by varghesep** [comment]
Finally it is solve 👍 . The issue was with the connection string. I dont have the (local) DB so I should use the SQLEXPRESS DB without the () surrounding them.

![image](https://cloud.githubusercontent.com/assets/12233474/22025322/c85c476e-dc92-11e6-83f2-62fb274c5289.png)
