### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by varghesep** [VirtoCommerce/vc-platform#706]
I'm very much confused by the documentation on this page https://virtocommerce.com/docs/vc2userguide/merchandise-management/products-catalog . 

I'm confused by:

1. items (products) 
**Qn.** _What terminology is being used in the VC platform? Item or Product?_
2. The documentation says every product needs to have a SKU. 
**Qn.** _How the ambiguity is removed when there are product variations? All the variations will have SKU?_
3. "One of the products is the title (main) product being one of the variations at the same time."
**Qn.** _Confused. What is this **title (main) product**?_
4. title product (variation)
**Qn.** _What do you mean by **title product (variation)**?_

Instead of repeating the same description under _Product and Product Variations_, can this documentation be improved and more understandable?

**Comment by eMazeika** [comment]
The terms "Product" and "Item" do mean the same concept in VC. Did “the ambiguity” mentioned in the docs confused you?
Regarding to Variations and Products: from the system’s point of view, we don't have special object type for variations, we have only product type and product objects. If you’d have three kind of shoes (blue, red, green), these were represented as three product objects with own descriptions, images, SKUs, etc. in the system. One of those three products should be titular (main) for grouping in presentation purposes. 'Variation' may inherit some information from 'Titular' product such as description, images, properties, etc. (for more convenient management), but they also can have individual values of those properties.

Does this make you a better picture?
