### ISSUE TITLE
Need to improve Content publishing list in Dynamic content

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#709]
We have a lot content publishing elements and UI is not good.

Content publishing list:
1. Sort a list alphabetically
2. Add ability to filter (By default: don't display not active or expired)
3. Add ability to search by keyword
4. Provide ability to create a folder

Content publishing element:
1. Provide ability to clear Start and End date. (I see Clear button, but it doesn't work and I see date again after save and refresh)
2. Provide ability to set custom name (name is generated automatically)

![image](https://cloud.githubusercontent.com/assets/7639413/22237748/742ce188-e216-11e6-8946-16adbd22c60d.png)

**Comment by tatarincev** [comment]
Partially done in latest marketing module release.
All not completed requirements were included in the https://github.com/VirtoCommerce/vc-platform/issues/689 issue
