### ISSUE TITLE
The Native VirtoCommerce catalog data import from CSV doens't work for virtual catalog

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#714]
The Native VirtoCommerce catalog data import from CSV doens't work for virtual catalog.

**Problems:**
1. Doesn't set [Csv column delimiter] by default. (Which I should use for CSV file from "Native VirtoCommerce catalog data export to CSV")
2. Doesn't restore link on folder 
3. Doesn't restore link on product
4. If delete virtual folder after import, it deletes products from physical catalog instead of remove link.
5. Errors like Null Reference are occurred 

**How to reproduce the error:**
1. Create a virtual catalog with link on folders and link on products
2. Export virtual catalog using "Native VirtoCommerce catalog data export to CSV". 
3. Create a new virtual catalog
4. Import virtual catalog using "Native VirtoCommerce catalog data import from CSV". 

![image](https://cloud.githubusercontent.com/assets/7639413/22363021/e9f5ce10-e46f-11e6-97a4-23983b7b23ec.png)

**Comment by eMazeika** [comment]
Any problem with this ticket? If not, place it "On Deck", please

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog-csv-import #2](https://github.com/VirtoCommerce/vc-module-catalog-csv-import/issues/2) via [**ZenHub**](https://www.zenhub.com/)
