### ISSUE TITLE
Chrome and Safary are not rendering SVG referenced via <img> tag from Azure Blob

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#718]
We use SVG for product images, but Chrome and Safary are not rendering SVG referenced via <img> tag from Azure Blob.

What I found out was that the content type header of azure server wasn't correct. I fixed it by adding Content Type "image/svg+xml" manually.  

http://stackoverflow.com/questions/10040403/set-content-type-of-media-files-stored-on-blob

Very nice, if you set correct Content Type, when upload file to azure blob-storage.

**Comment by asvishnyakov** [comment]
Probably by design; waiting for user response, On Hold until that

**Comment by asvishnyakov** [comment]
Already fixed
