### ISSUE TITLE
Add ability to overwrite title, description and SEO link for products

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#719]
Since same product can be displayed by multiple sites, each site needs a slightly different description, product name and SEO link for a product to make SEO optimized.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #36](https://github.com/VirtoCommerce/vc-module-catalog/issues/36) via [**ZenHub**](https://www.zenhub.com/)
