### ISSUE TITLE
swagger documentation xml comments is sometimes missed

### ISSUE THREAD

**Issue by pierresetteskog** [VirtoCommerce/vc-platform#720]
We are very depending in our own module to have working xml comments on our api and it seems to be a general problem in the later release of virto. see picture or commerce core module
http://demo.virtocommerce.com/admin/docs/ui/index

![image](https://cloud.githubusercontent.com/assets/4455363/22550773/f6343f68-e951-11e6-85a9-a08dc74c67c7.png)

**Comment by artem-dudarev** [comment]
The build script on Jenkins had invalid parameter and all XML documentation was stripped from the output directory.
I've fixed it and next releases should contain documentation again.
