### ISSUE TITLE
virto login box dosnt shows up

### ISSUE THREAD

**Issue by pierresetteskog** [VirtoCommerce/vc-platform#721]
this bundle is sometimes stucked and gives a timeout which results in that the login box is not showing.
It's really strange. Often happening the first time accessing a new server.
/scripts/angular?v=iDGrLu6d6hEbUqHFT5VG_ZxNOyakgem1HzFXwHhJzrc1

Hard refresh and different browser gives the same result. The last time it happened it started to work after swithing to https.

![image](https://cloud.githubusercontent.com/assets/4455363/22550866/78bb46ca-e952-11e6-931c-cc30e5a03192.png)

**Comment by tatarincev** [comment]
It is happened on Azure cloud  app?

**Comment by pierresetteskog** [comment]
Yes and it seems to happen on small servers.  Usually i scale up the server.


Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Tatarincev Eugeney <notifications@github.com>
Datum: 2017-02-02 15:05 (GMT+01:00)
Till: VirtoCommerce/vc-platform <vc-platform@noreply.github.com>
Kopia: Pierre Setteskog <pierre.setteskog@wipcore.se>, Author <author@noreply.github.com>
Rubrik: Re: [VirtoCommerce/vc-platform] virto login box dosnt shows up (#721)


It is happened on Azure cloud app?

-

**Comment by OlegoO** [comment]
Fixed
