### ISSUE TITLE
Could not restore price list

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#722]
Exported demo price list and try to import on new site, but get error (( source is null

I've attached example
[exported_data (1).zip](https://github.com/VirtoCommerce/vc-platform/files/749957/exported_data.1.zip)

**Comment by Andrew-Orlov** [comment]
Seems that export was done within old version of Pricing module and attempted to import to a newer one: attached zip contains wrong JSON structure (for a current Pricing module version) - `Assignments` and `Prices` collections are belong to every `Pricelist` object. For current version of Pricing module `Pricelists`, `Prices` and `Assignments` are on the same level.
