### ISSUE TITLE
[High] Improve UI|UX in Promotion List

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#723]
I would like to see real quick in promotion list:

 Active or not (could be green background - very light green - if active and very light red-ish if not active)
- [x]  Which store
- [x] End date or number of products limit left
- [x] Filter: by store or hide not active promotions
- [x] Have ability to clone (create a new promotion base on already created promotions)
- [ ] Would be nice if a promotion has localized "description", perhaps we can use that description on Product page. 

![image](https://cloud.githubusercontent.com/assets/7639413/22595296/8a7a2d4e-ea2f-11e6-8b40-8e7362397442.png)

**Comment by tatarincev** [comment]
All of these requirements may be achieved by using ui-grid columns customization and sorting for some while.

**Comment by OlegoO** [comment]
> All of these requirements may be achieved 
only first two

**Comment by eMazeika** [comment]
@tatarincev any comment on requirements 3-6? Can any/some of them be implemented quickly? Or "won't fix"?

**Comment by tatarincev** [comment]
At the moment we have not implemented promotion clone functionality and description localization.
Promotion clone functionality can be implemented only on client  code side, by calling POST api/promotion method with promotion without Id.

What relate to description localization, current description used as system and represent to short promotion description for using only on system level. You might achieve  promotion localization description by using localization resources on client (storefront) side, where promotion key represent as  key of localization resource.

**Comment by eMazeika** [comment]
Promotion cloning implemented
