### ISSUE TITLE
[High] The Catalog module doesn't index linked categories or products in Virtual Catalog

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#727]
The Catalog module doesn't index linked categories or products in Virtual Catalog

We added a link on category or product in Virtual Catalog 
And didn't see it on storefront because Catalog module did not index them automatically.

To fix it, we need to rebuild catalog every time (((.

**Comment by eMazeika** [comment]
Any problem with this ticket? If not, place it "On Deck", please

**Comment by OlegoO** [comment]
Workaround: 
1. Go to search index
2. Select Categories and Products and click build index
