### ISSUE TITLE
Fail when request product with many associations in Storefront

### ISSUE THREAD

**Issue by FreeKen** [VirtoCommerce/vc-platform#731]
When I want to get the product via a standard controller Storefront products, it makes a request of all products from product associations, and falls because that it requests through api/catalog/products?ids thereby exceeding MaxLen request

**Comment by OlegoO** [comment]
http://########.azurewebsites.net/api/catalog/products?ids=3f3e7c74fb444efc93e0b5b2403f7f0c&ids=7b1e36b5f3e44559837b6222a22133ff&ids=8e4ca90ca8c44cb8ae925a7c436bd968&ids=a1199826c60144f5bd155f7395fbe951&ids=2518653257974a35aae22cf571cc2549&ids=40fe91d570b34fd295263bdb83e41c2a&ids=27f394dd7c174035b96e3e967b9e38db&ids=4586c1b9b5524d2cb9b0bcf60cd6bace&ids=1985997f1209458fa11e6e3352eb39c1&ids=776c197451b94ac0937c630323225405&ids=6569f670ef8f4e7491e9c5ad85d29cc6&ids=6cbbe268a5a84895a9bdec91ab8d8caf&ids=5be7ab5212db493f956ded063cff2027&ids=7f4d176f3f5d4167bc2c45ea58dba0c8&ids=ee0c470efab84bb690da2f99b692ba06&ids=e5c0457f3bf648029edbaa70e61bbb58&ids=4c38431091d446ac87decd3f1763a31b&ids=e34366a4cfc24f0cb214c8fb376530e3&ids=2ec8880a4429489799ad44296c8073ee&ids=4eef61304bba4e3998edc759fc2e15c7&ids=4cd30608ec1748aca1d22a4b280e16bf&ids=483caab5fb8a4f9f8d69bf598cfe6058&ids=475394e29bcd47d3b6dc5a6396a2a7b3&ids=895725525ab74646844f13c05536b757&ids=d5d2aafc8d9a47f9924a2e83d35ff1c4&ids=0f5269dca1cf4e28a3e0f2bb1031d687&ids=33514a93d055426e9a64eff2328a7abb&ids=9f46cbab046a4043a300659aed042601&ids=e703f7aa81ff47bda9190fa5bc85991d&ids=64db89209e814423a988e89b887f0415&ids=4b98958379124b66aa74e704e810deea&ids=e7841fc85fa84585810b778fe17224ba&ids=d9a5df3e26c1477192cd057d854c5548&ids=439e877ff1fd4976b1a9f704374e964d&ids=2189dfa686ce43ed92c2c3fd59efbd63&ids=f4a52258ce364229aa90045fcdbfd954&ids=96e983523c4443beaac95b29ad6d25e1&ids=2835656df1ee430999b74d9e6b5d1e42&ids=05db864bbeb7428c8fce04dbfd74e287&ids=a25e967aad9442c2971fe8be12c44319&ids=dc80921c94e647d8a8c6ce79df6ef1dc&ids=ee5708f715e64f918f50a23a8b043527&ids=062f440bb35f431e83260a3250bf3df9&ids=0c60c14ab1f24d3c82807bd414293d50&ids=60f857d2fa664df39a4f02b69f7cfc16&ids=9cf934d4d40341d78e10471b8a273ce1&ids=bfd2aa2c30924a6fb955155dbcd068b1&ids=a1c89881408f4ae1bfc771696e9a8602&ids=742c322ae9a64cfcb0a7c37f21f1e9d3&ids=949621675cd24852b249305bfcd11780&ids=359e0f0c3be74fa3b9f4ec2ba56a0c2b&ids=98fd709dae3b409691319a2268161055&ids=13447fb166fb481dac4c893cea8f2959&ids=d8cd0faf12624aa994395e813c196da6&ids=a0e5fa65e3454545903210a1ddd513e6&ids=63033e1f77204e3ba56cc7fc30231be4&ids=3f81d6691122482d820ca9c9c97bdf6d&ids=56ccc01b1c244e5abafec2bbee553beb&ids=2bcd9ba061ad444bb1bf762de255df26&ids=db9d8890852749d7a550d3f2b77dc2de&ids=f5c0772168014161b7051297c73405f3&ids=b5c822fcfd894aaf9045b445c25e8f6b&ids=e14609d746ae4bf692c3718cd019a474&ids=05687daa3d5e4ab787a086a8eafcdc07&ids=f6adf72f6d74475b94a3f7de3a664eaa&ids=322a664765534e319bd2f1bb2d2fccf5&ids=eea62c90bd1f4737b19f24e22b02040c&ids=1b48af1683af42799581d5c6d3c27a8e&ids=a2df5918a02a4fea9775c281449aedbf&ids=974cf3a461554a22803fdb2144531174&ids=c5faeee0b4c943ea9e5ec3800c99a26a&ids=a236bbdb7b954ecabd8584e5ae0031b2&ids=95082497e3624e71a7fe3eb47955a1e2&ids=f01119fc3cb34b82bfeb02f98c407509&ids=a689f3ed1e974f25b2162215d768aed8&ids=59f832b5a9674136b8635aa9a1412d53&ids=9a5cd6e7849e4c009f71b90e1918ea15&ids=116519c4728143ad8bbf953969473d39&ids=549fb8c6d7b443b597589556ae84db0b&ids=f059d63daf44423b902efca4c6728f5c&ids=ae6a470bc54540328d6b6202d67b5107&ids=79fc52e2d3504a019b314a53307df16f&ids=abbd8aad77264af79a88efe794f7b8d6&ids=97f8bc0829e24f8bb56aaed1ef688c67&ids=16eb28d0c08f413cb5de682b7edcac84&ids=de84f63ca99442de94cacd1113cf5c28&ids=92c56ba251e6489bbd0e480353e0a06a&ids=d8c5715996be47cc82f09630b538ba4d&ids=036ce83905ea47088340fe9ebcd7840a&ids=69d165cfaa67469ba8c3baff3c6a69cd&ids=f4bb365a3a0f40318d9a0c539581d0ca&ids=78cda8a13c8441898521b607880e773f&ids=ec4e1688eb0c49798a7dc7009513c3bd&ids=c5cf64e2cc31437aa7b133812703080f&ids=d9fa6849211b469591c1b14f4c5b2ab7&ids=06b475a63b7e4546b3514fe834f6499f&ids=31941267ee114c92a6d745a0471e18af&ids=215e2bc99b0d4bae94643b8c90723b88&ids=baf26ed78e5842bb8fd2f7e637e63deb&ids=cf2b6421858447a1b1df165af3aa30cc&ids=01f437ea521f4471bc6673da63149a0c&ids=9d1cf7dc8e6740fbbc95c940a60e7ec9&ids=dd8745c149b54275b4a0cdbbdd0a1573&ids=ab60a29f384e4692aa9b255742c168f1&ids=35b9cd8b2987447e980126a79a621e33&ids=342cefb285c84ee497a9b642214b2dbc&ids=8b8e6eea34334185a4cdefdcf498c055&ids=5be3384058c147e188e25af922c7b405&ids=758c01dac977482d8102dc15a7db448a&ids=d44e64ec1c274122ac9c1c60f632d935&ids=2186a99b256543c79336fe9213f82da2&ids=9564fd64ef804afca5e6f0cc39a66040&ids=302591e9047d43dc8aa5307d72964f3e&ids=7ed5c68eda5c49768aecce633463fa29&ids=853c44e412c9484ca7ce5d5f5ef0a9a2&ids=da2412d9d53143c98cd6ec0936497fc1&ids=220700cbe7d74c5f9b939c0e715a61d7&ids=7c654ad55bca45debb2ce531b700d2fd&ids=eea0a00636e2401ea0884c7deba59dd6&ids=efb90cd35dc54513bc1a0330f187c185&ids=ccb0549004a54374ba5fc78cc41e797b&ids=3266b33d002045aab72a5b8b466ccb89&ids=997d615f3a0f40619d91221120c12992&ids=ee805626e4e2424da21281c97f0b11fa&ids=78f04fe196424cf088ca115b9836f1b7&ids=4be4819522d54ea2943a6e92449fc0da&ids=bbf0dd337517412a90867c124ee1bce5&ids=e7e748368c4549deb6611cfc38986f2a&ids=6443e4c71a344adca9ab52986c0f8327&ids=009cf824039d4f15a53a78304ad97f51&ids=0f68072d30774d95bd961904763858e8&ids=4cbdf307d39a42b7ae3fdc0b77ef3506&ids=4e29dd32ca9c4ea69607f00f170ba98b&ids=32022c2dc62a48db977472a5d3239de5&ids=65aa23f1b3b5492fab79cd991acdd176&ids=cfa2123dadae4a4a9fef625ae2ccf87d&ids=2e7d386e611444b899f42aabd603e097&respGroup=1601

**Comment by OlegoO** [comment]
Should use POST instead of GET

**Comment by tatarincev** [comment]
Duplicate, merged with  https://github.com/VirtoCommerce/vc-platform/issues/758
