### ISSUE TITLE
Updating an email address in Customer details, Manage emails does not update other tables

### ISSUE THREAD

**Issue by tsmith-sdm** [VirtoCommerce/vc-platform#733]
dbo.PlatformAccount.UserName and dbo.AspNetUsers.Email are not updated after updating dbo.Email.Address from Admin Contacts, Customer details, Manage emails. 

_This is based on the assumption of an email only based login and so username and email should be identical_

**Comment by tatarincev** [comment]
Because `Member.Emails` it is a table  from absolute different subsystem related to customer profile.  `dbo.PlatformAccount.UserName` and `dbo.AspNetUsers.Email` these tables are related to other Security subsystem and cannot be updated within of customer contact update. One customer contact may have multiple emails records which stored in `dbo.Email` table and not related to security accounts emails.

**Comment by tsmith-sdm** [comment]
I was looking for the ability to edit / update a customer's email for instances when they want to change their email, forget their password and lose access to their previous email.

**Comment by alewis-github** [comment]
I just came across this thread as I am having some problems understanding how the Virto "customer" tables all interact.

Firstly in the version I have, there is a column in PlatformAccount table called MemberId which is declared NVARCHAR(64). By observation, this DOES correspond to the Member.Id column, but that is declared NVARCHAR(128) so no foreign key association is possible. However, there does seem to be this link at least between the "Member" world and the "Platform" world. But the only password information I can see being held anywhere is in the AspNetUsers world, which has no apparent links to anything else. But in our world, Customers can log in to the website, and so surely also must be AspNetUsers. Is it really true that we can't link customers to their login details?

I think I must be misunderstanding something!

Ade

**Comment by tatarincev** [comment]
VC  contains three 'worlds' related to authentication, authorization and customer profiles.

**First world** - ASP.NET identity, used only for authentication, social logins, password storage and other auth tasks (all tables with prefix `AspNet`)
**Second world** - VC platform security which main task is authorization which store account  ACL, user type and API keys. Table `PlatformAccount`. all records from this table have same id as user from AspNet tables.
**Third world** - VC Customer module it contains all data which related to CRM (contacts, emails, phones etc) each customer contact in this system may have multiple or zero security accounts from 'second world'. Member.Id 1 - 0..*  PlatformAccount.MemberId 

But all of three 'worlds' are absolutely isolated and might be replaced to other implementation independently!

**Comment by alewis-github** [comment]
OK, I missed the link between ASPNetUsers and PlatformAccount!
