### ISSUE TITLE
Creating order in frontend generates the following exception

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#735]
System.Exception: Operation returned an invalid status code 'InternalServerError'
 {"message":"An error has occurred.","exceptionMessage":"Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.\r\nThe FullName field is required.","exceptionType":"System.ServiceModel.FaultException","stackTrace":" at VirtoCommerce.Platform.Data.Common.ExceptionExtensions.ThrowFaultException(Exception ex) in C:\\Projects\\GitHub\\vc-platform\\VirtoCommerce.Platform.Data\\Common\\ExceptionExtensions.cs:line 13\r\n at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.CommitChanges(IRepository repository) in C:\\Projects\\GitHub\\vc-platform\\VirtoCommerce.Platform.Data\\Infrastructure\\ServiceBase.cs:line 21\r\n at VirtoCommerce.CustomerModule.Data.Services.MemberServiceBase.SaveChanges(Member[] members)\r\n at VirtoCommerce.CacheModule.Web.Decorators.MemberServicesDecorator.SaveChanges(Member[] members)\r\n at VirtoCommerce.CustomerModule.Web.Controllers.Api.CustomerModuleController.UpdateMember(Member member)\r\n at VirtoCommerce.CustomerModule.Web.Controllers.Api.CustomerModuleController.UpdateContact(Contact contact)\r\n at lambda_method(Closure , Object , Object[] )\r\n at

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-order #15](https://github.com/VirtoCommerce/vc-module-order/issues/15) via [**ZenHub**](https://www.zenhub.com/)
