### ISSUE TITLE
The Catalog blade show wrong catalog & categories list when user is non-administrator

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#739]
How to reproduce:
1. Create new user
2. Assign role "Clothing accessory category manager" to it
3. Open catalog, try to browse catalogs. You will see pic 1. instead of pic. 2.
![pic. 1](https://cloud.githubusercontent.com/assets/6369252/23211939/2b8602c6-f926-11e6-906b-abbe1291e5f0.png)
![pic. 2](https://cloud.githubusercontent.com/assets/6369252/23211942/2f02107a-f926-11e6-9469-82b752c2e08b.png)
You may also try to assign "Electronic  store administrator" role.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #64](https://github.com/VirtoCommerce/vc-module-catalog/issues/64) via [**ZenHub**](https://www.zenhub.com/)
