### ISSUE TITLE
Provide fallback font for unicode support

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#748]
Currently, we have no custom font for Unicode symbols, so browsers render them with standard font. We may provide fallback font (Exo support only latin, latin-extended & cyrillic unicode subsets).

**Comment by asvishnyakov** [comment]
Proposal: Noto font

**Comment by asvishnyakov** [comment]
https://github.com/VirtoCommerce/vc-platform/issues/741

**Comment by asvishnyakov** [comment]
#741

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog.
https://virtocommerce.atlassian.net/browse/PRD-107
