### ISSUE TITLE
Improve blade usability

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#750]
When blade is list/grid, it opens 1st utilizing full width of window (window itself can be resized and blade will resize with it). When user clicks on element in the list, list blade shrinks to normal size (only displaying name + "..." with all other columns hidden) and detail blade opens (doesn't need to be full width, but can be). 

Example: order module. When orders is clicked, we display list of orders in full width, allowing us to show a lot of information about the view. When i click to individual order, we minimize order list to a small blade (allowing quickly navigating between orders) and display order details screen.

**Comment by asvishnyakov** [comment]
Related with #749

**Comment by tatarincev** [comment]
1. All children blades freeze for some time
2. Order items stay on screen when states switched
3. Maximize/MInimize button
