### ISSUE TITLE
Image uploading issue

### ISSUE THREAD

**Issue by AlexMoore94** [VirtoCommerce/vc-platform#752]
It is not possible to upload a picture if an image with the same name has already been uploaded.

*Ex.* If you uploaded a 'picture1.png' then now any file (no matter an image, a text file, an archive or just a set of bytes) you'd upload with the name 'picture1.png' will be displayed as a previously uploaded picture.

**Comment by tatarincev** [comment]
If you mean  product images, then each product assets or image have stored in folder with have name same as product code and it is  expected  behaviour for override if you want to upload in same follder file with name already exist in this folder.

**Comment by AlexMoore94** [comment]
Yes, I mean product images. When I edited svg image that was loaded to product assets and then tried to upload it product image did not change.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #16](https://github.com/VirtoCommerce/vc-module-catalog/issues/16) via [**ZenHub**](https://www.zenhub.com/)

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-catalog #15](https://github.com/VirtoCommerce/vc-module-catalog/issues/15) via [**ZenHub**](https://www.zenhub.com/)
