### ISSUE TITLE
newer version of application insight needed

### ISSUE THREAD

**Issue by pierresetteskog** [VirtoCommerce/vc-platform#753]
because of I want to set my instrumentationkey by code from a virto setting (simpler deployment)
Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.InstrumentationKey = instrumentationKey;

it tracks traces and logs  but all httprequest fails to be tracked to application insigth with error:

> Activated Event Time Duration Thread [msg=HanderFailure];[exception=System.InvalidOperationException: Operation is not valid due to the current state of the object. at Microsoft.ApplicationInsights.Web.RequestTrackingTelemetryModule.OnEndRequest(EventWrittenEventArgs args) at Microsoft.ApplicationInsights.Web.Implementation.WebEventsSubscriber.OnEventWritten(EventWrittenEventArgs eventData)]

I needed to upgrade all application insight packages from 2.1.0 to 2.2.0 then it worked, Can virto be updated with latest nuget packages for application insight next release?

**Comment by tatarincev** [comment]
Yes, no problem, we have plans to make release on this week.
