### ISSUE TITLE
Catalog personalization

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#756]
### Functional requirements:
- Allow to control the visibility of catalog objects such as Product and Categories, through manual tagging of these objects with special attribute `Usergroups` which can contains multiple predefined values which also may be defined for customer profile.
- Inheritance `UserGroups` between  catalogs objects depend on catalog  taxonomy. (products inherit this property from parent category, variation inherit it from main product) 
- Allow to use  `UserGroups` from customer profile to products or categories filtration in the storefront search.
- Display products and categories which are not tagged by any `UserGroups`  for all customers. (Default visibility)
- Allow  to control the visibility of CMS objects such as menu links with related to  catalogs objects.
 
### User stories

- [ ]  As a manager I want to tag product or category with one or multiple `UserGroups` tags
- [ ]   As a customer, I want to see only those products and categories and menu links that have the same value of `UserGroups` as in my profile or do not have them at all.

**Comment by megafreeman** [comment]
Released https://github.com/VirtoCommerce/vc-module-catalog-personalization/releases/tag/v1.0.0
