### ISSUE TITLE
Improved frontend search UI

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#762]
**Purpose**
Improve frontend search so that it will consider autocomplete, recommendation, empty results, spell checking, search pages and blogs

**Requirements**
- [ ] ?

**Related issues**
- [ ] #950 Storefront: Add relevant suggestion for search phrase

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-47
