### ISSUE TITLE
Personalized product catalogs

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#763]
**Purpose**
Add personalisation feature to the products catalog so that store owner could define different user experiences for one catalog categories and products 

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by retschgi** [comment]
I've some Ideas for this Issue. The following Requirements would be nice:
- Limit Products to User Groups or Users
- Limit Product-Variations to User Groups or Users
- Limit Categories to User Groups or Users

**Comment by tatarincev** [comment]
A temporary workaround with the `user_groups` property  in index.  Need more time for analytics related to  this task.

**Comment by tatarincev** [comment]
Moved to #756
