### ISSUE TITLE
B2B company management on storefront

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#764]
**Purpose**
Customer with manager role should able to manage company members, budgets, addresses on storefront.

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-42
