### ISSUE TITLE
Grey admin - Community license 2.13.0 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#780]
Often admin looks like this to me when I haven't used it for a while.
Community license 2.13.0 

![image](https://cloud.githubusercontent.com/assets/7639413/24045710/a79a665e-0b28-11e7-8c13-4179a3ccbf27.png)

Step to reproduce:
1. Sign in to Admin. Use it for a while.
2. Select other tabs within same Chrome
3. Select Admin tab again after a while -> grey. You can't even refresh.

Solution is to close tab, open a new tab and sign in again.

**Comment by asvishnyakov** [comment]
Is this issue occurs only when you upgrade platform to 2.13.0 or it was present before?

**Comment by OlegoO** [comment]
No on 2.13.2 hppens to me all the time know. When you log in, seems to work. But then you come back to Admin after 5 minutes. It just hangs. Grey screen. You have to Close the tab and restart.

**Comment by asvishnyakov** [comment]
But there is no 2.13.2 :) Did you mean dev branch?

I can't reproduce your issue, so I need help. Write your browser name and version, please, also let me know do you have "Disable cache" checkbox checked or not. Also, if you can, may you open Dev Tools in your browser and leave it for 5 min until admin will grey out? And then send me screenshot

**Comment by OlegoO** [comment]
Sorry, we use 2.13.0. 

Chrome. We don't disable cache,

![default](https://cloud.githubusercontent.com/assets/7639413/24402461/ff4d529c-13b8-11e7-9569-cc369350332f.png)

**Comment by OlegoO** [comment]
Also easily reproduced in firefox

![default](https://cloud.githubusercontent.com/assets/7639413/24403050/7fd1df44-13bb-11e7-93aa-290178c087fe.png)

![default](https://cloud.githubusercontent.com/assets/7639413/24403066/8bb0260e-13bb-11e7-8eb4-2a026aa92029.png)

**Comment by OlegoO** [comment]
Updated to 2.13.1. Will test it and provide feedback.

**Comment by asvishnyakov** [comment]
On Hold until feedback will be provided

**Comment by IgorisB** [comment]
@OlegoO please confirm if issue is solved

**Comment by asvishnyakov** [comment]
@OlegoO Are you still have problems described in this issue?
