### ISSUE TITLE
cant autoinstall modules from multiple groups

### ISSUE THREAD

**Issue by pierresetteskog** [VirtoCommerce/vc-platform#802]
I have tried with
<add key="VirtoCommerce:AutoInstallModuleBundles" value="Commerce;xxx" />
and
<add key="VirtoCommerce:AutoInstallModuleBundles" value="Commerce,xxx" />

but the row in ModulesController.cs
var moduleBundles = ConfigurationManager.AppSettings.GetValues("VirtoCommerce:AutoInstallModuleBundles");

will always return an array with one element, and aftter some googling it doesnt seems to be supported without custom string split code  .

**Comment by artem-dudarev** [comment]
Added splitting by semicolon
