### ISSUE TITLE
I wasn't able to deploy code using deploy button

### ISSUE THREAD

**Issue by dimitri-ak** [VirtoCommerce/vc-platform#809]
Deployment process is never ended. When I checked what resources were created, I saw web app and storage account, but no database.

**Comment by dimitri-ak** [comment]
I did some investigation regarding this issue. It seems that this error is still exist for MSDN subscription, but for regular paid subscription deploy button is worked, I guess.
I forgot to mention, that I think it is related to the available regions where you can create a databases. Here is a screenshot, where you can see which regions are available:
![image](https://cloud.githubusercontent.com/assets/7642075/24423014/deba99ac-13fb-11e7-826d-7a585827d2a2.png)
And I was trying to deploy in West US region.

**Comment by artem-dudarev** [comment]
The deployment wizard supports two different location lists: site location and SQL server location. I changed our azuredeploy.json to use the SQL server location list but it still contains invalid regions.

I belive it's a bug in the deployment wizard and submitted an isue: [https://github.com/projectkudu/slingshot/issues/77](https://github.com/projectkudu/slingshot/issues/77)

The workaroud is to check which regions are available for SQL server through the Azure portal and select the correct location in the wizard.

**Comment by IgorisB** [comment]
@dimitri-ak @artem-dudarev is this still an issue?
