### ISSUE TITLE
CMS Theme Settings Editor

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#812]
**Purpose**

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by Woland2k** [comment]
Should we discuss this in more details? I thought we already had design for this editor.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
