### ISSUE TITLE
Sample subscription store

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#814]
**Purpose**

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
