### ISSUE TITLE
Sample Marketplace store

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#816]
**Purpose**

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by lorenzonet** [comment]
Well, as I wrote in the [uservoice page](https://virtocommerce.uservoice.com/forums/225442-virto-commerce-ideas-feedback/suggestions/17607244-marketplace) it should allow:
- different sellers with their own shop;
- user accounts for all shops;
- top level domain-name or subdomain name for each shop; 
- single shared database;
- marketplace tenants cannot view order item/history from other shops;
- marketplace tenants cannot view user accounts that have not purchased from tenant;
- custom layout for each shop;

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-86
