### ISSUE TITLE
Bundles, Packages and product grouping feature

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#817]
**Purpose**

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-82
