### ISSUE TITLE
Improvements to CMS publishing / support for cooperative work

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#818]
**Purpose**

**Requirements**
- [ ] ?

**Related issues**
- [ ] #766 Content publishing

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
The [CMS page designer](https://github.com/VirtoCommerce/vc-cms-page-designer) should solve these requirements
