### ISSUE TITLE
Support NoSQL catalog

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#819]
**Purpose**

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
We already have some custom project are implemented by our partners that use NoSQL databases
I think we don't need to do anything for this special right now.
