### ISSUE TITLE
Multi vendor, multi ERP, multi country business solution for marketplace

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#820]
**Purpose**
Multi vendor, multi ERP, multi country business solution for marketplace

**Requirements**
- [ ] ?

**Related issues**
- [ ] ?

**User stories**
- [ ] ?

**Acceptance criteria**
- [ ] ?

**Definition of Done**
- [ ] ?

**Comment by tatarincev** [comment]
This is our main goal for 2020 and this task has already presented in the internal backlog.
