### ISSUE TITLE
Check that platform Azure deployment works

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#822]

**Comment by artem-dudarev** [comment]
It works.
![image](https://cloud.githubusercontent.com/assets/8775253/24412604/30d8132c-13d9-11e7-8cec-7bf239987ee7.png)

**Comment by Woland2k** [comment]
It looks like it has something to do with regions, refer to ticket #809

**Comment by tatarincev** [comment]
Duplicated https://github.com/VirtoCommerce/vc-platform/issues/809
