### ISSUE TITLE
Theme colors stopped working

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#823]
When changing theme default definition from Blue to Dark, color schema no longer changes, only left filter changes. This is a showcase feature during the demo and needs to work. The bug is current in dev branch.

**Comment by Andrew-Orlov** [comment]
How can I repeat this issue? I changed the "current" parameter in config/settings_data.json from "Blue" to "Dark" and "Soft Green" and the corresponding color schema applied successfully.
![img_29032017_105428_0](https://cloud.githubusercontent.com/assets/10347112/24446654/93f00e02-146e-11e7-9de9-5f7a5cd25f84.png)
![img_29032017_105728_0](https://cloud.githubusercontent.com/assets/10347112/24446655/93f198bc-146e-11e7-8496-9ee07f770948.png)

**Comment by Woland2k** [comment]
Try changing this using admin UI. You will need to change part for CMS folder in storefront web.config.

**Comment by Andrew-Orlov** [comment]
After pointing the CMS Content module setting "CMS content connection string" to the same folder as declared in Storefront web.config, creating a new theme, overriding only one file "config/settings_data.json" in it and all of the changes in this config-file was applied for storefront successfully. But if Platform has a "CmdContentConnectionString" - it has a higher priority than content module setting.

**Comment by Woland2k** [comment]
When I change it to "Dark" in config, only menu changes (I used dev branch for storefront and commerce manager):

![image](https://cloud.githubusercontent.com/assets/1566470/24467328/e7cf3120-1468-11e7-86a6-c538b59093a4.png)

**Comment by Woland2k** [comment]
This still doesn't work, the easiest way to replicate is currently in our demo, changing from blue to dark, doesn't change the storefront:

![image](https://cloud.githubusercontent.com/assets/1566470/25204742/cc5b325c-2513-11e7-8f48-58dfc4d4296f.png)

**Comment by Woland2k** [comment]
@tatarincev @Andrew-Orlov this still doesn't work on demo
