### ISSUE TITLE
storefront can't open without default theme

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#826]
default theme shouldn't be a requirement for storefront to work, but when default folder is removed the following error occurs:

![image](https://cloud.githubusercontent.com/assets/1566470/24475659/7c7f3308-1485-11e7-92d6-ffcd0add1e9e.png)

If we must include certain scripts, they shouldn't be part of the default theme but added some other way. Preferably we should not have code dependency on default folder however.

**Comment by OlegoO** [comment]
Fixed
