### ISSUE TITLE
Platform - when the session expires there is no redirect to the login page

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#830]

**Comment by trueboroda** [comment]
![image](https://user-images.githubusercontent.com/13153256/68857948-08a4e580-06f5-11ea-8d85-949f356c07f3.png)

**Comment by asvishnyakov** [comment]
@trueboroda Just reopen it

**Comment by tatarincev** [comment]
This bug might be relevant for both platform versions

**Comment by OlegoO** [comment]
Duplicated ub https://github.com/VirtoCommerce/vc-platform/issues/1723
