### ISSUE TITLE
cannot modify SEOInfo for certain storefront pages

### ISSUE THREAD

**Issue by alireza-salehi** [VirtoCommerce/vc-platform#839]
Some pages like account, cart, login,register, contact, profile,reset password, customer order,customer addresses,...  are showing active store SEOInfo (title and description), problem exist in both Electronic and clothing theme.

i added following code to fix it as a workaround to desired controller actions (with hard coded slugs):

```
var seo = WorkContext.CurrentStore.SeoInfos.FirstOrDefault(x => x.Language == WorkContext.CurrentLanguage && x.Slug == "customers-account");
if (seo != null)
{
WorkContext.CurrentPageSeo = seo;
}

```

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-storefront #43](https://github.com/VirtoCommerce/vc-storefront/issues/43) via [**ZenHub**](https://www.zenhub.com/)
