### ISSUE TITLE
As a Manager, I want to see which product version is in production

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#843]
As a Manager, I want to see which product version is in production

**Acceptance criteria**
- [ ] 

**Definition of Done**
- [ ] Unit tests pass with Code coverage 100%
- [ ] Code review
- [ ] Documentation

**Tasks**
- [ ] ?

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
