### ISSUE TITLE
Storefront - Meta title and Meta descriptions always for product and cart pages always the same

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#847]
i don't want to set slug, i need to change Title and Description for those pages, not the url.
all of them showing store title and description, and this is not good.

**Comment by Andrew-Orlov** [comment]
It is possible to set SEO title and description for shopping cart, personal cabinet and similar pages by checking the Liquid-template name on the theme layout before using Liquid-variables `page_title` and `page_description`. Like so:
```
...
{% if template == 'cart' %}
  {% assign page_title = 'cart.general.title' | t %}
  {% assign page_description = 'cart.general.title' | t | append: ' - ' | append: shop.name %}
{% endif %}
...
<title>... {{ page_title }} ...</title>
<meta name="description" content="{{ page_description | escape }}" />
```
