### ISSUE TITLE
Bug in VirtoCommerce.Platform.Web/Scripts/common/directives/genericValueInput.tpl.html

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-platform#849]
After that commit: https://github.com/VirtoCommerce/vc-platform/commit/4f63b092e9cbfbadb58de50936931d5b2d9f4c0c multivalue html dynamic properies stops work, need to change here to fix it: https://github.com/VirtoCommerce/vc-platform/blob/139380cabb8685583800f171c1c1976c42929419/VirtoCommerce.Platform.Web/Scripts/common/directives/genericValueInput.tpl.html#L148

**Comment by asvishnyakov** [comment]
Fixed with 1fa3660. Sorry :(
