### ISSUE TITLE
Problem with installing on azure

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#852]
Client had a problem installing on azure, below is his info (need to test both marketplace and github deployments):

I think SQL server password complexity caused the issue for deployment.  It said successful but now when I visit http://virtotest2.azurewebsites.net/
 
It shows Runtime Error…nothing else.  I did see a few tables created in the database, but I do not think it was fully installed and possibly Timeout Error.
 
I increased the Web plan size to see if that will help get through the installation faster.  Now I just received this error:
 
502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by BuzzKeith** [comment]
I think this may be the same error I was experiencing (exception below).  I would get a few tables generated each time I restarted the app.  Eventually after numerous restarts all migrations would run.  Whilst I haven't had a chance to test it I think it may have been related to the App Service Plan being scaled out to 2 instances. 

[SqlException (0x80131904): User does not have permission to alter database 'BuzzVirto', the database does not exist, or the database is not in a state that allows access checks.]
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) +2442598 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) +5766516
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +285
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4162
System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) +948
System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) +286 System.Data.SqlClient.SqlCommand.ExecuteNonQuery() +286 VirtoCommerce.Platform.Data.Infrastructure.SetupDatabaseInitializer2.InitializeDbSettings(TContext context) in D:\home\site\repository\VirtoCommerce.Platform.Data\Infrastructure\SetupDatabaseInitializer.cs:83
VirtoCommerce.Platform.Data.Infrastructure.SetupDatabaseInitializer`2.InitializeDatabase(TContext context) in D:\home\site\repository\VirtoCommerce.Platform.Data\Infrastructure\SetupDatabaseInitializer.cs:56
VirtoCommerce.Platform.Web.Startup.InitializePlatform(IAppBuilder app, IUnityContainer container, String connectionStringName, HangfireLauncher hangfireLauncher, String modulesPath) in D:\home\site\repository\VirtoCommerce.Platform.Web\Startup.cs:312
VirtoCommerce.Platform.Web.Startup.Configuration(IAppBuilder app, String virtualRoot, String routPrefix) in D:\home\site\repository\VirtoCommerce.Platform.Web\Startup.cs:125
VirtoCommerce.Platform.Web.Startup.Configuration(IAppBuilder app) in D:\home\site\repository\VirtoCommerce.Platform.Web\Startup.cs:77
[TargetInvocationException: Exception has been thrown by the target of an invocation.]
System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +160
System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +101
Owin.Loader.<>cDisplayClass12.<MakeDelegate>bb(IAppBuilder builder) +66
Owin.Loader.<>cDisplayClass1.<LoadImplementation>b0(IAppBuilder builder) +123
Microsoft.Owin.Host.SystemWeb.<>cDisplayClass2.<InitializeBlueprint>b0(IAppBuilder builder) +71
Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action1 startup) +462 Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action1 startup) +40
Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +70
System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +115
Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +106
System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +536
System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296
[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9963380
System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
