### ISSUE TITLE
Property service returns old dictionary values

### ISSUE THREAD

**Issue by dvs39** [VirtoCommerce/vc-platform#855]
If property was dictionary and then it becomes any other value type then IPropertyService.GetAllCatalogProperties still returns 
values from dictionary. So SearchApiModuleController get incorrect values:
```
var properties = _propertyService.GetAllCatalogProperties(catalogId);
```

**Comment by asvishnyakov** [comment]
Which search provider you use - Elastic or Lucene?

**Comment by dvs39** [comment]
Elastic
