### ISSUE TITLE
Notifications: Make wire-frame for notification UI redesign 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#856]

**Comment by Andrew-Orlov** [comment]
Prototype is available here: https://app.moqups.com/ao@virtoway.com/vKhclVVLjF/view/page/ad64222d5

**Comment by tatarincev** [comment]
wireframes  for notifications  journal remains

**Comment by tatarincev** [comment]
![notifications management](https://user-images.githubusercontent.com/7566324/35574035-6ba6ed48-05e1-11e8-8d5a-4ad6a05a3561.png)
