### ISSUE TITLE
How to customize the work space area color

### ISSUE THREAD

**Issue by rukai-kooboo** [VirtoCommerce/vc-platform#866]
Hi There,

Thanks great job to build this platform. 

We have new requirement is can we easy change the color of this panel?
![image](https://cloud.githubusercontent.com/assets/4899310/25176879/554e65ca-2532-11e7-894f-c16cc9b181ea.png)

Maybe we can build a customized module to do this? Any guides?
Thanks!

**Comment by tatarincev** [comment]
We have some settings that can change some manager UI parts. We can extend these settings with a new one. But as a normal solution, of course, there should be support for a design-time configuration (based on scss variables) of theme color schemes.
![image](https://user-images.githubusercontent.com/7566324/71510520-e8417c80-2897-11ea-9a25-4f8ac85bf820.png)
