### ISSUE TITLE
Error when uploading a module with missing dependency

### ISSUE THREAD

**Issue by artem-dudarev** [VirtoCommerce/vc-platform#867]
Module A depends on module B.
Both modules are not installed.
I'm uploading module A manually and instead of module description I see the error message in the header of the blade: File uploaded with error status: 500
![image](https://cloud.githubusercontent.com/assets/8775253/25183137/fe8c14d2-2516-11e7-8391-7ef2ab157e5e.png)

**Comment by asvishnyakov** [comment]
#674

**Comment by asvishnyakov** [comment]
Pricing module is not installed:
![screenshot 329](https://user-images.githubusercontent.com/6369252/29027746-6f69c87c-7b9b-11e7-87a3-d1f1586a57e1.png)
