### ISSUE TITLE
VC Admin + Azure Web Apps + Hangfire Job + Worker Process requested recycle due to 'Percent Memory' limit

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#868]
When we start re-index catalog (~15000 products) in VC Admin, we can not finish the process because Azure automatically recycles Web Apps. 

Error message: 
Worker Process requested recycle due to 'Percent Memory' limit. Memory Used: 4273229824 out of 3757625344 available. Exceeded 90 Percent of Memory.

Web Apps Price plan is S2.

Please advise.
Temporary workaround is "Increase price plan to S3".

**Comment by Woland2k** [comment]
@tatarincev Wasn't this tested in our environment with 1M products already?

**Comment by IgorisB** [comment]
@tatarincev @OlegoO is it solved?

**Comment by OlegoO** [comment]
Fixed in 2.13.9 release
