### ISSUE TITLE
404 error on demo site when opening order

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#870]
![image](https://cloud.githubusercontent.com/assets/1566470/25289571/ffd6797c-267e-11e7-9b95-252485da0a99.png)

**Comment by Woland2k** [comment]
This is due to old scripts used, we need to add some version number when scripts are loaded, so application updates cache automatically.

**Comment by asvishnyakov** [comment]
@Woland2k Is it cache-related issue? Are you sure?

**Comment by tatarincev** [comment]
It is not script cache issue. It happened because old(not exist now) grid column stored in local browser storage. It is necessary in future releases to take care of cleanup.

**Comment by Woland2k** [comment]
@tatarincev local storage is cache, so it is cache issue

**Comment by Woland2k** [comment]
this is an issue with templates missing not localstorage as shown here: 

![image](https://cloud.githubusercontent.com/assets/1566470/25354328/6d943f16-28e7-11e7-9be8-6ce6e26dfabd.png)
