### ISSUE TITLE
How to view/edit GTIN property in ADMIN

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#872]
![image](https://cloud.githubusercontent.com/assets/7639413/25421360/d577c51e-2a5c-11e7-974c-41ee788d8338.png)

**Comment by tatarincev** [comment]
I think better position for GTIN number will be here and also need to add placeholder for input field
![image](https://user-images.githubusercontent.com/7566324/27334684-62ab02b4-55ca-11e7-960f-ebf1e290ac74.png)
