### ISSUE TITLE
Extend UI and backend address functionality

### ISSUE THREAD

**Issue by EugeneOkhriemnko** [VirtoCommerce/vc-platform#873]
Add organization information

**Comment by eMazeika** [comment]
More detailed task definition needed

**Comment by tatarincev** [comment]
Need to migrate current Address detail blade in Core module to meta-form. It will allow to extending this blade with new fields from custom modules.

**Comment by eMazeika** [comment]
@tatarincev , maybe custom placeholders should be also implemented. Check the difference: 
**generic vs custom placeholders**
![image](https://user-images.githubusercontent.com/5801549/29806234-ed1e4732-8c96-11e7-8327-5e2b8d4b933e.png)

**Comment by tatarincev** [comment]
@eMazeika  @Andrew-Orlov  Definitely we need a way allow to define custom placeholders instead default. May we do it through using translate directive where the key for placeholders will be field name?
