### ISSUE TITLE
Could not clear (reset) backorder date

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#883]
I set back order date and then I want to clear.
If I click Clear and Save, it does not work.  
Maybe same problem with other date time fields

Open 
![default](https://cloud.githubusercontent.com/assets/7639413/25803485/5f0ee296-33f7-11e7-8996-97a2416de620.png)

Clear
![default](https://cloud.githubusercontent.com/assets/7639413/25803520/85e60af2-33f7-11e7-9f98-8ff2ba9c5a0d.png)

After save
![default](https://cloud.githubusercontent.com/assets/7639413/25803538/9a7726fe-33f7-11e7-8886-8b5dfb75797c.png)

**Comment by tatarincev** [comment]
Could you change style for checkboxes  in inventory blade to platform stylized.
![image](https://user-images.githubusercontent.com/7566324/28512275-80552226-7051-11e7-9389-2dee9531ef44.png)

And add placeholders  to the  date input fields
![image](https://user-images.githubusercontent.com/7566324/28512288-8d7fb4fc-7051-11e7-95ca-bdb30b69d1b4.png)

**Comment by eMazeika** [comment]
current UI:
![image](https://user-images.githubusercontent.com/5801549/29916840-ad4279f4-8e48-11e7-9863-8fcd7b48dc67.png)
