### ISSUE TITLE
CreatePromotion: The field Name must be a string with a maximum length of 128.

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#889]
Got error when try to create a new promotion. 
Please add client side validation for name.

FaultException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

The field Name must be a string with a maximum length of 128.
   at VirtoCommerce.Platform.Data.Common.ExceptionExtensions.ThrowFaultException(Exception ex)
   at VirtoCommerce.Platform.Data.Infrastructure.ServiceBase.CommitChanges(IRepository repository)
   at VirtoCommerce.MarketingModule.Data.Services.PromotionServiceImpl.CreatePromotion(Promotion promotion)

**Comment by megafreeman** [comment]
Added client side restriction for promotion name with a maximum length of 128
![image](https://user-images.githubusercontent.com/7536694/28629159-ed67231a-7226-11e7-827a-427b923e3d49.png)
![image](https://user-images.githubusercontent.com/7536694/28629294-500adcbe-7227-11e7-9bad-6d1b341700e6.png)
![image](https://user-images.githubusercontent.com/7536694/28629375-8941580a-7227-11e7-9b57-a3f20ec71f3c.png)

https://github.com/VirtoCommerce/vc-module-marketing/commit/f314f6193256cdb4210fe81fade5ff997cd9e18d
