### ISSUE TITLE
Implement new search abstraction in Customer module

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#909]

**Comment by artem-dudarev** [comment]
Implemented indexation and indexed search.
The following repositories have been changed:
* https://github.com/VirtoCommerce/vc-module-core/tree/search-redesign
* https://github.com/VirtoCommerce/vc-module-customer/tree/search-redesign
* https://github.com/VirtoCommerce/vc-module-cache/tree/search-redesign
* https://github.com/VirtoCommerce/vc-storefront/tree/search-redesign

**Comment by Woland2k** [comment]
@artem-dudarev need to finish adding addresses and notes during index. That way we can find customer by phone number or street address.
