### ISSUE TITLE
Subscription & recurring payments

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#91]
Research & implementation

**Comment by Woland2k** [comment]
Any details on implementation? We should probably post some documentation regarding how we are intending to implement this feature.

**Comment by CforED** [comment]
Woland2k,

Yes, this would be a great idea to post information on the implementation details. In particular, database protocols to search for a member's identity hooked to each gateway transaction.

Hal

**Comment by Woland2k** [comment]
Another example of how frontend can look when ordering recurring products: https://www.grainger.com

**Comment by Woland2k** [comment]
was this task completed?

**Comment by Skrypt** [comment]
Is it implemented in 2.9 ?

**Comment by Woland2k** [comment]
No, it is not yet implemented.
