### ISSUE TITLE
Storefront:  Error when change contact data for user account without associated contact record

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#917]
I try to add a user via the Security/Users dialogue. It creates an entry in the PlatformAccount table, including a MemberId, but no entry in the Member table. There seems to be no way to add any address/telephone details at this level. So I then login to the front-end using the newly created username/password. I log in successfully, but when I then try to add an address, it crashes because the "full name" field was not supplied. But there is no "full name" field on the form? Is there a procedure for doing this successfully?
PS This also behaves the same way on the online demo site

**Comment by alewis-github** [comment]
Another point on this (which may be a separate issue?)

When you create/modify a User via the Security/Users dialogue, it doesn't allow you to specify the Store with which the User is associated.

**Comment by tatarincev** [comment]
I've added new issue which related to mentioned you feature. After it will be done you will able to change storeId for any registered account. 
 https://github.com/VirtoCommerce/vc-platform/issues/920

**Comment by alewis-github** [comment]
Thanks!
