### ISSUE TITLE
Change projectUrl section in all modules manifests to point to virtcommerce.com/apps on our main site

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#935]
example:
module.manifest
`<projectUrl>https://virtocommerce.com/apps/extensions/catalog-publishing</projectUrl>`

**Comment by asvishnyakov** [comment]
- [ ] [VirtoCommerce/vc-module-pricing](https://github.com/VirtoCommerce/vc-module-pricing)
- [ ] [VirtoCommerce/vc-module-core](https://github.com/VirtoCommerce/vc-module-core)
- [ ] [VirtoCommerce/vc-module-catalog](https://github.com/VirtoCommerce/vc-module-catalog)
- [ ] [VirtoCommerce/vc-module-product-recommendations](https://github.com/VirtoCommerce/vc-module-product-recommendations)
- [ ] [VirtoCommerce/vc-platform](https://github.com/VirtoCommerce/vc-platform)
- [ ] [VirtoCommerce/vc-content](https://github.com/VirtoCommerce/vc-content)
- [ ] [VirtoCommerce/vc-module-elastic-search](https://github.com/VirtoCommerce/vc-module-elastic-search)
- [ ] [VirtoCommerce/vc-modules](https://github.com/VirtoCommerce/vc-modules)
- [ ] [VirtoCommerce/vc-module-store](https://github.com/VirtoCommerce/vc-module-store)
- [ ] [VirtoCommerce/vc-module-lucene-search](https://github.com/VirtoCommerce/vc-module-lucene-search)
- [ ] [VirtoCommerce/vc-module-customer](https://github.com/VirtoCommerce/vc-module-customer)
- [ ] [VirtoCommerce/vc-module-azure-search](https://github.com/VirtoCommerce/vc-module-azure-search)
- [ ] [VirtoCommerce/vc-module-notifications](https://github.com/VirtoCommerce/vc-module-notifications)
- [ ] [VirtoCommerce/vc-module-search](https://github.com/VirtoCommerce/vc-module-search)
- [ ] [VirtoCommerce/vc-module-marketing](https://github.com/VirtoCommerce/vc-module-marketing)
- [ ] [VirtoCommerce/vc-storefront](https://github.com/VirtoCommerce/vc-storefront)
- [ ] [VirtoCommerce/vc-module-search-api](https://github.com/VirtoCommerce/vc-module-search-api)
- [ ] [VirtoCommerce/vc-b2b-theme](https://github.com/VirtoCommerce/vc-b2b-theme)
- [ ] [VirtoCommerce/vc-module-order](https://github.com/VirtoCommerce/vc-module-order)
- [ ] [VirtoCommerce/vc-module-inventory](https://github.com/VirtoCommerce/vc-module-inventory)
- [ ] [VirtoCommerce/vc-module-sitemaps](https://github.com/VirtoCommerce/vc-module-sitemaps)
- [ ] [VirtoCommerce/vc-module-catalog-publishing](https://github.com/VirtoCommerce/vc-module-catalog-publishing)
- [ ] [VirtoCommerce/vc-module-content](https://github.com/VirtoCommerce/vc-module-content)
- [ ] [VirtoCommerce/vc-module-subscription](https://github.com/VirtoCommerce/vc-module-subscription)
- [ ] [VirtoCommerce/vc-module-quote](https://github.com/VirtoCommerce/vc-module-quote)
- [ ] [VirtoCommerce/vc-module-cart](https://github.com/VirtoCommerce/vc-module-cart)
- [ ] [VirtoCommerce/vc-module-cache](https://github.com/VirtoCommerce/vc-module-cache)
- [ ] [VirtoCommerce/vc-module-KlarnaCheckout-Euro](https://github.com/VirtoCommerce/vc-module-KlarnaCheckout-Euro)
- [ ] [VirtoCommerce/vc-module-KlarnaCheckout-US](https://github.com/VirtoCommerce/vc-module-KlarnaCheckout-US)
- [ ] [VirtoCommerce/vc-module-Amazon-Merchant](https://github.com/VirtoCommerce/vc-module-Amazon-Merchant)
- [ ] [VirtoCommerce/vc-module-MeS](https://github.com/VirtoCommerce/vc-module-MeS)
- [ ] [VirtoCommerce/vc-module-Paypal-ExpressCheckout](https://github.com/VirtoCommerce/vc-module-Paypal-ExpressCheckout)
- [ ] [VirtoCommerce/vc-module-Paypal-DirectPayments](https://github.com/VirtoCommerce/vc-module-Paypal-DirectPayments)
- [ ] [VirtoCommerce/vc-module-Paypal-AdaptivePayments](https://github.com/VirtoCommerce/vc-module-Paypal-AdaptivePayments)
- [ ] [VirtoCommerce/vc-module-Authorize.Net](https://github.com/VirtoCommerce/vc-module-Authorize.Net)
- [ ] [VirtoCommerce/vc-module-shopify-import](https://github.com/VirtoCommerce/vc-module-shopify-import)
- [ ] [VirtoCommerce/vc-module-avatax](https://github.com/VirtoCommerce/vc-module-avatax)
- [ ] [VirtoCommerce/vc-module-DIBS](https://github.com/VirtoCommerce/vc-module-DIBS)
- [ ] [VirtoCommerce/vc-samples](https://github.com/VirtoCommerce/vc-samples)
- [ ] [VirtoCommerce/vc-localization](https://github.com/VirtoCommerce/vc-localization)
- [ ] [VirtoCommerce/vc-benchmark](https://github.com/VirtoCommerce/vc-benchmark)
- [ ] [VirtoCommerce/vc-module-mobile-agent](https://github.com/VirtoCommerce/vc-module-mobile-agent)
- [ ] [VirtoCommerce/vc-demo-theme](https://github.com/VirtoCommerce/vc-demo-theme)
- [ ] [VirtoCommerce/material-theme](https://github.com/VirtoCommerce/material-theme)
- [ ] [VirtoCommerce/jenkins-pipeline-scripts](https://github.com/VirtoCommerce/jenkins-pipeline-scripts)
- [ ] [VirtoCommerce/vc-module-licensing](https://github.com/VirtoCommerce/vc-module-licensing)
- [ ] [VirtoCommerce/vc-module-javascript-shoppingcart](https://github.com/VirtoCommerce/vc-module-javascript-shoppingcart)
- [ ] [VirtoCommerce/vc-module-Shipstation](https://github.com/VirtoCommerce/vc-module-Shipstation)
- [ ] [VirtoCommerce/vc-module-tilda](https://github.com/VirtoCommerce/vc-module-tilda)
- [ ] [VirtoCommerce/vc-module-image-tools](https://github.com/VirtoCommerce/vc-module-image-tools)
- [ ] [VirtoCommerce/vc-module-dynamic-expressions](https://github.com/VirtoCommerce/vc-module-dynamic-expressions)
- [ ] [VirtoCommerce/vc-mobile](https://github.com/VirtoCommerce/vc-mobile)
- [ ] [VirtoCommerce/vc-azure-api-app](https://github.com/VirtoCommerce/vc-azure-api-app)
- [ ] [VirtoCommerce/autorest](https://github.com/VirtoCommerce/autorest)
- [ ] [VirtoCommerce/vc-module-CyberSource](https://github.com/VirtoCommerce/vc-module-CyberSource)
- [ ] [VirtoCommerce/vc-module-checkout](https://github.com/VirtoCommerce/vc-module-checkout)
- [ ] [VirtoCommerce/vc-module-google-ecommerce-analytics](https://github.com/VirtoCommerce/vc-module-google-ecommerce-analytics)
- [ ] [VirtoCommerce/blog-redirect](https://github.com/VirtoCommerce/blog-redirect)
- [ ] [VirtoCommerce/vc-module-zapier](https://github.com/VirtoCommerce/vc-module-zapier)
- [ ] [VirtoCommerce/vc-module-jenkinssample](https://github.com/VirtoCommerce/vc-module-jenkinssample)
- [ ] [VirtoCommerce/virtocommerce.com](https://github.com/VirtoCommerce/virtocommerce.com)
- [ ] [VirtoCommerce/vc-module-zendesk](https://github.com/VirtoCommerce/vc-module-zendesk)
- [ ] [VirtoCommerce/vc-module-MailChimp](https://github.com/VirtoCommerce/vc-module-MailChimp)
- [ ] [VirtoCommerce/vc-module-GoogleShopping](https://github.com/VirtoCommerce/vc-module-GoogleShopping)
- [ ] [VirtoCommerce/swagger-codegen](https://github.com/VirtoCommerce/swagger-codegen)
- [ ] [VirtoCommerce/vc-bot](https://github.com/VirtoCommerce/vc-bot)
- [ ] [VirtoCommerce/vc-marketplace](https://github.com/VirtoCommerce/vc-marketplace)
- [ ] [VirtoCommerce/Amazon-MWS-Client](https://github.com/VirtoCommerce/Amazon-MWS-Client)
- [ ] [VirtoCommerce/dotliquid](https://github.com/VirtoCommerce/dotliquid)
- [ ] [VirtoCommerce/vc-orchard-cms](https://github.com/VirtoCommerce/vc-orchard-cms)
- [ ] [VirtoCommerce/Swashbuckle](https://github.com/VirtoCommerce/Swashbuckle)
- [ ] [VirtoCommerce/Timber](https://github.com/VirtoCommerce/Timber)
- [ ] [VirtoCommerce/skeleton-theme](https://github.com/VirtoCommerce/skeleton-theme)

**Comment by asvishnyakov** [comment]
@tatarincev Make review please
