### ISSUE TITLE
ui-grid am-time-ago.cell.html template not found error

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#936]
Each ui-grid can have stored columns in the browser local storage and one of these columns can contain recently removed `am-time-ago.cell.html` cell template. It causes 404 error on UI.

Solution:  on the platform level in the global cache register a template named 'am-time-ago.cell.html'.

**Comment by asvishnyakov** [comment]
It's impossible to do that. For $templateCache There is no specific *key* for template, key is template url. See [official $templateCache docs](https://docs.angularjs.org/api/ng/service/$templateCache). We may fix it with one of two workarounds:

**Comment by asvishnyakov** [comment]
It's impossible to do that. For $templateCache There is no specific *key* for template, key is template url. See [official $templateCache docs](https://docs.angularjs.org/api/ng/service/$templateCache). We may fix it with workaround: remove `am-time-ago.cell.html` template name from column definition in $localStorage when we load ui-grid.

**Comment by tatarincev** [comment]
I've merged your PR
