### ISSUE TITLE
Fulfilment center: add search to the list

### ISSUE THREAD

**Issue by IgorisB** [VirtoCommerce/vc-platform#940]

**Comment by anivirtoway** [comment]
already done
![image](https://user-images.githubusercontent.com/45942974/51971987-8b70f280-248b-11e9-87e0-3a5345bfd5a5.png)

**Comment by tatarincev** [comment]
@anivirtoway You cannot close issue you have't created

**Comment by yecli** [comment]
@IgorisB Is requested functionality is presented now?

**Comment by IgorisB** [comment]
@yecli it is good, approved
