### ISSUE TITLE
Sorting does not work in promotion lists 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#943]
Sorting does not work in promotion lists for all columns: Title, Is Active, Created or Modified date and etc

![image](https://user-images.githubusercontent.com/7639413/26972029-1c101b2c-4d10-11e7-819c-d41da58e1e33.png)

Also wrong UI style for Created date

**Comment by asvishnyakov** [comment]
Which versions of platform and Marketing module you have?

**Comment by megafreeman** [comment]
Sorting issue was fixed
![image](https://user-images.githubusercontent.com/7536694/28630253-1a266bb0-722a-11e7-91f4-28ca00f7ad72.png)
![image](https://user-images.githubusercontent.com/7536694/28630416-8288680c-722a-11e7-861f-684a72817943.png)
Issue with wrong UI style doesn't reproduce in both browsers FF and Chrome.
https://github.com/VirtoCommerce/vc-module-marketing/commit/c1d2de51a87c8e1a7a925db2e809646eae087f60

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-marketing #2](https://github.com/VirtoCommerce/vc-module-marketing/issues/2) via [**ZenHub**](https://www.zenhub.com/)
