### ISSUE TITLE
Create GitHub issue template for all repositories

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#946]
List of repositories:
- [x] [VirtoCommerce/vc-platform](https://github.com/VirtoCommerce/vc-platform) (already done)
- [x] [VirtoCommerce/vc-storefront](https://github.com/VirtoCommerce/vc-storefront)
- [ ] [VirtoCommerce/vc-modules](https://github.com/VirtoCommerce/vc-modules)
- [ ] [VirtoCommerce/vc-samples](https://github.com/VirtoCommerce/vc-samples)
- [ ] [VirtoCommerce/vc-module-jenkinssample](https://github.com/VirtoCommerce/vc-module-jenkinssample)
- [ ] [VirtoCommerce/vc-benchmark](https://github.com/VirtoCommerce/vc-benchmark)
- [ ] [VirtoCommerce/vc-localization](https://github.com/VirtoCommerce/vc-localization)
- [ ] [VirtoCommerce/virtocommerce.com](https://github.com/VirtoCommerce/virtocommerce.com)
- [ ] [VirtoCommerce/vc-content](https://github.com/VirtoCommerce/vc-content)
- [ ] [VirtoCommerce/vc-marketplace](https://github.com/VirtoCommerce/vc-marketplace)
- [ ] [VirtoCommerce/blog-redirect](https://github.com/VirtoCommerce/blog-redirect)
- [ ] [VirtoCommerce/vc-demo-theme](https://github.com/VirtoCommerce/vc-demo-theme)
- [ ] [VirtoCommerce/material-theme](https://github.com/VirtoCommerce/material-theme)
- [ ] [VirtoCommerce/jenkins-pipeline-scripts](https://github.com/VirtoCommerce/jenkins-pipeline-scripts)
- [ ] [VirtoCommerce/vc-azure-api-app](https://github.com/VirtoCommerce/vc-azure-api-app)
- [ ] [VirtoCommerce/vc-mobile](https://github.com/VirtoCommerce/vc-mobile)
- [ ] [VirtoCommerce/vc-bot](https://github.com/VirtoCommerce/vc-bot)
- [ ] [VirtoCommerce/vc-module-checkout](https://github.com/VirtoCommerce/vc-module-checkout)
- [ ] [VirtoCommerce/vc-module-licensing](https://github.com/VirtoCommerce/vc-module-licensing)
- [ ] [VirtoCommerce/vc-orchard-cms](https://github.com/VirtoCommerce/vc-orchard-cms)
- [ ] [VirtoCommerce/vc-module-tilda](https://github.com/VirtoCommerce/vc-module-tilda)
- [ ] [VirtoCommerce/vc-module-zendesk](https://github.com/VirtoCommerce/vc-module-zendesk)
- [ ] [VirtoCommerce/vc-module-Amazon-Merchant](https://github.com/VirtoCommerce/vc-module-Amazon-Merchant)
- [ ] [VirtoCommerce/vc-module-GoogleShopping](https://github.com/VirtoCommerce/vc-module-GoogleShopping)
- [ ] [VirtoCommerce/vc-module-KlarnaCheckout-US](https://github.com/VirtoCommerce/vc-module-KlarnaCheckout-US)
- [ ] [VirtoCommerce/vc-module-MailChimp](https://github.com/VirtoCommerce/vc-module-MailChimp)
- [ ] [VirtoCommerce/Amazon-MWS-Client](https://github.com/VirtoCommerce/Amazon-MWS-Client)
- [ ] [VirtoCommerce/vc-module-mobile-agent](https://github.com/VirtoCommerce/vc-module-mobile-agent)
- [ ] [VirtoCommerce/vc-module-elastic-search](https://github.com/VirtoCommerce/vc-module-elastic-search)
- [ ] [VirtoCommerce/vc-module-lucene-search](https://github.com/VirtoCommerce/vc-module-lucene-search)
- [ ] [VirtoCommerce/vc-module-azure-search](https://github.com/VirtoCommerce/vc-module-azure-search)
- [ ] [VirtoCommerce/vc-module-notifications](https://github.com/VirtoCommerce/vc-module-notifications)
- [ ] [VirtoCommerce/vc-b2b-theme](https://github.com/VirtoCommerce/vc-b2b-theme)
- [ ] [VirtoCommerce/vc-module-catalog](https://github.com/VirtoCommerce/vc-module-catalog)
- [ ] [VirtoCommerce/vc-module-product-recommendations](https://github.com/VirtoCommerce/vc-module-product-recommendations)
- [ ] [VirtoCommerce/vc-module-pricing](https://github.com/VirtoCommerce/vc-module-pricing)
- [ ] [VirtoCommerce/vc-module-core](https://github.com/VirtoCommerce/vc-module-core)
- [ ] [VirtoCommerce/vc-module-store](https://github.com/VirtoCommerce/vc-module-store)
- [ ] [VirtoCommerce/vc-module-customer](https://github.com/VirtoCommerce/vc-module-customer)
- [ ] [VirtoCommerce/vc-module-search](https://github.com/VirtoCommerce/vc-module-search)
- [ ] [VirtoCommerce/vc-module-marketing](https://github.com/VirtoCommerce/vc-module-marketing)
- [ ] [VirtoCommerce/vc-module-search-api](https://github.com/VirtoCommerce/vc-module-search-api)
- [ ] [VirtoCommerce/vc-module-order](https://github.com/VirtoCommerce/vc-module-order)
- [ ] [VirtoCommerce/vc-module-inventory](https://github.com/VirtoCommerce/vc-module-inventory)
- [ ] [VirtoCommerce/vc-module-sitemaps](https://github.com/VirtoCommerce/vc-module-sitemaps)
- [ ] [VirtoCommerce/vc-module-catalog-publishing](https://github.com/VirtoCommerce/vc-module-catalog-publishing)
- [ ] [VirtoCommerce/vc-module-content](https://github.com/VirtoCommerce/vc-module-content)
- [ ] [VirtoCommerce/vc-module-subscription](https://github.com/VirtoCommerce/vc-module-subscription)
- [ ] [VirtoCommerce/vc-module-quote](https://github.com/VirtoCommerce/vc-module-quote)
- [ ] [VirtoCommerce/vc-module-cart](https://github.com/VirtoCommerce/vc-module-cart)
- [ ] [VirtoCommerce/vc-module-cache](https://github.com/VirtoCommerce/vc-module-cache)
- [ ] [VirtoCommerce/vc-module-KlarnaCheckout-Euro](https://github.com/VirtoCommerce/vc-module-KlarnaCheckout-Euro)
- [ ] [VirtoCommerce/vc-module-MeS](https://github.com/VirtoCommerce/vc-module-MeS)
- [ ] [VirtoCommerce/vc-module-Paypal-ExpressCheckout](https://github.com/VirtoCommerce/vc-module-Paypal-ExpressCheckout)
- [ ] [VirtoCommerce/vc-module-Paypal-DirectPayments](https://github.com/VirtoCommerce/vc-module-Paypal-DirectPayments)
- [ ] [VirtoCommerce/vc-module-Paypal-AdaptivePayments](https://github.com/VirtoCommerce/vc-module-Paypal-AdaptivePayments)
- [ ] [VirtoCommerce/vc-module-Authorize.Net](https://github.com/VirtoCommerce/vc-module-Authorize.Net)
- [ ] [VirtoCommerce/vc-module-shopify-import](https://github.com/VirtoCommerce/vc-module-shopify-import)
- [ ] [VirtoCommerce/vc-module-avatax](https://github.com/VirtoCommerce/vc-module-avatax)
- [ ] [VirtoCommerce/vc-module-DIBS](https://github.com/VirtoCommerce/vc-module-DIBS)
- [ ] [VirtoCommerce/vc-module-javascript-shoppingcart](https://github.com/VirtoCommerce/vc-module-javascript-shoppingcart)
- [ ] [VirtoCommerce/vc-module-Shipstation](https://github.com/VirtoCommerce/vc-module-Shipstation)
- [ ] [VirtoCommerce/vc-module-image-tools](https://github.com/VirtoCommerce/vc-module-image-tools)
- [ ] [VirtoCommerce/vc-module-dynamic-expressions](https://github.com/VirtoCommerce/vc-module-dynamic-expressions)
- [ ] [VirtoCommerce/vc-module-CyberSource](https://github.com/VirtoCommerce/vc-module-CyberSource)
- [ ] [VirtoCommerce/vc-module-google-ecommerce-analytics](https://github.com/VirtoCommerce/vc-module-google-ecommerce-analytics)
- [ ] [VirtoCommerce/vc-module-zapier](https://github.com/VirtoCommerce/vc-module-zapier)
- [ ] ~~[VirtoCommerce/autorest](https://github.com/VirtoCommerce/autorest)~~ (fork)
- [ ] ~~[VirtoCommerce/swagger-codegen](https://github.com/VirtoCommerce/swagger-codegen)~~ (fork)
- [ ] ~~[VirtoCommerce/dotliquid](https://github.com/VirtoCommerce/dotliquid)~~ (fork)
- [ ] ~~[VirtoCommerce/Swashbuckle](https://github.com/VirtoCommerce/Swashbuckle)~~ (fork)
- [ ] ~~[VirtoCommerce/Timber](https://github.com/VirtoCommerce/Timber)~~ (fork)
- [ ] ~~[VirtoCommerce/skeleton-theme](https://github.com/VirtoCommerce/skeleton-theme)~~ (fork)

**Comment by asvishnyakov** [comment]
Has very low priority. Will be completed at free time. On hold until that

**Comment by Woland2k** [comment]
how about writing a script that does this, instead of manually creating a template in each repo

**Comment by asvishnyakov** [comment]
yep, good idea, but it need a little time too :)
