### ISSUE TITLE
[storefront] Display 500 error instead of "Liquid error on"

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#947]
How to display 500 error instead of "Liquid error on"

Version info: 
- Browser version: Any
- Platform version: 2.13.7
- Module version: Storefront

### Expected behavior
As a Developer, I want to display 500 error on production instead of "Liquid error on ...".
It provide ability to detect this error faster, because we will see error in Application Insights.

### Actual behavior
Sometimes our customer see "Liquid error on ...." on the page.

**Comment by OlegoO** [comment]
I think, it can be done if set RethrowErrors to True here.

https://github.com/VirtoCommerce/vc-storefront/blob/master/VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs#L288

Please advise

**Comment by OlegoO** [comment]
+ add some improvents to code
https://github.com/VirtoCommerce/vc-storefront/blob/2a0e8c99244151cf22328648f14abb71f3ad79ee/VirtoCommerce.LiquidThemeEngine/ShopifyLiquidThemeEngine.cs#L288

`            var renderParams = new RenderParameters()
            {
                LocalVariables = Hash.FromDictionary(parameters),
                RethrowErrors = ConfigurationManager.AppSettings.GetValue("VirtoCommerce:LiquidThemeEngine:RethrowErrors", false)
            };`

https://github.com/VirtoCommerce/vc-storefront/blob/09b8c450b228a94df1463301c0a56032f8d443ce/VirtoCommerce.LiquidThemeEngine/Extensions/TemplateExtensions.cs#L54

`           catch(Exception ex)
            {
                Trace.TraceError(FlattenException(ex));
                throw;
            }`

**Comment by tatarincev** [comment]
Would be better if this behavior will be depend on  special ASP.NET web.config sections such as 
 <compilation targetFramework="4.6.1" debug="true" /> 
Better will be to make little research about similar behavior for ASP.NET MVC Razor views.

**Comment by Andrew-Orlov** [comment]
The key `VirtoCommerce:LiquidThemeEngine:RethrowErrors` was added to `appSettings` with default value `true`. To test Liquid errors can be used the next string: `{{ 2 | divided_by: 10 | remove: '.0' }}`.

**Comment by Woland2k** [comment]
Default value should be false. I don't want to site to blow up when regular user makes error in liquid.
