### ISSUE TITLE
Storefront: menu not working on mobile devices / devices with narrow screen

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-platform#952]
Version info:
- Browser version: Chrome 58 Desktop / for Android
- Platform version: 2.13.8 (public demo)
- Module version: Storefront 2.21.3 (public demo)

### Expected behavior
When you click/tap on `Menu` button, menu must appear.

### Actual behavior
When you try to do it on account dashboard, nothing happens.

### Steps to reproduce
1. Open http://demo.virtocommerce.com on mobile device or set width of your browser window to less than `768px`.
2. Sign in.
3. Open menu and click to `View account`.
4. Try to open menu now.

### Why it happens?
JS functions what allow you to open menu is defined in `shop.js.liquid`, which is not included in `account/scripts` bundle

**Comment by tatarincev** [comment]
Sign In on mobile device didn't work. After successful login, menu contains the Sign In command  and header not changed.

**Comment by Andrew-Orlov** [comment]
![image](https://user-images.githubusercontent.com/10347112/28625656-385beaea-721d-11e7-9525-1c68dcd98459.png)
