### ISSUE TITLE
Storefront: Show multiple prices from different price lists

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#953]
Customer question:

> It looks like that StoreFront is using [GET /api/products/{productId}/prices] to get product price based on the prioroty of pricelist (but only showing one price).
> 
> But I want to get some advices to help me solving this scenario:
> I have two price lists for each product, one is for online price and another one is for in-store price. From the StoreFront page, I want to show my customers both prices. I'm not sure how do I achieve this?

* need to modify platform api/pricing/evaluate method to return multiple prices 
* need to modify storefront ProductPrice model to support multiple prices form different price lists

**Comment by Woland2k** [comment]
Why not use extra field in price for that (extra property)?

**Comment by tatarincev** [comment]
Client wants to show more than 10 price lists on the StoreFront site.
