### ISSUE TITLE
404 error when opening price list assignment

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#955]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: latest
- Platform version: 2.13.8
- Module version: 
price module 2.16.3

### Expected behavior
Display list of price list assignments

### Actual behavior
Error is displayed
![image](https://user-images.githubusercontent.com/1566470/27248857-2ccaa3b6-52be-11e7-8326-2b64aed9c865.png)

### Steps to reproduce
1. Open price list assignment page for default demo store.

**Comment by ksavosteev** [comment]
Cannot reproduce this bug either on http://demo.virtocommerce.com/admin or locally.

**Comment by tatarincev** [comment]
@Woland2k  Could you provide 404 server error details from browser console?

**Comment by Woland2k** [comment]
Resolved in the latest platform build
