### ISSUE TITLE
Marketing - Expiration date does not include last date

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#956]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version:  Any
- Platform version: 2.13.7
- Module version:  2.16.1

### Expected behavior
Select Expiration date, for example 2017-06-19 and see that promotion should be expired at  2017-06-19T23:59:59

### Actual behavior
Select Expiration date, for example 2017-06-19 and promotion was expired at  2017-06-19T00:00:00

### Steps to reproduce
1. Go to admin create promotion, set  Expiration date to current date
2. Promotion is expired

**Comment by ksavosteev** [comment]
Since modifying date in code is a bit ugly I think adding an ability to pick a time of day is a better solution.

**Comment by OlegoO** [comment]
First, I think you can add a comment about expected behavior. 
Then as workaround, you can add 23:59:59 as default time.

**Comment by Woland2k** [comment]
is the time in the timezone of the user, server or utc?

**Comment by OlegoO** [comment]
> is the time in the timezone of the user, server or utc?
Good question 

![default](https://user-images.githubusercontent.com/7639413/27351441-abc204ec-55fd-11e7-995e-71289c579a3d.png)

**Comment by tatarincev** [comment]
All time displayed on manager depend on timezone setting in user profile
![image](https://user-images.githubusercontent.com/7566324/27354188-074dbf46-5607-11e7-99e4-2b3df2b35b0d.png)

**Comment by Woland2k** [comment]
What about time saved? I think it should use midnight in user timezone when only date is specified. We should also add a note explaining what time zone and when it will expire or start.

**Comment by asvishnyakov** [comment]
All date pickers in platform follow the same behavior which still unchanged after i18n and timezones was applied - they use 00:00:00 UTC of the day which you choose. If you will not use UTC everywhere (use 00:00:00 of local time) then same dates defined by different users will has different time, so, for example, two promotions with the same expiration date really will expire in 7 hour difference, if the first was created by user in NY and the second was created by user in Moscow. We always use UTC for all manipulation with dates and time and this behavior must not be changed to avoid illogical (and potentially dangerous) situations.

If we want to include expiration day (which, probably, not) we may add 24 hours to this date-time.

**Comment by Woland2k** [comment]
@asvishnyakov the date should be saved in UTC format (but the actual date should be in local time). For example, lets consider, Swedish company that creates new promotion to start on Monday and end on Wednesday. So when time hits midnight on Monday night, the promotion should start applying (not when it is 23:00 as it would if time is UTC).

when they select for promotion to start on a certain date

**Comment by megafreeman** [comment]
Now expiration date include last promotion date
![image](https://user-images.githubusercontent.com/7536694/28724307-d8939f24-73b9-11e7-9c14-3dce7b37b29f.png)
![image](https://user-images.githubusercontent.com/7536694/28724484-6f1ad49e-73ba-11e7-849b-d2d21ffd6604.png)
https://github.com/VirtoCommerce/vc-module-marketing/commit/9e3737786a37cabb462fa0a4d2ddfea175c8bb34

**Comment by asvishnyakov** [comment]
Wrong implementation was released. You just set 23:59:59 UTC. Use this code for correct time calculation (23:59:59 local time):
```
blade.currentEntity.endDate = moment(blade.currentEntity.endDate).add({ hours: 23, minutes: 59, seconds: 59 }).toDate();
```

**Comment by megafreeman** [comment]
Promotion endDate now depends on time zone that set in user profile

**Comment by megafreeman** [comment]
The hours will be set only when the end date of promotion was assigned

**Comment by megafreeman** [comment]
@asvishnyakov could you make a code review of this issue?

**Comment by asvishnyakov** [comment]
@megafreeman Compare end date of currentEntity and origEntity and set 23:59:59 only if endDate changed. Otherwise any user that modify promotion also will also change end date.

**Comment by megafreeman** [comment]
Issue moved to [VirtoCommerce/vc-module-marketing #5](https://github.com/VirtoCommerce/vc-module-marketing/issues/5) via [**ZenHub**](https://www.zenhub.com/)
