### ISSUE TITLE
CatalogModule: Redesign UX for a catalog images blade

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#957]
![image](https://user-images.githubusercontent.com/7566324/27858559-fe17eb2a-6175-11e7-8fd3-4d0e59cb4b78.png)

Use common asset search control for link already exist images from asset library

**Comment by ksavosteev** [comment]
Gallery UI change suggestions:
1. Separate the image upload part of the blade from the gallery: image upload could be done in a separate blade.
2. Replace image tiles with a table. Each row will have a pic thumbnail and a checkbox for mass operations, similar to the products table. 
3. UI element for changing category over multiple images could be placed in another blade which will open by a Change Category button in the toolbar. The button will become active after selecting a group of images through checkboxes.

**Comment by tatarincev** [comment]
Product images blade
No data - when no images in the grid (copy from categories-items-list.tpl)
Drag&drop in product images list (for change image priority) (need to display some special symbol or icon indicating that d&d operation is available)
Context menu for each image shoudl contains next operations (download, copy link, delete) similar as it made in asset browsing blade

asset-select
- pagination overlaps Ok button and there is unable to select image

new image blade
- preview uploaded image. Images should be added to the product images only after user confirmation  (click to ok)
- 500 server error admin/api/image/thumbnails when new image is uploaded

**Comment by tatarincev** [comment]
-  Product images blade bottom pane with `Ok` and `Cancel` actions probably overlaps pagination links and make unavailable to see all images. (probably solution is to get of rid this pane and reflect all changes to a product in  the parent blade)
- Image priority spinner allow to make negative value
- When images grid has a Priority sort order then any changes on  priority  automatically was changing  images position and focus became on different image
