### ISSUE TITLE
Make partial updates like change status of order

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#958]
I think that default update should support partial updates like change status of order.

### Expected behavior
Update order status only

### Actual behavior
We update all order as one document and can override previous update

**Comment by tatarincev** [comment]
We have the task in the backlog https://virtocommerce.atlassian.net/browse/PRD-52 after implementing this requirement will be no longer relevant. There will be no requirements for changing status within the CRUD operation,
