### ISSUE TITLE
Integration the serverless  architecture in the storefront 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#965]
Main goal:
New storefront extension model allow to extending functionality through theme and platform modules modification. Will provide simplification of storefront code by moving most of the functionality in the platform modules and SPA defined in storefront theme. 
Actually storefront server code will be contain only common functions and server rendering code which necessary for correct search engines indexation (products, landing pages).

Technical topics:
- [ ] Cross-domain authentication (strorefront <-> platform) It is proposed to use OAuth2 protocol
- [ ]  API Gateway  for routing all storefront API calls to platform. (also hide real platform internet address)
- [ ] Use  Hypermedia As The Engine Of Application State (HATEOAS) pattern  as primary uniform interface

**Comment by Woland2k** [comment]
In regards to API Gateway, we don't need to create one, we should rely on other services for that one of which can be Azure API (there are many others)
Our data model is JSON/REST, what is the format for HATEOAS when used with Json?

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-53
