### ISSUE TITLE
Storefront: Store customer comments in the cart 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#967]
**Customer question:**

> In the storefront code I can see that the Shopping cart has a Comment property and also the LineItem has a Comment property. I also found that there is a text area for entering "Special instructions for seller" in the checkout page.
> My questions are:
> Where the "Special instructions for seller" is stored since I could not see it in the order section in admin panel.

**Technical specification:**
Need to save user comment in Cart.Comment property 
![image](https://user-images.githubusercontent.com/7566324/27476393-e4c85c5c-5808-11e7-9787-00f163e23ba8.png)

and ensure what it will be copied in resulting order
![image](https://user-images.githubusercontent.com/7566324/27476486-3e5e9a6a-5809-11e7-89d4-6e8ac7e8f0ae.png)

**Comment by Andrew-Orlov** [comment]
Added a button "Submit comment" to the shopping cart page, after creating order a comment will be shown in a appropriate widget on the order blade.
![image](https://user-images.githubusercontent.com/10347112/31441821-a0b61684-ae94-11e7-95d1-710d341b1879.png)
![image](https://user-images.githubusercontent.com/10347112/31441882-d23d9ea2-ae94-11e7-9f3e-58c0e4910876.png)

**Comment by Woland2k** [comment]
@Andrew-Orlov remove submit comment button, it should be added only when checkout is pressed, no need for a special action.

**Comment by vkrashenko** [comment]
![commenttoorder](https://user-images.githubusercontent.com/29459286/32321094-a5520302-bfc8-11e7-800f-f5e4601fec06.gif)

**Comment by tatarincev** [comment]
The only this PR left for release
https://github.com/VirtoCommerce/vc-theme-default/pull/18/files

**Comment by asvishnyakov** [comment]
@tatarincev Duplicate changes to storefront-core

**Comment by tatarincev** [comment]
@asvishnyakov  Already done

**Comment by tatarincev** [comment]
Released  https://github.com/VirtoCommerce/vc-storefront-core/releases/tag/v3.0.2
