### ISSUE TITLE
Pricelists fetched by IPricingService.EvaluatePriceLists do not contain populated PricelistAssignment collection.

### ISSUE THREAD

**Issue by busbina** [VirtoCommerce/vc-platform#968]
Version info: 
- Browser version: 
All
- Platform version:
2.23.0.0
- Module version: 

### Expected behavior
Pricelist.PricelistAssignment is populated with related PricelistAssignment.
### Actual behavior
Pricelist.PricelistAssignment is null.
### Steps to reproduce
1. Make a IPricingService.EvaluatePriceLists call.
2. returned Pricelist.PricelistAssignment will be null.

Work around is to fetch the list again by ID.

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-pricing #6](https://github.com/VirtoCommerce/vc-module-pricing/issues/6) via [**ZenHub**](https://www.zenhub.com/)
