### ISSUE TITLE
Unique number key generation on multiple platform instances

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#970]
Current implementation loaded pre-generated numbers in memory and it my cause duplication with work on several application instances.
 https://github.com/VirtoCommerce/vc-module-core/blob/master/VirtoCommerce.CoreModule.Data/Services/SequenceUniqueNumberGeneratorServiceImpl.cs

**Comment by WimVergouwe** [comment]
Hey guys, when will you include this? We ran into this issue!

**Comment by tatarincev** [comment]
@WimVergouwe I got your message. I'll let you know today about the fix estimates.

**Comment by Elyseum** [comment]
FYI: we're currently trying to fix this on StandaardBoekhandel using Medallion library (https://github.com/madelson/DistributedLock).
It allows you to take a distributed lock using SQL:

    private static readonly SqlDistributedLock _distributedSequenceLock = new SqlDistributedLock(
            "DistributedSequenceUniqueNumber",
            ConfigurationManager.ConnectionStrings["VirtoCommerce"].ConnectionString,
            SqlDistributedLockConnectionStrategy.Azure);

    ...
    
    using (_distributedSequenceLock.Acquire(TimeSpan.FromSeconds(5)))
    {
         InitCounters(numberTemplate, out var startCounter, out var endCounter);
         _inMemorySequences[numberTemplate].Pregenerate(startCounter, endCounter, numberTemplate);
         break;
    }

**Comment by tatarincev** [comment]
We've found the solution. We can  fix this problem by using `Optimistic Concurrency` update conflict handling in this place https://github.com/VirtoCommerce/vc-module-core/blob/dev/VirtoCommerce.CoreModule.Data/Services/SequenceUniqueNumberGeneratorServiceImpl.cs#L83
So we are starting work on a quick fix and will roll-out release as soon as finished and tested.

**Comment by yecli** [comment]
Released https://github.com/VirtoCommerce/vc-module-core/releases/tag/v2.25.30
