### ISSUE TITLE
Refactor faceting

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#977]
- [x] Add facet names list to product search criteria to allow storefront to control which facets to return (if any).
- [x] Add range bounds to AggregationItem in search results.
- [x] Convert serialized facets from XML to JSON
- [x] Remove localization from serialized facets.
- [x] Get localized property names and values from catalog metadata.
- [x] Support attribute facet values in serialized facets.
- [x] Generate localized range values using templates on storefront.
- [x] Move faceting logic from ProductSearchRequestBuilder to a separate service. Add tests.
- [x] Implement visual editor for range facets.
- [x] Implement visual editor for attribute facet values.

**Comment by artem-dudarev** [comment]
https://github.com/VirtoCommerce/vc-module-catalog/tree/search-redesign
https://github.com/VirtoCommerce/vc-storefront/tree/search-redesign

**Comment by artem-dudarev** [comment]
@tatarincev was assigned for code review

**Comment by tatarincev** [comment]
- Redundant registration construction in module.cs
`_container.RegisterType<IProductSearchService, ProductSearchService>(new InjectionConstructor(typeof(ISearchRequestBuilder[]), typeof(ISearchProvider), typeof(ISettingsManager), typeof(IItemService), typeof(IBlobUrlResolver), typeof(IAggregationResponseBuilder)));`

- Probably performance issue with frequently `IAggregationLabelService.GetPropertyLabels`  calls 
- Need to join three new abstractions `IAggregationLabelService`, `IAggregationRequestBuilder`, `IAggregationResponseBuilder` to one abstraction with the name closest to the ubiquitous business language 
- `IBrowseFilterService`  should be left the responsibility to work with a store. I'll suggest moving serialization/deserialization logic to the extension method and do the read/write fillers from a store property in client code.
