### ISSUE TITLE
List of organization members

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#984]
Grid columns: member email, status (invited, active, not active), registration date.
search members by email or keyword
allow to sort by all columns
members list should support pagination 
Click to any member should open member detail view

![image](https://user-images.githubusercontent.com/7566324/27581226-6a2e5064-5b2d-11e7-8ff0-b695887a44c2.png)

Invite and register new members should be make as popup

**Comment by IgorisB** [comment]
These has low priority and implement at the end of sprint if other requirements will be done:
- search members by email or keyword
- allow to sort by all columns

Grid also should contain First and Last names, Title. Registration date is not really needed in the list.

**Comment by tatarincev** [comment]
Use member invitation process as shown and described in the user story. I see to missing things in mockup:

One email? Should be list of email. Bulk invitation is important feature for B2B.
Should be preview of recipients and email content. It will be as confirmation page.

**Comment by IgorisB** [comment]
Activate/deactivate, edit actions are not needed for invited member (not registered yet)

**Comment by megafreeman** [comment]
All features almost done except sorting and search
