### ISSUE TITLE
Security roles view - remake to new requirements

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#988]
![image](https://user-images.githubusercontent.com/7566324/27581161-33606450-5b2d-11e7-81d4-3e3500217b87.png)

Roles list as radio-group buttons

**Comment by IgorisB** [comment]
It is not part of the user stories... We decided that security (roles management) is defined in theme settings, so it is part of system configuration. Why it is on dashboard?

**Comment by tatarincev** [comment]
It is user active role

**Comment by IgorisB** [comment]
Show user role in "Profile" as readonly field
