### ISSUE TITLE
Organization members list view

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#989]
![image](https://user-images.githubusercontent.com/7566324/27581226-6a2e5064-5b2d-11e7-8ff0-b695887a44c2.png)

Invite and register new members should be make as popup

**Comment by IgorisB** [comment]
Use member invitation process as shown and described in the user story. I see to missing things in mockup:
- One email? Should be list of email. Bulk invitation is important feature for B2B.
- Should be preview of recipients and email content. It will be as confirmation page.

**Comment by tatarincev** [comment]
Duplicated https://github.com/VirtoCommerce/vc-platform/issues/984
