### ISSUE TITLE
Member registration component

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-platform#992]
![image](https://user-images.githubusercontent.com/7566324/27581906-5dbf377e-5b2f-11e7-8b54-f01e75d8aceb.png)

Should allow to disable or hide follow fields (organization, email)
Can be used inside popup or in separated view (Registration organization owner, registration new member, registration from members list)

**Comment by IgorisB** [comment]
Add Title field (after Last name)

**Comment by IgorisB** [comment]
I created member from invitation link, however my profile empty. First and last name, email were entered in registration form.

**Comment by asvishnyakov** [comment]
Probably caused by cache

**Comment by asvishnyakov** [comment]
@IgorisB Looks like appear because company owner was created before we implement new types (Company & CompanyMember). If I create new company owner, then all ok.
