### ISSUE TITLE
Create VS Templates

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#997]
Create templates (https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates, https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates) for common VC projects, including:

1. Managed module
2. Unmanaged module

when creating template it should include:

1. all the necessary/latest nuget libraries.
2. ~~projects ({Name}.Core, {Name}.Data, {Name}.Web, {Name}.Tests)~~ (will make it too complicated).
3. namespaces should be automatically substituted. 
4. appropriate readme template
5. JenkinsFile for it to be built by jenkins CI
6. security permissions and configuration parameters
7. .gitignore file
8. Scripts and Content folders 
9. Scripts/{name}.js with contain AngularJS module registration and empty `run` function with comment how to register new menu item and ui-route state
10. Content/logo.png
11. module manifest file should contains `<styles>` and `<scripts>` and commented `<settings>` and `<permissions>` sections  
 
The resulting project should be completely ready to be compiled and deployed to VC as a new module.

The template should be packages as a VSIX and uploaded to VS gallery as described here: https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-the-vsix-project-template

Change current documentation article https://virtocommerce.com/docs/vc2devguide/working-with-platform-manager/extending-functionality/creating-new-module add to it  instructions how to use new VS template

**References**
https://github.com/sjkp/Delegate.SPA.Template
https://stackoverflow.com/questions/28885257/cannot-use-root-name-for-items-in-multi-project-vstemplate

**Comment by asvishnyakov** [comment]
Wow. It's my developer pain since I start working in VirtoWay.

**Comment by IgorisB** [comment]
And it needs to think how to automatically test templates.

**Comment by Woland2k** [comment]
This is now has been implemented.

**Comment by Woland2k** [comment]
Here is a download link https://marketplace.visualstudio.com/items?itemName=VirtoCommerce2xModuleProjectTemplate.VirtoCommerce2xModule

**Comment by asvishnyakov** [comment]
Commonly, we use CommonAssemblyInfo.cs from root of solution folder to have a single point where we need to change module info (version, etc.) when we release it.
