### ISSUE TITLE
[BUG] Content publishing - Can not create a new publishing because Name is removed automatically on lost focus 

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-platform#998]
Can not create a new publishing because Name is removed automatically on lost focus 

Version info: 
- Browser version: Firefox
- Platform version: 2.13.9
- Module version: 

### Expected behavior
Enter publishing name, when create a new Content publishing element.

### Actual behavior
Name is removed automatically on lost focus 

### Steps to reproduce
0. GO to http://demo.virtocommerce.com/admin#/workspace/marketing
1. Try create a new Content publishing element.
2. Name is required field
![image](https://user-images.githubusercontent.com/7639413/27634114-51d10c2a-5c02-11e7-8908-01c9ba2bc650.png)

3. Enter name
![image](https://user-images.githubusercontent.com/7639413/27634137-6cd3e290-5c02-11e7-82bd-ee31036a3305.png)

4. Click on any next element or try enter description 
5. Value is removed automatically on lost focus from name 

![image](https://user-images.githubusercontent.com/7639413/27634176-9b0a615c-5c02-11e7-9af5-1d8c518d5e89.png)

**Comment by tatarincev** [comment]
Publishing name generates automatically depend on selected placeholders and items. But anyway it look as UX bug and need ti be fixed.

**Comment by megafreeman** [comment]
Value does not change if it already exists.
![image](https://user-images.githubusercontent.com/7536694/28634270-f4ed3d9e-7236-11e7-8c62-ce649179d1ea.png)
![image](https://user-images.githubusercontent.com/7536694/28634277-00538972-7237-11e7-9adb-99161c6f8b58.png)
https://github.com/VirtoCommerce/vc-module-marketing/commit/f3e192867935711e784a32b7bc69052911180277

**Comment by OlegoO** [comment]
Issue moved to [VirtoCommerce/vc-module-marketing #3](https://github.com/VirtoCommerce/vc-module-marketing/issues/3) via [**ZenHub**](https://www.zenhub.com/)
