### ISSUE TITLE
Refresh linked module when new DLL is compiled

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-platform#999]
This is a critical issue as it will affect beginner developers the most. It also wastes a lot of time of developers working on module functionality.

Version info: 
- Browser version: all
- Platform version: 2.13
- Module version: 

### Expected behavior
When module is compiled I expect platform to immediately pick up the new implementation. 

### Actual behavior
Module DLL is not updated.

**Comment by tatarincev** [comment]
This feature request has been closed and added to the internal product backlog. 
https://virtocommerce.atlassian.net/browse/PRD-90
